"""
GLV-HNP Phase 2, Thread 23: reformulate the lattice so the planted vector is lambda_1.

Background (RESEARCH_AUTOLAB_LOG.md, 2026-07-29, EXP T5):
  In the Phase-2 lattice of glv_hnp_phase2_20bit.py:262 the vector
      n * S_D * e_m        (the "d-column" vector, S_D = 1)
  is always in the lattice and always shorter than the planted vector:
      ||n*e_m||       = n
      ||v_planted||^2 ~ n^2 * (2m/3 + 2)
  so the planted vector is NEVER lambda_1, for any m >= 1, and no choice of
  S_D removes it (both scale linearly in S_D).  T5 measured |sv[m]|/n = 1.0000
  on every curve tested.  Recovery is therefore a BDD/coset condition, not an
  SVP condition.

  The 2026-07-29 next-step proposal: quotient out the trivial n*e_m direction
  and see whether (a) the planted vector becomes lambda_1 and (b) the K1 wall
  measured in T4 moves outward.  Falsifier as stated in the log:
      "if sv/pv rises above 1 after the reformulation and the K1 wall in T4
       moves outward on the lam*=0.07 curve (currently K1~4-6), the
       reformulation is a real improvement; if the wall stays at K1~4-6, then
       the wall is information-theoretic and Phase 2 is at its ceiling."

This script runs a 2x2 factorial to separate two independent changes:

  P (project)  drop the d-column entirely.  d is not a small unknown -- it is
               uniform in [0,n) -- so it contributes an n-scale coordinate to
               the planted vector while buying nothing.  Eliminating it also
               kills n*e_m.  d is read back afterwards from the recovered
               nonce:  d = (k1_0 + lam*k2_0 - A_0) * B_0^{-1} mod n.

  C (center)   replace k1_i in [0,K1) by k1_i - K1/2 in [-K1/2, K1/2), same
               for k2_i.  Implemented by shifting the Kannan row's constants:
               A'_i = (A_i - K1/2 - lam*K2/2) mod n.  Halves the rms of every
               small coordinate, i.e. shortens the planted vector by ~2.

  V1   = baseline (as built 2026-06-15, dim 2m+2)
  V1c  = baseline + centering                       (dim 2m+2)
  V2   = projected                                  (dim 2m+1)
  V2c  = projected + centering                      (dim 2m+1)

Explicit V2 basis (rank 2m+1, no rank deficiency).  With u = B_0^{-1} mod n
and C_i = B_i*u mod n (so C_0 = 1), the column-0..m-1 sublattice generated by
{n*e_i} and (B_i) equals the one generated by g = (1, C_1, ..., C_{m-1}) and
{n*e_j, j>=1}, because n*e_0 = n*g - sum_{i>=1} C_i*(n*e_i).  Basis rows:

    row_g      : (S_K1, C_1*S_K1, ..., C_{m-1}*S_K1 | 0...0 | 0)
    row_n[j]   : n*S_K1 at col j,  j = 1..m-1
    row_k2[i]  : -lam*S_K1 at col i,  S_K2 at col m+i,  i = 0..m-1
    row_A      : (A'_i*S_K1)_i | 0...0 | S_KANNAN

    det(V2) = n^(m-1) * S_K1^m * S_K2^m * S_KANNAN = n^(3m) / (K1*K2)^m
            = det(V1) / (n*S_D)      [projection along n*S_D*e_m, as intended]

    planted  = (d*B_0 mod n)*row_g + sum_i k2'_i*row_k2[i] + row_A  - reductions
             = (k1'_i*S_K1 | k2'_i*S_K2 | S_KANNAN)

Experiments:
  E0  membership + determinant checks for all four variants (exact, sympy)
  E1  sv/pv and recovery on the three historical Phase-2 curves
  E2  the T4 K1-wall grid, all four variants, m=12, 5 seeds  <- the falsifier
  E3  m-dependence of sv/pv (does the projected planted vector stay lambda_1?)
  E4  20-bit replication of the E2 wall for V1 vs V2c

Run: python3 glv_hnp_phase2_v2_lattice.py
Deps: fpylll, sympy   (pip install fpylll cysignals sympy)
"""

import math
import random

import sympy
from fpylll import IntegerMatrix, LLL, BKZ

# ---------------------------------------------------------------------------
# Minimal EC arithmetic (short Weierstrass, a=0) -- verbatim from
# glv_hnp_phase2_lambda_threshold.py so the comparison to 2026-07-29 is exact.
# ---------------------------------------------------------------------------

def modinv(a, m):
    return pow(a, -1, m)

def ec_add(P, Q, p):
    if P is None: return Q
    if Q is None: return P
    x1, y1 = P; x2, y2 = Q
    if x1 == x2:
        if (y1 + y2) % p == 0: return None
        s = 3 * x1 * x1 * modinv(2 * y1, p) % p
    else:
        s = (y2 - y1) * modinv(x2 - x1, p) % p
    x3 = (s * s - x1 - x2) % p
    y3 = (s * (x1 - x3) - y1) % p
    return (x3, y3)

def ec_mul(P, k, p):
    if k == 0: return None
    R, Q = None, P
    while k > 0:
        if k & 1: R = ec_add(R, Q, p)
        Q = ec_add(Q, Q, p)
        k >>= 1
    return R

def tonelli_shanks(nn, p):
    nn %= p
    if nn == 0: return 0
    if pow(nn, (p - 1) // 2, p) != 1: return None
    if p % 4 == 3: return pow(nn, (p + 1) // 4, p)
    q, s = p - 1, 0
    while q % 2 == 0: q //= 2; s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1: z += 1
    m, c, t, r = s, pow(z, q, p), pow(nn, q, p), pow(nn, (q + 1) // 2, p)
    while True:
        if t == 0: return 0
        if t == 1: return r
        i, tmp = 0, t
        while tmp != 1: tmp = tmp * tmp % p; i += 1
        bb = pow(c, 1 << (m - i - 1), p)
        m, c, t, r = i, bb * bb % p, t * bb * bb % p, r * bb % p

def find_point(p, b, seed=42):
    rng = random.Random(seed)
    for _ in range(10000):
        x = rng.randint(0, p - 1)
        rhs = (pow(x, 3, p) + b) % p
        y = tonelli_shanks(rhs, p)
        if y is not None and y != 0:
            return (x, y)
    return None

def find_generator(p, b, n, seed=12345):
    rng = random.Random(seed)
    for _ in range(10000):
        x = rng.randint(0, p - 1)
        rhs = (pow(x, 3, p) + b) % p
        y = tonelli_shanks(rhs, p)
        if y is None or y == 0: continue
        P = (x, y)
        if ec_mul(P, n, p) is None and P is not None:
            return P
    return None

def eisenstein_decompose(p):
    """
    (a,b) with a^2 - a*b + b^2 = p, for p = 1 mod 3.

    Cornacchia-Smith on 4p = x^2 + 3y^2, then (a,b) = ((x+y)/2, y).  O(log p),
    vs the O(sqrt p) brute force in glv_hnp_phase2_20bit.py:146 (which is
    correct; this is only faster).  Verified to agree with brute force on all
    p = 1 mod 3 in 8/12/17/20/24-bit ranges -- see E0b below.
    """
    if p % 3 != 1: return None
    x0 = tonelli_shanks((p - 3) % p, p)          # sqrt(-3) mod p
    if x0 is None: return None
    if x0 % 2 == 0: x0 = p - x0                  # need x0 = D = -3 (mod 2)
    a0, b0 = 2 * p, x0
    lim = math.isqrt(4 * p)
    while b0 > lim:
        a0, b0 = b0, a0 % b0
    rem = 4 * p - b0 * b0
    if rem % 3 != 0: return None
    t = rem // 3
    s = math.isqrt(t)
    if s * s != t: return None
    x, y = b0, s
    if (x + y) % 2 != 0: return None
    a, b = (x + y) // 2, y
    if a * a - a * b + b * b != p: return None
    return (a, b)


def eisenstein_decompose_bruteforce(p):
    """Verbatim from glv_hnp_phase2_20bit.py:146 -- the reference implementation."""
    for a in range(1, 2 * math.isqrt(p // 3) + 3):
        disc = 4 * p - 3 * a * a
        if disc < 0: break
        s = math.isqrt(disc)
        if s * s != disc: continue
        for num in (a + s, a - s):
            if num % 2 == 0:
                b = num // 2
                if b >= 0 and a * a - a * b + b * b == p:
                    return (a, b)
    return None

def j0_traces(a, b):
    return [2*a - b, -2*a + b, -(a + b), a + b, 2*b - a, a - 2*b]

def glv_roots(n):
    sq = tonelli_shanks((n - 3) % n, n)
    if sq is None: return None, None
    inv2 = modinv(2, n)
    r1 = (n - 1 + sq) * inv2 % n
    r2 = (n - 1 + (n - sq)) * inv2 % n
    if (r1 * r1 + r1 + 1) % n != 0: r1, r2 = r2, r1
    if (r1 * r1 + r1 + 1) % n != 0: return None, None
    return min(r1, r2), max(r1, r2)

def lam_star(lam, n):
    return min(lam % n, n - (lam % n)) / n


# ---------------------------------------------------------------------------
# Signatures
# ---------------------------------------------------------------------------

def scales(n, k1_bound, k2_bound):
    """(S_K1, S_D, S_K2, S_KANNAN) -- unchanged from the baseline."""
    return (n // k1_bound, 1, max(1, n // k2_bound), n)

def gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2_bound, seed=42):
    rng = random.Random(seed)
    sigs = []
    attempts = 0
    while len(sigs) < m and attempts < 200000:
        attempts += 1
        k1 = rng.randint(0, k1_bound - 1)
        k2 = rng.randint(0, k2_bound - 1)
        k_full = (k1 + lam * k2) % n
        if k_full == 0: continue
        R = ec_mul(G, k_full, p)
        if R is None: continue
        r = R[0] % n
        if r == 0: continue
        h = rng.randint(0, n - 1)
        s = modinv(k_full, n) * (h + d_secret * r) % n
        if s == 0: continue
        s_inv = modinv(s, n)
        A = h * s_inv % n
        B = r * s_inv % n
        assert (A + B * d_secret) % n == k_full
        sigs.append({'A': A, 'B': B, 'k1': k1, 'k2': k2})
    return sigs


# ---------------------------------------------------------------------------
# Lattice variants
# ---------------------------------------------------------------------------

def offsets(k1_bound, k2_bound, center):
    return (k1_bound // 2, k2_bound // 2) if center else (0, 0)


def build_v1(sigs, n, lam, k1_bound, k2_bound, center=False):
    """Baseline (2026-06-15) lattice, dim 2m+2, optionally centered."""
    m = len(sigs)
    dim = 2 * m + 2
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    off1, off2 = offsets(k1_bound, k2_bound, center)
    M = [[0] * dim for _ in range(dim)]
    for i in range(m):
        M[i][i] = n * S_K1
    for i in range(m):
        M[m][i] = sigs[i]['B'] * S_K1
    M[m][m] = S_D
    for i in range(m):
        M[m + 1 + i][i] = -lam * S_K1
        M[m + 1 + i][m + 1 + i] = S_K2
    for i in range(m):
        Ap = (sigs[i]['A'] - off1 - lam * off2) % n
        M[2 * m + 1][i] = Ap * S_K1
    M[2 * m + 1][dim - 1] = S_KAN
    return M


def planted_v1(sigs, d_secret, n, k1_bound, k2_bound, center=False):
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    off1, off2 = offsets(k1_bound, k2_bound, center)
    v = [0] * (2 * m + 2)
    for i in range(m):
        v[i] = (sigs[i]['k1'] - off1) * S_K1
        v[m + 1 + i] = (sigs[i]['k2'] - off2) * S_K2
    v[m] = d_secret * S_D
    v[2 * m + 1] = S_KAN
    return v


def build_v2(sigs, n, lam, k1_bound, k2_bound, center=False):
    """Projected lattice (d-column removed), dim 2m+1, full rank."""
    m = len(sigs)
    dim = 2 * m + 1
    S_K1, _S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    off1, off2 = offsets(k1_bound, k2_bound, center)
    u = modinv(sigs[0]['B'] % n, n)
    C = [sigs[i]['B'] * u % n for i in range(m)]      # C[0] == 1
    assert C[0] == 1
    M = [[0] * dim for _ in range(dim)]
    # row 0: g = (1, C_1, ..., C_{m-1})
    for i in range(m):
        M[0][i] = C[i] * S_K1
    # rows 1..m-1: n*e_j, j = 1..m-1
    for j in range(1, m):
        M[j][j] = n * S_K1
    # rows m..2m-1: the k2 rows
    for i in range(m):
        M[m + i][i] = -lam * S_K1
        M[m + i][m + i] = S_K2
    # row 2m: Kannan
    for i in range(m):
        Ap = (sigs[i]['A'] - off1 - lam * off2) % n
        M[2 * m][i] = Ap * S_K1
    M[2 * m][dim - 1] = S_KAN
    return M


def planted_v2(sigs, n, k1_bound, k2_bound, center=False):
    m = len(sigs)
    S_K1, _S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    off1, off2 = offsets(k1_bound, k2_bound, center)
    v = [0] * (2 * m + 1)
    for i in range(m):
        v[i] = (sigs[i]['k1'] - off1) * S_K1
        v[m + i] = (sigs[i]['k2'] - off2) * S_K2
    v[2 * m] = S_KAN
    return v


VARIANTS = {
    'V1':  dict(proj=False, center=False),
    'V1c': dict(proj=False, center=True),
    'V2':  dict(proj=True,  center=False),
    'V2c': dict(proj=True,  center=True),
}


def build(variant, sigs, n, lam, k1_bound, k2_bound):
    cfg = VARIANTS[variant]
    f = build_v2 if cfg['proj'] else build_v1
    return f(sigs, n, lam, k1_bound, k2_bound, center=cfg['center'])


def planted(variant, sigs, d_secret, n, k1_bound, k2_bound):
    cfg = VARIANTS[variant]
    if cfg['proj']:
        return planted_v2(sigs, n, k1_bound, k2_bound, center=cfg['center'])
    return planted_v1(sigs, d_secret, n, k1_bound, k2_bound, center=cfg['center'])


# ---------------------------------------------------------------------------
# Recovery
# ---------------------------------------------------------------------------

def norm(v):
    return math.sqrt(sum(x * x for x in v))


def recover_v1(rows, m, n, S_KAN, d_secret):
    dim = 2 * m + 2
    for row in rows:
        if abs(row[dim - 1]) != S_KAN: continue
        sign = 1 if row[dim - 1] > 0 else -1
        d_cand = (sign * row[m]) % n
        if d_cand and d_cand == d_secret:
            return d_cand
    return None


def recover_v2(rows, m, n, lam, sigs, k1_bound, k2_bound, center, d_secret):
    """Read the nonce off the Kannan row, then solve for d."""
    S_K1, _S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    off1, off2 = offsets(k1_bound, k2_bound, center)
    dim = 2 * m + 1
    B0inv = modinv(sigs[0]['B'] % n, n)
    for row in rows:
        if abs(row[dim - 1]) != S_KAN: continue
        sign = 1 if row[dim - 1] > 0 else -1
        if sign * row[0] % S_K1 or sign * row[m] % S_K2:
            continue
        k1_0 = sign * row[0] // S_K1 + off1
        k2_0 = sign * row[m] // S_K2 + off2
        k_full = (k1_0 + lam * k2_0) % n
        d_cand = (k_full - sigs[0]['A']) * B0inv % n
        if d_cand and d_cand == d_secret:
            return d_cand
    return None


def run_once(variant, curve, m, d_secret, k1_bound, seed=42,
             use_bkz=False, bkz_beta=20):
    """Returns (recovered, ||planted||, ||shortest reduced row||)."""
    p, b, n, lam, G = curve
    cfg = VARIANTS[variant]
    k2_bound = math.isqrt(n) + 1
    sigs = gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2_bound, seed)
    if len(sigs) < m:
        return None
    M = build(variant, sigs, n, lam, k1_bound, k2_bound)
    dim = len(M)
    A = IntegerMatrix.from_matrix(M)
    if use_bkz:
        BKZ.reduction(A, BKZ.Param(bkz_beta))
    else:
        LLL.reduction(A)
    rows = [[A[i][j] for j in range(dim)] for i in range(dim)]
    _, _, _, S_KAN = scales(n, k1_bound, k2_bound)
    if cfg['proj']:
        ok = recover_v2(rows, m, n, lam, sigs, k1_bound, k2_bound,
                        cfg['center'], d_secret) is not None
    else:
        ok = recover_v1(rows, m, n, S_KAN, d_secret) is not None
    pv = planted(variant, sigs, d_secret, n, k1_bound, k2_bound)
    nz = [norm(r) for r in rows if any(r)]
    return (ok, norm(pv), min(nz) if nz else float('nan'))


SEEDS = [42, 1234, 9999, 555, 31337]


def success_rate(variant, curve, m, k1_bound, seeds=SEEDS,
                 use_bkz=False, bkz_beta=20):
    """Returns (wins, total, mean sv/pv)."""
    wins, ratios = 0, []
    n = curve[2]
    for seed in seeds:
        d_trial = random.Random(seed + 7777).randint(1, n - 1)
        res = run_once(variant, curve, m, d_trial, k1_bound, seed,
                       use_bkz=use_bkz, bkz_beta=bkz_beta)
        if res is None: continue
        ok, pn, sn = res
        wins += bool(ok)
        ratios.append(sn / pn if pn else float('nan'))
    return wins, len(seeds), (sum(ratios) / len(ratios) if ratios else float('nan'))


# ===========================================================================

print("=" * 78)
print("Thread 23 — reformulate the Phase-2 lattice so the planted vector is L1")
print("=" * 78)

HIST = [
    # label,             p,    b, n,    lam,  K1, m
    ("8-bit/199",        211,  2, 199,  106,  2,  6),
    ("12-bit/2557",      2557, 2, 2659, 1755, 8,  8),
    ("12-bit/2677 FAIL", 2677, 2, 2647, 185,  8,  10),
]

hist = []
for label, p, b, n, lam, k1, m in HIST:
    G = find_generator(p, b, n)
    assert G is not None, f"no generator for {label}"
    assert (lam * lam + lam + 1) % n == 0, f"bad lam for {label}"
    hist.append((label, (p, b, n, lam, G), k1, m))

ORDER = ['V1', 'V1c', 'V2', 'V2c']

# ---------------------------------------------------------------------------
# E0 — exactness checks: planted vector really is in each lattice, and the
#      determinants are what the projection argument predicts.
# ---------------------------------------------------------------------------

print("\n" + "-" * 78)
print("E0: membership of the planted vector + determinant of each variant")
print("-" * 78)

from sympy import Matrix, Rational

label, curve, k1_e0, m_e0 = hist[1]
p, b, n, lam, G = curve
k2b = math.isqrt(n) + 1
d0 = random.Random(42 + 7777).randint(1, n - 1)
sigs0 = gen_signatures(G, d0, m_e0, n, lam, p, k1_e0, k2b, 42)
S_K1, S_D, S_K2, S_KAN = scales(n, k1_e0, k2b)

print(f"probe curve {label}: n={n}, m={m_e0}, K1={k1_e0}, K2={k2b}, "
      f"S_K1={S_K1}, S_K2={S_K2}, S_KAN={S_KAN}")
print(f"{'variant':<8} {'dim':>4} {'in lattice':>11} {'det':>26} "
      f"{'det/det(V1)':>13} {'||planted||/n':>14}")

det_v1 = None
for v in ORDER:
    M = build(v, sigs0, n, lam, k1_e0, k2b)
    pv = planted(v, sigs0, d0, n, k1_e0, k2b)
    MM = Matrix(M)
    det = abs(MM.det())
    x = MM.T.solve(Matrix(pv))                      # planted = x^T * M
    integral = all(Rational(xi).q == 1 for xi in x)
    if det_v1 is None: det_v1 = det
    print(f"{v:<8} {len(M):>4} {str(integral):>11} {str(det):>26} "
          f"{str(sympy.nsimplify(Rational(det, det_v1))):>13} "
          f"{norm(pv)/n:>14.4f}")

print(f"\npredicted det(V1) = (n*S_K1)^m * S_D * S_K2^m * S_KAN = "
      f"{(n*S_K1)**m_e0 * S_D * S_K2**m_e0 * S_KAN}")
print(f"predicted det(V2) = det(V1)/(n*S_D)              = "
      f"{(n*S_K1)**m_e0 * S_D * S_K2**m_e0 * S_KAN // (n*S_D)}")
print("(so V2 is exactly the projection of V1 along the trivial vector n*S_D*e_m)")

print("\nE0b: Cornacchia eisenstein_decompose vs the O(sqrt p) brute force of")
print("     glv_hnp_phase2_20bit.py:146 (trace SETS must agree, not the tuple:")
print("     the six associates give the same six traces).")
print(f"{'range':>8} {'p=1mod3':>8} {'cornacchia ok':>14} {'trace sets equal':>17}")
for lo, hi, nm in [(2**8, 2**9, '8b'), (2**12, 2**13, '12b'),
                   (2**16, 2**17, '17b'), (2**19, 2**20, '20b')]:
    pp = int(sympy.nextprime(lo)); tot = ok = same = 0
    while pp < hi and tot < 120:
        if pp % 3 == 1:
            tot += 1
            rc, rb = eisenstein_decompose(pp), eisenstein_decompose_bruteforce(pp)
            if rc is not None:
                ok += 1
                if rb is not None and sorted(j0_traces(*rc)) == sorted(j0_traces(*rb)):
                    same += 1
        pp = int(sympy.nextprime(pp))
    print(f"{nm:>8} {tot:>8} {str(ok)+'/'+str(tot):>14} {str(same)+'/'+str(tot):>17}")


# ---------------------------------------------------------------------------
# E1 — historical curves at their historical (K1, m)
# ---------------------------------------------------------------------------

print("\n" + "-" * 78)
print("E1: the three historical Phase-2 curves, at their historical (K1, m)")
print("-" * 78)
print("sv/pv = ||shortest reduced row|| / ||planted||.  sv/pv >= 1 means the")
print("planted vector IS a shortest vector (the Thread 23 goal).\n")

hdr = f"{'curve':<18} {'lam*':>6} {'K1':>3} {'m':>3} "
for v in ORDER:
    hdr += f"{v+' win':>8} {v+' sv/pv':>10}"
print(hdr)
for label, curve, k1, m in hist:
    p, b, n, lam, G = curve
    line = f"{label:<18} {lam_star(lam,n):>6.4f} {k1:>3} {m:>3} "
    for v in ORDER:
        w, t, r = success_rate(v, curve, m, k1)
        line += f"{str(w)+'/'+str(t):>8} {r:>10.4f}"
    print(line)


# ---------------------------------------------------------------------------
# E2 — the falsifier: the T4 K1-wall grid for all four variants
# ---------------------------------------------------------------------------

print("\n" + "-" * 78)
print("E2: K1 wall (the 2026-07-29 T4 grid), m=12, 5 seeds, all four variants")
print("-" * 78)
print("T4 baseline for reference (V1): 12-bit/2557 wall at K1~12-16,")
print("                                12-bit/2677 wall at K1~4-6.\n")

K1_GRID = [2, 3, 4, 6, 8, 12, 16, 24, 32, 48]
M_E2 = 12

for label, curve, _k1, _m in hist:
    p, b, n, lam, G = curve
    if n < 2000: continue
    k2b = math.isqrt(n) + 1
    print(f"\n{label}   lam*={lam_star(lam,n):.4f}  n={n}  K2={k2b}")
    print(f"{'variant':<8} " + " ".join(f"K1={k:<4}" for k in K1_GRID))
    walls = {}
    for v in ORDER:
        cells, wall = [], None
        for k1 in K1_GRID:
            w, t, _ = success_rate(v, curve, M_E2, k1)
            cells.append(f"{w}/{t} ")
            if w == t: wall = k1
        walls[v] = wall
        print(f"{v:<8} " + " ".join(f"{c:<7}" for c in cells))
    print(f"{'eff':<8} " + " ".join(f"{k*k2b/n:<7.3f}" for k in K1_GRID))
    print("last K1 with 5/5: " + ", ".join(f"{v}={walls[v]}" for v in ORDER))

    print(f"\n  sv/pv at each K1 (mean over seeds):")
    print(f"  {'variant':<8} " + " ".join(f"K1={k:<4}" for k in K1_GRID))
    for v in ORDER:
        cells = []
        for k1 in K1_GRID:
            _, _, r = success_rate(v, curve, M_E2, k1)
            cells.append(f"{r:.3f}")
        print(f"  {v:<8} " + " ".join(f"{c:<7}" for c in cells))


# ---------------------------------------------------------------------------
# E3 — m-dependence of sv/pv:  does the projected planted vector stay lambda_1
#      as m grows?  Theory says the m copies of the 2-D block
#      L2 = <(n*S_K1,0), (-lam*S_K1, S_K2)> have lambda_1 ~ n/sqrt(eff) while
#      ||planted|| ~ n*sqrt(2m/3+1), so the planted vector loses its lambda_1
#      status once m > (3/2)(1/eff - 1).
# ---------------------------------------------------------------------------

print("\n" + "-" * 78)
print("E3: m-dependence of sv/pv on the lam*=0.07 curve, K1=4 (eff=0.079)")
print("-" * 78)
fail_curve = [c for lbl, c, _, _ in hist if c[2] == 2647][0]
n_f = fail_curve[2]
k2_f = math.isqrt(n_f) + 1
K1_E3 = 4
eff_e3 = K1_E3 * k2_f / n_f
m_pred = 1.5 * (1.0 / eff_e3 - 1.0)
print(f"eff = {eff_e3:.4f}; predicted m where planted stops being lambda_1: "
      f"m ~ {m_pred:.1f}")
print(f"{'m':>4} " + " ".join(f"{v+' win':>8} {v+' sv/pv':>10}" for v in ORDER))
for m_try in (4, 6, 8, 12, 16, 24, 32):
    line = f"{m_try:>4} "
    for v in ORDER:
        w, t, r = success_rate(v, fail_curve, m_try, K1_E3)
        line += f"{str(w)+'/'+str(t):>8} {r:>10.4f}"
    print(line)


# ---------------------------------------------------------------------------
# E4 — 20-bit replication of the wall, V1 vs V2c
# ---------------------------------------------------------------------------

print("\n" + "-" * 78)
print("E4: 20-bit replication (fresh j=0 GLV curves), V1 / V1c / V2c, m=12")
print("-" * 78)

def build_curve(p, n, seed=12345):
    lam, _ = glv_roots(n)
    if lam is None: return None
    for b_try in range(1, 60):
        P = find_point(p, b_try)
        if P is None: continue
        if ec_mul(P, n, p) is None:
            G = find_generator(p, b_try, n, seed)
            if G is None: continue
            return (p, b_try, n, lam, G)
    return None

def search_curves(lo, hi, want=4):
    out = []
    p = int(sympy.nextprime(lo))
    while p < hi and len(out) < want:
        if p % 3 == 1:
            eis = eisenstein_decompose(p)
            if eis is not None:
                for t in j0_traces(*eis):
                    nc = p + 1 - t
                    if nc < 2 or not sympy.isprime(nc) or nc % 3 != 1:
                        continue
                    cur = build_curve(p, nc)
                    if cur is not None:
                        out.append(cur)
                        break
        p = int(sympy.nextprime(p))
    return out

curves20 = search_curves(2**19, 2**20, want=6)
print(f"found {len(curves20)} 20-bit curves")
print("swept by eff = K1*K2/n (K2 = isqrt(n)+1 = ~726 here, so the raw K1 grid")
print("of E2 would top out at eff=0.07 and every cell would pass).\n")

EFF_GRID = [0.04, 0.08, 0.12, 0.16, 0.24, 0.31, 0.40, 0.47, 0.63, 0.80]
print(f"{'p':>8} {'n':>8} {'lam*':>7} {'variant':<6} "
      + " ".join(f"{e:<6.2f}" for e in EFF_GRID) + "  wall(eff)")
walls20 = {}
for cur in curves20:
    p, b, n, lam, G = cur
    k2b = math.isqrt(n) + 1
    k1s = [max(1, round(e * n / k2b)) for e in EFF_GRID]
    for v in ('V1', 'V1c', 'V2c'):
        cells, wall = [], None
        for e, k1 in zip(EFF_GRID, k1s):
            w, t, _ = success_rate(v, cur, 12, k1)
            cells.append(f"{w}/{t}")
            if w == t: wall = e
        walls20.setdefault(v, []).append((lam_star(lam, n), wall))
        print(f"{p:>8} {n:>8} {lam_star(lam,n):>7.4f} {v:<6} "
              + " ".join(f"{c:<6}" for c in cells) + f"  {wall}")
    print()

print("wall (largest eff still 5/5) vs lam*, per variant:")
for v in ('V1', 'V1c', 'V2c'):
    rows = walls20.get(v, [])
    if not rows: continue
    ws = [w for _, w in rows if w is not None]
    print(f"  {v:<4} walls={[w for _, w in rows]}  "
          f"median={sorted(ws)[len(ws)//2] if ws else None}  "
          f"lam*={[round(l,3) for l, _ in rows]}")

print("\nDone.")
