"""
GLV-HNP Phase 2 — Thread 20c: controlled test of nu_hat as the Phase 2 separator.

Background
----------
Thread 20a falsified mu = min(lam,n-lam)/n as a Phase 2 predictor.  Thread 20b
(100 curves, 24 seeds each, 9600 trials) falsified the residual "hard band"
conjecture -- mu is flat -- but found a real monotone signal in the
lattice-geometric invariant

    nu_hat = lambda_1(L2) / sqrt(det L2),

where L2 is the NON-PLANTED 2-dimensional sublattice generated by

    u = (n * S_K1, 0)        [modular row i]
    v = (-lam * S_K1, S_K2)  [GLV row m+1+i]

on the coordinate pair (i, m+1+i).  det(L2) = n*S_K1*S_K2 is independent of
lam, so nu_hat isolates exactly the lam-dependence of the geometry.

    Spearman(nu_hat, p_hat):  m=8 -0.339, m=9 -0.468, m=10 -0.533, m=11 -0.568

The sign is the OPPOSITE of the naive guess.  A *short* rival vector (small
nu_hat) makes the attack EASIER, not harder.  Reading via lambda_1*lambda_2 ~
det: small nu_hat means L2 is skew, so its second minimum lambda_2 ~
det/lambda_1 is unusually long, and the planted vector is comparatively short.
A balanced L2 (nu_hat -> 1) surrounds the planted vector with 2m rival vectors
all of norm ~sqrt(det), crowding it out.

This script tests that as a controlled claim rather than a fitted correlation.

Design
------
Arm 1 (20-bit, matched mu):  harvest curves with nu_hat <= LOW_CUT and
  nu_hat >= HIGH_CUT, both restricted to mu in (0.05, 0.45) so the groups are
  comparable in mu; verify with a permutation test that mu does NOT differ
  between groups (no confound), then compare p_hat.
Arm 2 (24-bit): the same low/high contrast at a different bit size, to check
  the effect is not a 20-bit artifact.
Arm 3: permutation p-value for the Spearman correlation on a fresh pooled
  sample, plus the historical anchor curves as out-of-sample checks.

H-nu' : p_hat is higher for low-nu_hat curves than for high-nu_hat curves.
Falsifier: permutation p > 0.05 in Arm 1, or sign reversal / null in Arm 2.

Run: python3 glv_hnp_phase2_nuhat_control.py
"""

import math
import random
import sys
import time

import sympy

import importlib.util
_spec = importlib.util.spec_from_file_location(
    "_t20a", __file__.rsplit("/", 1)[0] + "/glv_hnp_phase2_lambda_threshold_20a.py")
_t20a = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_t20a)

eisenstein_decompose = _t20a.eisenstein_decompose
j0_traces = _t20a.j0_traces
glv_eigenvalues = _t20a.glv_eigenvalues
mu_of = _t20a.mu_of
identify_twist = _t20a.identify_twist
find_generator = _t20a.find_generator
rival_sublattice_nu = _t20a.rival_sublattice_nu
run_experiment = _t20a.run_experiment

_spec_b = importlib.util.spec_from_file_location(
    "_t20b", __file__.rsplit("/", 1)[0] + "/glv_hnp_phase2_mu_response.py")
_t20b = importlib.util.module_from_spec(_spec_b)
_spec_b.loader.exec_module(_t20b)
perm_test = _t20b.perm_test
spearman = _t20b.spearman

# ---------------------------------------------------------------------------

EFF_TARGET = 0.05
LOW_CUT, HIGH_CUT = 0.45, 0.90
MU_LO, MU_HI = 0.05, 0.45
GROUP_N = 30
SEEDS_N = 48
M_FIXED = [8, 9, 10, 11]
PERM_ITERS = 20000

def k1k2(n):
    return max(2, int(EFF_TARGET * math.sqrt(n))), math.isqrt(n) + 1

def harvest_by_nuhat(bits_lo, bits_hi, group_n, max_primes=200000):
    """Collect group_n curves with nu_hat<=LOW_CUT and group_n with >=HIGH_CUT."""
    low, high, seen = [], [], set()
    scanned = 0
    p = int(sympy.nextprime(bits_lo))
    t0 = time.time()
    while p < bits_hi and scanned < max_primes:
        scanned += 1
        if p % 3 == 1:
            eis = eisenstein_decompose(p)
            if eis is not None:
                for t in j0_traces(*eis):
                    n = p + 1 - t
                    if n < 2 or n in seen or n % 3 != 1 or not sympy.isprime(n):
                        continue
                    roots = glv_eigenvalues(n)
                    if roots is None:
                        continue
                    lam = roots[0]
                    mu = mu_of(lam, n)
                    if not (MU_LO < mu < MU_HI):
                        continue
                    k1, k2 = k1k2(n)
                    _, _, nu_hat = rival_sublattice_nu(n, lam, k1, k2)
                    tgt = None
                    if nu_hat <= LOW_CUT and len(low) < group_n:
                        tgt = low
                    elif nu_hat >= HIGH_CUT and len(high) < group_n:
                        tgt = high
                    if tgt is None:
                        continue
                    b = identify_twist(p, n)
                    if b is None:
                        break
                    G = find_generator(p, b, n)
                    if G is None:
                        break
                    seen.add(n)
                    tgt.append({'p': p, 'b': b, 'n': n, 'lam': lam,
                                'mu': mu, 'nu_hat': nu_hat, 'G': G})
                    break
        if len(low) >= group_n and len(high) >= group_n:
            break
        p = int(sympy.nextprime(p))
    print(f"  harvested low={len(low)} high={len(high)} from {scanned} primes "
          f"in {time.time()-t0:.1f}s")
    return low, high

def measure(curve, m, seeds_n, seed_base=0):
    n = curve['n']
    k1, k2 = k1k2(n)
    wins = 0
    for s in range(seeds_n):
        seed = seed_base + 1000 * m + s
        d = random.Random(seed + 7777).randint(1, n - 1)
        wins += run_experiment(curve['p'], n, curve['lam'], curve['G'],
                               m, d, k1, k2, seed)
    return wins / seeds_n

def run_arm(label, low, high, seeds_n, rng, m_fixed=M_FIXED):
    print(f"\n--- {label} ---")
    if not low or not high:
        print("  SKIPPED: a group is empty")
        return
    for c in low + high:
        c['p_hat'] = {m: measure(c, m, seeds_n) for m in m_fixed}
    curves = low + high
    is_low = [True] * len(low) + [False] * len(high)

    mus = [c['mu'] for c in curves]
    d_mu, p_mu = perm_test(mus, is_low, PERM_ITERS, rng)
    print(f"  nu_hat  low group: mean={sum(c['nu_hat'] for c in low)/len(low):.3f} "
          f"[{min(c['nu_hat'] for c in low):.3f}, {max(c['nu_hat'] for c in low):.3f}]")
    print(f"  nu_hat high group: mean={sum(c['nu_hat'] for c in high)/len(high):.3f} "
          f"[{min(c['nu_hat'] for c in high):.3f}, {max(c['nu_hat'] for c in high):.3f}]")
    print(f"  CONFOUND CHECK mu: low={sum(c['mu'] for c in low)/len(low):.3f} "
          f"high={sum(c['mu'] for c in high)/len(high):.3f} "
          f"diff={d_mu:+.3f} perm p={p_mu:.4f} "
          f"({'balanced' if p_mu > 0.05 else 'IMBALANCED -- confounded'})")

    for m in m_fixed:
        vals = [c['p_hat'][m] for c in curves]
        obs, pv = perm_test(vals, is_low, PERM_ITERS, rng)
        lo_m = sum(c['p_hat'][m] for c in low) / len(low)
        hi_m = sum(c['p_hat'][m] for c in high) / len(high)
        star = '***' if pv < 0.001 else '**' if pv < 0.01 else '*' if pv < 0.05 else ''
        print(f"  m={m:<3} p_hat(low nu_hat)={lo_m:.3f}  p_hat(high nu_hat)={hi_m:.3f}  "
              f"diff={obs:+.3f}  perm p={pv:.4f} {star}")

def spearman_perm_p(xs, ys, iters, rng):
    obs = spearman(xs, ys)
    ys2 = list(ys)
    hits = 0
    for _ in range(iters):
        rng.shuffle(ys2)
        if abs(spearman(xs, ys2)) >= abs(obs) - 1e-15:
            hits += 1
    return obs, (hits + 1) / (iters + 1)

def main():
    print("=" * 78)
    print("GLV-HNP Phase 2 — Thread 20c: controlled test of nu_hat")
    print("=" * 78)
    print(f"eff={EFF_TARGET}, cuts: low<={LOW_CUT} high>={HIGH_CUT}, "
          f"mu restricted to ({MU_LO},{MU_HI}), {SEEDS_N} seeds/(curve,m)")
    rng = random.Random(20260729)

    t0 = time.time()
    print("\n--- Arm 1 harvest: 20-bit ---")
    low20, high20 = harvest_by_nuhat(2 ** 19, 2 ** 20, GROUP_N)
    run_arm("Arm 1: 20-bit, mu-matched low vs high nu_hat", low20, high20, SEEDS_N, rng)

    print("\n--- Arm 2 harvest: 24-bit ---")
    low24, high24 = harvest_by_nuhat(2 ** 23, 2 ** 24, 20)
    run_arm("Arm 2: 24-bit replication", low24, high24, SEEDS_N, rng)

    print("\n--- Arm 3: Spearman permutation p-values (pooled 20-bit sample) ---")
    pooled = low20 + high20
    for m in M_FIXED:
        xs = [c['nu_hat'] for c in pooled]
        ys = [c['p_hat'][m] for c in pooled]
        r, pv = spearman_perm_p(xs, ys, 5000, rng)
        print(f"  m={m:<3} spearman(nu_hat, p_hat)={r:+.3f}  perm p={pv:.4f}")

    print("\n--- Arm 4: historical anchor curves (out of sample) ---")
    anchors = [(211, 2, 199, 106, 2, "8-bit/199,  3/3 at m=4"),
               (2557, 2, 2659, 1755, 8, "12-bit/2557, 3/3 at m=7"),
               (2677, 2, 2647, 185, 8, "12-bit/2677, NEVER 3/3")]
    for p, b, n, lam, k1, note in anchors:
        k2 = math.isqrt(n) + 1
        _, _, nu_hat = rival_sublattice_nu(n, lam, k1, k2)
        print(f"  n={n:<6} mu={mu_of(lam,n):.4f} nu_hat={nu_hat:.4f}   {note}")
    print("  (2026-07-26 Thread 20a single binary failure: n=525913, "
          "nu_hat=0.9993 = 96th pct of that sample)")

    print("\n--- Arm 5: causal test — ONE fixed curve, synthetic lambda sweep ---")
    print("  The lattice attack only needs the nonce to be generated as")
    print("  k = k1 + lam*k2 mod n with k1 small; lam need not be a GLV")
    print("  eigenvalue for the HNP instance to be well posed.  So we can hold")
    print("  (p, b, n, G, K1, K2) FIXED and vary lam alone.  Any curve-level")
    print("  confound is eliminated by construction.")
    base = low20[0]
    p0, n0, G0 = base['p'], base['n'], base['G']
    k1_0, k2_0 = k1k2(n0)
    print(f"  fixed curve: p={p0}, n={n0}, K1={k1_0}, K2={k2_0}")
    lam_rng = random.Random(31337)
    samples = []
    for _ in range(120):
        lam = lam_rng.randint(2, n0 - 2)
        _, _, nh = rival_sublattice_nu(n0, lam, k1_0, k2_0)
        samples.append({'lam': lam, 'nu_hat': nh, 'mu': mu_of(lam, n0),
                        'p': p0, 'n': n0, 'G': G0})
    for s in samples:
        s['p_hat'] = {9: measure(s, 9, 24)}
    xs = [s['nu_hat'] for s in samples]
    ys = [s['p_hat'][9] for s in samples]
    ms = [s['mu'] for s in samples]
    r_nu, p_nu = spearman_perm_p(xs, ys, 5000, rng)
    r_mu, p_mu2 = spearman_perm_p(ms, ys, 5000, rng)
    print(f"  n=120 synthetic lambdas, m=9, 24 seeds each")
    print(f"    spearman(nu_hat, p_hat) = {r_nu:+.3f}  perm p={p_nu:.4f}")
    print(f"    spearman(mu,     p_hat) = {r_mu:+.3f}  perm p={p_mu2:.4f}")
    order = sorted(samples, key=lambda s: s['nu_hat'])
    third = len(order) // 3
    for name, grp in (("low  nu_hat tertile", order[:third]),
                      ("mid  nu_hat tertile", order[third:2 * third]),
                      ("high nu_hat tertile", order[2 * third:])):
        print(f"    {name}: nu_hat={sum(s['nu_hat'] for s in grp)/len(grp):.3f}  "
              f"p_hat={sum(s['p_hat'][9] for s in grp)/len(grp):.3f}  "
              f"mu={sum(s['mu'] for s in grp)/len(grp):.3f}")

    print(f"\nTotal wall time {time.time()-t0:.1f}s")
    print("Done.")

if __name__ == '__main__':
    sys.exit(main())
