"""
GLV-HNP Phase 2, Thread 23: reformulate the lattice so the target is a BDD
solution rather than a (non-)shortest vector.

Background (RESEARCH_AUTOLAB_LOG.md, 2026-07-29 entry, exp T5):
  In the Phase-2 Kannan lattice `build_glv_lattice` (dim 2m+2) the shortest
  vector after LLL is ALWAYS the trivial vector n*S_D*e_m (|sv[m]|/n = 1.0000
  on every curve tested), 2-3x shorter than the planted vector.  Recovery is
  therefore not an SVP condition but a BDD/coset condition.  That run proposed
  Thread 23: quotient out the trivial e_m direction and solve BDD directly.

This script does that, and adds a second, cheaper improvement that falls out
of the same analysis (target centering).

Three formulations, all on identical signature sets:

  K   baseline Kannan embedding, dim 2m+2, LLL, scan rows for |last|=S_KANNAN.
      (verbatim from glv_hnp_phase2_20bit.py:262 / lambda_threshold.py:254)

  P   projected CVP.  Drop the d-column and the Kannan column.  The lattice
      L' subset Z^{2m} is generated by the 2m+1 rows

          r_i     = n*S_K1 * e_i                       (i = 0..m-1)
          r_d     = (B_0*S_K1, ..., B_{m-1}*S_K1 | 0)
          r_{2,i} = -lam*S_K1 * e_i  +  S_K2 * e_{m+i}

      (rank 2m; the relation n*r_d = sum_i B_i*r_i is exactly the trivial
      vector that T5 found).  Target

          t = (-A_0*S_K1, ..., -A_{m-1}*S_K1 | 0, ..., 0).

      For the lattice point v = sum c_i r_i + d r_d + sum k2_i r_{2,i},

          v - t = (k1_i*S_K1 | k2_i*S_K2)

      because A_i + B_i*d - lam*k2_i = k1_i (mod n).  So the planted solution
      is the BDD solution, d is the r_d coefficient, and d is read back
      algebraically from the recovered (k1_1, k2_1) without needing the LLL
      transformation matrix.

  PC  projected CVP with a CENTERED target: shift by (c1*S_K1 | c2*S_K2) with
      c1 = K1//2, c2 = K2//2.  The error becomes ((k1_i-c1)*S_K1 |
      (k2_i-c2)*S_K2), whose expected norm is 2x smaller (E[x^2] = X^2/12
      instead of X^2/3 for x ~ U[0,X)).  Under the Gaussian-heuristic BDD
      condition ||e|| < lambda_1/2 this predicts a 4x outward shift of the
      K1 wall.

Capacity model (derived here, tested in E4):
  det L' = n^{m-1} * S_K1^m * S_K2^m = n^{2m-1} / eff^m,  eff = K1*K2/n,
  so  lambda_1(L') ~ sqrt(m/(pi e)) * n^{1-1/(2m)} / sqrt(eff),
  while ||e_planted|| ~ n*sqrt(2m/3) (P) or n*sqrt(m/6) (PC).
  ||e|| < lambda_1/2  becomes

      sqrt(eff) * n^{1/(2m)}  <  0.2096   (P)
      sqrt(eff) * n^{1/(2m)}  <  0.4192   (PC)

  i.e.  K1 < K1_max = C^2 * n^(1/2 - 1/m) / kappa,  with kappa = K2/sqrt(n)
  and C = 0.2096 (P) / 0.4192 (PC).

Experiments:
  E1  K1 wall on the three historical curves, all three formulations.
  E2  geometry: ||e_planted||, lambda_1(L') from LLL, ratio, BDD margin.
  E3  does the trivial vector still dominate?  (sv of L' vs sv of Kannan L)
  E4  capacity law: predicted vs measured K1 wall on fresh 12/17/20-bit curves.

Run: python3 glv_hnp_phase2_bdd.py
Deps: fpylll (+ cysignals), sympy.
"""

import math
import random
import sys

import sympy
from fpylll import IntegerMatrix, LLL, CVP, GSO

# ---------------------------------------------------------------------------
# Minimal EC arithmetic (a=0 short Weierstrass) -- copied from
# glv_hnp_phase2_lambda_threshold.py so this script stands alone.
# ---------------------------------------------------------------------------

def modinv(a, m):
    return pow(a, -1, m)

def ec_add(P, Q, p):
    if P is None: return Q
    if Q is None: return P
    x1, y1 = P; x2, y2 = Q
    if x1 == x2:
        if (y1 + y2) % p == 0: return None
        s = 3 * x1 * x1 * modinv(2 * y1, p) % p
    else:
        s = (y2 - y1) * modinv(x2 - x1, p) % p
    x3 = (s * s - x1 - x2) % p
    y3 = (s * (x1 - x3) - y1) % p
    return (x3, y3)

def ec_mul(P, k, p):
    if k == 0: return None
    R, Q = None, P
    while k > 0:
        if k & 1: R = ec_add(R, Q, p)
        Q = ec_add(Q, Q, p)
        k >>= 1
    return R

def tonelli_shanks(a, p):
    a %= p
    if a == 0: return 0
    if pow(a, (p - 1) // 2, p) != 1: return None
    if p % 4 == 3: return pow(a, (p + 1) // 4, p)
    q, s = p - 1, 0
    while q % 2 == 0: q //= 2; s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1: z += 1
    mm, c, t, r = s, pow(z, q, p), pow(a, q, p), pow(a, (q + 1) // 2, p)
    while True:
        if t == 0: return 0
        if t == 1: return r
        i, tmp = 0, t
        while tmp != 1: tmp = tmp * tmp % p; i += 1
        b = pow(c, 1 << (mm - i - 1), p)
        mm, c, t, r = i, b * b % p, t * b * b % p, r * b % p

def find_generator(p, b, n, seed=12345):
    rng = random.Random(seed)
    for _ in range(20000):
        x = rng.randint(0, p - 1)
        rhs = (pow(x, 3, p) + b) % p
        y = tonelli_shanks(rhs, p)
        if y is None or y == 0: continue
        P = (x, y)
        if ec_mul(P, n, p) is None and P is not None:
            return P
    return None

# ---------------------------------------------------------------------------
# j=0 CM curve search (Eisenstein)
# ---------------------------------------------------------------------------

def eisenstein_decompose(p):
    """p = a^2 - a*b + b^2 with p = 1 mod 3 (norm form of Z[omega])."""
    if p % 3 != 1: return None
    sq = tonelli_shanks(p - 3, p)          # sqrt(-3) mod p
    if sq is None: return None
    # Cornacchia on x^2 + 3 y^2 = 4p
    a, b = 2 * p, (sq if sq % 2 == 1 else p - sq) % (2 * p)
    if b % 2 == 0: b = 2 * p - b
    lim = math.isqrt(4 * p)
    while b > lim:
        a, b = b, a % b
    r = 4 * p - b * b
    if r % 3 != 0: return None
    c2 = r // 3
    c = math.isqrt(c2)
    if c * c != c2: return None
    # 4p = b^2 + 3c^2  ->  (a_e, b_e) with p = a^2-ab+b^2
    for (u, v) in (((b + 3 * c) // 2, c), ((b - 3 * c) // 2, -c),
                   ((-b + 3 * c) // 2, c), ((b + c) // 2, (b - c) // 2)):
        if u * u - u * v + v * v == p:
            return (u, v)
    return None

def j0_traces(a, b):
    return [2 * a - b, -2 * a + b, -(a + b), a + b, 2 * b - a, a - 2 * b]

def glv_roots(n):
    """The two roots of x^2+x+1 = 0 mod n (n = 1 mod 3), or None."""
    sq = tonelli_shanks((n - 3) % n, n)
    if sq is None: return None
    inv2 = modinv(2, n)
    r1 = (n - 1 + sq) * inv2 % n
    r2 = (n - 1 + (n - sq)) * inv2 % n
    if (r1 * r1 + r1 + 1) % n != 0: r1, r2 = r2, r1
    if (r1 * r1 + r1 + 1) % n != 0: return None
    return (min(r1, r2), max(r1, r2))

def lam_star(lam, n):
    return min(lam, n - lam) / n

def build_curve(p, n, seed=12345):
    rng = random.Random(seed)
    for _ in range(400):
        b = rng.randint(1, p - 1)
        x = rng.randint(0, p - 1)
        rhs = (pow(x, 3, p) + b) % p
        y = tonelli_shanks(rhs, p)
        if y is None or y == 0: continue
        if ec_mul((x, y), n, p) is None:
            G = find_generator(p, b, n, seed=seed)
            if G is not None:
                return (b, G)
    return None

def search_curves(lo, hi, want, seed=12345):
    """j=0 GLV curves with p in [lo,hi), n prime, n = 1 mod 3."""
    out = []
    p = int(sympy.nextprime(lo))
    while p < hi and len(out) < want:
        if p % 3 == 1:
            eis = eisenstein_decompose(p)
            if eis is not None:
                for t in j0_traces(*eis):
                    nc = p + 1 - t
                    if nc < 8 or nc % 3 != 1 or not sympy.isprime(nc):
                        continue
                    roots = glv_roots(nc)
                    if roots is None: continue
                    cur = build_curve(p, nc, seed)
                    if cur is None: continue
                    out.append((p, cur[0], nc, roots[0], cur[1]))
                    break
        p = int(sympy.nextprime(p))
    return out

# ---------------------------------------------------------------------------
# Signatures and scales (verbatim from lambda_threshold.py:227/230)
# ---------------------------------------------------------------------------

def scales(n, k1_bound, k2_bound):
    return (n // k1_bound, 1, max(1, n // k2_bound), n)

def gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2_bound, seed=42):
    rng = random.Random(seed)
    sigs = []
    attempts = 0
    while len(sigs) < m and attempts < 200000:
        attempts += 1
        k1 = rng.randint(0, k1_bound - 1)
        k2 = rng.randint(0, k2_bound - 1)
        k_full = (k1 + lam * k2) % n
        if k_full == 0: continue
        R = ec_mul(G, k_full, p)
        if R is None: continue
        r = R[0] % n
        if r == 0: continue
        h = rng.randint(0, n - 1)
        s = modinv(k_full, n) * (h + d_secret * r) % n
        if s == 0: continue
        s_inv = modinv(s, n)
        A = h * s_inv % n
        B = r * s_inv % n
        assert (A + B * d_secret) % n == k_full
        sigs.append({'A': A, 'B': B, 'k1': k1, 'k2': k2})
    return sigs

def norm(v):
    return math.sqrt(sum(float(x) * float(x) for x in v))

# ---------------------------------------------------------------------------
# Formulation K -- baseline Kannan embedding
# ---------------------------------------------------------------------------

def build_kannan(sigs, n, lam, k1_bound, k2_bound):
    m = len(sigs)
    dim = 2 * m + 2
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    M = [[0] * dim for _ in range(dim)]
    for i in range(m):
        M[i][i] = n * S_K1
    for i in range(m):
        M[m][i] = sigs[i]['B'] * S_K1
    M[m][m] = S_D
    for i in range(m):
        M[m + 1 + i][i] = -lam * S_K1
        M[m + 1 + i][m + 1 + i] = S_K2
    for i in range(m):
        M[2 * m + 1][i] = sigs[i]['A'] * S_K1
    M[2 * m + 1][dim - 1] = S_KAN
    return M

def kannan_planted(sigs, d_secret, n, k1_bound, k2_bound):
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    v = [0] * (2 * m + 2)
    for i in range(m):
        v[i] = sigs[i]['k1'] * S_K1
        v[m + 1 + i] = sigs[i]['k2'] * S_K2
    v[m] = d_secret * S_D
    v[2 * m + 1] = S_KAN
    return v

def build_kannan_centered(sigs, n, lam, k1_bound, k2_bound):
    """Same lattice, shifted embedding row.  The planted vector becomes
    ((k1_i-c1)*S_K1 | (d-n/2)*S_D | (k2_i-c2)*S_K2 | S_KANNAN), i.e. the
    centering of PC applied WITHOUT the projection.  This is the control that
    separates 'centering' from 'projected CVP'."""
    m = len(sigs)
    dim = 2 * m + 2
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    c1, c2 = k1_bound // 2, k2_bound // 2
    M = build_kannan(sigs, n, lam, k1_bound, k2_bound)
    for i in range(m):
        M[2 * m + 1][i] -= c1 * S_K1
        M[2 * m + 1][m + 1 + i] = -c2 * S_K2
    M[2 * m + 1][m] = -(n // 2) * S_D
    return M

def run_K(sigs, n, lam, k1_bound, k2_bound, d_secret, centered=False):
    m = len(sigs)
    dim = 2 * m + 2
    _, _, _, S_KAN = scales(n, k1_bound, k2_bound)
    shift = (n // 2) if centered else 0
    M = (build_kannan_centered if centered else build_kannan)(
        sigs, n, lam, k1_bound, k2_bound)
    A = IntegerMatrix.from_matrix(M)
    LLL.reduction(A)
    for i in range(dim):
        last = A[i][dim - 1]
        if abs(last) != S_KAN: continue
        sign = 1 if last > 0 else -1
        if (sign * A[i][m] + shift) % n == d_secret:
            return True, None
    return False, None

# ---------------------------------------------------------------------------
# Formulations P / PC -- projected CVP
# ---------------------------------------------------------------------------

def build_projected(sigs, n, lam, k1_bound, k2_bound):
    """(2m+1) x 2m generating matrix of L' (rank 2m) and the target."""
    m = len(sigs)
    S_K1, _, S_K2, _ = scales(n, k1_bound, k2_bound)
    cols = 2 * m
    rows = []
    for i in range(m):                       # r_i
        r = [0] * cols; r[i] = n * S_K1; rows.append(r)
    r = [sigs[i]['B'] * S_K1 for i in range(m)] + [0] * m     # r_d
    rows.append(r)
    for i in range(m):                       # r_{2,i}
        r = [0] * cols
        r[i] = -(lam % n) * S_K1
        r[m + i] = S_K2
        rows.append(r)
    target = [-sigs[i]['A'] * S_K1 for i in range(m)] + [0] * m
    return rows, target

def projected_basis(rows, cols):
    """LLL-reduce the rank-deficient generating set, drop zero rows,
    return a full-rank (cols x cols) IntegerMatrix basis of L'."""
    A = IntegerMatrix.from_matrix(rows)
    LLL.reduction(A)
    keep = [i for i in range(A.nrows) if any(A[i][j] != 0 for j in range(cols))]
    assert len(keep) == cols, f"rank {len(keep)} != {cols}"
    return IntegerMatrix.from_matrix([[A[i][j] for j in range(cols)] for i in keep])

def run_P(sigs, n, lam, k1_bound, k2_bound, d_secret, centered, babai=False):
    """Returns (ok, info).  info carries geometry for E2/E3.
    babai=True replaces exact CVP by Babai nearest-plane on the LLL basis,
    isolating how much of the gain needs exact CVP."""
    m = len(sigs)
    S_K1, _, S_K2, _ = scales(n, k1_bound, k2_bound)
    cols = 2 * m
    rows, target = build_projected(sigs, n, lam, k1_bound, k2_bound)
    c1 = k1_bound // 2 if centered else 0
    c2 = k2_bound // 2 if centered else 0
    t = list(target)
    for i in range(m):
        t[i] += c1 * S_K1
        t[m + i] += c2 * S_K2

    B = projected_basis(rows, cols)
    lam1 = norm([B[0][j] for j in range(cols)])       # LLL b_1 (upper bd on l_1)

    e_planted = [(sigs[i]['k1'] - c1) * S_K1 for i in range(m)] + \
                [(sigs[i]['k2'] - c2) * S_K2 for i in range(m)]
    e_norm = norm(e_planted)

    if babai:
        gso = GSO.Mat(B, float_type='mpfr' if n.bit_length() > 40 else 'd')
        gso.update_gso()
        coef = gso.babai([int(x) for x in t])
        v = [sum(coef[i] * B[i][j] for i in range(cols)) for j in range(cols)]
    else:
        v = CVP.closest_vector(B, tuple(t))
    e = [v[j] - t[j] for j in range(cols)]

    # read (k1_i, k2_i) back out of the error vector
    k1s, k2s = [], []
    ok_shape = True
    for i in range(m):
        if e[i] % S_K1 or e[m + i] % S_K2:
            ok_shape = False; break
        k1s.append(e[i] // S_K1 + c1)
        k2s.append(e[m + i] // S_K2 + c2)
    d_cand = None
    if ok_shape:
        # A_i + B_i*d - lam*k2_i = k1_i (mod n)  ->  d = (k1_i + lam*k2_i - A_i)/B_i
        for i in range(m):
            try:
                cand = (k1s[i] + lam * k2s[i] - sigs[i]['A']) * modinv(sigs[i]['B'], n) % n
            except ValueError:
                continue
            hits = sum(1 for j in range(m)
                       if (sigs[j]['A'] + sigs[j]['B'] * cand - lam * k2s[j]) % n == k1s[j] % n)
            if hits == m:
                d_cand = cand
                break
    info = {'lam1': lam1, 'e_norm': e_norm, 'found_norm': norm(e),
            'margin': lam1 / (2.0 * e_norm) if e_norm else float('inf')}
    return (d_cand == d_secret and d_cand is not None), info

# ---------------------------------------------------------------------------
# Capacity model
# ---------------------------------------------------------------------------

C_P, C_PC = 0.2096, 0.4192

def predicted_k1_max(n, m, k2_bound, C):
    """K1 < C^2 * n^(1/2-1/m) / kappa,  kappa = K2/sqrt(n)."""
    kappa = k2_bound / math.sqrt(n)
    return C * C * n ** (0.5 - 1.0 / m) / kappa

def gh_lambda1(n, m, k1_bound, k2_bound):
    S_K1, _, S_K2, _ = scales(n, k1_bound, k2_bound)
    logdet = (m - 1) * math.log(n) + m * math.log(S_K1) + m * math.log(S_K2)
    return math.sqrt(2 * m / (2 * math.pi * math.e)) * math.exp(logdet / (2 * m))

# ---------------------------------------------------------------------------
# Drivers
# ---------------------------------------------------------------------------

SEEDS = [42, 1234, 9999, 555, 31337]

def trial(curve, m, k1_bound, seed, variant):
    p, b, n, lam, G = curve
    k2_bound = math.isqrt(n) + 1
    d = random.Random(seed + 7777).randint(1, n - 1)
    sigs = gen_signatures(G, d, m, n, lam, p, k1_bound, k2_bound, seed)
    if len(sigs) < m:
        return False, None
    if variant in ('K', 'KC'):
        return run_K(sigs, n, lam, k1_bound, k2_bound, d, centered=(variant == 'KC'))
    return run_P(sigs, n, lam, k1_bound, k2_bound, d,
                 centered=(variant in ('PC', 'PCb')), babai=(variant == 'PCb'))

def rate(curve, m, k1_bound, variant, seeds=SEEDS):
    wins, infos = 0, []
    for s in seeds:
        ok, info = trial(curve, m, k1_bound, s, variant)
        wins += ok
        if info: infos.append(info)
    return wins, infos

def wall(curve, m, variant, grid, seeds=SEEDS, thresh=0.6):
    """Largest K1 in `grid` with success rate >= thresh (0 if none)."""
    best = 0
    for k1 in grid:
        w, _ = rate(curve, m, k1, variant, seeds)
        if w / len(seeds) >= thresh:
            best = k1
        else:
            break
    return best


HIST = [
    # label,              p,    b, n,    lam,   m
    ("8-bit/199",         211,  2, 199,  106,   12),
    ("12-bit/2557",       2557, 2, 2659, 1755,  12),
    ("12-bit/2677",       2677, 2, 2647, 185,   12),
]

def hist_curves():
    out = []
    for label, p, b, n, lam, m in HIST:
        G = find_generator(p, b, n)
        assert G is not None, label
        assert (lam * lam + lam + 1) % n == 0, label
        out.append((label, (p, b, n, lam, G), m))
    return out


print("=" * 78)
print("Thread 23 -- BDD reformulation of the GLV-HNP Phase-2 lattice")
print("=" * 78)

CURVES = hist_curves()
VARIANTS = ('K', 'KC', 'P', 'PC', 'PCb')
GRID = [2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 64, 96, 128, 192, 256, 384, 512, 768]

# ===========================================================================
# E1 -- K1 wall, three formulations
# ===========================================================================
print("\n" + "-" * 78)
print("E1: K1 wall (successes out of %d seeds), m=12" % len(SEEDS))
print("-" * 78)
print("K   = Kannan  (baseline, dim 2m+2, LLL)")
print("KC  = Kannan, CENTERED embedding row (dim 2m+2, LLL)   <- centering control")
print("P   = projected exact CVP, uncentered target (dim 2m)")
print("PC  = projected exact CVP, centered target (dim 2m)")
print("PCb = projected Babai nearest-plane, centered target   <- exact-CVP control")
print()

e1 = {}
GRID_E1 = [k for k in GRID if k <= 96]
hdr = "curve            var | " + " ".join(f"{k:>4d}" for k in GRID_E1)
print(hdr)
print("-" * len(hdr))
for label, curve, m in CURVES:
    n = curve[2]
    for var in VARIANTS:
        cells = []
        for k1 in GRID_E1:
            if k1 >= n:
                cells.append("   -"); continue
            w, _ = rate(curve, m, k1, var)
            cells.append(f"{w:>4d}")
        e1[(label, var)] = cells
        print(f"{label:<16} {var:<3} | " + " ".join(cells))
        sys.stdout.flush()
    print()

# derived walls
print("Wall = largest K1 with >=3/5 successes:")
print(f"{'curve':<16} " + " ".join(f"{v:>5}" for v in VARIANTS) +
      f"   {'pred P':>7} {'pred PC':>8}")
walls = {}
for label, curve, m in CURVES:
    n = curve[2]
    k2b = math.isqrt(n) + 1
    row = []
    for var in VARIANTS:
        w = 0
        for k1, c in zip(GRID_E1, e1[(label, var)]):
            if c.strip() == '-': break
            if int(c) >= 3: w = k1
            else: break
        row.append(w)
    walls[label] = row
    print(f"{label:<16} " + " ".join(f"{x:>5d}" for x in row) +
          f"   {predicted_k1_max(n, m, k2b, C_P):>7.1f} "
          f"{predicted_k1_max(n, m, k2b, C_PC):>8.1f}")

# ===========================================================================
# E2 -- geometry of L' at the wall
# ===========================================================================
print("\n" + "-" * 78)
print("E2: BDD geometry of the projected lattice L' (seed 42)")
print("-" * 78)
print(f"{'curve':<16} {'K1':>4} {'var':>4} {'||e||':>11} {'b1(LLL)':>11} "
      f"{'GH l_1':>11} {'b1/(2||e||)':>12} {'ok':>4}")
for label, curve, m in CURVES:
    p, b, n, lam, G = curve
    k2b = math.isqrt(n) + 1
    for k1 in (2, 4, 8, 16, 32):
        if k1 >= n: continue
        for var in ('P', 'PC'):
            ok, info = trial(curve, m, k1, 42, var)
            if info is None: continue
            print(f"{label:<16} {k1:>4d} {var:>4} {info['e_norm']:>11.4g} "
                  f"{info['lam1']:>11.4g} {gh_lambda1(n, m, k1, k2b):>11.4g} "
                  f"{info['margin']:>12.3f} {'Y' if ok else 'n':>4}")
    sys.stdout.flush()

# ===========================================================================
# E3 -- is the trivial vector gone?
# ===========================================================================
print("\n" + "-" * 78)
print("E3: trivial-vector check.  Kannan sv vs projected sv (seed 42, K1=4)")
print("-" * 78)
print("T5 (2026-07-29) found |sv[m]|/n == 1.0000 in the Kannan lattice, i.e. the")
print("shortest vector is n*S_D*e_m and carries no information.")
print()
print(f"{'curve':<16} {'Kannan |sv|':>13} {'|sv[m]|/n':>10} {'sv==triv':>9} "
      f"{'proj |b1|':>12} {'proj |e|':>12} {'|e|/|b1|':>9}")
for label, curve, m in CURVES:
    p, b, n, lam, G = curve
    k2b = math.isqrt(n) + 1
    k1 = 4
    d = random.Random(42 + 7777).randint(1, n - 1)
    sigs = gen_signatures(G, d, m, n, lam, p, k1, k2b, 42)
    dim = 2 * m + 2
    A = IntegerMatrix.from_matrix(build_kannan(sigs, n, lam, k1, k2b))
    LLL.reduction(A)
    sv = [A[0][j] for j in range(dim)]
    triv = (abs(sv[m]) == n and all(sv[j] == 0 for j in range(dim) if j != m))
    _, info = run_P(sigs, n, lam, k1, k2b, d, centered=False)
    print(f"{label:<16} {norm(sv):>13.5g} {abs(sv[m]) / n:>10.4f} "
          f"{'YES' if triv else 'no':>9} {info['lam1']:>12.5g} "
          f"{info['e_norm']:>12.5g} {info['e_norm'] / info['lam1']:>9.3f}")
    sys.stdout.flush()

# ===========================================================================
# E4 -- capacity law on fresh curves
# ===========================================================================
print("\n" + "-" * 78)
print("E4: capacity law K1_max = C^2 * n^(1/2-1/m) / kappa   (kappa = K2/sqrt n)")
print("-" * 78)
E4_ROWS = []
FRESH = []
for lo, hi, want in ((2**11, 2**12, 2), (2**16, 2**17, 2), (2**19, 2**20, 2)):
    FRESH.extend(search_curves(lo, hi, want))
print(f"{'n':>9} {'bits':>5} {'lam*':>7} {'m':>3} | " +
      " ".join(f"{v:>5}" for v in VARIANTS) + f" | {'pred P':>7} {'pred PC':>8}")
for (p, b, n, lam, G) in FRESH:
    curve = (p, b, n, lam, G)
    m = 12
    k2b = math.isqrt(n) + 1
    g = [k for k in GRID if k < n]
    ws = [wall(curve, m, v, g) for v in VARIANTS]
    E4_ROWS.append((n, m, k2b, ws))
    print(f"{n:>9d} {n.bit_length():>5d} {lam_star(lam, n):>7.4f} {m:>3d} | " +
          " ".join(f"{x:>5d}" for x in ws) +
          f" | {predicted_k1_max(n, m, k2b, C_P):>7.1f} "
          f"{predicted_k1_max(n, m, k2b, C_PC):>8.1f}")
    sys.stdout.flush()

# ===========================================================================
# E5 -- calibrate the capacity constant C from the measured walls
# ===========================================================================
print("\n" + "-" * 78)
print("E5: calibrated capacity constant  C_emp = sqrt(eff_wall) * n^(1/(2m))")
print("-" * 78)
print("Theory (||e|| < lambda_1/2, Gaussian heuristic): C_P = 0.2096, C_PC = 0.4192.")
print("A measured C_emp ~ 2*C_theory means BDD is succeeding out to ||e|| ~ lambda_1,")
print("not lambda_1/2 -- the /2 uniqueness margin is not needed in practice.")
print()
ALL = [(curve[2], m, math.isqrt(curve[2]) + 1, walls[label])
       for label, curve, m in CURVES] + E4_ROWS
print(f"{'n':>9} {'m':>3} | " + " ".join(f"{v:>6}" for v in VARIANTS))
acc = {v: [] for v in VARIANTS}
for (n, m, k2b, ws) in ALL:
    cells = []
    for v, w in zip(VARIANTS, ws):
        if w == 0 or w >= GRID[-1]:
            cells.append("     -"); continue
        c = math.sqrt(w * k2b / n) * n ** (1.0 / (2 * m))
        acc[v].append(c)
        cells.append(f"{c:>6.3f}")
    print(f"{n:>9d} {m:>3d} | " + " ".join(cells))
print()
for v in VARIANTS:
    if acc[v]:
        mu = sum(acc[v]) / len(acc[v])
        sd = math.sqrt(sum((x - mu) ** 2 for x in acc[v]) / len(acc[v]))
        print(f"  C_emp[{v:<3}] = {mu:.3f} +/- {sd:.3f}   (n={len(acc[v])})")

print("\n" + "=" * 78)
print("done")
print("=" * 78)
