"""
GLV-HNP Phase 2 — Thread 23: make the planted vector the target of the search.

Background (2026-07-29 log, EXP T5)
-----------------------------------
In the (2m+2)-dimensional Phase-2 lattice built by
`glv_hnp_phase2_lambda_threshold.py:254 build_glv_lattice()`, the vector

    v_triv = n * S_D * e_m                          (the d-column axis vector)

is ALWAYS in the lattice, because  n*row_m - sum_i B_i*row_i  =  (0,...,0, n*S_D, 0,...,0).
With S_D = 1 its norm is exactly n, while

    ||v_planted||^2 ~ n^2 * (2m/3 + 4/3)     =>   ||v_planted|| ~ 3.05 n   at m=12.

So v_triv is ~3x shorter than the planted vector on EVERY instance: LLL's shortest
output row is v_triv with 100% of its energy in the d-column (measured: |sv[m]|/n =
1.0000 on all curves tested).  The planted vector is never lambda_1, and no choice of
S_D changes this (both vectors scale linearly in S_D).  Recovery is therefore a BDD /
coset condition, not an SVP condition.

v_triv carries no information: d is only defined mod n, so "d -> d + n" is the trivial
symmetry of the problem and v_triv is exactly that symmetry sitting inside the lattice.

Thread 23 — the reformulation
-----------------------------
Quotient the symmetry out.  Two ways, both implemented here:

  VARIANT B ("projected"): delete column m.  The kernel of the coordinate projection
    pi: Z^{2m+2} -> Z^{2m+1} intersected with L is exactly <v_triv>, so pi(L) is a rank
    (2m+1) lattice with det = det(L)/(n*S_D) and v_triv |-> 0.  The planted vector
    projects to (k1_i*S_K1, k2_i*S_K2, S_KANNAN), which still identifies the secret:
    from any single k1_i, k2_i we get d algebraically via
        A_i + d*B_i = k1_i + lam*k2_i  (mod n)   =>   d = (k1_i + lam*k2_i - A_i)/B_i.

  VARIANT C ("CVP"): drop the d-column AND the Kannan embedding, and solve the
    inhomogeneous problem directly.  Let L0 subset Z^{2m} be generated by
        n*S_K1*e_i                       (i < m)          [modular rows]
        (-lam*S_K1 @ col i, S_K2 @ col m+i)                [GLV rows]
        (B_0*S_K1, ..., B_{m-1}*S_K1, 0, ..., 0)           [the d row]
    and t = (A_0*S_K1, ..., A_{m-1}*S_K1, 0, ..., 0).  Then
        v = (k1_i*S_K1, k2_i*S_K2) = t + u  with  u in L0,
    so u is (heuristically) the closest lattice vector to -t.  Babai nearest-plane on
    an LLL-reduced basis of L0 gives u; v = t + u; read off k1, k2; solve for d.
    rank(L0) = 2m, det(L0) = n^{m-1} * S_K1^m * S_K2^m.

VARIANT A is the unmodified 2026-07-29 baseline, replicated verbatim for comparison.

Falsifier (stated in the 2026-07-29 log entry, quoted verbatim)
--------------------------------------------------------------
  "if sv/pv rises above 1 after the reformulation and the K1 wall in T4 moves outward
   on the lam*=0.07 curve (currently K1~4-6), the reformulation is a real improvement;
   if the wall stays at K1~4-6, then the wall is information-theoretic and Phase 2 is
   at its ceiling."

Experiments
-----------
  X1  correctness: does the algebraic d-recovery from (k1,k2) reproduce d_secret?
  X2  is the planted vector lambda_1 now?  (sv/pv for A vs B)
  X3  the T4 K1 grid, all three variants, on the historical success/failure pair.
  X4  T4b analogue: does more data (m) rescue variant B/C at the wall?

Run: python3 glv_hnp_phase2_projected.py
"""

import importlib.util
import math
import os
import random
import sys

from fpylll import IntegerMatrix, LLL, GSO

_HERE = os.path.dirname(os.path.abspath(__file__))
_SRC = os.path.join(_HERE, "glv_hnp_phase2_lambda_threshold.py")

# That module runs its full T1-T5 suite (incl. a 17-bit curve search) at import
# time, so importing it is not an option.  Exec only the helper prefix, i.e.
# everything above the "EXPERIMENT T1" banner.  The lattice construction we
# compare against is therefore byte-identical to the 2026-07-29 one.
with open(_SRC) as _f:
    _text = _f.read()
_cut = _text.index("# EXPERIMENT T1")
_cut = _text.rindex("# ====", 0, _cut)
_t20a = {}
exec(compile(_text[:_cut], _SRC, "exec"), _t20a)

modinv = _t20a['modinv']
scales = _t20a['scales']
gen_signatures = _t20a['gen_signatures']
build_glv_lattice = _t20a['build_glv_lattice']
planted_vector = _t20a['planted_vector']
recover_d = _t20a['recover_d']
norm = _t20a['norm']
find_generator = _t20a['find_generator']
lam_star = _t20a['lam_star']
glv_roots = _t20a['glv_roots']


# ---------------------------------------------------------------------------
# Variant B — projected lattice (d-column deleted)
# ---------------------------------------------------------------------------

def build_projected_lattice(sigs, n, lam, k1_bound, k2_bound):
    """The (2m+2) x (2m+1) generator matrix of pi(L), column m deleted.

    Rank is 2m+1, not 2m+2: n*row_m - sum_i B_i*row_i = 0 after the deletion.
    fpylll's LLL tolerates the rank deficiency and emits a zero row.
    Column layout: [0, m) = k1 block, [m, 2m) = k2 block, 2m = Kannan.
    """
    m = len(sigs)
    dim = 2 * m + 1
    S_K1, _S_D, S_K2, S_KANNAN = scales(n, k1_bound, k2_bound)
    M = [[0] * dim for _ in range(2 * m + 2)]
    for i in range(m):                                  # modular rows
        M[i][i] = n * S_K1
    for i in range(m):                                  # d row (d-column gone)
        M[m][i] = sigs[i]['B'] * S_K1
    for i in range(m):                                  # GLV rows
        M[m + 1 + i][i] = -lam * S_K1
        M[m + 1 + i][m + i] = S_K2
    for i in range(m):                                  # Kannan / target row
        M[2 * m + 1][i] = sigs[i]['A'] * S_K1
    M[2 * m + 1][dim - 1] = S_KANNAN
    return M


def projected_planted(sigs, n, k1_bound, k2_bound):
    """pi(v_planted) = (k1_i*S_K1, k2_i*S_K2, S_KANNAN)."""
    m = len(sigs)
    S_K1, _S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    v = [0] * (2 * m + 1)
    for i in range(m):
        v[i] = sigs[i]['k1'] * S_K1
        v[m + i] = sigs[i]['k2'] * S_K2
    v[2 * m] = S_KAN
    return v


def d_from_k(k1_i, k2_i, sig, n, lam):
    """A + d*B = k1 + lam*k2 (mod n)  =>  d."""
    B = sig['B'] % n
    if B == 0:
        return None
    return (k1_i + lam * k2_i - sig['A']) * modinv(B, n) % n


def recover_d_projected(rows, sigs, n, lam, k1_bound, k2_bound):
    """Scan reduced rows for one with |last| = S_KANNAN, then solve for d.

    Consistency-checked: the same d must come out of every index i, which makes a
    false positive vanishingly unlikely.  Returns d or None.  Does NOT look at
    d_secret, so this is an honest attack, not an oracle.
    """
    m = len(sigs)
    S_K1, _S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    for row in rows:
        last = row[2 * m]
        if abs(last) != S_KAN:
            continue
        sign = 1 if last > 0 else -1
        k1s, k2s, ok = [], [], True
        for i in range(m):
            a, b = sign * row[i], sign * row[m + i]
            if a % S_K1 or b % S_K2:
                ok = False
                break
            k1s.append(a // S_K1)
            k2s.append(b // S_K2)
        if not ok:
            continue
        cands = {d_from_k(k1s[i], k2s[i], sigs[i], n, lam) for i in range(m)}
        cands.discard(None)
        if len(cands) == 1:
            d = cands.pop()
            if d:
                return d
    return None


# ---------------------------------------------------------------------------
# Variant C — explicit CVP (Babai nearest-plane), no Kannan embedding
# ---------------------------------------------------------------------------

def build_homogeneous_lattice(sigs, n, lam, k1_bound, k2_bound):
    """L0 subset Z^{2m}: rank 2m from 2m+1 generators.  Columns [0,m)=k1, [m,2m)=k2."""
    m = len(sigs)
    dim = 2 * m
    S_K1, _S_D, S_K2, _S_KAN = scales(n, k1_bound, k2_bound)
    M = [[0] * dim for _ in range(2 * m + 1)]
    for i in range(m):
        M[i][i] = n * S_K1
    for i in range(m):
        M[m][i] = sigs[i]['B'] * S_K1
    for i in range(m):
        M[m + 1 + i][i] = -lam * S_K1
        M[m + 1 + i][m + i] = S_K2
    return M


def babai_nearest_plane(basis_rows, target):
    """Babai nearest plane against an LLL-reduced basis (exact rational GS in floats).

    basis_rows: list of independent integer rows.  Returns the lattice vector.
    """
    k = len(basis_rows)
    dim = len(basis_rows[0])
    # Gram-Schmidt in floating point (dimensions here are small: 2m <= 64).
    bstar = []
    mu = [[0.0] * k for _ in range(k)]
    for i in range(k):
        v = [float(x) for x in basis_rows[i]]
        for j in range(i):
            nj = sum(y * y for y in bstar[j])
            if nj == 0.0:
                mu[i][j] = 0.0
                continue
            mu[i][j] = sum(float(basis_rows[i][t]) * bstar[j][t]
                           for t in range(dim)) / nj
            for t in range(dim):
                v[t] -= mu[i][j] * bstar[j][t]
        bstar.append(v)
    w = [float(x) for x in target]
    coeffs = [0] * k
    for i in range(k - 1, -1, -1):
        nb = sum(y * y for y in bstar[i])
        if nb == 0.0:
            continue
        c = sum(w[t] * bstar[i][t] for t in range(dim)) / nb
        ci = int(math.floor(c + 0.5))
        coeffs[i] = ci
        if ci:
            for t in range(dim):
                w[t] -= ci * float(basis_rows[i][t])
    out = [0] * dim
    for i in range(k):
        if coeffs[i]:
            for t in range(dim):
                out[t] += coeffs[i] * basis_rows[i][t]
    return out


def run_cvp(sigs, n, lam, k1_bound, k2_bound):
    """Variant C.  Returns recovered d or None."""
    m = len(sigs)
    S_K1, _S_D, S_K2, _S_KAN = scales(n, k1_bound, k2_bound)
    M = build_homogeneous_lattice(sigs, n, lam, k1_bound, k2_bound)
    A = IntegerMatrix.from_matrix(M)
    LLL.reduction(A)
    rows = [[A[i][j] for j in range(2 * m)] for i in range(A.nrows)]
    rows = [r for r in rows if any(r)]                  # drop the zero row
    t = [0] * (2 * m)
    for i in range(m):
        t[i] = -(sigs[i]['A'] % n) * S_K1               # target is -t (see docstring)
    u = babai_nearest_plane(rows, t)
    v = [t[j] - u[j] for j in range(2 * m)]             # v = t_pos + u' ; sign folded
    v = [-x for x in v]
    cands = set()
    for i in range(m):
        if v[i] % S_K1 or v[m + i] % S_K2:
            return None
        d = d_from_k(v[i] // S_K1, v[m + i] // S_K2, sigs[i], n, lam)
        if d is None:
            return None
        cands.add(d)
    if len(cands) == 1:
        d = cands.pop()
        return d or None
    return None


# ---------------------------------------------------------------------------
# Drivers
# ---------------------------------------------------------------------------

def trial(curve, m, k1_bound, seed, variant):
    """One (curve, m, K1, seed) instance.  Returns (recovered, pn, sv, sigs_ok)."""
    p, b, n, lam, G = curve
    k2_bound = math.isqrt(n) + 1
    d_secret = random.Random(seed + 7777).randint(1, n - 1)
    sigs = gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2_bound, seed)
    if len(sigs) < m:
        return None
    _S_K1, _S_D, _S_K2, S_KAN = scales(n, k1_bound, k2_bound)

    if variant == 'A':
        M = build_glv_lattice(sigs, n, lam, k1_bound, k2_bound)
        dim = 2 * m + 2
        A = IntegerMatrix.from_matrix(M)
        LLL.reduction(A)
        rows = [[A[i][j] for j in range(dim)] for i in range(dim)]
        got = recover_d(rows, m, n, S_KAN, d_secret)
        pn = norm(planted_vector(sigs, d_secret, n, k1_bound, k2_bound))
        sv = min(norm(r) for r in rows if any(r))
        return (got is not None, pn, sv)

    if variant == 'B':
        M = build_projected_lattice(sigs, n, lam, k1_bound, k2_bound)
        dim = 2 * m + 1
        A = IntegerMatrix.from_matrix(M)
        LLL.reduction(A)
        rows = [[A[i][j] for j in range(dim)] for i in range(A.nrows)]
        got = recover_d_projected(rows, sigs, n, lam, k1_bound, k2_bound)
        pn = norm(projected_planted(sigs, n, k1_bound, k2_bound))
        nz = [r for r in rows if any(r)]
        sv = min(norm(r) for r in nz) if nz else float('nan')
        return (got == d_secret, pn, sv)

    if variant == 'C':
        got = run_cvp(sigs, n, lam, k1_bound, k2_bound)
        pn = norm(projected_planted(sigs, n, k1_bound, k2_bound))
        return (got == d_secret, pn, float('nan'))

    raise ValueError(variant)


def rate(curve, m, k1_bound, seeds, variant):
    wins, ratios = 0, []
    for s in seeds:
        r = trial(curve, m, k1_bound, s, variant)
        if r is None:
            continue
        ok, pn, sv = r
        wins += bool(ok)
        if pn and not math.isnan(sv):
            ratios.append(sv / pn)
    mr = sum(ratios) / len(ratios) if ratios else float('nan')
    return wins, len(seeds), mr


SEEDS = [42, 1234, 9999, 555, 31337]
K1_GRID = [2, 3, 4, 6, 8, 12, 16, 24]

HIST = [
    ("12-bit/2557", 2557, 2, 2659, 1755),
    ("12-bit/2677", 2677, 2, 2647, 185),
]

# ===========================================================================
# EXPERIMENT X1 — driver section.  Thread 23b execs only the prefix above this
# banner, so nothing below here runs when that script reuses these helpers.
# ===========================================================================

curves = []
for label, p, b, n, lam in HIST:
    G = find_generator(p, b, n)
    assert G is not None, label
    assert (lam * lam + lam + 1) % n == 0, label
    curves.append((label, (p, b, n, lam, G)))

print("=" * 78)
print("Thread 23 — quotient out the trivial vector; is the planted vector reachable?")
print("=" * 78)
print("A = baseline (2m+2)-dim Kannan lattice   [2026-07-29 T4 replication]")
print("B = projected: d-column deleted, rank 2m+1, d recovered algebraically")
print("C = explicit CVP: Babai nearest-plane on the rank-2m homogeneous lattice")

# --- X1: correctness of the algebraic d-recovery -----------------------------
print("\n" + "-" * 78)
print("X1: correctness — does d_from_k() reproduce d_secret from the true k's?")
print("-" * 78)
allok = True
for label, curve in curves:
    p, b, n, lam, G = curve
    k2b = math.isqrt(n) + 1
    d0 = random.Random(4242).randint(1, n - 1)
    sg = gen_signatures(G, d0, 12, n, lam, p, 8, k2b, 42)
    got = {d_from_k(s['k1'], s['k2'], s, n, lam) for s in sg}
    ok = (got == {d0})
    allok &= ok
    print(f"  {label:<14} d_secret={d0:<6} recovered={sorted(got)[:1]} -> {ok}")
print(f"  algebraic recovery correct: {allok}")

# --- X2: is the planted vector lambda_1 now? ---------------------------------
print("\n" + "-" * 78)
print("X2: sv/pv — shortest reduced row over planted norm (>1 means planted is")
print("    a candidate for lambda_1; <1 means something shorter still dominates)")
print("-" * 78)
print(f"{'curve':<14} {'K1':>3} {'A: sv/pv':>10} {'B: sv/pv':>10} "
      f"{'A |sv_m|/n':>11}")
for label, curve in curves:
    p, b, n, lam, G = curve
    for k1 in (4, 8):
        _, _, ra = rate(curve, 12, k1, SEEDS, 'A')
        _, _, rb = rate(curve, 12, k1, SEEDS, 'B')
        # energy of A's shortest vector in the d-column
        k2b = math.isqrt(n) + 1
        d0 = random.Random(42 + 7777).randint(1, n - 1)
        sg = gen_signatures(G, d0, 12, n, lam, p, k1, k2b, 42)
        M = build_glv_lattice(sg, n, lam, k1, k2b)
        Am = IntegerMatrix.from_matrix(M)
        LLL.reduction(Am)
        rws = [[Am[i][j] for j in range(26)] for i in range(26)]
        sv_row = min((r for r in rws if any(r)), key=norm)
        frac = abs(sv_row[12]) / n
        print(f"{label:<14} {k1:>3} {ra:>10.3f} {rb:>10.3f} {frac:>11.4f}")

# --- X3: the T4 K1 grid, three variants --------------------------------------
print("\n" + "-" * 78)
print("X3: T4 K1 sweep (m=12, 5 seeds, K2=52) — does the wall move?")
print("-" * 78)
walls = {}
for variant in ('A', 'B', 'C'):
    print(f"\n  variant {variant}")
    print(f"  {'curve':<14} {'lam*':>7} " + " ".join(f"K1={k:<4}" for k in K1_GRID))
    for label, curve in curves:
        p, b, n, lam, G = curve
        cells, wall = [], None
        for k1 in K1_GRID:
            w, t, _ = rate(curve, 12, k1, SEEDS, variant)
            cells.append(f"{w}/{t} ")
            if w == t:
                wall = k1
        walls[(variant, label)] = wall
        print(f"  {label:<14} {lam_star(lam,n):>7.4f} " + " ".join(cells))

print("\n  largest K1 with 5/5 recovery ('the wall'):")
print(f"  {'curve':<14} " + " ".join(f"{v:>6}" for v in ('A', 'B', 'C')))
for label, _ in curves:
    print(f"  {label:<14} "
          + " ".join(f"{str(walls[(v,label)]):>6}" for v in ('A', 'B', 'C')))

# --- X4: does more data rescue the wall? -------------------------------------
print("\n" + "-" * 78)
print("X4: at K1=8 (the 2026-07-26 failure point), does more data rescue B/C?")
print("-" * 78)
fail = [c for lbl, c in curves if c[2] == 2647][0]
for variant in ('A', 'B', 'C'):
    cells = []
    for m_try in (8, 12, 16, 24, 32):
        w, t, _ = rate(fail, m_try, 8, SEEDS, variant)
        cells.append(f"m={m_try}: {w}/{t}")
    print(f"  {variant}:  " + "   ".join(cells))

print("\n" + "=" * 78)
print("done")
print("=" * 78)
