"""
GLV-HNP Phase 2, Thread 23 (part 2): the EXACT information-theoretic boundary
of the Phase-2 lattice, by brute-force coset enumeration.

Thread 20 / T5 established that recovery in the Phase-2 lattice is a coset
(BDD) condition, not an SVP condition, and Thread 23 asked whether the
observed "K1 wall" is information-theoretic or algorithmic.  This script
answers that exactly, at toy size, with no heuristic.

STRUCTURE OF THE PHASE-2 LATTICE
--------------------------------
With columns [k1_0..k1_{m-1} | d | k2_0..k2_{m-1} | kannan], the rows

    r_i     = n*S_K1*e_i                          (i < m)
    r_k2,i  = -lam*S_K1*e_i  +  S_K2*e_{m+1+i}    (i < m)

span a sublattice  Lam = B (+) B (+) ... (+) B  (m copies), where

    B = < (n*S_K1, 0), (-lam*S_K1, S_K2) >   in the (k1_i, k2_i) plane,
    det B = n * S_K1 * S_K2.

Every copy is the SAME 2-dimensional lattice B -- it depends on the curve
only through lam.  The remaining two rows r_d and r_t satisfy
L / Lam = Z^2, generated by their images.  Any vector of L with kannan
coordinate +-S_KANNAN lies in the coset

    C(d') = (+-)r_t + d'*r_d + Lam,      d' in Z,

and its block-i component is the point  (S_K1*(A_i + d'*B_i), 0)  reduced
modulo B.  Hence the squared norm of the SHORTEST vector of C(d') is

    E(d') = sum_i dist^2( (S_K1*(A_i + d'*B_i) mod n*S_K1, 0), B )
            + (d'*S_D)^2  +  S_KANNAN^2                       (*)

with d' taken in the centred range (-n/2, n/2].  Each dist^2 is an exact
2-dimensional CVP -- O(1) via the Gauss-reduced basis of B.

So the whole attack has an exactly computable information-theoretic answer:
  the secret d is recoverable AT ALL from these m signatures iff d minimises
  E over all n candidates.  n is a few thousand here, so we enumerate.

EXPERIMENTS
  V1  exact rank of the true d under E(.) vs. LLL success, on the T4 K1-grid
  V2  the m-sweep of Thread 20 T4b (K1 = 6, 8) redone exactly
  V3  the per-block geometry:  nu = sqrt(E_planted_blk / E_random_blk).
      This is the corrected form of the falsified T2 statistic rho.

RESULTS (2026-08-02 run; see glv_hnp_phase23_coset_exact_output.txt):
  V1  At m = 12 the exact ML boundary tracks the LLL wall to within one K1
      step on both 12-bit curves (2557: exact 5/5 to K1=12, LLL 5/5 to K1=12,
      both dead at 16; 2677: exact 3/5 at K1=6, LLL 2/5, both dead at 8).
      At m = 12 the wall really is information-theoretic.
  V2  THREAD 20 T4b IS WRONG.  More data DOES cross the wall -- LLL just
      cannot exploit it.  On 12-bit/2677 at K1=6, as m goes 8/12/16/24/32/48:
          exact  1/5  3/5  3/5  5/5  5/5  5/5
          LLL    1/5  2/5  1/5  1/5  1/5  1/5
      and at K1=8:  exact 2,1,1,3,5,5   vs   LLL 1,0,0,1,2,1.
      So from m >= 24 the K1 wall on this curve is PURELY ALGORITHMIC: the
      secret is the unique global minimiser of E over all n cosets and plain
      LLL still misses it 4 times out of 5.
      (On 12-bit/2557 at K1=6 and K1=8 there is no wall at any m in [8,48]:
      exact and LLL are both 5/5 throughout.)
  V3  The block shape, not lam, is what differs: at K1=4 the two 12-bit
      curves have the same det B (9.0e7 vs 8.9e7) but Gauss-reduced skews of
      8.61 (2557) and 1.02 (2677).  Skew large => Voronoi cell long and thin
      => wrong cosets pushed further away => nu small => recoverable.
      This also retro-explains Thread 20 T2: T2 tested rho = mu1/||v|| with
      the sign convention "large rho is good" and found the failure curve had
      the LARGEST rho.  With det B fixed, mu1 ~ sqrt(det/skew), so LARGE mu1
      means SMALL skew means HARD.  T2's data was right; its sign was
      backwards.  Quantified in glv_hnp_phase23_block_predictor.py.

Run: python3 glv_hnp_phase23_coset_exact.py
"""

import math
import random

from glv_hnp_phase23_gh_law import (          # shared, already validated
    modinv, ec_mul, find_generator, lam_star,
    scales, gen_signatures, build_glv_lattice, recover_d, rate,
    gamma_orig, EFF_CRIT_INF,
)

# ---------------------------------------------------------------------------
# Exact 2-D lattice tools
# ---------------------------------------------------------------------------

def gauss_reduce_2d(u, v):
    """Lagrange/Gauss reduction (verbatim from glv_hnp_phase2_lambda_threshold.py:188)."""
    def nrm2(w): return w[0] * w[0] + w[1] * w[1]
    def dot(w, z): return w[0] * z[0] + w[1] * z[1]
    if nrm2(u) > nrm2(v): u, v = v, u
    while True:
        num, den = dot(v, u), nrm2(u)
        if den == 0: break
        q = (2 * num + den) // (2 * den) if num >= 0 else -((-2 * num + den) // (2 * den))
        v = (v[0] - q * u[0], v[1] - q * u[1])
        if nrm2(v) >= nrm2(u): break
        u, v = v, u
    return u, v

class Block2D:
    """The 2-D block B = <(n*S_K1,0), (-lam*S_K1,S_K2)> with exact CVP."""

    def __init__(self, n, lam, S_K1, S_K2):
        self.b1, self.b2 = gauss_reduce_2d((n * S_K1, 0), (-(lam % n) * S_K1, S_K2))
        self.det = abs(self.b1[0] * self.b2[1] - self.b1[1] * self.b2[0])
        # Gram matrix for exact rounding
        self.g11 = self.b1[0] ** 2 + self.b1[1] ** 2
        self.g22 = self.b2[0] ** 2 + self.b2[1] ** 2
        self.g12 = self.b1[0] * self.b2[0] + self.b1[1] * self.b2[1]
        self.mu1 = math.sqrt(self.g11)
        self.mu2 = math.sqrt(self.g22)

    def dist2(self, t, window=3):
        """Exact squared distance from t=(x,y) to the lattice.
        Babai rounding in the Gauss-reduced basis, then an exhaustive
        +-window search -- exact for 2-D reduced bases (window>=2 suffices)."""
        det = float(self.g11 * self.g22 - self.g12 * self.g12)
        if det <= 0:
            return float(t[0] ** 2 + t[1] ** 2)
        tb1 = t[0] * self.b1[0] + t[1] * self.b1[1]
        tb2 = t[0] * self.b2[0] + t[1] * self.b2[1]
        c1 = (tb1 * self.g22 - tb2 * self.g12) / det
        c2 = (tb2 * self.g11 - tb1 * self.g12) / det
        r1, r2 = int(round(c1)), int(round(c2))
        best = None
        for a in range(r1 - window, r1 + window + 1):
            for b in range(r2 - window, r2 + window + 1):
                dx = t[0] - a * self.b1[0] - b * self.b2[0]
                dy = t[1] - a * self.b1[1] - b * self.b2[1]
                v = dx * dx + dy * dy
                if best is None or v < best:
                    best = v
        return best

    def mean_random_dist2(self, trials=4000, seed=7):
        """E[dist^2] for a uniformly random coset of B."""
        rng = random.Random(seed)
        tot = 0.0
        for _ in range(trials):
            x = rng.uniform(0, 1); y = rng.uniform(0, 1)
            t = (x * self.b1[0] + y * self.b2[0], x * self.b1[1] + y * self.b2[1])
            tot += self.dist2(t)
        return tot / trials

# ---------------------------------------------------------------------------
# Exact coset enumeration
# ---------------------------------------------------------------------------

def coset_energy_profile(sigs, n, lam, k1_bound, k2_bound, d_secret):
    """E(d') from (*) for every d' in Z_n.  Returns (rank_of_true_d,
    E(d_true), E_min, d_argmin, gap_ratio)."""
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    B = Block2D(n, lam, S_K1, S_K2)
    mod = n * S_K1

    # incremental: target_i(d'+1) = target_i(d') + B_i*S_K1  (mod n*S_K1)
    step = [s['B'] * S_K1 % mod for s in sigs]
    cur = [s['A'] * S_K1 % mod for s in sigs]

    energies = [0.0] * n
    for dp in range(n):
        e = 0.0
        for i in range(m):
            e += B.dist2((cur[i], 0))
        dc = dp if dp <= n // 2 else dp - n       # centred representative
        energies[dp] = e + (dc * S_D) ** 2
        for i in range(m):
            cur[i] += step[i]
            if cur[i] >= mod: cur[i] -= mod

    e_true = energies[d_secret]
    d_min = min(range(n), key=lambda j: energies[j])
    e_min = energies[d_min]
    rank = sum(1 for e in energies if e < e_true)
    return rank, e_true, e_min, d_min, math.sqrt(e_true / e_min) if e_min > 0 else float('inf')


def exact_rate(curve, m, k1_bound, seeds):
    """Fraction of seeds for which the true d is the exact global minimiser."""
    p, b, n, lam, G = curve
    k2 = math.isqrt(n) + 1
    w = t = 0
    ranks = []
    for seed in seeds:
        rng = random.Random(seed ^ 0x5eed)
        d_secret = rng.randrange(1, n)
        sigs = gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2, seed)
        if len(sigs) < m: continue
        rk, et, em, dm, gr = coset_energy_profile(sigs, n, lam, k1_bound, k2, d_secret)
        t += 1; w += 1 if rk == 0 else 0
        ranks.append(rk)
    return w, t, ranks

# ===========================================================================

if __name__ == '__main__':

    print("=" * 78)
    print("Thread 23 part 2 -- exact information-theoretic boundary (coset enum)")
    print("=" * 78)

    SEEDS = [42, 1234, 9999, 555, 31337]

    HIST = [
        ("8-bit/199",   211,  2, 199,  106),
        ("12-bit/2557", 2557, 2, 2659, 1755),
        ("12-bit/2677", 2677, 2, 2647, 185),
    ]
    hist = []
    for label, p, b, n, lam in HIST:
        G = find_generator(p, b, n)
        assert G is not None and (lam * lam + lam + 1) % n == 0, label
        hist.append((label, (p, b, n, lam, G)))

    # sanity: the planted vector must be an element of its own coset with the
    # energy predicted by (*) -- check E(d_true) <= ||v_planted||^2 - S_KAN^2
    print("\nsanity check: E(d_true) vs the actual planted block energy")
    label, curve = hist[1]
    p, b, n, lam, G = curve
    k2 = math.isqrt(n) + 1
    S_K1, S_D, S_K2, S_KAN = scales(n, 4, k2)
    rng = random.Random(1)
    d0 = rng.randrange(1, n)
    sg = gen_signatures(G, d0, 8, n, lam, p, 4, k2, 42)
    Bk = Block2D(n, lam, S_K1, S_K2)
    plant = sum((s['k1'] * S_K1) ** 2 + (s['k2'] * S_K2) ** 2 for s in sg)
    dc = d0 if d0 <= n // 2 else d0 - n
    rk, et, em, dm, gr = coset_energy_profile(sg, n, lam, 4, k2, d0)
    print(f"  planted block energy = {plant + dc**2:.4g}   E(d_true) = {et:.4g}   "
          f"(E must be <=)  ok={et <= plant + dc**2 + 1e-6}")
    print(f"  block B: mu1={Bk.mu1:.4g} mu2={Bk.mu2:.4g} det={Bk.det:.6g} "
          f"skew mu2/mu1={Bk.mu2/Bk.mu1:.3f}")

    # ---------------------------------------------------------------------------
    print("\n" + "-" * 78)
    print("V1: exact info-theoretic recoverability vs LLL, on the T4 K1-grid (m=12)")
    print("-" * 78)
    print("'exact' = true d is the global minimiser of E(.) over all n candidates.")
    print("'LLL'   = the Phase-2 LLL attack recovers d.  gap => algorithmic loss.")
    for label, curve in hist[1:]:
        p, b, n, lam, G = curve
        k2 = math.isqrt(n) + 1
        print(f"\n{label}: n={n} lam*={lam_star(lam,n):.3f}")
        print(f"{'K1':>4} {'eff':>7} {'gamma':>7} {'exact':>6} {'LLL':>6} "
              f"{'medrank':>8} {'E_t/E_min':>10}")
        for k1 in (2, 4, 6, 8, 12, 16, 24, 32):
            eff = k1 * k2 / n
            we, te, ranks = exact_rate(curve, 12, k1, SEEDS)
            wl, tl = rate(curve, 12, k1, SEEDS)
            ranks_s = sorted(ranks)
            med = ranks_s[len(ranks_s) // 2] if ranks_s else -1
            # energy ratio on the first seed
            rng = random.Random(SEEDS[0] ^ 0x5eed)
            ds = rng.randrange(1, n)
            sg = gen_signatures(G, ds, 12, n, lam, p, k1, k2, SEEDS[0])
            _, et, em, _, gr = coset_energy_profile(sg, n, lam, k1, k2, ds)
            print(f"{k1:>4} {eff:>7.3f} {gamma_orig(12,n,k1,k2):>7.3f} "
                  f"{str(we)+'/'+str(te):>6} {str(wl)+'/'+str(tl):>6} "
                  f"{med:>8} {gr:>10.4f}")

    # ---------------------------------------------------------------------------
    print("\n" + "-" * 78)
    print("V2: Thread 20 T4b redone exactly -- does more data cross the K1 wall?")
    print("-" * 78)
    for label, curve in hist[1:]:
        p, b, n, lam, G = curve
        k2 = math.isqrt(n) + 1
        for k1 in (6, 8):
            print(f"\n{label}  K1={k1}  eff={k1*k2/n:.4f}")
            print(f"{'m':>4} {'exact':>6} {'LLL':>6} {'medrank':>8}")
            for m in (8, 12, 16, 24, 32, 48):
                we, te, ranks = exact_rate(curve, m, k1, SEEDS)
                wl, tl = rate(curve, m, k1, SEEDS)
                rs = sorted(ranks)
                print(f"{m:>4} {str(we)+'/'+str(te):>6} {str(wl)+'/'+str(tl):>6} "
                      f"{(rs[len(rs)//2] if rs else -1):>8}")

    # ---------------------------------------------------------------------------
    print("\n" + "-" * 78)
    print("V3: per-block geometry -- the corrected form of the falsified T2 rho")
    print("-" * 78)
    print("nu = sqrt( E[planted block energy] / E[random-coset block energy] ).")
    print("nu < 1 means one signature already pushes the true coset below a random")
    print("one; the wall is then a large-deviation/union-bound effect over n cosets.")
    print(f"{'curve':>13} {'lam*':>6} {'K1':>4} {'mu1':>10} {'mu2':>10} {'skew':>6} "
          f"{'Erand':>10} {'Eplant':>10} {'nu':>7} {'m*':>5} {'exact':>6}")
    for label, curve in hist:
        p, b, n, lam, G = curve
        k2 = math.isqrt(n) + 1
        for k1 in (2, 4, 6, 8, 12):
            S_K1, S_D, S_K2, S_KAN = scales(n, k1, k2)
            Bk = Block2D(n, lam, S_K1, S_K2)
            er = Bk.mean_random_dist2(trials=2000)
            ep = (k1 * S_K1) ** 2 / 3.0 + (k2 * S_K2) ** 2 / 3.0
            nu = math.sqrt(ep / er) if er > 0 else float('inf')
            # union-bound m*: smallest m with m*ln(1/nu^2)/2 > ln n  (crude)
            if nu < 1:
                m_star = math.ceil(2 * math.log(n) / math.log(1.0 / (nu * nu)))
            else:
                m_star = -1
            we, te, _ = exact_rate(curve, 12, k1, SEEDS)
            print(f"{label:>13} {lam_star(lam,n):>6.3f} {k1:>4} {Bk.mu1:>10.4g} "
                  f"{Bk.mu2:>10.4g} {Bk.mu2/Bk.mu1:>6.2f} {er:>10.4g} {ep:>10.4g} "
                  f"{nu:>7.3f} {m_star:>5} {str(we)+'/'+str(te):>6}")

    print("\n" + "=" * 78)
    print("done")
    print("=" * 78)
