"""
GLV-HNP Phase 2, Thread 25: is mu a second coordinate, or is its apparent
power mediated by NU after all?

Pre-registered by the 2026-08-07 (Thread 24) log entry:

  H25: within the ambiguous band 1.04 <= NU <= 2.20 (where the nearest-plane
       guarantee gives no answer), AUC(-mu -> Kannan-LLL recovery) stays
       >= 0.8.
  If yes, mu is a genuine second coordinate and the pair (NU, mu) is the
  2-parameter viability test Phase 2 has been missing; the deliverable is a
  logistic fit on (log NU, log mu) with its decision boundary.
  If no -- if mu's apparent power is entirely mediated by NU after all --
  then the W5 result is a stratification artifact and the closed form should
  be retired.

Why it matters.  Thread 24 established two things that do not sit together:
NU = max_i 2|<e,b*_i>|/||b*_i||^2 is an exact, sound nearest-plane certificate
(96 TP / 0 FP over 410 instances at NU <= 1), yet at fixed bias strength it is
a WORSE ranker of actual Kannan-LLL recovery than nu_hat = mu/sqrt(det L2),
which needs no lattice reduction at all -- and the two are mutually
uncorrelated inside every eff stratum (Spearman -0.28..+0.16).  Two
uncorrelated predictors of the same event means two mechanisms.  Thread 25
asks whether the second one survives conditioning on the first.

Three confounds this script has to kill before H25 can be believed:

  C1  scale.  mu = lambda_1(L2) carries an absolute scale that moves with
      (n, K1, K2).  Conditioning on a NU band pools across eff strata, so a
      raw-mu AUC can be re-reading the bias strength.  nu_hat = mu/sqrt(det2)
      is the size-free version; both are reported, and `eff` itself is
      carried as a control column throughout.
  C2  composition.  If NU-band membership correlates with eff, then ANY
      eff-correlated score separates inside a band for free.  A2 therefore
      re-does the test inside (NU band x eff stratum) cells, where neither
      NU nor eff can vary much.
  C3  the reverse direction.  If mu is a real second coordinate then NU must
      also separate at fixed mu.  A1b runs the transpose: condition on
      nu_hat bands and measure AUC(-NU).

Data: the 500-instance 17-bit table of Thread 24's W5/W6, regenerated by
  python3 glv_hnp_phase2_gsprofile_strat.py --dump-json strat17.jsonl
(20 j=0 GLV curves x 5 eff strata x 5 seeds, dim 24, m = 12).

Run: python3 glv_hnp_phase2_nu_conditional.py [strat17.jsonl]
"""

import json
import math
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from glv_hnp_phase2_gsprofile import auc, spearman

# Thread 24 W4, 17 bits, dim 24: sufficient NU < 1.040, necessary NU > 2.199.
BAND_LO = 1.040
BAND_HI = 2.199
M17 = 12


# ---------------------------------------------------------------------------
# statistics
# ---------------------------------------------------------------------------

def auc_split(rows, key):
    """AUC of the score -key over rows, or nan if a class is empty."""
    pos = [r[key] for r in rows if r['ok']]
    neg = [r[key] for r in rows if not r['ok']]
    return auc(pos, neg)


def auc_perm_p(rows, key, trials=2000, seed=20250807):
    """One-sided permutation p-value for AUC > 0.5 (label shuffle)."""
    pos = [r[key] for r in rows if r['ok']]
    neg = [r[key] for r in rows if not r['ok']]
    if not pos or not neg:
        return float('nan')
    obs = auc(pos, neg)
    vals = pos + neg
    npos = len(pos)
    rng = random.Random(seed)
    hits = 0
    for _ in range(trials):
        rng.shuffle(vals)
        if auc(vals[:npos], vals[npos:]) >= obs:
            hits += 1
    return (hits + 1.0) / (trials + 1.0)


def logistic_irls(X, y, ridge=1e-6, iters=60):
    """IRLS logistic fit.  X includes no intercept column; one is prepended."""
    n = len(X)
    d = len(X[0]) + 1
    A = [[1.0] + list(row) for row in X]
    w = [0.0] * d
    for _ in range(iters):
        # gradient and Hessian of the ridge-penalised log-likelihood
        g = [0.0] * d
        H = [[ridge if i == j else 0.0 for j in range(d)] for i in range(d)]
        for i in range(n):
            z = sum(w[j] * A[i][j] for j in range(d))
            z = max(-30.0, min(30.0, z))
            pi = 1.0 / (1.0 + math.exp(-z))
            r = y[i] - pi
            s = max(pi * (1.0 - pi), 1e-9)
            for j in range(d):
                g[j] += r * A[i][j]
                for k in range(d):
                    H[j][k] += s * A[i][j] * A[i][k]
        for j in range(d):
            g[j] -= ridge * w[j]
        step = solve(H, g)
        if step is None:
            break
        w = [w[j] + step[j] for j in range(d)]
        if max(abs(s) for s in step) < 1e-10:
            break
    return w


def solve(M, b):
    """Gaussian elimination with partial pivoting."""
    d = len(b)
    A = [row[:] + [b[i]] for i, row in enumerate(M)]
    for c in range(d):
        piv = max(range(c, d), key=lambda r: abs(A[r][c]))
        if abs(A[piv][c]) < 1e-14:
            return None
        A[c], A[piv] = A[piv], A[c]
        for r in range(d):
            if r == c:
                continue
            f = A[r][c] / A[c][c]
            for k in range(c, d + 1):
                A[r][k] -= f * A[c][k]
    return [A[i][d] / A[i][i] for i in range(d)]


def loglik(X, y, w):
    tot = 0.0
    for i, row in enumerate(X):
        z = w[0] + sum(w[j + 1] * row[j] for j in range(len(row)))
        z = max(-30.0, min(30.0, z))
        p = 1.0 / (1.0 + math.exp(-z))
        tot += math.log(p if y[i] else 1.0 - p + 1e-300)
    return tot


def model_auc(X, y, w):
    sc = []
    for row in X:
        sc.append(w[0] + sum(w[j + 1] * row[j] for j in range(len(row))))
    # higher score -> more likely to recover, and auc() scores -x, so negate
    pos = [-s for s, t in zip(sc, y) if t]
    neg = [-s for s, t in zip(sc, y) if not t]
    return auc(pos, neg)


def fmt(x, w=8, p=4):
    return f"{'   n/a':>{w}}" if x != x else f"{x:>{w}.{p}f}"


# ---------------------------------------------------------------------------

def load(path):
    rows = []
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    for r in rows:
        # W1b's two-block step: head of the profile is m copies of lambda_1(L2),
        # the second block sits at lambda_2 and collapses onto the head as the
        # K1 wall is crossed.  step -> 0 is the collapse.
        p = r['prof']
        head = sum(math.log2(v) for v in p[:M17] if v > 0) / M17
        tail = sum(math.log2(v) for v in p[M17:] if v > 0) / (len(p) - M17)
        r['step'] = tail - head
        r['step1'] = (math.log2(p[M17]) - math.log2(p[0])) if p[0] > 0 else 0.0
        # sign-corrected: the empirical direction is LARGER step -> recovery,
        # so -step is the score to compare fairly against nu_hat.
        r['mstep'] = -r['step']
        r['logNU'] = math.log(r['NU'])
        r['lognuhat'] = math.log(r['nuhat'])
        r['logmu'] = math.log(r['mu'])
    return rows


if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "strat17.jsonl"
    rows = load(path)
    EFFS = sorted({r['effq'] for r in rows})

    print("=" * 78)
    print("Thread 25 — does mu separate INSIDE a NU band?")
    print("=" * 78)
    print(f"\n{len(rows)} instances, dim {rows[0]['k']}, m = {M17}, 17-bit "
          f"j=0 GLV curves")
    print(f"NU bracket from Thread 24 W4: sufficient NU < {BAND_LO}, "
          f"necessary NU > {BAND_HI}")

    bands = [
        ("NU < 1.040  (nearest-plane SUFFICIENT)",
         lambda r: r['NU'] < BAND_LO),
        ("1.040 <= NU <= 2.199  (AMBIGUOUS — the H25 band)",
         lambda r: BAND_LO <= r['NU'] <= BAND_HI),
        ("NU > 2.199  (nearest-plane says NOTHING recovers)",
         lambda r: r['NU'] > BAND_HI),
    ]

    print("\n" + "-" * 78)
    print("EXP A1: AUC within each NU band.  NU is (nearly) constant inside a")
    print("        band, so anything that still separates is a 2nd coordinate.")
    print("-" * 78)
    print(f"{'band':<46} {'N':>4} {'rec':>8}")
    print(f"{'':<46} {'AUC mu':>8} {'AUC nuh':>8} {'AUC eff':>8} "
          f"{'AUC NU':>8} {'AUC lam*':>9} {'AUC step':>9}")
    for name, pred in bands:
        sub = [r for r in rows if pred(r)]
        w = sum(1 for r in sub if r['ok'])
        print(f"\n{name:<46} {len(sub):>4} "
              f"{str(w) + '/' + str(len(sub)):>8}")
        print(f"{'':<46}"
              f"{fmt(auc_split(sub, 'mu'))} {fmt(auc_split(sub, 'nuhat'))} "
              f"{fmt(auc_split(sub, 'eff'))} {fmt(auc_split(sub, 'NU'))} "
              f"{fmt(auc_split(sub, 'lamstar'), 9)} "
              f"{fmt(auc_split(sub, 'step'), 9)}")

    amb = [r for r in rows if BAND_LO <= r['NU'] <= BAND_HI]
    a_mu = auc_split(amb, 'mu')
    a_nh = auc_split(amb, 'nuhat')
    print(f"\nH25 verdict target: AUC(-mu) inside the ambiguous band "
          f">= 0.8 ?  -> {a_mu:.4f}")
    print(f"  permutation p (AUC mu    > 0.5): "
          f"{auc_perm_p(amb, 'mu'):.5f}")
    print(f"  permutation p (AUC nuhat > 0.5): "
          f"{auc_perm_p(amb, 'nuhat'):.5f}")
    print(f"  permutation p (AUC NU    > 0.5): "
          f"{auc_perm_p(amb, 'NU'):.5f}")

    print("\n" + "-" * 78)
    print("EXP A1b: the transpose (confound C3).  Condition on nu_hat bands")
    print("         and ask whether NU still separates at fixed geometry.")
    print("-" * 78)
    nh = sorted(r['nuhat'] for r in rows)
    q = [nh[int(len(nh) * f)] for f in (1 / 3.0, 2 / 3.0)]
    nbands = [
        (f"nu_hat < {q[0]:.4f}", lambda r: r['nuhat'] < q[0]),
        (f"{q[0]:.4f} <= nu_hat < {q[1]:.4f}",
         lambda r: q[0] <= r['nuhat'] < q[1]),
        (f"nu_hat >= {q[1]:.4f}", lambda r: r['nuhat'] >= q[1]),
    ]
    print(f"{'band':<28} {'N':>4} {'rec':>8} {'AUC NU':>8} {'AUC mu':>8} "
          f"{'AUC eff':>8} {'AUC step':>9}")
    for name, pred in nbands:
        sub = [r for r in rows if pred(r)]
        w = sum(1 for r in sub if r['ok'])
        print(f"{name:<28} {len(sub):>4} "
              f"{str(w) + '/' + str(len(sub)):>8} "
              f"{fmt(auc_split(sub, 'NU'))} {fmt(auc_split(sub, 'mu'))} "
              f"{fmt(auc_split(sub, 'eff'))} "
              f"{fmt(auc_split(sub, 'step'), 9)}")

    print("\n" + "-" * 78)
    print("EXP A2: double conditioning (confound C2).  Inside each")
    print("        (NU band x eff stratum) cell neither NU nor eff can move.")
    print("-" * 78)
    print(f"{'NU band':<12} {'eff':>5} {'N':>4} {'rec':>7} {'AUC mu':>8} "
          f"{'AUC nuh':>8} {'AUC NU':>8} {'AUC step':>9}")
    bshort = ["NU<1.04", "1.04-2.20", "NU>2.20"]
    for bi, (name, pred) in enumerate(bands):
        for eff in EFFS:
            sub = [r for r in rows if pred(r) and r['effq'] == eff]
            w = sum(1 for r in sub if r['ok'])
            if not sub or w == 0 or w == len(sub):
                tag = "(all rec)" if sub and w == len(sub) else (
                    "(none rec)" if sub else "(empty)")
                print(f"{bshort[bi]:<12} {eff:>5.2f} {len(sub):>4} "
                      f"{str(w) + '/' + str(len(sub)):>7} {tag:>8}")
                continue
            print(f"{bshort[bi]:<12} {eff:>5.2f} {len(sub):>4} "
                  f"{str(w) + '/' + str(len(sub)):>7} "
                  f"{fmt(auc_split(sub, 'mu'))} {fmt(auc_split(sub, 'nuhat'))} "
                  f"{fmt(auc_split(sub, 'NU'))} "
                  f"{fmt(auc_split(sub, 'step'), 9)}")

    print("\n" + "-" * 78)
    print("EXP A3: logistic fit on (log NU, log nu_hat).  If the two carry")
    print("        independent information both coefficients stay significant")
    print("        and the 2-feature model beats either 1-feature model.")
    print("-" * 78)
    y = [1 if r['ok'] else 0 for r in rows]
    specs = [
        ("logNU only", ['logNU']),
        ("log nu_hat only", ['lognuhat']),
        ("log mu only", ['logmu']),
        ("logNU + log nu_hat", ['logNU', 'lognuhat']),
        ("logNU + log nu_hat + log eff", ['logNU', 'lognuhat', 'logeff']),
    ]
    for r in rows:
        r['logeff'] = math.log(r['eff'])
    base = None
    print(f"{'model':<30} {'loglik':>10} {'AUC':>7}   coefficients")
    for name, feats in specs:
        X = [[r[f] for f in feats] for r in rows]
        w = logistic_irls(X, y)
        ll = loglik(X, y, w)
        if base is None:
            base = ll
        cs = "  ".join(f"{f}={w[i + 1]:+.3f}" for i, f in enumerate(feats))
        print(f"{name:<30} {ll:>10.2f} {model_auc(X, y, w):>7.4f}   "
              f"b0={w[0]:+.3f}  {cs}")

    X2 = [[r['logNU'], r['lognuhat']] for r in rows]
    w2 = logistic_irls(X2, y)
    print(f"\ndecision boundary of the 2-feature model (P = 1/2):")
    print(f"  {w2[0]:+.4f} {w2[1]:+.4f}*log(NU) {w2[2]:+.4f}*log(nu_hat) = 0")
    # b0 + a*log NU + b*log nu_hat = 0  <=>  nu_hat * NU^(a/b) = exp(-b0/b),
    # and a, b < 0 so the recovery side (z > 0) is the SMALL side.
    expo = w2[1] / w2[2]
    thresh = math.exp(-w2[0] / w2[2])
    print(f"  i.e.  nu_hat * NU^{expo:.3f}  <  {thresh:.4f}   => recover")
    prod = [r['lognuhat'] + expo * r['logNU'] for r in rows]
    ppos = [v for v, t in zip(prod, y) if t]
    pneg = [v for v, t in zip(prod, y) if not t]
    print(f"  AUC of that single combined score: {auc(ppos, pneg):.4f}")
    tp = sum(1 for v, t in zip(prod, y) if v < math.log(thresh) and t)
    fp = sum(1 for v, t in zip(prod, y) if v < math.log(thresh) and not t)
    fn = sum(1 for v, t in zip(prod, y) if v >= math.log(thresh) and t)
    tn = len(rows) - tp - fp - fn
    print(f"  rule at P=1/2:  TP {tp}  FP {fp}  FN {fn}  TN {tn}   "
          f"accuracy {(tp + tn) / len(rows):.4f}")
    print(f"  exponent is {expo:.3f} ~ 1, so the boundary is essentially the")
    print(f"  PRODUCT  NU * nu_hat  <  {thresh:.3f}.  AUC of the plain "
          f"product: "
          f"{auc([r['lognuhat'] + r['logNU'] for r in rows if r['ok']], [r['lognuhat'] + r['logNU'] for r in rows if not r['ok']]):.4f}")

    print("\nleave-one-CURVE-out CV (20 curves; the fit above is in-sample and")
    print("the 5 seeds of a curve are not independent):")
    curves = sorted({r['n'] for r in rows})
    for name, feats in specs[:4]:
        sc, lab = [], []
        for cn in curves:
            tr = [r for r in rows if r['n'] != cn]
            te = [r for r in rows if r['n'] == cn]
            wf = logistic_irls([[r[f] for f in feats] for r in tr],
                               [1 if r['ok'] else 0 for r in tr])
            for r in te:
                sc.append(wf[0] + sum(wf[i + 1] * r[f]
                                      for i, f in enumerate(feats)))
                lab.append(r['ok'])
        print(f"  {name:<30} held-out AUC = "
              f"{auc([-s for s, t in zip(sc, lab) if t], [-s for s, t in zip(sc, lab) if not t]):.4f}")

    X1 = [[r['logNU']] for r in rows]
    w1 = logistic_irls(X1, y)
    d = 2.0 * (loglik(X2, y, w2) - loglik(X1, y, w1))
    print(f"\nlikelihood-ratio, adding log nu_hat to log NU: "
          f"2*dLL = {d:.2f} on 1 df")
    X1b = [[r['lognuhat']] for r in rows]
    w1b = logistic_irls(X1b, y)
    d2 = 2.0 * (loglik(X2, y, w2) - loglik(X1b, y, w1b))
    print(f"likelihood-ratio, adding log NU to log nu_hat: "
          f"2*dLL = {d2:.2f} on 1 df")
    print("(chi2_1 critical values: 3.84 at p=0.05, 10.83 at p=0.001)")

    print("\n" + "-" * 78)
    print("EXP A4: the W1b two-block step as a predictor in its own right.")
    print("        step = mean log2||b*_i|| over the tail block minus the head")
    print("        block; W1b says step -> 0 exactly as the K1 wall is crossed.")
    print("-" * 78)
    print(f"{'eff':>5} {'N':>4} {'rec':>7} {'AUC step':>9} {'AUC step1':>10} "
          f"{'AUC NU':>8} {'AUC nuh':>8} | {'mean step':>10}")
    for eff in EFFS:
        sub = [r for r in rows if r['effq'] == eff]
        w = sum(1 for r in sub if r['ok'])
        ms = sum(r['step'] for r in sub) / len(sub)
        if w == 0 or w == len(sub):
            print(f"{eff:>5.2f} {len(sub):>4} "
                  f"{str(w) + '/' + str(len(sub)):>7} {'(degenerate)':>9}"
                  f"{'':>29} | {ms:>10.4f}")
            continue
        print(f"{eff:>5.2f} {len(sub):>4} {str(w) + '/' + str(len(sub)):>7} "
              f"{fmt(auc_split(sub, 'mstep'), 9)} "
              f"{fmt(auc_split(sub, 'step1'), 10)} "
              f"{fmt(auc_split(sub, 'NU'))} {fmt(auc_split(sub, 'nuhat'))} | "
              f"{ms:>10.4f}")
    print("\n(the AUC step column scores -step: the empirical direction is")
    print(" LARGER step -> recovery, i.e. the OPPOSITE of what W1b's "
          "'step -> 0\n at the wall' reading predicts.)")
    print(f"\npooled AUC(-(-step)) = {auc_split(rows, 'mstep'):.4f}")
    print(f"pooled AUC(-step1)   = {auc_split(rows, 'step1'):.4f}")
    print(f"Spearman(step, log nu_hat) = "
          f"{spearman([r['step'] for r in rows], [r['lognuhat'] for r in rows]):+.4f}")
    print(f"Spearman(step, log NU)     = "
          f"{spearman([r['step'] for r in rows], [r['logNU'] for r in rows]):+.4f}")
    print(f"Spearman(log mu, log nu_hat) = "
          f"{spearman([r['logmu'] for r in rows], [r['lognuhat'] for r in rows]):+.4f}")

    print("\n" + "=" * 78)
    print("done")
    print("=" * 78)
