"""
GLV-HNP Phase 2, Thread 23: reformulate the lattice so the planted vector is
the shortest vector.

Background (RESEARCH_AUTOLAB_LOG.md, 2026-07-29 run, EXP T5):
  In the Phase-2 lattice R0 the shortest vector after LLL is, on every curve
  tested, exactly the trivial vector  n*S_D*e_m  (100% of its energy in the
  d-column, |sv[m]|/n = 1.0000, Kannan coordinate 0).  It is in the lattice
  because

        n*(row_d)  -  sum_i B_i*(row_i)  =  (0,...,0, n*S_D, 0,...,0)

  and it is shorter than the planted vector for every m >= 1, since
  ||v_planted||^2 ~ n^2*(2m/3 + 4/3)  while  ||n*S_D*e_m||^2 = n^2.
  It carries no information (d is only defined mod n) and no choice of S_D
  removes it: both vectors scale linearly in S_D.  Recovery in R0 is therefore
  a BDD/coset condition, not an SVP condition.

  Proposal logged on 2026-07-29:
    "project the lattice along e_m (quotient out the trivial n*e_m direction)
     and solve BDD in the projection, or replace the Kannan embedding with an
     explicit CVP call (Babai nearest-plane) targeting (A_i*S_K1, 0, ...)".

  Falsifier, as logged:
    "if sv/pv rises above 1 after the reformulation AND the K1 wall in T4
     moves outward on the lam*=0.07 curve (currently K1~4-6), the
     reformulation is a real improvement; if the wall stays at K1~4-6, then
     the wall is information-theoretic and Phase 2 is at its ceiling."

This script implements both reformulations and runs that falsifier.

  R0  baseline (2m+2)-dim Kannan lattice with an explicit d-column.
  R1  R0 with the d-column DELETED: the image pi(L) under the projection that
      drops coordinate m.  pi(n*S_D*e_m) = 0, so the trivial vector is gone by
      construction.  dim = 2m+1, rank 2m+1, given by 2m+2 generators (one
      dependency, which LLL turns into a zero row).  d is no longer a lattice
      coordinate; it is recovered arithmetically afterwards from the k1/k2
      block of the found vector via
            d = (k1_0 + lam*k2_0 - A_0) * B_0^{-1}  (mod n).
  R2  no Kannan embedding at all: explicit BDD.  The lattice L2 lives in the
      2m-dim (k1|k2) space and is generated by the modular rows, the d-row and
      the k2-rows; the target is t = (-A_i*S_K1, 0, ..., 0).  Babai
      nearest-plane on the LLL-reduced basis gives w ~ t, and
            k1_i = w_i/S_K1 + A_i,   k2_i = w_{m+i}/S_K2.

Experiments:
  P1  structural check: is n*S_D*e_m in R0?  is it lambda_1?  is L cap <e_m>
      exactly Z*n*S_D*e_m?  is the projected planted vector in R1?
  P2  sv/pv for R0 vs R1 on the three historical curves (the T5 table, redone
      in the projection).
  P3  THE FALSIFIER.  The exact T4 grid (m=12, K1 in {2,3,4,6,8,12,16,24},
      5 seeds, both 12-bit curves) run under R0, R1 and R2.  Does the K1 wall
      move?
  P4  Gaussian-heuristic accounting: ||v_planted|| / GH(L) per K1, for R0 and
      R1, against the empirical wall.  Distinguishes "bad lattice shape"
      from "information-theoretically absent".
  P5  BKZ(20)/BKZ(40) retry of R1 at the wall.
  P6  anatomy of lambda_1(R1), and the BDD unique-decoding criterion
      gamma = ||pv_0|| / (lambda_1(L2)/2) tested against the empirical wall.

Run: python3 glv_hnp_phase2_projected.py
"""

import math
import random

from fpylll import IntegerMatrix, LLL, BKZ, GSO, SVP

from glv_hnp_common import (
    modinv, ec_mul, find_generator, glv_roots, lam_star,
    scales, gen_signatures, build_glv_lattice, planted_vector, norm,
    recover_d, gauss_2d,
)

SEEDS = [42, 1234, 9999, 555, 31337]

# Historical Phase-2 curves (RESEARCH_AUTOLAB_LOG.md 2026-06-15 / 2026-07-26)
HIST = [
    # label,             p,    b, n,    lam,  K1, m
    ("8-bit/199",        211,  2, 199,  106,  2,  6),
    ("12-bit/2557",      2557, 2, 2659, 1755, 8,  8),
    ("12-bit/2677 FAIL", 2677, 2, 2647, 185,  8,  10),
]


# ===========================================================================
# R1 — the projected lattice (d-column deleted)
# ===========================================================================

def build_projected_lattice(sigs, n, lam, k1_bound, k2_bound):
    """R1.  Columns: 0..m-1 = k1 (scale S_K1), m..2m-1 = k2 (scale S_K2),
    2m = Kannan.  Rows: m modular, 1 d-row, m k2-rows, 1 A-row = 2m+2 rows in
    2m+1 columns (rank 2m+1; the dependency is exactly the image of the
    trivial vector, which projects to 0)."""
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    dim = 2 * m + 1
    M = []
    for i in range(m):                       # modular rows
        r = [0] * dim; r[i] = n * S_K1; M.append(r)
    r = [0] * dim                            # d-row (its S_D entry is deleted)
    for i in range(m):
        r[i] = sigs[i]['B'] * S_K1
    M.append(r)
    for i in range(m):                       # k2-rows
        r = [0] * dim; r[i] = -lam * S_K1; r[m + i] = S_K2; M.append(r)
    r = [0] * dim                            # A-row + Kannan
    for i in range(m):
        r[i] = sigs[i]['A'] * S_K1
    r[2 * m] = S_KAN
    M.append(r)
    return M


def planted_vector_proj(sigs, n, k1_bound, k2_bound):
    """(k1_i*S_K1, k2_i*S_K2, S_KANNAN) — the R0 planted vector with the
    d-coordinate dropped."""
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    v = [0] * (2 * m + 1)
    for i in range(m):
        v[i] = sigs[i]['k1'] * S_K1
        v[m + i] = sigs[i]['k2'] * S_K2
    v[2 * m] = S_KAN
    return v


def recover_d_proj(rows, sigs, n, lam, k1_bound, k2_bound, d_secret):
    """R1 recovery.  d is not a lattice coordinate any more: read (k1_0, k2_0)
    off a row whose Kannan coordinate is +-S_KANNAN and solve the congruence
    A_0 + B_0*d = k1_0 + lam*k2_0 (mod n) for d."""
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    for row in rows:
        last = row[2 * m]
        if abs(last) != S_KAN:
            continue
        sign = 1 if last > 0 else -1
        for i in range(m):
            a, b = sign * row[i], sign * row[m + i]
            if a % S_K1 or b % S_K2:
                continue
            k1_i, k2_i = a // S_K1, b // S_K2
            B = sigs[i]['B']
            if B % n == 0:
                continue
            d_cand = (k1_i + lam * k2_i - sigs[i]['A']) * modinv(B, n) % n
            if d_cand == d_secret:
                return d_cand
    return None


# ===========================================================================
# R2 — explicit BDD, no Kannan embedding
# ===========================================================================

def build_bdd_lattice(sigs, n, lam, k1_bound, k2_bound):
    """L2 in the 2m-dim (k1|k2) space: modular rows, d-row, k2-rows."""
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    dim = 2 * m
    M = []
    for i in range(m):
        r = [0] * dim; r[i] = n * S_K1; M.append(r)
    r = [0] * dim
    for i in range(m):
        r[i] = sigs[i]['B'] * S_K1
    M.append(r)
    for i in range(m):
        r = [0] * dim; r[i] = -lam * S_K1; r[m + i] = S_K2; M.append(r)
    return M


def bdd_target(sigs, n, k1_bound, k2_bound):
    """t = (-A_i*S_K1, 0, ..., 0).  The lattice vector w = d*row_d + sum k2_i
    row_k2i - sum c_i row_i has k1-block (k1_i - A_i)*S_K1 and k2-block
    k2_i*S_K2, so w is within ~||(k1*S_K1, k2*S_K2)|| of t."""
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    t = [0] * (2 * m)
    for i in range(m):
        t[i] = -sigs[i]['A'] * S_K1
    return t


def recover_d_bdd(w, sigs, n, lam, k1_bound, k2_bound, d_secret):
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    for i in range(m):
        if w[i] % S_K1 or w[m + i] % S_K2:
            continue
        k1_i = w[i] // S_K1 + sigs[i]['A']
        k2_i = w[m + i] // S_K2
        B = sigs[i]['B']
        if B % n == 0:
            continue
        d_cand = (k1_i + lam * k2_i - sigs[i]['A']) * modinv(B, n) % n
        if d_cand == d_secret:
            return d_cand
    return None


def babai_nearest_plane(M_rows, target):
    """Babai nearest-plane on an LLL-reduced copy of M_rows.  Returns the
    lattice vector closest to `target` found by the algorithm."""
    A = IntegerMatrix.from_matrix(M_rows)
    LLL.reduction(A)
    rows = [[A[i][j] for j in range(A.ncols)] for i in range(A.nrows)]
    keep = [r for r in rows if any(r)]
    B = IntegerMatrix.from_matrix(keep)
    G = GSO.Mat(B)
    G.update_gso()
    coeffs = G.babai([int(x) for x in target])
    w = [0] * B.ncols
    for i, c in enumerate(coeffs):
        if c:
            for j in range(B.ncols):
                w[j] += c * keep[i][j]
    return w


# ===========================================================================
# Lattice-geometry helpers
# ===========================================================================

def log_det(M_rows):
    """log(covolume) of the lattice generated by M_rows (any rank)."""
    A = IntegerMatrix.from_matrix(M_rows)
    LLL.reduction(A)
    keep = [[A[i][j] for j in range(A.ncols)] for i in range(A.nrows)]
    keep = [r for r in keep if any(r)]
    B = IntegerMatrix.from_matrix(keep)
    G = GSO.Mat(B)
    G.update_gso()
    return 0.5 * sum(math.log(G.get_r(i, i)) for i in range(B.nrows)), B.nrows


def gaussian_heuristic(logdet, dim):
    return math.exp(0.5 * math.log(dim / (2 * math.pi * math.e)) + logdet / dim)


# ===========================================================================
# Runners
# ===========================================================================

def run_R0(curve, m, d_secret, k1_bound, seed, algo='LLL', beta=20):
    p, b, n, lam, G = curve
    k2b = math.isqrt(n) + 1
    sigs = gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2b, seed)
    if len(sigs) < m:
        return None
    M = build_glv_lattice(sigs, n, lam, k1_bound, k2b)
    A = IntegerMatrix.from_matrix(M)
    if algo == 'LLL':
        LLL.reduction(A)
    else:
        BKZ.reduction(A, BKZ.Param(beta))
    rows = [[A[i][j] for j in range(A.ncols)] for i in range(A.nrows)]
    _, _, _, S_KAN = scales(n, k1_bound, k2b)
    ok = recover_d(rows, m, n, S_KAN, d_secret) is not None
    pv = norm(planted_vector(sigs, d_secret, n, k1_bound, k2b))
    sv = min(norm(r) for r in rows if any(r))
    return ok, pv, sv, sigs


def run_R1(curve, m, d_secret, k1_bound, seed, algo='LLL', beta=20):
    p, b, n, lam, G = curve
    k2b = math.isqrt(n) + 1
    sigs = gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2b, seed)
    if len(sigs) < m:
        return None
    M = build_projected_lattice(sigs, n, lam, k1_bound, k2b)
    A = IntegerMatrix.from_matrix(M)
    if algo == 'LLL':
        LLL.reduction(A)
    else:
        BKZ.reduction(A, BKZ.Param(beta))
    rows = [[A[i][j] for j in range(A.ncols)] for i in range(A.nrows)]
    ok = recover_d_proj(rows, sigs, n, lam, k1_bound, k2b, d_secret) is not None
    pv = norm(planted_vector_proj(sigs, n, k1_bound, k2b))
    nz = [r for r in rows if any(r)]
    sv = min(norm(r) for r in nz) if nz else float('nan')
    return ok, pv, sv, sigs


def run_R2(curve, m, d_secret, k1_bound, seed):
    p, b, n, lam, G = curve
    k2b = math.isqrt(n) + 1
    sigs = gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2b, seed)
    if len(sigs) < m:
        return None
    M = build_bdd_lattice(sigs, n, lam, k1_bound, k2b)
    t = bdd_target(sigs, n, k1_bound, k2b)
    w = babai_nearest_plane(M, t)
    ok = recover_d_bdd(w, sigs, n, lam, k1_bound, k2b, d_secret) is not None
    return ok, 0.0, 0.0, sigs


RUNNERS = {'R0': run_R0, 'R1': run_R1, 'R2': run_R2}


def success_rate(kind, curve, m, k1_bound, seeds, **kw):
    n = curve[2]
    wins, ratios = 0, []
    for seed in seeds:
        d_trial = random.Random(seed + 7777).randint(1, n - 1)
        res = RUNNERS[kind](curve, m, d_trial, k1_bound, seed, **kw)
        if res is None:
            continue
        ok, pv, sv, _ = res
        wins += bool(ok)
        if pv:
            ratios.append(sv / pv)
    return wins, len(seeds), (sum(ratios) / len(ratios) if ratios else float('nan'))


# ===========================================================================
print("=" * 78)
print("Thread 23 — make the planted vector lambda_1 (GLV-HNP Phase 2)")
print("=" * 78)

hist = []
for label, p, b, n, lam, k1, m in HIST:
    G = find_generator(p, b, n)
    assert G is not None, f"no generator for {label}"
    assert (lam * lam + lam + 1) % n == 0, f"bad lam for {label}"
    hist.append((label, (p, b, n, lam, G), k1, m))


# ---------------------------------------------------------------------------
print("\n" + "-" * 78)
print("EXP P1: structural check — the trivial vector, and its removal")
print("-" * 78)
print("(a) n*row_d - sum_i B_i*row_i == n*S_D*e_m exactly?")
print("(b) is that vector the shortest LLL vector of R0?")
print("(c) does the projected planted vector lie in R1?")
print("(d) rank and covolume of R0 vs R1 (predicted det(R1) = det(R0)/(n*S_D))\n")

print(f"{'curve':<18} {'m':>3} {'(a)':>6} {'(b)':>6} {'(c)':>6} "
      f"{'rk R0':>6} {'rk R1':>6} {'log det R0':>11} {'log det R1':>11} {'pred':>11}")
for label, curve, k1, m in hist:
    p, b, n, lam, G = curve
    k2b = math.isqrt(n) + 1
    d0 = random.Random(42 + 7777).randint(1, n - 1)
    sigs = gen_signatures(G, d0, m, n, lam, p, k1, k2b, 42)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1, k2b)
    M0 = build_glv_lattice(sigs, n, lam, k1, k2b)
    dim0 = 2 * m + 2

    # (a) explicit combination
    comb = [n * M0[m][j] for j in range(dim0)]
    for i in range(m):
        for j in range(dim0):
            comb[j] -= sigs[i]['B'] * M0[i][j]
    expect = [0] * dim0
    expect[m] = n * S_D
    a_ok = (comb == expect)

    # (b) shortest LLL vector of R0
    A = IntegerMatrix.from_matrix(M0)
    LLL.reduction(A)
    rows0 = [[A[i][j] for j in range(dim0)] for i in range(A.nrows)]
    sv0 = min((r for r in rows0 if any(r)), key=norm)
    b_ok = (norm(sv0) == n * S_D and abs(sv0[m]) == n * S_D)

    # (c) projected planted vector in R1?  solve by integer linear algebra:
    #     it is by construction  A-row + d*d-row + sum k2_i*k2-row - sum c_i*mod-row
    M1 = build_projected_lattice(sigs, n, lam, k1, k2b)
    dim1 = 2 * m + 1
    v = [M1[2 * m + 1][j] for j in range(dim1)]          # A-row
    for j in range(dim1):
        v[j] += d0 * M1[m][j]                            # d * d-row
    for i in range(m):
        for j in range(dim1):
            v[j] += sigs[i]['k2'] * M1[m + 1 + i][j]     # k2_i * k2-row
    for i in range(m):
        c = v[i] // (n * S_K1)
        for j in range(dim1):
            v[j] -= c * M1[i][j]                         # reduce mod n
    c_ok = (v == planted_vector_proj(sigs, n, k1, k2b))

    ld0, rk0 = log_det(M0)
    ld1, rk1 = log_det(M1)
    pred = ld0 - math.log(n * S_D)
    print(f"{label:<18} {m:>3} {str(a_ok):>6} {str(b_ok):>6} {str(c_ok):>6} "
          f"{rk0:>6} {rk1:>6} {ld0:>11.4f} {ld1:>11.4f} {pred:>11.4f}")


# ---------------------------------------------------------------------------
print("\n" + "-" * 78)
print("EXP P2: sv/pv, R0 vs R1  (T5 of 2026-07-29 said sv/pv ~ 0.35 in R0)")
print("-" * 78)
print("sv/pv < 1 means LLL finds something SHORTER than the planted vector,")
print("i.e. the planted vector is not lambda_1 and SVP is the wrong target.\n")
print(f"{'curve':<18} {'K1':>4} {'m':>3} {'R0 sv/pv':>9} {'R1 sv/pv':>9} "
      f"{'R0 win':>7} {'R1 win':>7}")
for label, curve, k1, m in hist:
    w0, t0, r0 = success_rate('R0', curve, m, k1, SEEDS)
    w1, t1, r1 = success_rate('R1', curve, m, k1, SEEDS)
    print(f"{label:<18} {k1:>4} {m:>3} {r0:>9.3f} {r1:>9.3f} "
          f"{str(w0)+'/'+str(t0):>7} {str(w1)+'/'+str(t1):>7}")


# ---------------------------------------------------------------------------
print("\n" + "-" * 78)
print("EXP P3: THE FALSIFIER — does the K1 wall move? (m=12, the T4 grid)")
print("-" * 78)
print("2026-07-29 T4 (R0):  lam*=0.340 -> wall at K1 ~ 12-16")
print("                     lam*=0.070 -> wall at K1 ~ 4-6")
print("If R1/R2 push the lam*=0.07 wall outward, the reformulation is real.\n")

K1_GRID = [2, 3, 4, 6, 8, 12, 16, 24]
M_FIX = 12
grid = {}
for kind in ('R0', 'R1', 'R2'):
    print(f"\n[{kind}]")
    print(f"{'curve':<18} {'lam*':>7} " + " ".join(f"K1={k:<4}" for k in K1_GRID))
    for label, curve, _k1, _m in hist:
        p, b, n, lam, G = curve
        if n < 2000:
            continue                     # 8-bit curve: K2=15, grid incomparable
        cells = []
        for k1 in K1_GRID:
            w, t, _ = success_rate(kind, curve, M_FIX, k1, SEEDS)
            grid[(kind, label, k1)] = (w, t)
            cells.append(f"{w}/{t}  ")
        print(f"{label:<18} {lam_star(lam,n):>7.4f} " + " ".join(cells))

print("\n(eff = K1*K2/n with K2=52, n~2650: "
      + ", ".join(f"K1={k}:{k*52/2647:.3f}" for k in K1_GRID) + ")")


# ---------------------------------------------------------------------------
print("\n" + "-" * 78)
print("EXP P4: Gaussian-heuristic accounting — is the wall information-theoretic?")
print("-" * 78)
print("GH(L) = sqrt(dim/(2*pi*e)) * det^(1/dim).  If ||pv|| > GH(L) the planted")
print("vector is no shorter than a random lattice point: NO reduction algorithm")
print("can single it out, and the wall is information-theoretic, not algorithmic.\n")
print(f"{'curve':<18} {'K1':>4} {'eff':>6} {'R0 |pv|/GH':>11} {'R1 |pv|/GH':>11} "
      f"{'R0 win':>7} {'R1 win':>7}")
for label, curve, _k1, _m in hist:
    p, b, n, lam, G = curve
    if n < 2000:
        continue
    k2b = math.isqrt(n) + 1
    for k1 in K1_GRID:
        d0 = random.Random(42 + 7777).randint(1, n - 1)
        sigs = gen_signatures(G, d0, M_FIX, n, lam, p, k1, k2b, 42)
        M0 = build_glv_lattice(sigs, n, lam, k1, k2b)
        M1 = build_projected_lattice(sigs, n, lam, k1, k2b)
        ld0, rk0 = log_det(M0)
        ld1, rk1 = log_det(M1)
        gh0 = gaussian_heuristic(ld0, rk0)
        gh1 = gaussian_heuristic(ld1, rk1)
        pv0 = norm(planted_vector(sigs, d0, n, k1, k2b))
        pv1 = norm(planted_vector_proj(sigs, n, k1, k2b))
        w0 = grid[('R0', label, k1)]
        w1 = grid[('R1', label, k1)]
        print(f"{label:<18} {k1:>4} {k1*k2b/n:>6.3f} {pv0/gh0:>11.3f} "
              f"{pv1/gh1:>11.3f} {str(w0[0])+'/'+str(w0[1]):>7} "
              f"{str(w1[0])+'/'+str(w1[1]):>7}")


# ---------------------------------------------------------------------------
print("\n" + "-" * 78)
print("EXP P5: BKZ retry of R1 at the wall")
print("-" * 78)
for label, curve, _k1, _m in hist:
    p, b, n, lam, G = curve
    if n < 2000:
        continue
    print(f"\n{label} (lam*={lam_star(lam,n):.4f}):")
    for k1 in (6, 8, 12, 16):
        cells = []
        for algo, beta in (('LLL', 0), ('BKZ', 20), ('BKZ', 40)):
            w, t, _ = success_rate('R1', curve, M_FIX, k1, SEEDS,
                                   algo=algo, beta=beta)
            tag = 'LLL' if algo == 'LLL' else f'BKZ{beta}'
            cells.append(f"{tag}: {w}/{t}")
        print(f"   K1={k1:<3} " + "   ".join(cells))


# ---------------------------------------------------------------------------
print("\n" + "-" * 78)
print("EXP P6: what is lambda_1 of R1, and the BDD unique-decoding criterion")
print("-" * 78)
print("P3 showed R1 == R0 cell for cell, yet P2 shows R1 sv/pv is still < 1:")
print("removing the trivial vector exposed a DIFFERENT parasitic vector.")
print("Both R0 and R1 recover d from a vector in the coset {Kannan = +-S_KAN},")
print("so the governing quantity is not lambda_1 of the full lattice but")
print("        gamma = ||pv_0|| / (lambda_1(L_0)/2)")
print("where L_0 is the Kannan-0 sublattice (= the R2 lattice L2, generated by")
print("the modular rows, the d-row and the k2-rows) and pv_0 = (k1_i*S_K1,")
print("k2_i*S_K2) is the exact distance from the BDD target to L2.")
print("Unique decoding is possible iff gamma < 1.\n")

print("(a) anatomy of the shortest R1 vector (seed 42)")
print(f"{'curve':<18} {'K1':>4} {'sv/pv':>7} {'k1-blk':>7} {'k2-blk':>7} "
      f"{'kan':>6} {'supp':>5} {'lam-blk?':>8} {'sv/mu_min':>10}")
for label, curve, _k1, _m in hist:
    p, b, n, lam, G = curve
    if n < 2000:
        continue
    k2b = math.isqrt(n) + 1
    for k1 in (2, 4, 8, 16):
        S_K1, S_D, S_K2, S_KAN = scales(n, k1, k2b)
        d0 = random.Random(42 + 7777).randint(1, n - 1)
        sigs = gen_signatures(G, d0, M_FIX, n, lam, p, k1, k2b, 42)
        M1 = build_projected_lattice(sigs, n, lam, k1, k2b)
        A = IntegerMatrix.from_matrix(M1)
        LLL.reduction(A)
        rows = [[A[i][j] for j in range(A.ncols)] for i in range(A.nrows)]
        sv = min((r for r in rows if any(r)), key=norm)
        pv = planted_vector_proj(sigs, n, k1, k2b)
        m = M_FIX
        tot = sum(x * x for x in sv) or 1
        e_k1 = sum(sv[i] ** 2 for i in range(m)) / tot
        e_k2 = sum(sv[m + i] ** 2 for i in range(m)) / tot
        e_kan = sv[2 * m] ** 2 / tot
        supp = sum(1 for i in range(m) if sv[i] or sv[m + i])
        is_blk = (supp == 1 and sv[2 * m] == 0)
        # exact shortest vector of the 2D lambda-block (same for every i)
        mu = gauss_2d((n * S_K1, 0), (-(lam % n) * S_K1, S_K2))
        mu_n = math.sqrt(mu[0] ** 2 + mu[1] ** 2)
        print(f"{label:<18} {k1:>4} {norm(sv)/norm(pv):>7.3f} {e_k1:>7.3f} "
              f"{e_k2:>7.3f} {e_kan:>6.3f} {supp:>5} {str(is_blk):>8} "
              f"{norm(sv)/mu_n:>10.3f}")

print("\n(b) the BDD criterion gamma = ||pv_0|| / (lambda_1(L2)/2), 5 seeds")
print("    lambda_1(L2) is EXACT (fpylll SVP on the LLL-reduced L2, dim 2m=24)")
print(f"\n{'curve':<18} {'K1':>4} {'mean gamma':>11} {'pred<1':>7} {'R1 win':>7} "
      f"{'agree':>6}")
for label, curve, _k1, _m in hist:
    p, b, n, lam, G = curve
    if n < 2000:
        continue
    k2b = math.isqrt(n) + 1
    for k1 in K1_GRID:
        gammas, agree, npred = [], 0, 0
        for seed in SEEDS:
            d0 = random.Random(seed + 7777).randint(1, n - 1)
            sigs = gen_signatures(G, d0, M_FIX, n, lam, p, k1, k2b, seed)
            L2 = build_bdd_lattice(sigs, n, lam, k1, k2b)
            A = IntegerMatrix.from_matrix(L2)
            LLL.reduction(A)
            keep = [[A[i][j] for j in range(A.ncols)] for i in range(A.nrows)]
            keep = [r for r in keep if any(r)]
            B = IntegerMatrix.from_matrix(keep)
            try:
                sv2 = SVP.shortest_vector(B)
                lam1 = math.sqrt(sum(int(x) ** 2 for x in sv2))
            except Exception:
                BKZ.reduction(B, BKZ.Param(40))
                lam1 = min(norm([B[i][j] for j in range(B.ncols)])
                           for i in range(B.nrows)
                           if any(B[i][j] for j in range(B.ncols)))
            m = M_FIX
            S_K1, S_D, S_K2, S_KAN = scales(n, k1, k2b)
            pv0 = math.sqrt(sum((sigs[i]['k1'] * S_K1) ** 2
                                + (sigs[i]['k2'] * S_K2) ** 2 for i in range(m)))
            g = pv0 / (lam1 / 2)
            gammas.append(g)
            res = run_R1(curve, M_FIX, d0, k1, seed)
            ok = bool(res and res[0])
            pred = (g < 1)
            npred += pred
            agree += (pred == ok)
        w, t = grid[('R1', label, k1)]
        print(f"{label:<18} {k1:>4} {sum(gammas)/len(gammas):>11.3f} "
              f"{str(npred)+'/'+str(len(SEEDS)):>7} {str(w)+'/'+str(t):>7} "
              f"{str(agree)+'/'+str(len(SEEDS)):>6}")

print("\nDone.")
