"""
GLV-HNP Phase 2, Thread 23: reformulate the lattice so the planted vector is
lambda_1, and test whether the K1 wall moves.

Background (RESEARCH_AUTOLAB_LOG.md, 2026-07-29, EXP T5):
  In the Phase-2 lattice L_O (dim 2m+2, `build_glv_lattice` in
  glv_hnp_phase2_20bit.py:263) the shortest vector after LLL is ALWAYS the
  trivial vector  n*S_D*e_m  -- 100% of its energy in the d-column, and it
  carries no information because d is only defined mod n.  Measured
  ||sv||/||v_planted|| in [0.337, 0.368] for successes and failures alike.
  Recovery is therefore not an SVP condition but a BDD/coset condition.

  That run proposed Thread 23: quotient out the trivial e_m direction (or
  replace the Kannan embedding with an explicit CVP call) so that the planted
  vector really is the target of the reduction.

  Falsifier stated on 2026-07-29:
    "if sv/pv rises above 1 after the reformulation AND the K1 wall in T4
     moves outward on the lam*=0.07 curve (currently K1 ~ 4-6), the
     reformulation is a real improvement; if the wall stays at K1 ~ 4-6, then
     the wall is information-theoretic and Phase 2 is at its ceiling."

The three lattices compared here
--------------------------------
Write S_K1 = n//K1, S_D = 1, S_K2 = max(1, n//K2), S_KAN = n, and let the
signatures satisfy  A_i + d*B_i = k1_i + lam*k2_i  (mod n)  with
0 <= k1_i < K1 and 0 <= k2_i < K2.

  L_O  "original", dim 2m+2, columns [k1_0..k1_{m-1} | d | k2_0..k2_{m-1} | kan]
       planted v_O = (k1_i*S_K1, d*S_D, k2_i*S_K2, S_KAN)
       det(L_O) = n^(3m+1) / (K1*K2)^m
       contains  n*S_D*e_m  of norm n < ||v_O||  ==>  planted is never lambda_1.

  L_R  "reduced/projected", dim 2m+1: DROP the d-column.  d is not a
       coordinate; it is recovered algebraically afterwards from
         d = (k1_0 + lam*k2_0 - A_0) * B_0^{-1}  (mod n).
       planted v_R = (k1_i*S_K1, k2_i*S_K2, S_KAN)
       Generated by the same 2m+2 rows with column m deleted (rank 2m+1: the
       d-row is Q-dependent on the n*S_K1*e_i rows but Z-essential).
       det(L_R) = det(L_O) / (n*S_D) = n^(3m) / (K1*K2)^m.
       The e_m direction is gone, so no trivial short vector survives.

  L_B  "Babai/CVP", dim 2m: L_R with the Kannan column and row removed.
       Not an SVP instance at all: Babai nearest-plane against the target
       t = (A_i*S_K1, 0^m); the planted vector is t + w for w in L_B.
       det(L_B) = n^(3m-1) / (K1*K2)^m.

Experiments
-----------
  U0  Analytic Gaussian-heuristic prediction of the K1 wall for L_O and L_R.
      Done BEFORE the measurements so the empirical run is a real test.
  U1  Correctness: v_R is in L_R, v_B - t is in L_B, and algebraic d-recovery
      reproduces d_secret.
  U2  Is the planted vector lambda_1 now?  ||sv||/||pv|| for L_O vs L_R.
  U3  The 2026-07-29 T4 grid re-run for all three variants:
      the two historical 12-bit curves, K1 in {2,3,4,6,8,12,16,24}, m=12,
      5 seeds -- identical harness parameters to the T4 table so the wall
      positions are directly comparable.
  U4  BKZ(30) retry of L_R at the wall, to separate "reduction quality" from
      "information-theoretic".

Run:  python3 secp256k1_cm_audit/glv_hnp_phase2_projected.py
"""

import math
import random
import sys

from fpylll import IntegerMatrix, LLL, BKZ, GSO


# ---------------------------------------------------------------------------
# Arithmetic helpers (verbatim from glv_hnp_phase2_lambda_threshold.py:87-180)
# ---------------------------------------------------------------------------

def modinv(a, m):
    return pow(a, -1, m)

def ec_add(P, Q, p):
    if P is None: return Q
    if Q is None: return P
    x1, y1 = P; x2, y2 = Q
    if x1 == x2:
        if (y1 + y2) % p == 0: return None
        s = 3 * x1 * x1 * modinv(2 * y1, p) % p
    else:
        s = (y2 - y1) * modinv(x2 - x1, p) % p
    x3 = (s * s - x1 - x2) % p
    y3 = (s * (x1 - x3) - y1) % p
    return (x3, y3)

def ec_mul(P, k, p):
    if k == 0: return None
    R, Q = None, P
    while k > 0:
        if k & 1: R = ec_add(R, Q, p)
        Q = ec_add(Q, Q, p)
        k >>= 1
    return R

def tonelli_shanks(n, p):
    n %= p
    if n == 0: return 0
    if pow(n, (p - 1) // 2, p) != 1: return None
    if p % 4 == 3: return pow(n, (p + 1) // 4, p)
    q, s = p - 1, 0
    while q % 2 == 0: q //= 2; s += 1
    z = 2
    while pow(z, (p - 1) // 2, p) != p - 1: z += 1
    m, c, t, r = s, pow(z, q, p), pow(n, q, p), pow(n, (q + 1) // 2, p)
    while True:
        if t == 0: return 0
        if t == 1: return r
        i, tmp = 0, t
        while tmp != 1: tmp = tmp * tmp % p; i += 1
        b = pow(c, 1 << (m - i - 1), p)
        m, c, t, r = i, b * b % p, t * b * b % p, r * b % p

def find_generator(p, b, n, seed=12345):
    rng = random.Random(seed)
    for _ in range(20000):
        x = rng.randint(0, p - 1)
        rhs = (pow(x, 3, p) + b) % p
        y = tonelli_shanks(rhs, p)
        if y is not None and y != 0:
            P = (x, y)
            if ec_mul(P, n, p) is None:
                return P
    return None

def lam_star(lam, n):
    return min(lam % n, n - (lam % n)) / n

def norm(v):
    return math.sqrt(sum(x * x for x in v))


# ---------------------------------------------------------------------------
# Signature generation (verbatim from glv_hnp_phase2_lambda_threshold.py:230)
# ---------------------------------------------------------------------------

def scales(n, k1_bound, k2_bound):
    return (n // k1_bound, 1, max(1, n // k2_bound), n)

def gen_signatures(G, d_secret, m, n, lam, p, k1_bound, k2_bound, seed=42):
    rng = random.Random(seed)
    sigs = []
    attempts = 0
    while len(sigs) < m and attempts < 200000:
        attempts += 1
        k1 = rng.randint(0, k1_bound - 1)
        k2 = rng.randint(0, k2_bound - 1)
        k_full = (k1 + lam * k2) % n
        if k_full == 0: continue
        R = ec_mul(G, k_full, p)
        if R is None: continue
        r = R[0] % n
        if r == 0: continue
        h = rng.randint(0, n - 1)
        s = modinv(k_full, n) * (h + d_secret * r) % n
        if s == 0: continue
        s_inv = modinv(s, n)
        A = h * s_inv % n
        B = r * s_inv % n
        assert (A + B * d_secret) % n == k_full
        sigs.append({'A': A, 'B': B, 'k1': k1, 'k2': k2})
    return sigs


# ---------------------------------------------------------------------------
# L_O -- the original Phase-2 lattice (verbatim, dim 2m+2)
# ---------------------------------------------------------------------------

def build_lattice_O(sigs, n, lam, k1_bound, k2_bound):
    m = len(sigs)
    dim = 2 * m + 2
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    M = [[0] * dim for _ in range(dim)]
    for i in range(m):
        M[i][i] = n * S_K1
    for i in range(m):
        M[m][i] = sigs[i]['B'] * S_K1
    M[m][m] = S_D
    for i in range(m):
        M[m + 1 + i][i] = -lam * S_K1
        M[m + 1 + i][m + 1 + i] = S_K2
    for i in range(m):
        M[2 * m + 1][i] = sigs[i]['A'] * S_K1
    M[2 * m + 1][dim - 1] = S_KAN
    return M

def planted_O(sigs, d_secret, n, k1_bound, k2_bound):
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    v = [0] * (2 * m + 2)
    for i in range(m):
        v[i] = sigs[i]['k1'] * S_K1
        v[m + 1 + i] = sigs[i]['k2'] * S_K2
    v[m] = d_secret * S_D
    v[2 * m + 1] = S_KAN
    return v

def recover_O(rows, m, n, S_KAN, d_secret):
    dim = 2 * m + 2
    for row in rows:
        last = row[dim - 1]
        if abs(last) != S_KAN: continue
        sign = 1 if last > 0 else -1
        d_cand = (sign * row[m]) % n
        if d_cand == 0: continue
        if d_cand == d_secret:
            return d_cand
    return None


# ---------------------------------------------------------------------------
# L_R -- d-column deleted (dim 2m+1); d recovered algebraically
# ---------------------------------------------------------------------------

def build_lattice_R(sigs, n, lam, k1_bound, k2_bound):
    """2m+2 generating rows spanning a rank-(2m+1) lattice.  Column layout:
       [0..m-1] = k1 columns, [m..2m-1] = k2 columns, [2m] = Kannan."""
    m = len(sigs)
    dim = 2 * m + 1
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    rows = []
    for i in range(m):                              # n*S_K1*e_i
        r = [0] * dim; r[i] = n * S_K1; rows.append(r)
    r = [0] * dim                                   # d-row (no d column now)
    for i in range(m):
        r[i] = sigs[i]['B'] * S_K1
    rows.append(r)
    for i in range(m):                              # k2 rows
        r = [0] * dim
        r[i] = -lam * S_K1
        r[m + i] = S_K2
        rows.append(r)
    r = [0] * dim                                   # Kannan row
    for i in range(m):
        r[i] = sigs[i]['A'] * S_K1
    r[dim - 1] = S_KAN
    rows.append(r)
    return rows

def planted_R(sigs, n, k1_bound, k2_bound):
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    v = [0] * (2 * m + 1)
    for i in range(m):
        v[i] = sigs[i]['k1'] * S_K1
        v[m + i] = sigs[i]['k2'] * S_K2
    v[2 * m] = S_KAN
    return v

def d_from_k(sigs, k1s, k2s, n, lam):
    """d = (k1_i + lam*k2_i - A_i) * B_i^{-1} mod n, required consistent for all i."""
    d0 = None
    for i, sg in enumerate(sigs):
        try:
            binv = modinv(sg['B'], n)
        except ValueError:
            return None
        d_i = (k1s[i] + lam * k2s[i] - sg['A']) * binv % n
        if d0 is None:
            d0 = d_i
        elif d_i != d0:
            return None
    return d0

def recover_R(rows, sigs, n, lam, k1_bound, k2_bound, d_secret):
    """Read (k1,k2) off any row whose Kannan entry is +-S_KAN, then solve for d."""
    m = len(sigs)
    dim = 2 * m + 1
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    for row in rows:
        last = row[dim - 1]
        if abs(last) != S_KAN: continue
        sign = 1 if last > 0 else -1
        k1s, k2s, ok = [], [], True
        for i in range(m):
            a, b = sign * row[i], sign * row[m + i]
            if a % S_K1 or b % S_K2:
                ok = False; break
            k1s.append(a // S_K1); k2s.append(b // S_K2)
        if not ok:
            continue
        d_cand = d_from_k(sigs, k1s, k2s, n, lam)
        if d_cand is not None and d_cand == d_secret:
            return d_cand
    return None


# ---------------------------------------------------------------------------
# L_B -- explicit CVP (dim 2m), Babai nearest-plane
# ---------------------------------------------------------------------------

def build_lattice_B(sigs, n, lam, k1_bound, k2_bound):
    m = len(sigs)
    dim = 2 * m
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    rows = []
    for i in range(m):
        r = [0] * dim; r[i] = n * S_K1; rows.append(r)
    r = [0] * dim
    for i in range(m):
        r[i] = sigs[i]['B'] * S_K1
    rows.append(r)
    for i in range(m):
        r = [0] * dim
        r[i] = -lam * S_K1
        r[m + i] = S_K2
        rows.append(r)
    return rows

def babai_nearest_plane(basis_rows, target):
    """Exact-rational Babai nearest-plane; basis_rows must be LLL-reduced and
    linearly independent.  Returns the lattice vector closest to `target`."""
    from fractions import Fraction
    k = len(basis_rows)
    # Gram-Schmidt over Q (exact)
    gs, mu = [], []
    for i in range(k):
        v = [Fraction(x) for x in basis_rows[i]]
        coeffs = []
        for j in range(i):
            gj = gs[j]
            den = sum(x * x for x in gj)
            c = Fraction(0) if den == 0 else sum(a * b for a, b in zip(basis_rows[i], gj)) / den
            coeffs.append(c)
            v = [a - c * b for a, b in zip(v, gj)]
        gs.append(v); mu.append(coeffs)
    b = [Fraction(x) for x in target]
    coef = [0] * k
    for i in range(k - 1, -1, -1):
        gi = gs[i]
        den = sum(x * x for x in gi)
        if den == 0:
            continue
        c = sum(a * bb for a, bb in zip(b, gi)) / den
        ci = int(c + Fraction(1, 2)) if c >= 0 else -int(-c + Fraction(1, 2))
        coef[i] = ci
        b = [a - ci * Fraction(x) for a, x in zip(b, basis_rows[i])]
    out = [0] * len(target)
    for i in range(k):
        if coef[i]:
            for j in range(len(target)):
                out[j] += coef[i] * basis_rows[i][j]
    return out

def recover_B(basis_rows, sigs, n, lam, k1_bound, k2_bound, d_secret):
    m = len(sigs)
    S_K1, S_D, S_K2, S_KAN = scales(n, k1_bound, k2_bound)
    target = [sigs[i]['A'] * S_K1 for i in range(m)] + [0] * m
    w = babai_nearest_plane(basis_rows, [-t for t in target])
    cand = [t + x for t, x in zip(target, w)]
    for sign in (1, -1):
        k1s, k2s, ok = [], [], True
        for i in range(m):
            a, b = sign * cand[i], sign * cand[m + i]
            if a % S_K1 or b % S_K2:
                ok = False; break
            k1s.append(a // S_K1); k2s.append(b // S_K2)
        if not ok:
            continue
        d_cand = d_from_k(sigs, k1s, k2s, n, lam)
        if d_cand is not None and d_cand == d_secret:
            return d_cand
    return None


# ---------------------------------------------------------------------------
# fpylll driver: reduce a (possibly rank-deficient) generating set
# ---------------------------------------------------------------------------

def reduce_rows(rows, beta=None):
    """LLL (or BKZ if beta given) a list of integer rows.  Drops zero rows that
    fplll emits for rank-deficient generating sets.  Returns list of rows."""
    ncols = len(rows[0])
    A = IntegerMatrix(len(rows), ncols)
    for i, r in enumerate(rows):
        for j, x in enumerate(r):
            A[i, j] = x
    LLL.reduction(A)
    if beta is not None:
        BKZ.reduction(A, BKZ.Param(beta))
    out = [[A[i][j] for j in range(ncols)] for i in range(A.nrows)]
    return [r for r in out if any(r)]


# ---------------------------------------------------------------------------
# Gaussian-heuristic prediction
# ---------------------------------------------------------------------------

def gh(dim, det):
    """Gaussian heuristic for lambda_1: sqrt(dim/(2*pi*e)) * det^(1/dim)."""
    return math.sqrt(dim / (2 * math.pi * math.e)) * math.exp(math.log(det) / dim)

def predict(variant, m, n, K1, K2):
    """(gh, E||planted||, gap = gh/||planted||).  gap > 1 => planted plausibly
    the shortest vector, i.e. LLL/BKZ has a target to find."""
    S_K1, S_D, S_K2, S_KAN = scales(n, K1, K2)
    log_det_O = (3 * m + 1) * math.log(n) - m * (math.log(K1) + math.log(K2))
    if variant == 'O':
        dim = 2 * m + 2
        ld = log_det_O
        pv2 = (m * (K1 * S_K1) ** 2 / 3.0 + (n * S_D) ** 2 / 3.0
               + m * (K2 * S_K2) ** 2 / 3.0 + S_KAN ** 2)
    elif variant == 'R':
        dim = 2 * m + 1
        ld = log_det_O - math.log(n * S_D)
        pv2 = (m * (K1 * S_K1) ** 2 / 3.0
               + m * (K2 * S_K2) ** 2 / 3.0 + S_KAN ** 2)
    else:                                            # 'B'
        dim = 2 * m
        ld = log_det_O - math.log(n * S_D) - math.log(S_KAN)
        pv2 = (m * (K1 * S_K1) ** 2 / 3.0 + m * (K2 * S_K2) ** 2 / 3.0)
    g = math.sqrt(dim / (2 * math.pi * math.e)) * math.exp(ld / dim)
    pv = math.sqrt(pv2)
    return g, pv, g / pv

def eff_wall(variant, m, n, K2):
    """Largest real K1 with gap >= 1, by bisection on K1."# noqa"""
    lo, hi = 1.0, float(n)
    if predict(variant, m, n, max(1, int(lo)), K2)[2] < 1.0:
        return 0.0
    for _ in range(60):
        mid = (lo + hi) / 2
        S = max(1, int(mid))
        if predict(variant, m, n, S, K2)[2] >= 1.0:
            lo = mid
        else:
            hi = mid
    return lo


# ---------------------------------------------------------------------------
# One trial
# ---------------------------------------------------------------------------

def trial(curve, m, K1, seed, variant, beta=None, want_diag=False):
    p, b, n, lam, G = curve
    K2 = math.isqrt(n) + 1
    d_secret = random.Random(seed + 7777).randint(1, n - 1)
    sigs = gen_signatures(G, d_secret, m, n, lam, p, K1, K2, seed)
    if len(sigs) < m:
        return None
    S_K1, S_D, S_K2, S_KAN = scales(n, K1, K2)

    if variant == 'O':
        rows = reduce_rows(build_lattice_O(sigs, n, lam, K1, K2), beta)
        ok = recover_O(rows, m, n, S_KAN, d_secret) is not None
        pv = planted_O(sigs, d_secret, n, K1, K2)
    elif variant == 'R':
        rows = reduce_rows(build_lattice_R(sigs, n, lam, K1, K2), beta)
        ok = recover_R(rows, sigs, n, lam, K1, K2, d_secret) is not None
        pv = planted_R(sigs, n, K1, K2)
    else:
        basis = reduce_rows(build_lattice_B(sigs, n, lam, K1, K2), beta)
        ok = recover_B(basis, sigs, n, lam, K1, K2, d_secret) is not None
        pv = None
        rows = basis

    if not want_diag:
        return ok
    sv = min((r for r in rows if any(r)), key=norm)
    return ok, norm(sv), (norm(pv) if pv else float('nan')), sv, pv


def rate(curve, m, K1, seeds, variant, beta=None):
    w = 0
    for s in seeds:
        r = trial(curve, m, K1, s, variant, beta)
        if r: w += 1
    return w, len(seeds)


# ===========================================================================
# Setup
# ===========================================================================

SEEDS = [42, 1234, 9999, 555, 31337]
K1_GRID = [2, 3, 4, 6, 8, 12, 16, 24]
M_SIGS = 12                     # identical to the 2026-07-29 T4 grid

HIST = [
    # label,              p,    b, n,    lam
    ("12-bit/2557",       2557, 2, 2659, 1755),
    ("12-bit/2677 FAIL",  2677, 2, 2647, 185),
]
curves = []
for label, p, b, n, lam in HIST:
    G = find_generator(p, b, n)
    assert G is not None, f"no generator for {label}"
    assert (lam * lam + lam + 1) % n == 0, f"bad lam for {label}"
    curves.append((label, (p, b, n, lam, G)))

print("=" * 78)
print("Thread 23 -- does removing the trivial e_m direction move the K1 wall?")
print("=" * 78)
print(f"m = {M_SIGS} signatures, seeds = {SEEDS}")
for label, c in curves:
    p, b, n, lam, G = c
    print(f"  {label:<18} p={p} n={n} ({n.bit_length()}b) lam={lam} "
          f"lam*={lam_star(lam,n):.4f} K2={math.isqrt(n)+1}")


# ===========================================================================
# U0 -- analytic prediction, stated BEFORE the measurements
# ===========================================================================

print("\n" + "-" * 78)
print("EXP U0: Gaussian-heuristic prediction of the K1 wall (analytic)")
print("-" * 78)
print("det(L_O) = n^(3m+1)/(K1*K2)^m,  dim 2m+2,  ||v_O||^2 ~ n^2*(2m/3 + 4/3)")
print("det(L_R) = n^(3m)  /(K1*K2)^m,  dim 2m+1,  ||v_R||^2 ~ n^2*(2m/3 + 1)")
print("Both give, with eff = K1*K2/n and C = sqrt(3/(2*pi*e)) = "
      f"{math.sqrt(3/(2*math.pi*math.e)):.4f}:")
print("    L_O:  eff < C^2 * (C^2   / n)^(1/m)")
print("    L_R:  eff < C^2 * (C^2*3/(2m+3) * (2m+1)/(2m+3) ... )^(1/m)   [numeric below]")
print("i.e. dropping the d-column buys exactly one factor of  n*S_D  in the")
print("determinant, which amortises as  n^(1/m)  -- an m-th root.  Predicted")
print("gain is therefore SMALL.\n")

print(f"{'curve':<18} {'variant':>7} {'K1_wall':>8} {'eff_wall':>9} "
      f"{'gain vs O':>10}")
walls = {}
for label, c in curves:
    p, b, n, lam, G = c
    K2 = math.isqrt(n) + 1
    wO = eff_wall('O', M_SIGS, n, K2)
    for v in ('O', 'R', 'B'):
        w = eff_wall(v, M_SIGS, n, K2)
        walls[(label, v)] = w
        print(f"{label:<18} {v:>7} {w:>8.2f} {w*K2/n:>9.4f} "
              f"{(w/wO if wO else float('nan')):>9.3f}x")

print("\nPer-K1 gap = GH/||planted||  (gap > 1 predicts the planted vector is")
print("plausibly lambda_1; gap < 1 predicts it is drowned):")
for label, c in curves:
    p, b, n, lam, G = c
    K2 = math.isqrt(n) + 1
    print(f"\n  {label}   (K2={K2}, n={n})")
    print(f"    {'K1':>4} {'eff':>7} " + " ".join(f"{'gap_'+v:>8}" for v in 'ORB'))
    for K1 in K1_GRID:
        gaps = [predict(v, M_SIGS, n, K1, K2)[2] for v in 'ORB']
        print(f"    {K1:>4} {K1*K2/n:>7.4f} " + " ".join(f"{g:>8.3f}" for g in gaps))

print("\nPREDICTION (recorded before U3 runs): the L_R wall sits within ~10% of")
print("the L_O wall, so at integer K1 the two grids should be IDENTICAL.")


# ===========================================================================
# U1 -- correctness of the reformulation
# ===========================================================================

print("\n" + "-" * 78)
print("EXP U1: correctness -- v_R in L_R, and algebraic d-recovery works")
print("-" * 78)

def in_lattice(rows, v):
    """Is v in the Z-span of `rows`?  Solve by HNF-free elimination over Q with
    an integrality check: reduce v against an LLL-reduced basis via Babai and
    test for an exact hit."""
    w = babai_nearest_plane(rows, v)
    return all(a == b for a, b in zip(w, v))

allok = True
for label, c in curves:
    p, b, n, lam, G = c
    K2 = math.isqrt(n) + 1
    K1 = 4
    d_secret = random.Random(42 + 7777).randint(1, n - 1)
    sigs = gen_signatures(G, d_secret, 6, n, lam, p, K1, K2, 42)
    S_K1, S_D, S_K2, S_KAN = scales(n, K1, K2)
    basisR = reduce_rows(build_lattice_R(sigs, n, lam, K1, K2))
    vR = planted_R(sigs, n, K1, K2)
    hitR = in_lattice(basisR, vR)
    # algebraic d recovery from the true (k1,k2)
    d_alg = d_from_k(sigs, [s['k1'] for s in sigs], [s['k2'] for s in sigs], n, lam)
    # Babai target check for L_B
    basisB = reduce_rows(build_lattice_B(sigs, n, lam, K1, K2))
    tB = [sigs[i]['A'] * S_K1 for i in range(6)] + [0] * 6
    vB = [sigs[i]['k1'] * S_K1 for i in range(6)] + [sigs[i]['k2'] * S_K2 for i in range(6)]
    hitB = in_lattice(basisB, [a - b for a, b in zip(vB, tB)])
    print(f"  {label:<18} rank(L_R)={len(basisR):>3} (expect {2*6+1})  "
          f"v_R in L_R: {hitR}   d_alg==d: {d_alg == d_secret}   "
          f"v_B-t in L_B: {hitB}  rank(L_B)={len(basisB)} (expect {2*6})")
    allok &= hitR and (d_alg == d_secret) and hitB
print(f"  ALL CORRECTNESS CHECKS PASS: {allok}")


# ===========================================================================
# U2 -- is the planted vector lambda_1 now?
# ===========================================================================

print("\n" + "-" * 78)
print("EXP U2: ||shortest vector after LLL|| / ||planted||, L_O vs L_R")
print("-" * 78)
print("2026-07-29 T5 measured sv/pv in [0.337, 0.368] for L_O, with the")
print("shortest vector always = n*S_D*e_m (all energy in the d-column).")
print("If the reformulation works, L_R should show sv/pv ~ 1.\n")
print(f"{'curve':<18} {'K1':>3} {'sv/pv (O)':>10} {'|sv[m]|/n (O)':>13} "
      f"{'sv/pv (R)':>10} {'sv==pv (R)':>11} {'rec O':>6} {'rec R':>6}")
for label, c in curves:
    p, b, n, lam, G = c
    K2 = math.isqrt(n) + 1
    for K1 in (2, 4, 8):
        okO, svO, pvO, svvO, pvvO = trial(c, M_SIGS, K1, 42, 'O', want_diag=True)
        okR, svR, pvR, svvR, pvvR = trial(c, M_SIGS, K1, 42, 'R', want_diag=True)
        dcol = abs(svvO[M_SIGS]) / n
        same = (svR == pvR) and sorted(abs(x) for x in svvR) == sorted(abs(x) for x in pvvR)
        print(f"{label:<18} {K1:>3} {svO/pvO:>10.4f} {dcol:>13.4f} "
              f"{svR/pvR:>10.4f} {str(same):>11} {str(okO):>6} {str(okR):>6}")


# ===========================================================================
# U3 -- the T4 grid, all three variants
# ===========================================================================

print("\n" + "-" * 78)
print("EXP U3: the 2026-07-29 T4 K1 grid, re-run for L_O / L_R / L_B")
print("-" * 78)
print(f"m={M_SIGS}, {len(SEEDS)} seeds.  L_O column must reproduce the T4 table")
print("exactly (same harness, same seeds) -- that is the control.\n")
print(f"{'curve':<18} {'var':>4} " + " ".join(f"K1={k:<4}" for k in K1_GRID))
grid = {}
for label, c in curves:
    for v in ('O', 'R', 'B'):
        cells = []
        for K1 in K1_GRID:
            w, t = rate(c, M_SIGS, K1, SEEDS, v)
            grid[(label, v, K1)] = w
            cells.append(f"{w}/{t} ")
        print(f"{label:<18} {v:>4} " + " ".join(f"{x:<7}" for x in cells))
    print()

print("Wall position (largest K1 with >=3/5 recovery):")
for label, c in curves:
    for v in ('O', 'R', 'B'):
        best = max([K1 for K1 in K1_GRID if grid[(label, v, K1)] >= 3], default=0)
        print(f"  {label:<18} {v}: K1_wall = {best}")


# ===========================================================================
# U4 -- BKZ(30) on L_R at the wall
# ===========================================================================

print("\n" + "-" * 78)
print("EXP U4: BKZ(30) retry of L_R at and just past the wall")
print("-" * 78)
print("If the wall is a reduction-quality artefact, stronger reduction moves it.")
print("If it is information-theoretic, BKZ changes nothing.\n")
print(f"{'curve':<18} " + " ".join(f"K1={k:<9}" for k in (4, 6, 8, 12)))
for label, c in curves:
    cells = []
    for K1 in (4, 6, 8, 12):
        wl, t = rate(c, M_SIGS, K1, SEEDS, 'R')
        wb, _ = rate(c, M_SIGS, K1, SEEDS, 'R', beta=30)
        cells.append(f"LLL {wl}/{t} BKZ {wb}/{t}")
    print(f"{label:<18} " + " ".join(f"{x:<12}" for x in cells))


# ===========================================================================
# U5 -- where does the competing short vector live in L_R?
# ===========================================================================

print("\n" + "-" * 78)
print("EXP U5: energy localisation of the L_R shortest vector")
print("-" * 78)
print("T5 (2026-07-29) localised the L_O obstruction to the d-column.  That")
print("column is gone in L_R, so: what is short in L_R when the planted vector")
print("is not?  Columns: [0..m-1] k1-block, [m..2m-1] k2-block, [2m] Kannan.")
print("mu = exact shortest vector of the 2D lambda-block "
      "<(n*S_K1,0), (-lam*S_K1,S_K2)>.\n")

def gauss_reduce_2d(u, v):
    def nrm2(w): return w[0] * w[0] + w[1] * w[1]
    def dot(w, z): return w[0] * z[0] + w[1] * z[1]
    if nrm2(u) > nrm2(v):
        u, v = v, u
    while True:
        num, den = dot(v, u), nrm2(u)
        if den == 0: break
        q = (2*num + den)//(2*den) if num >= 0 else -((-2*num + den)//(2*den))
        v = (v[0] - q*u[0], v[1] - q*u[1])
        if nrm2(v) >= nrm2(u): break
        u, v = v, u
    return u

print(f"{'curve':<18} {'K1':>3} {'sv/pv':>7} {'E_k1':>6} {'E_k2':>6} {'E_kan':>6} "
      f"{'supp':>5} {'lam-blk':>8} {'mu/pv':>7} {'rec':>5}")
for label, c in curves:
    p, b, n, lam, G = c
    K2 = math.isqrt(n) + 1
    for K1 in (2, 4, 6, 8, 12):
        okR, svR, pvR, sv, pv = trial(c, M_SIGS, K1, 42, 'R', want_diag=True)
        m = M_SIGS
        e1 = sum(x*x for x in sv[:m]) / (svR*svR)
        e2 = sum(x*x for x in sv[m:2*m]) / (svR*svR)
        ek = sv[2*m]**2 / (svR*svR)
        supp = sum(1 for x in sv if x)
        # is sv supported on a single (i, m+i) lambda-block pair?
        idx = [i for i in range(m) if sv[i] or sv[m+i]]
        lamblk = (len(idx) == 1 and sv[2*m] == 0)
        S_K1, S_D, S_K2, S_KAN = scales(n, K1, K2)
        w = gauss_reduce_2d((n*S_K1, 0), (-(lam % n)*S_K1, S_K2))
        mu = math.sqrt(w[0]*w[0] + w[1]*w[1])
        print(f"{label:<18} {K1:>3} {svR/pvR:>7.4f} {e1:>6.3f} {e2:>6.3f} "
              f"{ek:>6.3f} {supp:>5} {str(lamblk):>8} {mu/pvR:>7.4f} {str(okR):>5}")

print("\n" + "=" * 78)
print("done")
print("=" * 78)
