\\ thread22_pari_crosscheck.gp
\\ Independent validation of the numpy char-poly engine in
\\ thread22_howe_realizability.py, using PARI's hyperellcharpoly.
\\
\\ For each witness curve y^2 = f(x) over F_p produced by the Python sweep,
\\ we check that
\\     hyperellcharpoly(f) == T^4 - s1 T^3 + s2 T^2 - p*s1*T + p^2
\\ with the (s1, s2) the Python code claims, and that the same quartic equals
\\ P_{E_i}(T) * P_{E_j}(T) for the sextic-twist pair it was matched to.

default(parisize, 256000000);

\\ Each entry: [p, i, j, s1, s2, Vec of f coefficients LOW->HIGH]
\\ (generated by thread22_howe_realizability.py --emit-gp)
read("secp256k1_cm_audit/thread22_witnesses.gp");

print("==================================================================");
print("Thread 22 PARI cross-check of the numpy genus-2 char-poly engine");
print("==================================================================");

ok = 0; bad = 0;
{
for(idx = 1, #W,
    e   = W[idx];
    p   = e[1]; ii = e[2]; jj = e[3]; s1 = e[4]; s2 = e[5];
    cf  = e[6];
    f   = sum(k = 1, #cf, cf[k] * x^(k-1));
    cp  = hyperellcharpoly(Mod(1,p) * f);
    wpol = x^4 - s1*x^3 + s2*x^2 - p*s1*x + p^2;
    \\ smoothness / genus sanity
    sf  = (poldegree(gcd(Mod(1,p)*f, deriv(Mod(1,p)*f))) == 0);
    if(cp == wpol && sf,
       ok++,
       bad++;
       print("MISMATCH p=", p, " pair=(", ii, ",", jj, ")");
       print("   f        = ", f);
       print("   squarefree = ", sf);
       print("   PARI     = ", cp);
       print("   expected = ", wpol));
   )
}
print("");
print("witnesses checked : ", #W);
print("agree with PARI   : ", ok);
print("mismatches        : ", bad);
print("");
{if(bad == 0,
   print("RESULT: numpy engine agrees with PARI hyperellcharpoly on all witnesses."),
   print("RESULT: DISAGREEMENT -- numpy engine is wrong, do not trust the sweep."));}
print("==================================================================");
