//! The relation lattice of a CSIDH-style class group action (Beullens–Kleinjung–Vercauteren 2019,
//! CSI-FiSh): with Cl(Z[sqrt(-p)]) computed through binary quadratic forms of discriminant -4p,
//! the lattice L = {e in Z^n : prod [l_i]^{e_i} = 1}, its LLL-reduced basis, and the reduction of
//! exponent vectors modulo L (Babai's nearest plane), so that any class is evaluated with a short
//! vector. The ideal l_i = (l_i, pi - 1) is the form (l_i, 2, (p+1)/l_i) (p = -1 mod l_i).
//!
//! The class number comes from baby-step giant-step on an interval around the analytic estimate
//! sqrt(|D|) L(1, chi_D)/pi (Euler product); discrete logarithms by baby-step giant-step. When the
//! group is cyclic and generated by [l_1] (checked), L has basis (h, 0, ..., 0) and
//! (-x_i e_1 + e_i) with [l_i] = [l_1]^{x_i}.
use std::collections::HashMap;

/// A positive-definite binary quadratic form (a, b, c), b^2 - 4ac = D < 0.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Form {
    pub a: i128,
    pub b: i128,
    pub c: i128,
}

fn xgcd(a: i128, b: i128) -> (i128, i128, i128) {
    let (mut r0, mut r1, mut s0, mut s1, mut t0, mut t1) = (a, b, 1i128, 0i128, 0i128, 1i128);
    while r1 != 0 {
        let q = r0.div_euclid(r1);
        (r0, r1) = (r1, r0 - q * r1);
        (s0, s1) = (s1, s0 - q * s1);
        (t0, t1) = (t1, t0 - q * t1);
    }
    if r0 < 0 {
        (-r0, -s0, -t0)
    } else {
        (r0, s0, t0)
    }
}

impl Form {
    pub fn disc(&self) -> i128 {
        self.b * self.b - 4 * self.a * self.c
    }
    pub fn identity(d: i128) -> Form {
        // (1, b, c) with b = d mod 2
        let b = d.rem_euclid(2);
        Form { a: 1, b, c: (b * b - d) / 4 }
    }
    pub fn inverse(&self) -> Form {
        Form { a: self.a, b: -self.b, c: self.c }.reduce()
    }
    /// Reduced representative: |b| <= a <= c, b >= 0 if |b| = a or a = c (Cohen 5.4.2).
    pub fn reduce(&self) -> Form {
        let (mut a, mut b, mut c) = (self.a, self.b, self.c);
        let d = self.disc();
        loop {
            // normalise: -a < b <= a
            if !(-a < b && b <= a) {
                let r = (a - b).div_euclid(2 * a);
                b += 2 * a * r;
                c = (b * b - d) / (4 * a);
            }
            if a > c {
                std::mem::swap(&mut a, &mut c);
                b = -b;
                continue;
            }
            if a == c && b < 0 {
                b = -b;
            }
            return Form { a, b, c };
        }
    }
    /// Gauss composition (Cohen, Algorithm 5.4.7), reduced.
    pub fn compose(&self, o: &Form) -> Form {
        let d = self.disc();
        let (f1, f2) = if self.a > o.a { (o, self) } else { (self, o) };
        let (a1, b1, _c1) = (f1.a, f1.b, f1.c);
        let (a2, b2, c2) = (f2.a, f2.b, f2.c);
        let s = (b1 + b2) / 2;
        let n = b2 - s;
        let (y1, dd) = if a2 % a1 == 0 {
            (0, a1)
        } else {
            let (g, u, _v) = xgcd(a2, a1);
            (u, g)
        };
        let (x2, y2, d1) = if s % dd == 0 {
            (0, -1, dd)
        } else {
            let (g, x, y) = xgcd(s, dd);
            (x, -y, g)
        };
        let v1 = a1 / d1;
        let v2 = a2 / d1;
        let r = (y1 * y2 % v1 * n % v1 - x2 * c2 % v1).rem_euclid(v1);
        let b3 = b2 + 2 * v2 * r;
        let a3 = v1 * v2;
        let c3 = (b3 * b3 - d) / (4 * a3);
        Form { a: a3, b: b3, c: c3 }.reduce()
    }
    pub fn pow(&self, mut e: i128) -> Form {
        let d = self.disc();
        let mut base = if e < 0 { self.inverse() } else { *self };
        if e < 0 {
            e = -e;
        }
        let mut r = Form::identity(d);
        while e > 0 {
            if e & 1 == 1 {
                r = r.compose(&base);
            }
            base = base.compose(&base);
            e >>= 1;
        }
        r
    }
}

/// The form of the CSIDH ideal (l, pi - 1) for p = -1 mod l, D = -4p.
pub fn prime_form(p: i128, ell: i128) -> Form {
    Form { a: ell, b: 2, c: (p + 1) / ell }.reduce()
}

/// Analytic estimate sqrt(|D|) L(1, chi_D) / pi with the Euler product over odd primes < bound
/// (and the factor at 2 for D = 0 mod 4: chi(2) = 0).
pub fn class_number_estimate(d: i128, bound: u64) -> f64 {
    let mut l = 1.0f64;
    let mut q = 3u64;
    while q < bound {
        if crate::field::is_prime(q) {
            // Kronecker symbol (d/q) by Euler's criterion
            let dm = d.rem_euclid(q as i128) as u64;
            let chi = if dm == 0 {
                0.0
            } else {
                let mut r = 1u128;
                let (mut b, mut e) = (dm as u128, ((q - 1) / 2) as u128);
                while e > 0 {
                    if e & 1 == 1 {
                        r = r * b % q as u128;
                    }
                    b = b * b % q as u128;
                    e >>= 1;
                }
                if r == 1 { 1.0 } else { -1.0 }
            };
            l /= 1.0 - chi / q as f64;
        }
        q += 2;
    }
    ((-d) as f64).sqrt() * l / std::f64::consts::PI
}

/// m in [lo, hi] with g^m = 1 (baby-step giant-step), the smallest.
pub fn bsgs_exponent(g: &Form, lo: i128, hi: i128) -> Option<i128> {
    let d = g.disc();
    let width = hi - lo + 1;
    let m = ((width as f64).sqrt().ceil() as i128).max(1);
    let mut baby: HashMap<Form, i128> = HashMap::new();
    let mut cur = Form::identity(d);
    for j in 0..m {
        baby.entry(cur).or_insert(j);
        cur = cur.compose(g);
    }
    // g^(lo + i m) * g^j = 1  <=>  g^(lo + i m) = g^-j : giant steps on g^(-lo - i m)
    let gm_inv = g.pow(m).inverse();
    let mut giant = g.pow(lo).inverse();
    let mut i = 0;
    while lo + i * m <= hi {
        if let Some(&j) = baby.get(&giant) {
            return Some(lo + i * m + j);
        }
        giant = giant.compose(&gm_inv);
        i += 1;
    }
    None
}

/// Exact order of g dividing the multiple n.
pub fn order_from_multiple(g: &Form, n: i128) -> i128 {
    let d = g.disc();
    let id = Form::identity(d);
    let mut o = n;
    for (q, _) in crate::field::factor_u64(n as u64) {
        let q = q as i128;
        while o % q == 0 && g.pow(o / q) == id {
            o /= q;
        }
    }
    o
}

/// log_g(h) with g of order n (baby-step giant-step).
pub fn dlog(g: &Form, h: &Form, n: i128) -> Option<i128> {
    let d = g.disc();
    let m = ((n as f64).sqrt().ceil() as i128).max(1);
    let mut baby: HashMap<Form, i128> = HashMap::new();
    let mut cur = Form::identity(d);
    for j in 0..m {
        baby.entry(cur).or_insert(j);
        cur = cur.compose(g);
    }
    let gm_inv = g.pow(m).inverse();
    let mut giant = *h;
    for i in 0..=(n / m + 1) {
        if let Some(&j) = baby.get(&giant) {
            return Some((i * m + j).rem_euclid(n));
        }
        giant = giant.compose(&gm_inv);
    }
    None
}

pub struct RelationLattice {
    pub h: i128,
    /// [l_i] = [l_1]^{logs[i]}
    pub logs: Vec<i128>,
    /// LLL-reduced basis (rows)
    pub basis: Vec<Vec<i64>>,
}

/// Class number h(-4p) and the relation lattice of the classes of the CSIDH primes when Cl is
/// cyclic: a generator g of order h is searched among the [l_i] and random products of them,
/// x_i = log_g [l_i], and L = {e : sum e_i x_i = 0 mod h} is obtained by unimodular row
/// operations on (x_1, ..., x_n) (Euclid on the values), then LLL-reduced.
pub fn relation_lattice(p: i128, primes: &[u64]) -> Option<RelationLattice> {
    let d = -4 * p;
    let n = primes.len();
    let est = class_number_estimate(d, 200_000);
    let (lo, hi) = (((est * 0.9) as i128).max(1), (est * 1.1) as i128 + 2);
    let forms: Vec<Form> = primes.iter().map(|&l| prime_form(p, l as i128)).collect();
    // h: the lcm of element orders, once it has a unique multiple in the window
    let mut lcm_ord = 1i128;
    let mut h = None;
    let mut seed = 0x5eedu64;
    let mut next = || {
        seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        seed >> 33
    };
    let mut cands: Vec<Form> = forms.clone();
    for _ in 0..40 {
        let mut g = Form::identity(d);
        for f in &forms {
            g = g.compose(&f.pow((next() % 7) as i128));
        }
        cands.push(g);
    }
    let mut gen = None;
    for g in &cands {
        let Some(m) = bsgs_exponent(g, lo, hi) else { continue };
        let ord = order_from_multiple(g, m);
        let gcd = |mut a: i128, mut b: i128| {
            while b != 0 {
                (a, b) = (b, a % b);
            }
            a
        };
        lcm_ord = lcm_ord / gcd(lcm_ord, ord) * ord;
        let mults: Vec<i128> = (lo..=hi).filter(|&x| x % lcm_ord == 0).collect();
        if mults.len() == 1 {
            h = Some(mults[0]);
        }
        if let Some(hh) = h {
            if ord == hh {
                gen = Some(*g);
                break;
            }
        }
    }
    let h = h?;
    let g = gen?; // None: no element of order h found (Cl probably not cyclic)
    let mut logs = vec![];
    for f in &forms {
        logs.push(dlog(&g, f, h)?);
    }
    // kernel of e -> sum e_i x_i mod h
    let mut rows: Vec<Vec<i64>> = (0..n).map(|i| (0..n).map(|j| (i == j) as i64).collect()).collect();
    let mut vals: Vec<i128> = logs.iter().map(|x| x.rem_euclid(h)).collect();
    loop {
        let nz: Vec<usize> = (0..n).filter(|&i| vals[i] != 0).collect();
        if nz.len() <= 1 {
            break;
        }
        let k = *nz.iter().min_by_key(|&&i| vals[i]).unwrap();
        for &j in &nz {
            if j != k {
                let q = vals[j] / vals[k];
                vals[j] -= q * vals[k];
                let rk = rows[k].clone();
                for (x, y) in rows[j].iter_mut().zip(&rk) {
                    *x -= q as i64 * y;
                }
            }
        }
    }
    let mut basis: Vec<Vec<i64>> = vec![];
    for i in 0..n {
        if vals[i] == 0 {
            basis.push(rows[i].clone());
        } else {
            let gk = vals[i];
            let mult = (h / gcd_i(gk, h)) as i64;
            basis.push(rows[i].iter().map(|x| x * mult).collect());
        }
    }
    let basis = lll(basis);
    Some(RelationLattice { h, logs, basis })
}

/// Relation lattice for any finite abelian class group of moderate size (no cyclicity needed):
/// grow the subgroup <[l_1], ..., [l_k]> in a hash table of elements with exponent vectors; the
/// smallest m_k with [l_k]^{m_k} in the previous subgroup gives the relation m_k e_k - v. The n
/// relations are a triangular basis of L (determinant prod m_k = #<[l_i]>), then LLL. Memory and
/// time are linear in the group order: for h up to a few million.
pub fn relation_lattice_explicit(p: i128, primes: &[u64], max_order: usize) -> Option<RelationLattice> {
    let d = -4 * p;
    let n = primes.len();
    let forms: Vec<Form> = primes.iter().map(|&l| prime_form(p, l as i128)).collect();
    // elements and their exponent vectors in flat arrays (one allocation each, not one per
    // element: millions of small vectors made the allocator's later consolidation dominate)
    let mut table: HashMap<Form, u32> = HashMap::new();
    let mut elems: Vec<Form> = vec![Form::identity(d)];
    let mut vecs: Vec<i64> = vec![0; n];
    table.insert(Form::identity(d), 0);
    let mut rels: Vec<Vec<i64>> = vec![];
    for (k, g) in forms.iter().enumerate() {
        let mut cur = *g;
        let mut m = 1i64;
        let idx = loop {
            if let Some(&i) = table.get(&cur) {
                break i as usize;
            }
            cur = cur.compose(g);
            m += 1;
            if elems.len() * m as usize > max_order {
                return None;
            }
        };
        let mut r: Vec<i64> = vecs[idx * n..(idx + 1) * n].iter().map(|x| -x).collect();
        r[k] += m;
        rels.push(r);
        if m > 1 {
            let old = elems.len();
            elems.reserve(old * (m as usize - 1));
            vecs.reserve(old * (m as usize - 1) * n);
            let mut gp = Form::identity(d);
            for j in 1..m {
                gp = gp.compose(g);
                for i in 0..old {
                    let nf = elems[i].compose(&gp);
                    let id = elems.len();
                    elems.push(nf);
                    for t in 0..n {
                        let v = vecs[i * n + t] + if t == k { j } else { 0 };
                        vecs.push(v);
                    }
                    table.insert(nf, id as u32);
                }
            }
        }
    }
    let h = elems.len() as i128;
    Some(RelationLattice { h, logs: vec![], basis: lll(rels) })
}

fn gcd_i(mut a: i128, mut b: i128) -> i128 {
    while b != 0 {
        (a, b) = (b, a % b);
    }
    a.abs()
}

/// LLL (delta = 0.99) on integer row vectors, floating-point Gram-Schmidt (small dimension and
/// entries: here entries are below 2^40).
pub fn lll(mut b: Vec<Vec<i64>>) -> Vec<Vec<i64>> {
    let n = b.len();
    let dot = |x: &[f64], y: &[f64]| x.iter().zip(y).map(|(a, c)| a * c).sum::<f64>();
    let gs = |b: &Vec<Vec<i64>>| -> (Vec<Vec<f64>>, Vec<Vec<f64>>) {
        let bf: Vec<Vec<f64>> = b.iter().map(|r| r.iter().map(|&x| x as f64).collect()).collect();
        let mut bs: Vec<Vec<f64>> = vec![];
        let mut mu = vec![vec![0f64; n]; n];
        for i in 0..n {
            let mut v = bf[i].clone();
            for j in 0..i {
                mu[i][j] = dot(&bf[i], &bs[j]) / dot(&bs[j], &bs[j]);
                for (vk, bk) in v.iter_mut().zip(&bs[j]) {
                    *vk -= mu[i][j] * bk;
                }
            }
            bs.push(v);
        }
        (bs, mu)
    };
    let mut k = 1;
    let (mut bs, mut mu) = gs(&b);
    while k < n {
        for j in (0..k).rev() {
            let q = mu[k][j].round();
            if q != 0.0 {
                let qi = q as i64;
                let bj = b[j].clone();
                for (x, y) in b[k].iter_mut().zip(&bj) {
                    *x -= qi * y;
                }
                let (nbs, nmu) = gs(&b);
                bs = nbs;
                mu = nmu;
            }
        }
        if dot(&bs[k], &bs[k]) >= (0.99 - mu[k][k - 1] * mu[k][k - 1]) * dot(&bs[k - 1], &bs[k - 1]) {
            k += 1;
        } else {
            b.swap(k, k - 1);
            let (nbs, nmu) = gs(&b);
            bs = nbs;
            mu = nmu;
            k = (k - 1).max(1);
        }
    }
    b
}

impl RelationLattice {
    /// e - v for the lattice vector v from Babai's nearest plane on the reduced basis.
    pub fn reduce(&self, e: &[i64]) -> Vec<i64> {
        let n = e.len();
        let b = &self.basis;
        let bf: Vec<Vec<f64>> = b.iter().map(|r| r.iter().map(|&x| x as f64).collect()).collect();
        let dot = |x: &[f64], y: &[f64]| x.iter().zip(y).map(|(a, c)| a * c).sum::<f64>();
        let mut bs: Vec<Vec<f64>> = vec![];
        for i in 0..n {
            let mut v = bf[i].clone();
            for bj in bs.iter().take(i) {
                let m = dot(&bf[i], bj) / dot(bj, bj);
                for (vk, bk) in v.iter_mut().zip(bj) {
                    *vk -= m * bk;
                }
            }
            bs.push(v);
        }
        let mut t: Vec<i64> = e.to_vec();
        for i in (0..n).rev() {
            let tf: Vec<f64> = t.iter().map(|&x| x as f64).collect();
            let c = (dot(&tf, &bs[i]) / dot(&bs[i], &bs[i])).round() as i64;
            if c != 0 {
                for k in 0..n {
                    t[k] -= c * b[i][k];
                }
            }
        }
        t
    }
    /// A reduced exponent vector of the class [l_1]^a.
    pub fn vector_of(&self, a: i128) -> Vec<i64> {
        let mut e = vec![0i64; self.basis.len()];
        e[0] = a.rem_euclid(self.h) as i64;
        self.reduce(&e)
    }
}
