//! **Camellia** — 128-bit block cipher (Aoki et al., NTT & Mitsubishi
//! 2000), standardised in **RFC 3713** and **ISO/IEC 18033-3**.
//!
//! Camellia is a Feistel-style cipher offering security comparable to
//! AES.  It is one of two algorithms (alongside AES) listed in the
//! Japanese e-Government CRYPTREC and EU NESSIE recommended-cipher
//! portfolios.
//!
//! ## Variants implemented
//!
//! | Name           | Block | Key  | Rounds | FL layers |
//! |----------------|-------|------|--------|-----------|
//! | [`Camellia128`]| 128 b | 128b | 18     | after r6, r12 |
//! | [`Camellia192`]| 128 b | 192b | 24     | after r6, r12, r18 |
//! | [`Camellia256`]| 128 b | 256b | 24     | after r6, r12, r18 |
//!
//! ## Round function
//!
//! Each Feistel round on a 128-bit state `(L, R)` (two 64-bit halves)
//! with round key `k`:
//!
//! ```text
//!     (L, R) ← (R ⊕ F(L, k), L)
//! ```
//!
//! `F(x, k) = P(S(x ⊕ k))` where `S` applies eight 8-bit S-boxes (the
//! four variants s1, s2, s3, s4 = s1∘rot, s1<<1, s1>>1) and `P` is a
//! GF(2) linear layer mixing the 8 output bytes.
//!
//! ## FL / FL⁻¹ keyed linear layers
//!
//! Inserted between every six rounds.  On a 64-bit input `x` with a
//! 64-bit subkey `(kl, kr)` (high and low 32-bit halves):
//!
//! ```text
//!     FL(x, k):    xR ⊕= ROL_1(xL ∧ kl);  xL ⊕= xR ∨ kr
//!     FL⁻¹(x, k):  xL ⊕= xR ∨ kr;        xR ⊕= ROL_1(xL ∧ kl)
//! ```
//!
//! ## Key schedule
//!
//! The user key is expanded into KL (the user key padded/folded) and
//! KR.  An auxiliary 128-bit value KA is generated by four Feistel
//! rounds applied to `KL ⊕ KR` using the Sigma constants as round
//! keys; for 192/256-bit keys a second auxiliary value KB is generated
//! from `KA ⊕ KR` by two more rounds.  Round keys, FL keys, and
//! whitening keys are produced by 128-bit left-rotations of KL, KR,
//! KA, KB at the rotation amounts specified in RFC 3713 §2.4.
//!
//! ## Byte conventions
//!
//! Camellia is a **big-endian** spec: bytes are loaded MSB-first into
//! 64-bit halves.  The 128-bit block is `bytes[0..8] = L (high)` and
//! `bytes[8..16] = R (low)`.

// ── S-box (RFC 3713 §2.3) ────────────────────────────────────────────

const SBOX1: [u8; 256] = [
    0x70, 0x82, 0x2c, 0xec, 0xb3, 0x27, 0xc0, 0xe5, 0xe4, 0x85, 0x57, 0x35, 0xea, 0x0c, 0xae, 0x41,
    0x23, 0xef, 0x6b, 0x93, 0x45, 0x19, 0xa5, 0x21, 0xed, 0x0e, 0x4f, 0x4e, 0x1d, 0x65, 0x92, 0xbd,
    0x86, 0xb8, 0xaf, 0x8f, 0x7c, 0xeb, 0x1f, 0xce, 0x3e, 0x30, 0xdc, 0x5f, 0x5e, 0xc5, 0x0b, 0x1a,
    0xa6, 0xe1, 0x39, 0xca, 0xd5, 0x47, 0x5d, 0x3d, 0xd9, 0x01, 0x5a, 0xd6, 0x51, 0x56, 0x6c, 0x4d,
    0x8b, 0x0d, 0x9a, 0x66, 0xfb, 0xcc, 0xb0, 0x2d, 0x74, 0x12, 0x2b, 0x20, 0xf0, 0xb1, 0x84, 0x99,
    0xdf, 0x4c, 0xcb, 0xc2, 0x34, 0x7e, 0x76, 0x05, 0x6d, 0xb7, 0xa9, 0x31, 0xd1, 0x17, 0x04, 0xd7,
    0x14, 0x58, 0x3a, 0x61, 0xde, 0x1b, 0x11, 0x1c, 0x32, 0x0f, 0x9c, 0x16, 0x53, 0x18, 0xf2, 0x22,
    0xfe, 0x44, 0xcf, 0xb2, 0xc3, 0xb5, 0x7a, 0x91, 0x24, 0x08, 0xe8, 0xa8, 0x60, 0xfc, 0x69, 0x50,
    0xaa, 0xd0, 0xa0, 0x7d, 0xa1, 0x89, 0x62, 0x97, 0x54, 0x5b, 0x1e, 0x95, 0xe0, 0xff, 0x64, 0xd2,
    0x10, 0xc4, 0x00, 0x48, 0xa3, 0xf7, 0x75, 0xdb, 0x8a, 0x03, 0xe6, 0xda, 0x09, 0x3f, 0xdd, 0x94,
    0x87, 0x5c, 0x83, 0x02, 0xcd, 0x4a, 0x90, 0x33, 0x73, 0x67, 0xf6, 0xf3, 0x9d, 0x7f, 0xbf, 0xe2,
    0x52, 0x9b, 0xd8, 0x26, 0xc8, 0x37, 0xc6, 0x3b, 0x81, 0x96, 0x6f, 0x4b, 0x13, 0xbe, 0x63, 0x2e,
    0xe9, 0x79, 0xa7, 0x8c, 0x9f, 0x6e, 0xbc, 0x8e, 0x29, 0xf5, 0xf9, 0xb6, 0x2f, 0xfd, 0xb4, 0x59,
    0x78, 0x98, 0x06, 0x6a, 0xe7, 0x46, 0x71, 0xba, 0xd4, 0x25, 0xab, 0x42, 0x88, 0xa2, 0x8d, 0xfa,
    0x72, 0x07, 0xb9, 0x55, 0xf8, 0xee, 0xac, 0x0a, 0x36, 0x49, 0x2a, 0x68, 0x3c, 0x38, 0xf1, 0xa4,
    0x40, 0x28, 0xd3, 0x7b, 0xbb, 0xc9, 0x43, 0xc1, 0x15, 0xe3, 0xad, 0xf4, 0x77, 0xc7, 0x80, 0x9e,
];

#[inline]
fn s1(x: u8) -> u8 {
    SBOX1[x as usize]
}
#[inline]
fn s2(x: u8) -> u8 {
    s1(x).rotate_left(1)
}
#[inline]
fn s3(x: u8) -> u8 {
    s1(x).rotate_right(1)
}
#[inline]
fn s4(x: u8) -> u8 {
    s1(x.rotate_left(1))
}

// ── Sigma constants for the key schedule (RFC 3713 §2.4) ─────────────

const SIGMA1: u64 = 0xA09E667F3BCC908B;
const SIGMA2: u64 = 0xB67AE8584CAA73B2;
const SIGMA3: u64 = 0xC6EF372FE94F82BE;
const SIGMA4: u64 = 0x54FF53A5F1D36F1C;
const SIGMA5: u64 = 0x10E527FADE682D1D;
const SIGMA6: u64 = 0xB05688C2B3E6C1FD;

// ── F function ───────────────────────────────────────────────────────

#[inline]
fn f(x: u64, k: u64) -> u64 {
    let t = x ^ k;
    let t0 = s1((t >> 56) as u8);
    let t1 = s2((t >> 48) as u8);
    let t2 = s3((t >> 40) as u8);
    let t3 = s4((t >> 32) as u8);
    let t4 = s2((t >> 24) as u8);
    let t5 = s3((t >> 16) as u8);
    let t6 = s4((t >> 8) as u8);
    let t7 = s1(t as u8);

    // P-function: GF(2) linear layer mixing 8 bytes.
    let y0 = t0 ^ t2 ^ t3 ^ t5 ^ t6 ^ t7;
    let y1 = t0 ^ t1 ^ t3 ^ t4 ^ t6 ^ t7;
    let y2 = t0 ^ t1 ^ t2 ^ t4 ^ t5 ^ t7;
    let y3 = t1 ^ t2 ^ t3 ^ t4 ^ t5 ^ t6;
    let y4 = t0 ^ t1 ^ t5 ^ t6 ^ t7;
    let y5 = t1 ^ t2 ^ t4 ^ t6 ^ t7;
    let y6 = t2 ^ t3 ^ t4 ^ t5 ^ t7;
    let y7 = t0 ^ t3 ^ t4 ^ t5 ^ t6;

    ((y0 as u64) << 56)
        | ((y1 as u64) << 48)
        | ((y2 as u64) << 40)
        | ((y3 as u64) << 32)
        | ((y4 as u64) << 24)
        | ((y5 as u64) << 16)
        | ((y6 as u64) << 8)
        | (y7 as u64)
}

// ── FL / FL⁻¹ ────────────────────────────────────────────────────────

#[inline]
fn fl(x: u64, k: u64) -> u64 {
    let mut xl = (x >> 32) as u32;
    let mut xr = x as u32;
    let kl = (k >> 32) as u32;
    let kr = k as u32;
    xr ^= (xl & kl).rotate_left(1);
    xl ^= xr | kr;
    ((xl as u64) << 32) | (xr as u64)
}

#[inline]
fn fl_inv(y: u64, k: u64) -> u64 {
    let mut yl = (y >> 32) as u32;
    let mut yr = y as u32;
    let kl = (k >> 32) as u32;
    let kr = k as u32;
    yl ^= yr | kr;
    yr ^= (yl & kl).rotate_left(1);
    ((yl as u64) << 32) | (yr as u64)
}

// ── 128-bit left rotation helpers ────────────────────────────────────

#[inline]
fn rotl128(hi: u64, lo: u64, n: u32) -> (u64, u64) {
    let n = n % 128;
    if n == 0 {
        (hi, lo)
    } else if n < 64 {
        let new_hi = (hi << n) | (lo >> (64 - n));
        let new_lo = (lo << n) | (hi >> (64 - n));
        (new_hi, new_lo)
    } else if n == 64 {
        (lo, hi)
    } else {
        let n = n - 64;
        let new_hi = (lo << n) | (hi >> (64 - n));
        let new_lo = (hi << n) | (lo >> (64 - n));
        (new_hi, new_lo)
    }
}

// ── Key schedule helper: build KA (and KB if needed) ─────────────────

/// Produce KA from KL and KR via four Feistel rounds with Sigma1..Sigma4.
/// If `gen_kb` is true, additionally produce KB from `(KA ⊕ KR)` via two
/// more rounds with Sigma5, Sigma6.
fn derive_ka_kb(
    kl_hi: u64,
    kl_lo: u64,
    kr_hi: u64,
    kr_lo: u64,
    gen_kb: bool,
) -> ((u64, u64), Option<(u64, u64)>) {
    let mut d1 = kl_hi ^ kr_hi;
    let mut d2 = kl_lo ^ kr_lo;
    d2 ^= f(d1, SIGMA1);
    d1 ^= f(d2, SIGMA2);
    d1 ^= kl_hi;
    d2 ^= kl_lo;
    d2 ^= f(d1, SIGMA3);
    d1 ^= f(d2, SIGMA4);
    let ka_hi = d1;
    let ka_lo = d2;

    let kb = if gen_kb {
        let mut d1 = ka_hi ^ kr_hi;
        let mut d2 = ka_lo ^ kr_lo;
        d2 ^= f(d1, SIGMA5);
        d1 ^= f(d2, SIGMA6);
        Some((d1, d2))
    } else {
        None
    };

    ((ka_hi, ka_lo), kb)
}

// ── Camellia-128 ─────────────────────────────────────────────────────

/// Camellia with a 128-bit key (18 Feistel rounds, 2 FL layers).
#[derive(Clone, Debug)]
pub struct Camellia128 {
    /// Whitening keys: `kw[0..2]` pre-whitening, `kw[2..4]` post-whitening.
    kw: [u64; 4],
    /// 18 round subkeys.
    k: [u64; 18],
    /// 4 FL/FL⁻¹ subkeys (2 layers × 2 halves).
    ke: [u64; 4],
}

impl Camellia128 {
    pub fn new(key: &[u8; 16]) -> Self {
        let kl_hi = u64::from_be_bytes(key[0..8].try_into().unwrap());
        let kl_lo = u64::from_be_bytes(key[8..16].try_into().unwrap());
        let kr_hi = 0u64;
        let kr_lo = 0u64;

        let ((ka_hi, ka_lo), _) = derive_ka_kb(kl_hi, kl_lo, kr_hi, kr_lo, false);

        let kl = (kl_hi, kl_lo);
        let ka = (ka_hi, ka_lo);

        // Rotation amounts per RFC 3713 §2.4 for the 128-bit-key schedule.
        // Whitening + 18 round keys + 4 FL keys, taken as the upper 64
        // bits of each rotation indicated below.
        let mut kw = [0u64; 4];
        let mut k = [0u64; 18];
        let mut ke = [0u64; 4];

        // Pre-whitening (rounds 0): KL <<< 0
        let (hi, lo) = rotl128(kl.0, kl.1, 0);
        kw[0] = hi;
        kw[1] = lo;

        // k1..k2: KA <<< 0
        let (hi, lo) = rotl128(ka.0, ka.1, 0);
        k[0] = hi;
        k[1] = lo;

        // k3..k4: KL <<< 15
        let (hi, lo) = rotl128(kl.0, kl.1, 15);
        k[2] = hi;
        k[3] = lo;

        // k5..k6: KA <<< 15
        let (hi, lo) = rotl128(ka.0, ka.1, 15);
        k[4] = hi;
        k[5] = lo;

        // ke1..ke2: KA <<< 30
        let (hi, lo) = rotl128(ka.0, ka.1, 30);
        ke[0] = hi;
        ke[1] = lo;

        // k7..k8: KL <<< 45
        let (hi, lo) = rotl128(kl.0, kl.1, 45);
        k[6] = hi;
        k[7] = lo;

        // k9: KA <<< 45 (high half), k10: KL <<< 60 (low half)
        let (hi, _) = rotl128(ka.0, ka.1, 45);
        k[8] = hi;
        let (_, lo) = rotl128(kl.0, kl.1, 60);
        k[9] = lo;

        // k11..k12: KA <<< 60
        let (hi, lo) = rotl128(ka.0, ka.1, 60);
        k[10] = hi;
        k[11] = lo;

        // ke3..ke4: KL <<< 77
        let (hi, lo) = rotl128(kl.0, kl.1, 77);
        ke[2] = hi;
        ke[3] = lo;

        // k13..k14: KL <<< 94
        let (hi, lo) = rotl128(kl.0, kl.1, 94);
        k[12] = hi;
        k[13] = lo;

        // k15..k16: KA <<< 94
        let (hi, lo) = rotl128(ka.0, ka.1, 94);
        k[14] = hi;
        k[15] = lo;

        // k17..k18: KL <<< 111
        let (hi, lo) = rotl128(kl.0, kl.1, 111);
        k[16] = hi;
        k[17] = lo;

        // Post-whitening: KA <<< 111
        let (hi, lo) = rotl128(ka.0, ka.1, 111);
        kw[2] = hi;
        kw[3] = lo;

        Self { kw, k, ke }
    }

    pub fn encrypt_block(&self, block: &mut [u8; 16]) {
        let mut l = u64::from_be_bytes(block[0..8].try_into().unwrap());
        let mut r = u64::from_be_bytes(block[8..16].try_into().unwrap());

        l ^= self.kw[0];
        r ^= self.kw[1];

        feistel6(&mut l, &mut r, &self.k[0..6]);
        l = fl(l, self.ke[0]);
        r = fl_inv(r, self.ke[1]);
        feistel6(&mut l, &mut r, &self.k[6..12]);
        l = fl(l, self.ke[2]);
        r = fl_inv(r, self.ke[3]);
        feistel6(&mut l, &mut r, &self.k[12..18]);

        // Final swap: output is (R, L) ⊕ post-whitening.
        let out_hi = r ^ self.kw[2];
        let out_lo = l ^ self.kw[3];

        block[0..8].copy_from_slice(&out_hi.to_be_bytes());
        block[8..16].copy_from_slice(&out_lo.to_be_bytes());
    }

    pub fn decrypt_block(&self, block: &mut [u8; 16]) {
        let mut l = u64::from_be_bytes(block[0..8].try_into().unwrap());
        let mut r = u64::from_be_bytes(block[8..16].try_into().unwrap());

        // Decryption uses the same structure with whitening and FL keys
        // swapped (kw3↔kw1, kw4↔kw2, ke4↔ke1, ke3↔ke2) and round keys
        // in reverse order.
        l ^= self.kw[2];
        r ^= self.kw[3];

        feistel6_rev(&mut l, &mut r, &self.k[12..18]);
        l = fl(l, self.ke[3]);
        r = fl_inv(r, self.ke[2]);
        feistel6_rev(&mut l, &mut r, &self.k[6..12]);
        l = fl(l, self.ke[1]);
        r = fl_inv(r, self.ke[0]);
        feistel6_rev(&mut l, &mut r, &self.k[0..6]);

        let out_hi = r ^ self.kw[0];
        let out_lo = l ^ self.kw[1];

        block[0..8].copy_from_slice(&out_hi.to_be_bytes());
        block[8..16].copy_from_slice(&out_lo.to_be_bytes());
    }
}

// ── Camellia-192 / Camellia-256 (shared 24-round structure) ──────────

/// Build the 24-round subkey set for a 192/256-bit key from KL, KR, KA, KB.
fn schedule_24(
    kl: (u64, u64),
    kr: (u64, u64),
    ka: (u64, u64),
    kb: (u64, u64),
) -> ([u64; 4], [u64; 24], [u64; 6]) {
    let mut kw = [0u64; 4];
    let mut k = [0u64; 24];
    let mut ke = [0u64; 6];

    // Pre-whitening: KL <<< 0
    let (hi, lo) = rotl128(kl.0, kl.1, 0);
    kw[0] = hi;
    kw[1] = lo;

    // k1..k2: KB <<< 0
    let (hi, lo) = rotl128(kb.0, kb.1, 0);
    k[0] = hi;
    k[1] = lo;

    // k3..k4: KR <<< 15
    let (hi, lo) = rotl128(kr.0, kr.1, 15);
    k[2] = hi;
    k[3] = lo;

    // k5..k6: KA <<< 15
    let (hi, lo) = rotl128(ka.0, ka.1, 15);
    k[4] = hi;
    k[5] = lo;

    // ke1..ke2: KR <<< 30
    let (hi, lo) = rotl128(kr.0, kr.1, 30);
    ke[0] = hi;
    ke[1] = lo;

    // k7..k8: KB <<< 30
    let (hi, lo) = rotl128(kb.0, kb.1, 30);
    k[6] = hi;
    k[7] = lo;

    // k9..k10: KL <<< 45
    let (hi, lo) = rotl128(kl.0, kl.1, 45);
    k[8] = hi;
    k[9] = lo;

    // k11..k12: KA <<< 45
    let (hi, lo) = rotl128(ka.0, ka.1, 45);
    k[10] = hi;
    k[11] = lo;

    // ke3..ke4: KL <<< 60
    let (hi, lo) = rotl128(kl.0, kl.1, 60);
    ke[2] = hi;
    ke[3] = lo;

    // k13..k14: KR <<< 60
    let (hi, lo) = rotl128(kr.0, kr.1, 60);
    k[12] = hi;
    k[13] = lo;

    // k15..k16: KB <<< 60
    let (hi, lo) = rotl128(kb.0, kb.1, 60);
    k[14] = hi;
    k[15] = lo;

    // k17..k18: KL <<< 77
    let (hi, lo) = rotl128(kl.0, kl.1, 77);
    k[16] = hi;
    k[17] = lo;

    // ke5..ke6: KA <<< 77
    let (hi, lo) = rotl128(ka.0, ka.1, 77);
    ke[4] = hi;
    ke[5] = lo;

    // k19..k20: KR <<< 94
    let (hi, lo) = rotl128(kr.0, kr.1, 94);
    k[18] = hi;
    k[19] = lo;

    // k21..k22: KA <<< 94
    let (hi, lo) = rotl128(ka.0, ka.1, 94);
    k[20] = hi;
    k[21] = lo;

    // k23..k24: KL <<< 111
    let (hi, lo) = rotl128(kl.0, kl.1, 111);
    k[22] = hi;
    k[23] = lo;

    // Post-whitening: KB <<< 111
    let (hi, lo) = rotl128(kb.0, kb.1, 111);
    kw[2] = hi;
    kw[3] = lo;

    (kw, k, ke)
}

#[inline]
fn feistel6(l: &mut u64, r: &mut u64, rk: &[u64]) {
    // 6 Feistel rounds, each: (L, R) ← (R ⊕ F(L, k), L).
    for &k in rk {
        let nl = *r ^ f(*l, k);
        let nr = *l;
        *l = nl;
        *r = nr;
    }
}

#[inline]
fn feistel6_rev(l: &mut u64, r: &mut u64, rk: &[u64]) {
    // Same Feistel structure with round keys consumed in reverse.
    for &k in rk.iter().rev() {
        let nl = *r ^ f(*l, k);
        let nr = *l;
        *l = nl;
        *r = nr;
    }
}

/// Encrypt one 128-bit block with the 24-round schedule.
fn encrypt_24(block: &mut [u8; 16], kw: &[u64; 4], k: &[u64; 24], ke: &[u64; 6]) {
    let mut l = u64::from_be_bytes(block[0..8].try_into().unwrap());
    let mut r = u64::from_be_bytes(block[8..16].try_into().unwrap());

    l ^= kw[0];
    r ^= kw[1];

    feistel6(&mut l, &mut r, &k[0..6]);
    l = fl(l, ke[0]);
    r = fl_inv(r, ke[1]);
    feistel6(&mut l, &mut r, &k[6..12]);
    l = fl(l, ke[2]);
    r = fl_inv(r, ke[3]);
    feistel6(&mut l, &mut r, &k[12..18]);
    l = fl(l, ke[4]);
    r = fl_inv(r, ke[5]);
    feistel6(&mut l, &mut r, &k[18..24]);

    let out_hi = r ^ kw[2];
    let out_lo = l ^ kw[3];

    block[0..8].copy_from_slice(&out_hi.to_be_bytes());
    block[8..16].copy_from_slice(&out_lo.to_be_bytes());
}

/// Decrypt one 128-bit block with the 24-round schedule.
fn decrypt_24(block: &mut [u8; 16], kw: &[u64; 4], k: &[u64; 24], ke: &[u64; 6]) {
    let mut l = u64::from_be_bytes(block[0..8].try_into().unwrap());
    let mut r = u64::from_be_bytes(block[8..16].try_into().unwrap());

    l ^= kw[2];
    r ^= kw[3];

    feistel6_rev(&mut l, &mut r, &k[18..24]);
    l = fl(l, ke[5]);
    r = fl_inv(r, ke[4]);
    feistel6_rev(&mut l, &mut r, &k[12..18]);
    l = fl(l, ke[3]);
    r = fl_inv(r, ke[2]);
    feistel6_rev(&mut l, &mut r, &k[6..12]);
    l = fl(l, ke[1]);
    r = fl_inv(r, ke[0]);
    feistel6_rev(&mut l, &mut r, &k[0..6]);

    let out_hi = r ^ kw[0];
    let out_lo = l ^ kw[1];

    block[0..8].copy_from_slice(&out_hi.to_be_bytes());
    block[8..16].copy_from_slice(&out_lo.to_be_bytes());
}

/// Camellia with a 192-bit key (24 Feistel rounds, 3 FL layers).
#[derive(Clone, Debug)]
pub struct Camellia192 {
    kw: [u64; 4],
    k: [u64; 24],
    ke: [u64; 6],
}

impl Camellia192 {
    pub fn new(key: &[u8; 24]) -> Self {
        let kl_hi = u64::from_be_bytes(key[0..8].try_into().unwrap());
        let kl_lo = u64::from_be_bytes(key[8..16].try_into().unwrap());
        // Per RFC 3713 §2.2: for 192-bit keys, KR = K_R || ~K_R where
        // K_R is the trailing 64 bits of the user key.
        let kr_hi = u64::from_be_bytes(key[16..24].try_into().unwrap());
        let kr_lo = !kr_hi;

        let ((ka_hi, ka_lo), kb) = derive_ka_kb(kl_hi, kl_lo, kr_hi, kr_lo, true);
        let (kb_hi, kb_lo) = kb.unwrap();

        let (kw, k, ke) = schedule_24(
            (kl_hi, kl_lo),
            (kr_hi, kr_lo),
            (ka_hi, ka_lo),
            (kb_hi, kb_lo),
        );
        Self { kw, k, ke }
    }

    pub fn encrypt_block(&self, block: &mut [u8; 16]) {
        encrypt_24(block, &self.kw, &self.k, &self.ke);
    }

    pub fn decrypt_block(&self, block: &mut [u8; 16]) {
        decrypt_24(block, &self.kw, &self.k, &self.ke);
    }
}

/// Camellia with a 256-bit key (24 Feistel rounds, 3 FL layers).
#[derive(Clone, Debug)]
pub struct Camellia256 {
    kw: [u64; 4],
    k: [u64; 24],
    ke: [u64; 6],
}

impl Camellia256 {
    pub fn new(key: &[u8; 32]) -> Self {
        let kl_hi = u64::from_be_bytes(key[0..8].try_into().unwrap());
        let kl_lo = u64::from_be_bytes(key[8..16].try_into().unwrap());
        let kr_hi = u64::from_be_bytes(key[16..24].try_into().unwrap());
        let kr_lo = u64::from_be_bytes(key[24..32].try_into().unwrap());

        let ((ka_hi, ka_lo), kb) = derive_ka_kb(kl_hi, kl_lo, kr_hi, kr_lo, true);
        let (kb_hi, kb_lo) = kb.unwrap();

        let (kw, k, ke) = schedule_24(
            (kl_hi, kl_lo),
            (kr_hi, kr_lo),
            (ka_hi, ka_lo),
            (kb_hi, kb_lo),
        );
        Self { kw, k, ke }
    }

    pub fn encrypt_block(&self, block: &mut [u8; 16]) {
        encrypt_24(block, &self.kw, &self.k, &self.ke);
    }

    pub fn decrypt_block(&self, block: &mut [u8; 16]) {
        decrypt_24(block, &self.kw, &self.k, &self.ke);
    }
}

// ── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn hex(s: &str) -> Vec<u8> {
        (0..s.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&s[i..i + 2], 16).unwrap())
            .collect()
    }

    /// **RFC 3713 Appendix A — Camellia-128**:
    /// Key `0123456789abcdeffedcba9876543210`,
    /// Plain `0123456789abcdeffedcba9876543210`,
    /// Cipher `67673138549669730857065648eabe43`.
    #[test]
    fn camellia128_rfc_vector() {
        let key: [u8; 16] = hex("0123456789abcdeffedcba9876543210")
            .try_into()
            .unwrap();
        let mut block: [u8; 16] = hex("0123456789abcdeffedcba9876543210")
            .try_into()
            .unwrap();
        let expected: [u8; 16] = hex("67673138549669730857065648eabe43")
            .try_into()
            .unwrap();

        let c = Camellia128::new(&key);
        c.encrypt_block(&mut block);
        assert_eq!(block, expected);

        c.decrypt_block(&mut block);
        let pt: [u8; 16] = hex("0123456789abcdeffedcba9876543210")
            .try_into()
            .unwrap();
        assert_eq!(block, pt);
    }

    /// **RFC 3713 Appendix A — Camellia-192**:
    /// Key `0123456789abcdeffedcba98765432100011223344556677`,
    /// Plain `0123456789abcdeffedcba9876543210`,
    /// Cipher `b4993401b3e996f84ee5cee7d79b09b9`.
    #[test]
    fn camellia192_rfc_vector() {
        let key: [u8; 24] = hex("0123456789abcdeffedcba98765432100011223344556677")
            .try_into()
            .unwrap();
        let mut block: [u8; 16] = hex("0123456789abcdeffedcba9876543210")
            .try_into()
            .unwrap();
        let expected: [u8; 16] = hex("b4993401b3e996f84ee5cee7d79b09b9")
            .try_into()
            .unwrap();

        let c = Camellia192::new(&key);
        c.encrypt_block(&mut block);
        assert_eq!(block, expected);

        c.decrypt_block(&mut block);
        let pt: [u8; 16] = hex("0123456789abcdeffedcba9876543210")
            .try_into()
            .unwrap();
        assert_eq!(block, pt);
    }

    /// **RFC 3713 Appendix A — Camellia-256**:
    /// Key `0123456789abcdeffedcba987654321000112233445566778899aabbccddeeff`,
    /// Plain `0123456789abcdeffedcba9876543210`,
    /// Cipher `9acc237dff16d76c20ef7c919e3a7509`.
    #[test]
    fn camellia256_rfc_vector() {
        let key: [u8; 32] =
            hex("0123456789abcdeffedcba987654321000112233445566778899aabbccddeeff")
                .try_into()
                .unwrap();
        let mut block: [u8; 16] = hex("0123456789abcdeffedcba9876543210")
            .try_into()
            .unwrap();
        let expected: [u8; 16] = hex("9acc237dff16d76c20ef7c919e3a7509")
            .try_into()
            .unwrap();

        let c = Camellia256::new(&key);
        c.encrypt_block(&mut block);
        assert_eq!(block, expected);

        c.decrypt_block(&mut block);
        let pt: [u8; 16] = hex("0123456789abcdeffedcba9876543210")
            .try_into()
            .unwrap();
        assert_eq!(block, pt);
    }

    /// Random round-trips across all three variants.
    #[test]
    fn camellia_round_trip() {
        let k16 = [0x42u8; 16];
        let k24 = [0x55u8; 24];
        let k32 = [0x77u8; 32];

        let c1 = Camellia128::new(&k16);
        let mut b1 = [0xAAu8; 16];
        let orig1 = b1;
        c1.encrypt_block(&mut b1);
        assert_ne!(b1, orig1);
        c1.decrypt_block(&mut b1);
        assert_eq!(b1, orig1);

        let c2 = Camellia192::new(&k24);
        let mut b2 = [0xBBu8; 16];
        let orig2 = b2;
        c2.encrypt_block(&mut b2);
        assert_ne!(b2, orig2);
        c2.decrypt_block(&mut b2);
        assert_eq!(b2, orig2);

        let c3 = Camellia256::new(&k32);
        let mut b3 = [0xCCu8; 16];
        let orig3 = b3;
        c3.encrypt_block(&mut b3);
        assert_ne!(b3, orig3);
        c3.decrypt_block(&mut b3);
        assert_eq!(b3, orig3);
    }
}
