#!/usr/bin/env python3
"""Tabulate results/*.json into RESULTS.md.

One row per (instance, arm): the factor base (points, columns), the
hit rate and trials per relation, where the cost lands (decomposition
share of the total), S = GAE / sqrt(r) as mean and range over the
repeats, the matched rho reference and the ratio, and whether every
repeat recovered the planted logarithm.  A second table gives the
head-to-head S_sym / S_x on each instance at each m, which is what the
contract in README.md is judged on.
"""
import glob
import json
import os
import statistics as st
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")

ARMS = ["sym", "sym4", "x", "mitm-x", "mitm-u", "sym-m3", "x-m3"]
INSTANCES = ["k1_17", "k0_23", "k1_23", "k0_31"]
NAMES = {
    "k1_17": "K_1 / GF(2^17)",
    "k0_23": "K_0 / GF(2^23)",
    "k1_23": "K_1 / GF(2^23)",
    "k0_31": "K_0 / GF(2^31)",
}


def load():
    out = {}
    for path in sorted(glob.glob(os.path.join(RES, "*.json"))):
        if path.endswith(".fb.json"):
            continue
        key = os.path.basename(path)[: -len(".json")]
        inst, arm = key.split("__", 1)
        with open(path) as fh:
            out[(inst, arm)] = json.load(fh)
    return out


def fb_hash(inst, arm):
    path = os.path.join(RES, f"{inst}__{arm}.fb.json")
    if not os.path.exists(path):
        return "—"
    with open(path) as fh:
        doc = json.load(fh)
    fbs = doc.get("factor_bases") or []
    return fbs[0]["point_list_blake3"][:12] if fbs else "—"


def fmt_range(xs, nd=1):
    if not xs:
        return "—"
    if len(xs) == 1:
        return f"{xs[0]:.{nd}f}"
    return f"{st.mean(xs):.{nd}f} ({min(xs):.{nd}f}–{max(xs):.{nd}f})"


def row(inst, arm, rep):
    rows = rep["rows"]
    if not rows:
        return None
    s = [r["s"] for r in rows]
    rho = rep.get("rho_reference") or {}
    rho_s = rho.get("mean_s") if rho.get("all_verified") else None
    hit = [r["decomposition"]["hit_rate"] for r in rows]
    trials = [r["decomposition"]["targets_tried"] for r in rows]
    rels = [r["decomposition"]["relations_found"] for r in rows]
    dec_share = [
        r["decomposition"]["cost"]["gae"] / r["total_gae"] if r["total_gae"] else 0.0
        for r in rows
    ]
    fb = rows[0]["factor_base"]
    solver = rows[0]["decomposition"].get("solver") or {}
    unit = solver.get("op_unit") or ("lookups" if arm.startswith("mitm") else "—")
    priced_by = solver.get("priced_by") or "count"
    # The counted lower bound: the solver phase repriced by its counted
    # word XORs alone at the pinned ns_per_word_xor, everything else as
    # priced.  The runner refuses to price by that count (the unit is
    # not exactly "word XORs": the count covers the eliminations, not
    # the whole F4), so this column is a floor on the solve, not its S.
    calib = rep.get("calibration") or {}
    s_xor = []
    for r in rows:
        sol = r["decomposition"].get("solver")
        if sol and calib.get("ns_per_word_xor") and calib.get("ns_per_add"):
            counted = sol["ops"] * calib["ns_per_word_xor"] / calib["ns_per_add"]
            s_xor.append((r["total_gae"] - sol["gae"] + counted) / (r["r"] ** 0.5))
        else:
            s_xor.append(r["s"])
    return {
        "instance": rep["instance"],
        "arm": arm,
        "pts": fb["signed_points"],
        "cols": fb["columns"],
        "fb": fb_hash(inst, arm),
        "hit": fmt_range(hit, 3),
        "trials_per_rel": fmt_range([t / max(k, 1) for t, k in zip(trials, rels)], 2),
        "dec_share": f"{100 * st.mean(dec_share):.0f}%",
        "unit": unit.split(" (")[0] + ("" if priced_by == "count" else f" ({priced_by})"),
        "S": fmt_range(s),
        "S_xor": fmt_range(s_xor),
        "S_xor_mean": st.mean(s_xor),
        "S_mean": st.mean(s),
        "rho": f"{rho_s:.3f}" if rho_s else "—",
        "vs_rho": f"{st.mean(s) / rho_s:.0f}×" if rho_s else "—",
        "verified": "yes" if all(r["verified"] for r in rows) else "NO",
        "repeats": len(rows),
        "wall": f"{sum(r['wall_seconds'] for r in rows):.1f}",
    }


def main():
    data = load()
    lines = [
        "# Results: torsion-symmetrised index calculus on Koblitz curves, end to end",
        "",
        "Generated by `report.py` from `results/*.json`; the contract is in `README.md`.",
        "`S = GAE / √r` over the whole pipeline (base, walk, every decomposition attempt,",
        "matrix, verification); mean over the repeats with the range in brackets.",
        "`fb` is the first 12 hex digits of the BLAKE3 hash of the frozen point list in",
        "`results/<instance>__<arm>.fb.json`.  `dec` is the decomposition phase's share of",
        "the total.  `vs rho` is `S / S_rho` on the matched reference (same seeds, same targets).",
        "",
        "`S_xor` reprices the solver phase by its counted word XORs alone at the pinned",
        "`ns_per_word_xor` (a floor on the solve; the runner prices the algebraic arms by",
        "measured wall because the count covers only the eliminations, and the `unit` column",
        "says so).  Runs are serial, one per core, so the measured price is not shared.",
        "",
        "| instance | arm | pts | cols | fb | hit rate | trials/rel | dec | unit | S | S_xor | S_rho | vs rho | verified | wall s |",
        "|:--|:--|--:|--:|:--|:--|:--|--:|:--|:--|:--|--:|--:|:--|--:|",
    ]
    means = {}
    xor_means = {}
    for inst in INSTANCES:
        for arm in ARMS:
            rep = data.get((inst, arm))
            if rep is None:
                log = os.path.join(RES, f"{inst}__{arm}.log")
                if os.path.exists(log):
                    with open(log) as fh:
                        tail = fh.read().strip().splitlines()
                    why = tail[-1] if tail else "no output"
                    lines.append(
                        f"| {NAMES.get(inst, inst)} | {arm} | — | — | — | — | — | — | — | not finished | — | — | — | — | {why} |"
                    )
                continue
            r = row(inst, arm, rep)
            if r is None:
                continue
            means[(inst, arm)] = r["S_mean"]
            xor_means[(inst, arm)] = r["S_xor_mean"]
            lines.append(
                "| {instance} | {arm} | {pts} | {cols} | `{fb}` | {hit} | {trials_per_rel} | {dec_share} | {unit} | {S} | {S_xor} | {rho} | {vs_rho} | {verified} ({repeats}) | {wall} |".format(
                    **r
                )
            )
    lines += [
        "",
        "## Head to head",
        "",
        "`S_sym / S_x` at the same `m`, `V` and seeds; `S_mitm-u / S_mitm-x` is the same",
        "comparison of the two bases under the combinatorial oracle, which isolates what",
        "the base's `+T` closure does to the hit rate from what the rewriting does to the solve.",
        "",
        "| instance | m | S_sym / S_x | S_xor: sym / x | S_sym4 / S_x | S_mitm-u / S_mitm-x |",
        "|:--|--:|--:|--:|--:|--:|",
    ]
    for inst in INSTANCES:
        for m, (a, b, c) in ((2, ("sym", "x", "sym4")), (3, ("sym-m3", "x-m3", None))):
            if (inst, a) not in means and (inst, b) not in means:
                continue

            def ratio(p, q, table=means):
                if p in table and q in table and table[q]:
                    return f"{table[p] / table[q]:.2f}"
                return "—"

            mm = ratio((inst, "mitm-u"), (inst, "mitm-x")) if m == 2 else "—"
            lines.append(
                f"| {NAMES.get(inst, inst)} | {m} | {ratio((inst, a), (inst, b))} | {ratio((inst, a), (inst, b), xor_means)} | {ratio((inst, c), (inst, b)) if c else '—'} | {mm} |"
            )
    host = os.path.join(RES, "host.txt")
    if os.path.exists(host):
        with open(host) as fh:
            lines += ["", "## Host", "", "```", fh.read().strip(), "```"]
    text = "\n".join(lines) + "\n"
    with open(os.path.join(HERE, "RESULTS.md"), "w") as fh:
        fh.write(text)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
