#!/usr/bin/env python3
"""Reference generator and oracle for the GPU Gray-code FES kernel.

FES (fast exhaustive search, Bouillaguet et al.; libfes-lite) enumerates every
assignment of a quadratic Boolean system in Gray-code order, so consecutive
points differ in one variable and each equation's value is updated in O(1)
amortized from a table of first/second derivatives.  It is the single most
parallelizable stage of a binary index-calculus decomposition: the 2^n cube
splits into independent sub-cubes, one per GPU thread.

This script

  * `system`  — emits a C header (`system.h`) describing one random quadratic
    system in `n` variables and `m` equations (m <= 64, packed one bit per
    equation) with a *planted* solution, plus that solution; and

  * `check`   — independently brute-forces the same system's solution set, for
    the host test to compare the kernel against.

The packed representation matches `fes.cuh`:
  value(x) = CONST ^ ⊕_{i: x_i=1} LIN[i] ⊕_{i>=j: x_i=x_j=1} QUAD[i][j]
where each of CONST, LIN[i], QUAD[i][j] is a u64 whose bit e is the coefficient
in equation e.  A point x is a solution iff value(x) == 0.
"""

import argparse
import random


def gen_system(n, m, seed):
    rng = random.Random(seed)
    mask = (1 << m) - 1
    # Planted solution: a random point that we force to be a zero.
    sol = rng.getrandbits(n)
    lin = [rng.getrandbits(m) & mask for _ in range(n)]
    quad = [[0] * n for _ in range(n)]
    for i in range(n):
        for j in range(i + 1):
            quad[i][j] = rng.getrandbits(m) & mask
    # Choose CONST so that value(sol) == 0.
    const = 0
    for i in range(n):
        if (sol >> i) & 1:
            const ^= lin[i]
            for j in range(i + 1):
                if (sol >> j) & 1:
                    const ^= quad[i][j]
    return const, lin, quad, sol


def value(x, const, lin, quad, n):
    v = const
    for i in range(n):
        if (x >> i) & 1:
            v ^= lin[i]
            for j in range(i + 1):
                if (x >> j) & 1:
                    v ^= quad[i][j]
    return v


def brute_solutions(const, lin, quad, n):
    return [x for x in range(1 << n) if value(x, const, lin, quad, n) == 0]


def emit_header(n, m, seed):
    const, lin, quad, sol = gen_system(n, m, seed)
    # Flatten QUAD lower triangle row-major (i from 0..n, j from 0..=i).
    flat = []
    for i in range(n):
        for j in range(i + 1):
            flat.append(quad[i][j])
    print("// Generated by fref.py -- do not edit.")
    print("#pragma once")
    print("#include <stdint.h>")
    print(f"#define FES_N {n}")
    print(f"#define FES_M {m}")
    print(f"static const uint64_t FES_CONST = {const}ULL;")
    print(f"static const uint64_t FES_LIN[{n}] = {{")
    print("  " + ", ".join(f"{v}ULL" for v in lin))
    print("};")
    print(f"static const uint64_t FES_QUAD_TRI[{len(flat)}] = {{")
    print("  " + ", ".join(f"{v}ULL" for v in flat))
    print("};")
    print(f"static const uint64_t FES_PLANTED = {sol}ULL;")
    # The full brute-forced solution set, sorted, for the host test.
    sols = brute_solutions(const, lin, quad, n)
    print(f"static const int FES_NUM_SOLUTIONS = {len(sols)};")
    print(f"static const uint64_t FES_SOLUTIONS[{max(1, len(sols))}] = {{")
    print("  " + ", ".join(f"{s}ULL" for s in sols) if sols else "  0ULL")
    print("};")


def main():
    ap = argparse.ArgumentParser()
    sub = ap.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("system")
    g.add_argument("--n", type=int, default=18)
    g.add_argument("--m", type=int, default=20)
    g.add_argument("--seed", type=int, default=1)
    c = sub.add_parser("check")
    c.add_argument("--n", type=int, default=18)
    c.add_argument("--m", type=int, default=20)
    c.add_argument("--seed", type=int, default=1)
    args = ap.parse_args()
    if args.cmd == "system":
        emit_header(args.n, args.m, args.seed)
    else:
        const, lin, quad, _ = gen_system(args.n, args.m, args.seed)
        sols = brute_solutions(const, lin, quad, args.n)
        print(f"solutions: {len(sols)}")
        for s in sols:
            print(s)


if __name__ == "__main__":
    main()
