//! **OFB — Output Feedback**.
//!
//! Stream-cipher mode where the keystream is generated by repeatedly
//! re-encrypting the IV:
//!
//! ```text
//!     O_0 = IV
//!     O_i = E(O_{i-1})    (the OFB keystream blocks)
//!     C_i = P_i ⊕ O_i
//! ```
//!
//! Standard: NIST SP 800-38A §6.4.
//!
//! ## Properties
//!
//! - **Symmetric**: encrypt and decrypt are the same operation
//!   (XOR with the keystream).
//! - **No error propagation**: a corrupted ciphertext bit corrupts
//!   exactly the corresponding plaintext bit and nothing else.
//! - **Pre-computable keystream**: independent of plaintext.
//! - **Nonce reuse is catastrophic** (XOR of two ciphertexts under the
//!   same IV leaks the XOR of plaintexts).

use super::cipher::BlockCipher;

/// **OFB encrypt / decrypt** — same operation, since OFB is an XOR
/// keystream.  Arbitrary-length input.
pub fn ofb_apply<C: BlockCipher<N>, const N: usize>(
    cipher: &C,
    iv: &[u8; N],
    data: &[u8],
) -> Vec<u8> {
    let mut out = Vec::with_capacity(data.len());
    let mut o = *iv;
    let mut idx = 0;
    while idx < data.len() {
        cipher.encrypt_block(&mut o);
        let chunk_len = N.min(data.len() - idx);
        for i in 0..chunk_len {
            out.push(data[idx + i] ^ o[i]);
        }
        idx += chunk_len;
    }
    out
}

// ── Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::symmetric::aes::AesKey;

    /// Encrypt then decrypt returns the original.
    #[test]
    fn ofb_round_trip() {
        let key = AesKey::new(&[0u8; 16]).unwrap();
        let iv = [42u8; 16];
        let pt = b"Some plaintext of arbitrary length, even more.";
        let ct = ofb_apply::<_, 16>(&key, &iv, pt);
        assert_eq!(ct.len(), pt.len());
        let recovered = ofb_apply::<_, 16>(&key, &iv, &ct);
        assert_eq!(recovered, pt);
    }

    /// **NIST SP 800-38A Appendix F.4 AES-128 OFB test vector**.
    /// Key:  2b7e151628aed2a6abf7158809cf4f3c
    /// IV:   000102030405060708090a0b0c0d0e0f
    /// PT1:  6bc1bee2 2e409f96 e93d7e11 7393172a
    /// CT1:  3b3fd92e b72dad20 333449f8 e83cfb4a
    #[test]
    fn ofb_aes128_nist_vector() {
        let key_bytes = [
            0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6, 0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf,
            0x4f, 0x3c,
        ];
        let iv = [
            0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d,
            0x0e, 0x0f,
        ];
        let pt: [u8; 16] = [
            0x6b, 0xc1, 0xbe, 0xe2, 0x2e, 0x40, 0x9f, 0x96, 0xe9, 0x3d, 0x7e, 0x11, 0x73, 0x93,
            0x17, 0x2a,
        ];
        let expected_ct: [u8; 16] = [
            0x3b, 0x3f, 0xd9, 0x2e, 0xb7, 0x2d, 0xad, 0x20, 0x33, 0x34, 0x49, 0xf8, 0xe8, 0x3c,
            0xfb, 0x4a,
        ];
        let key = AesKey::new(&key_bytes).unwrap();
        let ct = ofb_apply::<_, 16>(&key, &iv, &pt);
        assert_eq!(&ct[..], &expected_ct[..]);
    }

    /// OFB has no error propagation: bit flips localise.
    #[test]
    fn ofb_no_error_propagation() {
        let key = AesKey::new(&[0u8; 16]).unwrap();
        let iv = [0u8; 16];
        let pt = vec![0u8; 64];
        let mut ct = ofb_apply::<_, 16>(&key, &iv, &pt);
        ct[10] ^= 0xFF;
        let recovered = ofb_apply::<_, 16>(&key, &iv, &ct);
        // Only byte 10 differs.
        for (i, (&p, &r)) in pt.iter().zip(&recovered).enumerate() {
            if i == 10 {
                assert_ne!(p, r);
            } else {
                assert_eq!(p, r);
            }
        }
    }
}
