#!/usr/bin/env python3
"""E1 instrument: Frobenius eigenvalue orders mod ell for registered curves.

See PROTOCOL.md, section E1.  Pure Python, deterministic, no dependencies.

For every prime ell <= L_MAX and every registered curve (p, n), this
classifies ell (divides / atkin / elkies), computes the two Frobenius
eigenvalues lambda, mu in F_ell and their multiplicative orders r(lambda),
r(mu), and records r_min = min of the two.  r_min is the least k with
ell | #E(F_{p^k}); the kernel of the cheaper of the two rational
ell-isogenies is generated by a point over F_{p^{r_min}}.

Usage:
    python3 -I eigenvalue_orders.py --selftest
    python3 -I eigenvalue_orders.py --curve p256 --lmax 1048576 --out results/
"""

import argparse
import json
import math
import os
import random
import sys
import time

# Registered curves: (p, n) as in the walker's StartCurve.
CURVES = {
    "p192": (
        6277101735386680763835789423207666416083908700390324961279,
        6277101735386680763835789423176059013767194773182842284081,
    ),
    "p224": (
        26959946667150639794667015087019630673557916260026308143510066298881,
        26959946667150639794667015087019625940457807714424391721682722368061,
    ),
    "p256": (
        115792089210356248762697446949407573530086143415290314195533631308867097853951,
        115792089210356248762697446949407573529996955224135760342422259061068512044369,
    ),
}

R_LIST = [2, 3, 4, 6, 8, 12, 24, 48]
# Charge sheet (PROTOCOL.md, "Shared definitions").  Costs in F_p mults.
CV_LIST = [20, 60, 200]


def sieve(n):
    """Primes <= n."""
    flags = bytearray([1]) * (n + 1)
    flags[0] = flags[1] = 0
    for i in range(2, int(n ** 0.5) + 1):
        if flags[i]:
            flags[i * i :: i] = bytearray(len(flags[i * i :: i]))
    return [i for i in range(n + 1) if flags[i]]


def factor_small(m, primes):
    """Prime factorisation of m by trial division over `primes`
    (must cover sqrt(m))."""
    out = {}
    for q in primes:
        if q * q > m:
            break
        while m % q == 0:
            out[q] = out.get(q, 0) + 1
            m //= q
    if m > 1:
        out[m] = out.get(m, 0) + 1
    return out


def mult_order(a, ell, fac_ell_minus_1):
    """Order of a in F_ell^*, given the factorisation of ell - 1."""
    order = ell - 1
    for q in fac_ell_minus_1:
        while order % q == 0 and pow(a, order // q, ell) == 1:
            order //= q
    return order


def sqrt_mod(a, ell):
    """Tonelli-Shanks; a must be a QR mod prime ell."""
    a %= ell
    if a == 0:
        return 0
    if ell % 4 == 3:
        return pow(a, (ell + 1) // 4, ell)
    q, s = ell - 1, 0
    while q % 2 == 0:
        q //= 2
        s += 1
    z = 2
    while pow(z, (ell - 1) // 2, ell) != ell - 1:
        z += 1
    m, c, t, r = s, pow(z, q, ell), pow(a, q, ell), pow(a, (q + 1) // 2, ell)
    while t != 1:
        i, t2 = 0, t
        while t2 != 1:
            t2 = t2 * t2 % ell
            i += 1
        b = pow(c, 1 << (m - i - 1), ell)
        m, c, t, r = i, b * b % ell, t * b * b % ell, r * b % ell
    return r


def classify(p, t, ell):
    """('divides'|'atkin'|'elkies', lambda, mu) with lambda, mu in F_ell or None."""
    d = (t * t - 4 * p) % ell
    if ell == 2:
        # x^2 - tx + p over F_2.
        roots = [x for x in (0, 1) if (x * x - t * x + p) % 2 == 0]
        if d == 0 or len(roots) == 1:
            return "divides", roots[0] if roots else None, None
        return ("elkies", 0, 1) if len(roots) == 2 else ("atkin", None, None)
    if d == 0:
        return "divides", (t * pow(2, ell - 2, ell)) % ell, None
    if pow(d, (ell - 1) // 2, ell) != 1:
        return "atkin", None, None
    s = sqrt_mod(d, ell)
    inv2 = pow(2, ell - 2, ell)
    lam = (t + s) * inv2 % ell
    mu = (t - s) * inv2 % ell
    return "elkies", lam, mu


def s_r(fac_ell_minus_1, ell, R):
    """S_R(ell) = sum of phi(d) over d | ell - 1 with d <= R."""
    divs = [1]
    for q, e in fac_ell_minus_1.items():
        divs = [d * q ** k for d in divs for k in range(e + 1)]
    total = 0
    for d in divs:
        if d <= R:
            phi = d
            for q in factor_small(d, [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47]):
                phi = phi // q * (q - 1)
            total += phi
    return total


def charge_phi_route(ell, p):
    """Phi route with Phi_ell already built (per edge)."""
    logp = p.bit_length()
    return 2 * ell * ell + 4 * ell * logp + 20 * ell * ell + 20 * ell * ell


def charge_torsion_route(ell, p, r, cv):
    """C4 route: one cofactor multiplication over F_{p^r} plus sqrt-Velu."""
    bits = r * p.bit_length()
    scalar = 12 * bits * r * r
    velu = cv * math.sqrt(ell) * math.log2(ell) * r * r
    return scalar + velu


def run_curve(name, p, n, lmax, out_dir):
    t = p + 1 - n
    twist = 2 * p + 2 - n
    primes = sieve(lmax)
    t0 = time.time()
    counts = {R: 0 for R in R_LIST}
    model = {R: 0.0 for R in R_LIST}
    n_elkies = n_atkin = n_div = 0
    window12 = []
    window4_big = []
    r2_set = []
    twist_small = [q for q in primes if twist % q == 0]
    crossover_viol = {cv: [] for cv in CV_LIST}
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, f"e1_{name}.jsonl")
    with open(path, "w") as fh:
        for ell in primes:
            kind, lam, mu = classify(p, t, ell)
            if kind == "divides":
                n_div += 1
                continue
            if kind == "atkin":
                n_atkin += 1
                continue
            n_elkies += 1
            fac = factor_small(ell - 1, primes)
            r1 = mult_order(lam, ell, fac)
            r2 = mult_order(mu, ell, fac)
            rmin = min(r1, r2)
            rec = {"ell": ell, "lambda": lam, "mu": mu, "r_lambda": r1, "r_mu": r2, "r_min": rmin}
            for R in R_LIST:
                pr = min(1.0, 2.0 * s_r(fac, ell, R) / (ell - 1))
                model[R] += pr
                if rmin <= R:
                    counts[R] += 1
            if rmin == 2:
                r2_set.append(ell)
            if 61 < ell and rmin <= 12:
                window12.append(ell)
            if ell > 1000 and rmin <= 4:
                window4_big.append(ell)
            rec["charge_phi"] = charge_phi_route(ell, p)
            for cv in CV_LIST:
                c4 = charge_torsion_route(ell, p, rmin, cv)
                rec[f"charge_c4_cv{cv}"] = c4
                # E1.4 as registered, evaluated per cv.
                if ell > 200 and rmin <= 6 and not c4 < rec["charge_phi"]:
                    crossover_viol[cv].append(ell)
                if ell < 100 and rmin >= 8 and not c4 > rec["charge_phi"]:
                    crossover_viol[cv].append(ell)
            fh.write(json.dumps(rec) + "\n")
    summary = {
        "curve": name,
        "p_bits": p.bit_length(),
        "trace": t,
        "lmax": lmax,
        "primes": len(primes),
        "divides": n_div,
        "atkin": n_atkin,
        "elkies": n_elkies,
        "count_rmin_le_R": counts,
        "model_rmin_le_R": model,
        "ratio_actual_over_model": {R: (counts[R] / model[R] if model[R] else None) for R in R_LIST},
        "e1_2_rmin_eq_2": r2_set,
        "e1_2_twist_small_primes": twist_small,
        "e1_2_pass": r2_set == twist_small,
        "e1_3_window_rmin_le_12_above_61": window12,
        "e1_3_window_rmin_le_4_above_1000": window4_big,
        "e1_3_pass": len(window12) >= 20 and len(window4_big) >= 1,
        "e1_4_violations_by_cv": crossover_viol,
        "e1_4_pass_cv60": not crossover_viol[60],
        "seconds": time.time() - t0,
        "records": path,
    }
    summary["e1_1_pass"] = all(
        summary["ratio_actual_over_model"][R] is not None and 0.5 <= summary["ratio_actual_over_model"][R] <= 2.0
        for R in (4, 8, 12, 24)
    )
    return summary


def selftest(trials=200, seed=20261008):
    """THEOREM check: r_min(ell) == least k with ell | #E(F_{p^k})."""
    rng = random.Random(seed)
    primes = sieve(1 << 20)
    small = [q for q in primes if q < 200]
    big = [q for q in primes if 1000 < q]
    checked = 0
    for _ in range(trials):
        p = rng.choice(big)
        bound = int(2 * math.isqrt(p))
        t = rng.randint(-bound, bound)
        s_prev, s_cur = 2, t  # s_0, s_1
        orders = {}
        k = 1
        while k <= 500:
            orders[k] = p ** k + 1 - s_cur
            s_prev, s_cur = s_cur, t * s_cur - p * s_prev
            k += 1
        for ell in small:
            if ell == p:
                continue
            kind, lam, mu = classify(p, t, ell)
            if kind != "elkies":
                continue
            fac = factor_small(ell - 1, primes)
            rmin = min(mult_order(lam, ell, fac), mult_order(mu, ell, fac))
            least = next((k for k in range(1, 501) if orders[k] % ell == 0), None)
            if least != rmin:
                print(f"SELFTEST FAIL p={p} t={t} ell={ell} rmin={rmin} least={least}")
                return False
            checked += 1
    print(f"selftest ok: {checked} (p, t, ell) triples agree")
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--curve", choices=sorted(CURVES), action="append")
    ap.add_argument("--lmax", type=int, default=1 << 20)
    ap.add_argument("--out", default="results")
    a = ap.parse_args()
    if a.selftest:
        sys.exit(0 if selftest() else 1)
    summaries = []
    for name in a.curve or sorted(CURVES):
        p, n = CURVES[name]
        s = run_curve(name, p, n, a.lmax, a.out)
        summaries.append(s)
        print(json.dumps({k: v for k, v in s.items() if not k.startswith("e1_3_window")}, indent=1))
    with open(os.path.join(a.out, "e1_summary.json"), "w") as fh:
        json.dump(summaries, fh, indent=1)


if __name__ == "__main__":
    main()
