#!/usr/bin/env python3
"""Tabulate results/*.json into RESULTS.md for experiment A1 at m = 31.

One row per arm on icv1-f2m31-tm90707-c95f16f5: points, columns (unknowns), hit rate,
trials, relations found, matrix rows / rank, the decomposition cost and
the total in group-addition equivalents, the primary metric of the
research note (GAE per independent relation = decomposition-phase GAE
divided by the matrix rank, mean over repeats), S = GAE / sqrt(r), and
S over the matched rho reference.
"""
import glob, json, os, statistics as st

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")
ORDER = ["mitm-x-m2", "mitm-x-m2-proj", "mitm-u-m2", "mitm-u-m2-proj",
         "mitm-x-m3", "mitm-x-m3-proj", "mitm-u-m3", "mitm-u-m3-proj",
         "mitm-tz-m3", "mitm-tz-m3-proj", "sym-m2-proj", "sym-m3-proj"]

def fmt(xs, nd=1):
    if not xs: return "—"
    if len(xs) == 1: return f"{xs[0]:.{nd}f}"
    return f"{st.mean(xs):.{nd}f} ({min(xs):.{nd}f}–{max(xs):.{nd}f})"

def load():
    out = {}
    for path in sorted(glob.glob(os.path.join(RES, "k0_31__*.json"))):
        if path.endswith(".fb.json"): continue
        arm = os.path.basename(path)[len("k0_31__"):-len(".json")]
        with open(path) as fh: out[arm] = json.load(fh)
    return out

def main():
    data = load()
    lines = ["# Results: experiment A1 at m = 31 (icv1-f2m31-tm90707-c95f16f5, r = 1 439 393, h = 1492)", "",
             "Generated by `report.py` from `results/*.json`; the arms are in `run.sh`.", "",
             "| arm | pts | cols | hit rate | trials | rels | rows / rank | dec GAE | GAE per indep. rel | total GAE | S | S_rho | vs rho | verified | wall s |",
             "|:--|--:|--:|:--|:--|:--|:--|:--|:--|:--|:--|--:|--:|:--|--:|"]
    summary = {}
    for arm in ORDER:
        rep = data.get(arm)
        if rep is None:
            lines.append(f"| {arm} | — | — | — | — | — | — | — | — | — | not run | — | — | — | — |"); continue
        rows = rep["rows"]
        if not rows:
            lines.append(f"| {arm} | — | — | — | — | — | — | — | — | — | no rows | — | — | — | — |"); continue
        fb = rows[0]["factor_base"]
        rho = rep.get("rho_reference") or {}
        rho_s = rho.get("mean_s") if rho.get("all_verified") else None
        hit = [r["decomposition"]["hit_rate"] for r in rows]
        trials = [r["decomposition"]["targets_tried"] for r in rows]
        rels = [r["decomposition"]["relations_found"] for r in rows]
        rank = [r["linear_algebra"]["rank"] for r in rows]
        mrows = [r["linear_algebra"]["rows"] for r in rows]
        dec = [r["decomposition"]["cost"]["gae"] for r in rows]
        tot = [r["total_gae"] for r in rows]
        per = [d / max(k, 1) for d, k in zip(dec, rank)]
        s = [r["s"] for r in rows]
        summary[arm] = dict(cols=fb["columns"], pts=fb["signed_points"], hit=st.mean(hit),
                            per=st.mean(per), s=st.mean(s), rank=st.mean(rank), trials=st.mean(trials))
        lines.append("| {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |".format(
            arm, fb["signed_points"], fb["columns"], fmt(hit, 4), fmt(trials, 0), fmt(rels, 1),
            f"{st.mean(mrows):.1f} / {st.mean(rank):.1f}", fmt(dec, 0), fmt(per, 0), fmt(tot, 0), fmt(s, 1),
            f"{rho_s:.3f}" if rho_s else "—", f"{st.mean(s)/rho_s:.0f}×" if rho_s else "—",
            "yes" if all(r["verified"] for r in rows) else "NO", f"{sum(r.get('wall_seconds', 0) for r in rows):.1f}"))
    lines += ["", "## Paired ratios (mean over the three matched repeats)", "",
              "| comparison | cols | hit rate | GAE per indep. rel | S |", "|:--|--:|--:|--:|--:|"]
    pairs = [("mitm-u-m2 / mitm-x-m2", "mitm-u-m2", "mitm-x-m2"), ("mitm-u-m2-proj / mitm-x-m2-proj", "mitm-u-m2-proj", "mitm-x-m2-proj"),
             ("mitm-u-m2-proj / mitm-u-m2", "mitm-u-m2-proj", "mitm-u-m2"), ("mitm-x-m2-proj / mitm-x-m2", "mitm-x-m2-proj", "mitm-x-m2"),
             ("mitm-u-m3 / mitm-x-m3", "mitm-u-m3", "mitm-x-m3"), ("mitm-u-m3-proj / mitm-x-m3-proj", "mitm-u-m3-proj", "mitm-x-m3-proj"),
             ("mitm-u-m3-proj / mitm-u-m3", "mitm-u-m3-proj", "mitm-u-m3"), ("mitm-x-m3-proj / mitm-x-m3", "mitm-x-m3-proj", "mitm-x-m3"),
             ("mitm-tz-m3 / mitm-x-m3", "mitm-tz-m3", "mitm-x-m3"), ("mitm-tz-m3-proj / mitm-x-m3-proj", "mitm-tz-m3-proj", "mitm-x-m3-proj")]
    for label, a, b in pairs:
        if a in summary and b in summary:
            A, B = summary[a], summary[b]
            lines.append(f"| {label} | {A['cols']/B['cols']:.2f} | {A['hit']/B['hit'] if B['hit'] else float('nan'):.2f} | {A['per']/B['per'] if B['per'] else float('nan'):.2f} | {A['s']/B['s']:.2f} |")
    with open(os.path.join(HERE, "RESULTS.md"), "w") as fh: fh.write("\n".join(lines) + "\n")
    print("\n".join(lines))

if __name__ == "__main__": main()
