//! Odd-degree isogenies on alternate curve models (Moody–Shumow, Math. Comp. 2016):
//!
//! Twisted Edwards E_{a,d}: a x^2 + y^2 = 1 + d x^2 y^2, kernel F = {(0,1), (+-alpha_i, beta_i)},
//! l = 2s + 1: psi(P) = (prod_{Q in F} x(P+Q)/y(Q), prod_{Q in F} y(P+Q)/y(Q)) is an l-isogeny
//! onto E_{a^l, B^8 d^l}, B = prod beta_i (Corollary 1). For a = 1 the explicit form (Theorem 2):
//!   X = x/B^2 prod (beta_i^2 x^2 - alpha_i^2 y^2)/(1 - d^2 alpha_i^2 beta_i^2 x^2 y^2),
//!   Y = y/B^2 prod (beta_i^2 y^2 - alpha_i^2 x^2)/(1 - d^2 alpha_i^2 beta_i^2 x^2 y^2),
//! and the one-variable form X = x/B^2 prod (x^2 - alpha_i^2)/(1 - d alpha_i^2 x^2).
//!
//! Huff H_{a,b}: x(a y^2 - 1) = y(b x^2 - 1), kernel F = {(0,0), +-(alpha_i, beta_i)}:
//!   psi(x, y) = (x prod (x^2 - alpha_i^2)/(alpha_i^2 (1 - b^2 alpha_i^2 x^2)),
//!                y prod (y^2 - beta_i^2)/(beta_i^2 (1 - a^2 beta_i^2 y^2)))
//! onto H_{a^l B^4, b^l A^4}, A = prod alpha_i, B = prod beta_i (Theorem 4).
use crate::curve::Curve;
use crate::field::Field;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Edwards<E> {
    pub a: E,
    pub d: E,
}

impl<E: Copy + PartialEq> Edwards<E> {
    pub fn on_curve<F: Field<E = E>>(&self, f: &F, p: (E, E)) -> bool {
        let (x, y) = p;
        let x2 = f.sq(x);
        let y2 = f.sq(y);
        f.add(f.mul(self.a, x2), y2) == f.add(f.one(), f.mul(self.d, f.mul(x2, y2)))
    }
    /// Unified addition law.
    pub fn add<F: Field<E = E>>(&self, f: &F, p: (E, E), q: (E, E)) -> (E, E) {
        let (x1, y1) = p;
        let (x2, y2) = q;
        let t = f.mul(self.d, f.mul(f.mul(x1, x2), f.mul(y1, y2)));
        let x3 = f.div(f.add(f.mul(x1, y2), f.mul(y1, x2)), f.add(f.one(), t));
        let y3 = f.div(f.sub(f.mul(y1, y2), f.mul(self.a, f.mul(x1, x2))), f.sub(f.one(), t));
        (x3, y3)
    }
    /// j = 16 (a^2 + 14 a d + d^2)^3 / (a d (a - d)^4).
    pub fn j<F: Field<E = E>>(&self, f: &F) -> E {
        let (a, d) = (self.a, self.d);
        let t = f.add(f.add(f.sq(a), f.mul(f.from_u64(14), f.mul(a, d))), f.sq(d));
        let num = f.mul(f.from_u64(16), f.mul(t, f.sq(t)));
        let amd = f.sub(a, d);
        f.div(num, f.mul(f.mul(a, d), f.sq(f.sq(amd))))
    }
}

/// From a Montgomery curve B v^2 = u^3 + A u^2 + u (B = 1): (a, d) = (A + 2, A - 2) and the point
/// map (u, v) -> (u/v, (u - 1)/(u + 1)).
pub fn edwards_from_montgomery<F: Field>(f: &F, a_mont: F::E) -> Edwards<F::E> {
    let two = f.from_u64(2);
    Edwards { a: f.add(a_mont, two), d: f.sub(a_mont, two) }
}
pub fn mont_to_edwards_point<F: Field>(f: &F, u: F::E, v: F::E) -> (F::E, F::E) {
    (f.div(u, v), f.div(f.sub(u, f.one()), f.add(u, f.one())))
}

/// The kernel F generated by a point of odd order l: all l points (identity first).
pub fn edwards_kernel<F: Field>(f: &F, e: &Edwards<F::E>, k: (F::E, F::E), ell: u64) -> Vec<(F::E, F::E)> {
    let mut v = vec![(f.zero(), f.one())];
    let mut cur = k;
    for _ in 1..ell {
        v.push(cur);
        cur = e.add(f, cur, k);
    }
    v
}

pub struct EdwardsIso<E> {
    pub dom: Edwards<E>,
    pub cod: Edwards<E>,
    pub kernel: Vec<(E, E)>,
    /// (alpha_i, beta_i), i = 1..s (one of each +-alpha)
    pub half: Vec<(E, E)>,
    pub ell: u64,
}

pub fn edwards_isogeny<F: Field>(f: &F, e: &Edwards<F::E>, k: (F::E, F::E), ell: u64) -> EdwardsIso<F::E> {
    // s = (l-1)/2 additions for the half kernel; -(x, y) = (-x, y) gives the rest
    let s = ((ell - 1) / 2) as usize;
    let mut half = vec![k];
    for _ in 1..s {
        let nx = e.add(f, *half.last().unwrap(), k);
        half.push(nx);
    }
    let mut kernel = vec![(f.zero(), f.one())];
    kernel.extend(half.iter().copied());
    kernel.extend(half.iter().map(|&(x, y)| (f.neg(x), y)));
    let mut b = f.one();
    for &(_, beta) in &half {
        b = f.mul(b, beta);
    }
    let b8 = f.sq(f.sq(f.sq(b)));
    let cod = Edwards { a: f.pow(e.a, ell as u128), d: f.mul(b8, f.pow(e.d, ell as u128)) };
    EdwardsIso { dom: *e, cod, kernel, half, ell }
}

impl<E: Copy + PartialEq> EdwardsIso<E> {
    /// psi(P) by the definition: products of translates (any twisted Edwards curve).
    pub fn eval_def<F: Field<E = E>>(&self, f: &F, p: (E, E)) -> (E, E) {
        let (mut x, mut y) = (f.one(), f.one());
        for &q in &self.kernel {
            let r = self.dom.add(f, p, q);
            x = f.mul(x, f.div(r.0, q.1));
            y = f.mul(y, f.div(r.1, q.1));
        }
        (x, y)
    }
    /// psi(P) by Theorem 2 (a = 1).
    pub fn eval_explicit<F: Field<E = E>>(&self, f: &F, p: (E, E)) -> (E, E) {
        let (x, y) = p;
        let (x2, y2) = (f.sq(x), f.sq(y));
        let d2 = f.sq(self.dom.d);
        let (mut nx, mut ny, mut den, mut b2) = (f.one(), f.one(), f.one(), f.one());
        for &(al, be) in &self.half {
            let (a2, bb2) = (f.sq(al), f.sq(be));
            nx = f.mul(nx, f.sub(f.mul(bb2, x2), f.mul(a2, y2)));
            ny = f.mul(ny, f.sub(f.mul(bb2, y2), f.mul(a2, x2)));
            den = f.mul(den, f.sub(f.one(), f.mul(d2, f.mul(f.mul(a2, bb2), f.mul(x2, y2)))));
            b2 = f.mul(b2, bb2);
        }
        let di = f.inv(f.mul(den, b2));
        (f.mul(f.mul(x, nx), di), f.mul(f.mul(y, ny), di))
    }
    /// X-coordinate from x alone (a = 1): x/B^2 prod (x^2 - alpha_i^2)/(1 - d alpha_i^2 x^2).
    pub fn eval_x_only<F: Field<E = E>>(&self, f: &F, x: E) -> E {
        let x2 = f.sq(x);
        let (mut num, mut den) = (x, f.one());
        for &(al, be) in &self.half {
            let a2 = f.sq(al);
            num = f.mul(num, f.sub(x2, a2));
            den = f.mul(den, f.mul(f.sq(be), f.sub(f.one(), f.mul(self.dom.d, f.mul(a2, x2)))));
        }
        f.div(num, den)
    }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Huff<E> {
    pub a: E,
    pub b: E,
}

impl<E: Copy + PartialEq> Huff<E> {
    pub fn on_curve<F: Field<E = E>>(&self, f: &F, p: (E, E)) -> bool {
        let (x, y) = p;
        f.mul(x, f.sub(f.mul(self.a, f.sq(y)), f.one())) == f.mul(y, f.sub(f.mul(self.b, f.sq(x)), f.one()))
    }
    /// Addition for affine points whose sum is affine (Wu–Feng).
    pub fn add<F: Field<E = E>>(&self, f: &F, p: (E, E), q: (E, E)) -> Option<(E, E)> {
        let (x1, y1) = p;
        let (x2, y2) = q;
        let bx = f.mul(self.b, f.mul(x1, x2));
        let ay = f.mul(self.a, f.mul(y1, y2));
        let d1 = f.mul(f.add(f.one(), bx), f.sub(f.one(), ay));
        let d2 = f.mul(f.sub(f.one(), bx), f.add(f.one(), ay));
        if f.is_zero(d1) || f.is_zero(d2) {
            return None;
        }
        let x3 = f.div(f.mul(f.add(x1, x2), f.add(f.one(), ay)), d1);
        let y3 = f.div(f.mul(f.add(y1, y2), f.add(f.one(), bx)), d2);
        Some((x3, y3))
    }
    /// Weierstrass model y^2 = x^3 + (a+b) x^2 + a b x and the map (x, y) -> ((bx - ay)/(y - x), (b - a)/(y - x)).
    pub fn to_weierstrass_point<F: Field<E = E>>(&self, f: &F, p: (E, E)) -> (E, E) {
        let (x, y) = p;
        let t = f.inv(f.sub(y, x));
        (f.mul(f.sub(f.mul(self.b, x), f.mul(self.a, y)), t), f.mul(f.sub(self.b, self.a), t))
    }
    pub fn from_weierstrass_point<F: Field<E = E>>(&self, f: &F, p: (E, E)) -> (E, E) {
        let (x, y) = p;
        let yi = f.inv(y);
        (f.mul(f.add(x, self.a), yi), f.mul(f.add(x, self.b), yi))
    }
    /// j-invariant through the short Weierstrass model of y^2 = x^3 + (a+b)x^2 + ab x.
    pub fn short_weierstrass<F: Field<E = E>>(&self, f: &F) -> Curve<E> {
        let c = vec![f.zero(), f.mul(self.a, self.b), f.add(self.a, self.b), f.one()];
        crate::genus2::cubic_to_short(f, &c)
    }
}

pub struct HuffIso<E> {
    pub dom: Huff<E>,
    pub cod: Huff<E>,
    pub half: Vec<(E, E)>,
}

/// Huff l-isogeny from a kernel generator k of odd order l (Theorem 4).
pub fn huff_isogeny<F: Field>(f: &F, h: &Huff<F::E>, k: (F::E, F::E), ell: u64) -> Option<HuffIso<F::E>> {
    let s = ((ell - 1) / 2) as usize;
    let mut half = vec![k];
    for _ in 1..s {
        let nx = h.add(f, *half.last().unwrap(), k)?;
        half.push(nx);
    }
    let (mut aa, mut bb) = (f.one(), f.one());
    for &(al, be) in &half {
        aa = f.mul(aa, al);
        bb = f.mul(bb, be);
    }
    let cod = Huff {
        a: f.mul(f.pow(h.a, ell as u128), f.sq(f.sq(bb))),
        b: f.mul(f.pow(h.b, ell as u128), f.sq(f.sq(aa))),
    };
    Some(HuffIso { dom: *h, cod, half })
}

impl<E: Copy + PartialEq> HuffIso<E> {
    pub fn eval<F: Field<E = E>>(&self, f: &F, p: (E, E)) -> (E, E) {
        let (x, y) = p;
        let (x2, y2) = (f.sq(x), f.sq(y));
        let (mut nx, mut dx, mut ny, mut dy) = (x, f.one(), y, f.one());
        for &(al, be) in &self.half {
            let (a2, b2) = (f.sq(al), f.sq(be));
            nx = f.mul(nx, f.sub(x2, a2));
            dx = f.mul(dx, f.mul(a2, f.sub(f.one(), f.mul(f.sq(self.dom.b), f.mul(a2, x2)))));
            ny = f.mul(ny, f.sub(y2, b2));
            dy = f.mul(dy, f.mul(b2, f.sub(f.one(), f.mul(f.sq(self.dom.a), f.mul(b2, y2)))));
        }
        (f.div(nx, dx), f.div(ny, dy))
    }
}
