//! Velu (1971): enumerate the kernel, O(l) work to build the codomain and O(l) per evaluation.
use crate::curve::*;
use crate::field::Field;

pub struct VeluIso<F: Field> {
    pub dom: Curve<F::E>,
    pub cod: Curve<F::E>,
    pub deg: u64,
    /// (x_Q, v_Q, u_Q) for representatives Q of (G\{O})/{+-1}
    pub reps: Vec<(F::E, F::E, F::E)>,
}

/// Odd-degree Velu from the affine points {P, 2P, ..., ((l-1)/2) P}.
pub fn velu<F: Field>(f: &F, e: &Curve<F::E>, reps: &[Pt<F::E>], ell: u64) -> VeluIso<F> {
    let mut t = f.zero();
    let mut w = f.zero();
    let mut out = Vec::with_capacity(reps.len());
    for q in reps {
        let (x, y) = match *q {
            Pt::Aff(x, y) => (x, y),
            Pt::Inf => panic!("kernel point at infinity"),
        };
        let x2 = f.mul(x, x);
        let v = f.add(f.mul(f.from_u64(6), x2), f.mul(f.from_u64(2), e.a));
        let u = f.mul(f.from_u64(4), f.mul(y, y));
        t = f.add(t, v);
        w = f.add(w, f.add(u, f.mul(x, v)));
        out.push((x, v, u));
    }
    let a2 = f.sub(e.a, f.mul(f.from_u64(5), t));
    let b2 = f.sub(e.b, f.mul(f.from_u64(7), w));
    VeluIso {
        dom: *e,
        cod: Curve::new(a2, b2),
        deg: ell,
        reps: out,
    }
}

impl<F: Field> Isogeny<F> for VeluIso<F> {
    fn domain(&self) -> &Curve<F::E> {
        &self.dom
    }
    fn codomain(&self) -> &Curve<F::E> {
        &self.cod
    }
    fn degree(&self) -> u64 {
        self.deg
    }
    fn eval_x(&self, f: &F, x: F::E) -> Option<F::E> {
        self.eval(f, &Pt::Aff(x, f.one())).into_x()
    }
    fn eval(&self, f: &F, p: &Pt<F::E>) -> Pt<F::E> {
        let (x, y) = match *p {
            Pt::Inf => return Pt::Inf,
            Pt::Aff(x, y) => (x, y),
        };
        // one batch inversion for all (x - x_Q)
        let ds: Vec<F::E> = self.reps.iter().map(|&(xq, _, _)| f.sub(x, xq)).collect();
        if ds.iter().any(|&d| f.is_zero(d)) {
            return Pt::Inf;
        }
        let inv = f.batch_inv(&ds);
        let mut fx = x;
        let mut fd = f.one();
        let two = f.from_u64(2);
        for (&(_, v, u), &di) in self.reps.iter().zip(&inv) {
            let di2 = f.sq(di);
            let di3 = f.mul(di2, di);
            fx = f.add(fx, f.add(f.mul(v, di), f.mul(u, di2)));
            fd = f.sub(fd, f.add(f.mul(v, di2), f.mul(two, f.mul(u, di3))));
        }
        Pt::Aff(fx, f.mul(y, fd))
    }
}

pub trait IntoX<E> {
    fn into_x(self) -> Option<E>;
}
impl<E> IntoX<E> for Pt<E> {
    fn into_x(self) -> Option<E> {
        match self {
            Pt::Inf => None,
            Pt::Aff(x, _) => Some(x),
        }
    }
}

/// Velu from a generator: enumerate kP, k = 1..(l-1)/2, then apply the formulas.
pub fn velu_from_point<F: Field>(f: &F, e: &Curve<F::E>, p: &Pt<F::E>, ell: u64) -> VeluIso<F> {
    let n = ((ell - 1) / 2) as usize;
    let mut pts = Vec::with_capacity(n);
    let mut cur = *p;
    for _ in 0..n {
        pts.push(cur);
        cur = padd(f, e, &cur, p);
    }
    velu(f, e, &pts, ell)
}

/// Representatives of (G \ {O}) / {+-1} for the cyclic group of order `n` generated by `p`:
/// kP for k = 1..=n/2 (for even n the last one, (n/2)P, is the 2-torsion point).
pub fn cyclic_reps<F: Field>(f: &F, e: &Curve<F::E>, p: &Pt<F::E>, n: u64) -> Vec<Pt<F::E>> {
    let mut out = Vec::with_capacity((n / 2) as usize);
    let mut cur = *p;
    for _ in 0..n / 2 {
        out.push(cur);
        cur = padd(f, e, &cur, p);
    }
    out
}

/// Representatives of G\{O} modulo +-1 for the subgroup generated by `gens` (closure by BFS).
/// `None` if the subgroup has more than `max_order` elements.
pub fn subgroup_reps<F: Field>(
    f: &F,
    e: &Curve<F::E>,
    gens: &[Pt<F::E>],
    max_order: usize,
) -> Option<Vec<Pt<F::E>>> {
    use std::collections::HashSet;
    let mut seen: HashSet<Pt<F::E>> = HashSet::new();
    seen.insert(Pt::Inf);
    let mut frontier = vec![Pt::Inf];
    while let Some(q) = frontier.pop() {
        for g in gens {
            let r = padd(f, e, &q, g);
            if seen.insert(r) {
                if seen.len() > max_order {
                    return None;
                }
                frontier.push(r);
            }
        }
    }
    let mut reps = vec![];
    let mut used: HashSet<Pt<F::E>> = HashSet::new();
    for q in &seen {
        if *q == Pt::Inf || used.contains(q) {
            continue;
        }
        used.insert(*q);
        used.insert(neg(f, q));
        reps.push(*q);
    }
    Some(reps)
}

/// Vélu's formulas for an arbitrary finite subgroup (any order, cyclic or not, 2-torsion allowed),
/// given one representative per +-pair of non-zero points (2-torsion points appear once).
///   2-torsion Q: t_Q = 3x^2 + A,  u_Q = 0
///   other Q:     t_Q = 6x^2 + 2A, u_Q = 4 y^2
pub fn velu_general<F: Field>(f: &F, e: &Curve<F::E>, reps: &[Pt<F::E>]) -> VeluIso<F> {
    let mut t = f.zero();
    let mut w = f.zero();
    let mut out = Vec::with_capacity(reps.len());
    let mut order = 1u64;
    for q in reps {
        let (x, y) = match *q {
            Pt::Aff(x, y) => (x, y),
            Pt::Inf => panic!("kernel representative at infinity"),
        };
        let x2 = f.mul(x, x);
        let (v, u) = if f.is_zero(y) {
            order += 1;
            (f.add(f.mul(f.from_u64(3), x2), e.a), f.zero())
        } else {
            order += 2;
            (
                f.add(f.mul(f.from_u64(6), x2), f.mul(f.from_u64(2), e.a)),
                f.mul(f.from_u64(4), f.mul(y, y)),
            )
        };
        t = f.add(t, v);
        w = f.add(w, f.add(u, f.mul(x, v)));
        out.push((x, v, u));
    }
    let a2 = f.sub(e.a, f.mul(f.from_u64(5), t));
    let b2 = f.sub(e.b, f.mul(f.from_u64(7), w));
    VeluIso {
        dom: *e,
        cod: Curve::new(a2, b2),
        deg: order,
        reps: out,
    }
}

/// General Vélu from a generator of a cyclic subgroup of order n (any n >= 2).
pub fn velu_cyclic<F: Field>(f: &F, e: &Curve<F::E>, p: &Pt<F::E>, n: u64) -> VeluIso<F> {
    velu_general(f, e, &cyclic_reps(f, e, p, n))
}
