//! Vélu from the x-coordinate of a generator alone (short Weierstrass). The multiples x([k]P) are
//! obtained from division-polynomial values at x(P), so no y-coordinate is needed: the kernel
//! point may live in an extension field where y is not available, e.g. a Galois-stable kernel
//! whose points are not rational.
use super::velu::VeluIso;
use crate::curve::*;
use crate::field::Field;

/// g_n(x0) for n = 0..=n_max (g_n = psi_n for odd n, psi_n / (2y) for even n).
pub fn div_values<F: Field>(f: &F, e: &Curve<F::E>, x0: F::E, n_max: usize) -> Vec<F::E> {
    let c = |v: u64| f.from_u64(v);
    let fx = rhs(f, e, x0);
    let f16 = f.mul(c(16), f.mul(fx, fx));
    let (a2, a3, b2) = (
        f.mul(e.a, e.a),
        f.mul(e.a, f.mul(e.a, e.a)),
        f.mul(e.b, e.b),
    );
    let x2 = f.mul(x0, x0);
    let mut g = vec![f.zero(); n_max.max(4) + 1];
    g[1] = f.one();
    g[2] = f.one();
    // g3 = 3x^4 + 6Ax^2 + 12Bx - A^2
    g[3] = f.sub(
        f.add(
            f.add(f.mul(c(3), f.mul(x2, x2)), f.mul(c(6), f.mul(e.a, x2))),
            f.mul(c(12), f.mul(e.b, x0)),
        ),
        a2,
    );
    // g4 = 2(x^6 + 5Ax^4 + 20Bx^3 - 5A^2x^2 - 4ABx - 8B^2 - A^3)
    let x3 = f.mul(x2, x0);
    let x4 = f.mul(x2, x2);
    let x6 = f.mul(x3, x3);
    let inner = f.sub(
        f.sub(
            f.sub(
                f.add(
                    f.add(x6, f.mul(c(5), f.mul(e.a, x4))),
                    f.mul(c(20), f.mul(e.b, x3)),
                ),
                f.mul(c(5), f.mul(a2, x2)),
            ),
            f.mul(c(4), f.mul(f.mul(e.a, e.b), x0)),
        ),
        f.add(f.mul(c(8), b2), a3),
    );
    g[4] = f.mul(c(2), inner);
    let cube = |v: F::E| f.mul(v, f.mul(v, v));
    for n in 5..=n_max {
        g[n] = if n % 2 == 1 {
            let m = (n - 1) / 2;
            let t1 = f.mul(g[m + 2], cube(g[m]));
            let t2 = f.mul(g[m - 1], cube(g[m + 1]));
            if m % 2 == 0 {
                f.sub(f.mul(f16, t1), t2)
            } else {
                f.sub(t1, f.mul(f16, t2))
            }
        } else {
            let m = n / 2;
            let l = f.mul(g[m + 2], f.mul(g[m - 1], g[m - 1]));
            let r = f.mul(g[m - 2], f.mul(g[m + 1], g[m + 1]));
            f.mul(g[m], f.sub(l, r))
        };
    }
    g
}

/// x([k]P) for k = 1..=n_max given x0 = x(P); None if P has order <= n_max + 1 or is 2-torsion.
pub fn multiples_x<F: Field>(f: &F, e: &Curve<F::E>, x0: F::E, n_max: usize) -> Option<Vec<F::E>> {
    let g = div_values(f, e, x0, n_max + 1);
    let fx = rhs(f, e, x0);
    let four_f = f.mul(f.from_u64(4), fx);
    let mut xs = vec![x0];
    for k in 2..=n_max {
        if f.is_zero(g[k]) || f.is_zero(fx) {
            return None;
        }
        let prod = f.mul(g[k - 1], g[k + 1]);
        let gk2 = f.mul(g[k], g[k]);
        let delta = if k % 2 == 0 {
            f.div(prod, f.mul(four_f, gk2))
        } else {
            f.div(f.mul(four_f, prod), gk2)
        };
        xs.push(f.sub(x0, delta));
    }
    Some(xs)
}

/// Vélu for a kernel of odd order `ell` generated by a point with abscissa x0 (x-only input).
pub fn velu_xonly<F: Field>(f: &F, e: &Curve<F::E>, x0: F::E, ell: u64) -> Option<VeluIso<F>> {
    let n = ((ell - 1) / 2) as usize;
    let xs = multiples_x(f, e, x0, n)?;
    let (mut t, mut w) = (f.zero(), f.zero());
    let mut reps = Vec::with_capacity(n);
    for &x in &xs {
        let x2 = f.mul(x, x);
        let v = f.add(f.mul(f.from_u64(6), x2), f.mul(f.from_u64(2), e.a));
        let u = f.mul(f.from_u64(4), rhs(f, e, x));
        t = f.add(t, v);
        w = f.add(w, f.add(u, f.mul(x, v)));
        reps.push((x, v, u));
    }
    let cod = Curve::new(
        f.sub(e.a, f.mul(f.from_u64(5), t)),
        f.sub(e.b, f.mul(f.from_u64(7), w)),
    );
    Some(VeluIso {
        dom: *e,
        cod,
        deg: ell,
        reps,
    })
}
