//! # Research-grade ECDLP attack framework.
//!
//! Compares the empirical cost of different attacks across an
//! entire `S`-isogeny class.  The hypothesis under test:
//! "the structure of `End(E)` is observable in the runtime of
//! rho on `E`'s discrete log."
//!
//! Implemented attack variants:
//!
//! - **Generic rho** — Pollard's standard partition (this is the
//!   `O(√n)` baseline).  Forwarded to
//!   [`crate::cryptanalysis::pollard_rho`].
//! - **GLV-accelerated rho** — When `End(E)` contains a small
//!   non-trivial endomorphism `φ` (e.g. the cube-root-of-unity map
//!   on `j = 0` curves), the walk can apply `φ` as a third step,
//!   shrinking the effective walk length by `√2`.  This is the
//!   Gallant-Lambert-Vanstone (GLV) speedup as a rho variant.
//! - **MOV / Frey–Rück feasibility** — Computes the embedding
//!   degree `k` (smallest `k` with `n | p^k − 1`) and reports
//!   whether `k` is small enough that pairings give a polynomial-
//!   time descent into `F_{p^k}*`.
//! - **Anomalous-curve detection** — Smart's attack.  Reduces to a
//!   linear log in `F_p` whenever `#E(F_p) = p`.
//!
//! All four are *feasibility detectors*: they identify whether an
//! attack applies and produce a structured `AttackReport`.  Where
//! the rho is actually run, it is run via the existing generic
//! [`crate::cryptanalysis::pollard_rho::pollard_rho_dlp`] with a
//! curve-specific group-operation closure.

use super::cm::{cm_discriminant, CmData};
use super::SmallCurve;
use crate::cryptanalysis::pollard_rho::{pollard_rho_dlp, RhoOptions, RhoSolution};
use crate::ecc::point::Point;
use num_bigint::BigUint;
use num_traits::Zero;

/// Per-curve summary record.  Returned by [`run_attack_suite`] for
/// every curve in the experimental sweep.
#[derive(Clone, Debug, serde::Serialize)]
pub struct AttackReport {
    pub curve: (u64, u64, u64),
    pub cm: CmData,
    /// `(success, iters)` from the generic rho attempt.
    pub rho_iters: Option<u64>,
    pub rho_success: bool,
    /// Embedding degree if computable (≤ 32); `None` otherwise.
    pub embedding_degree: Option<u32>,
    /// Whether MOV/FR descent is computationally cheap.  Heuristic:
    /// `k ≤ 6` is feasible at this scale.
    pub mov_feasible: bool,
    /// Whether Smart's anomalous-curve attack applies (`#E = p`).
    pub smart_applies: bool,
    /// `End(E)` is generated by an extra automorphism (j = 0 or j = 1728)
    /// that the GLV speedup can use.
    pub glv_speedup_available: bool,
}

/// Compute the embedding degree `k = min { k ≥ 1 : n | p^k − 1 }`
/// up to a cap.  Returns `None` if no `k ≤ max_k` works.
pub fn embedding_degree(p: u64, n: u64, max_k: u32) -> Option<u32> {
    if n == 0 {
        return None;
    }
    let mut pk = 1u128 % n as u128;
    for k in 1..=max_k {
        pk = (pk * p as u128) % n as u128;
        if pk == 1 {
            return Some(k);
        }
    }
    None
}

/// Smart's anomalous-curve detector.  Returns `true` iff the curve
/// has `#E(F_p) = p`; the actual `O(log p)` attack lives in
/// [`crate::cryptanalysis::canonical_lift`].
pub fn smart_applies(curve: &SmallCurve) -> bool {
    let cm = cm_discriminant(curve);
    cm.anomalous
}

/// Detect whether the curve has the GLV-friendly extra
/// endomorphism: either `j(E) = 0` (CM by `Z[ω]`, cube-root
/// multiplier `β`) or `j(E) = 1728` (CM by `Z[i]`, multiplier `i`).
pub fn glv_endomorphism_available(curve: &SmallCurve) -> bool {
    // y² = x³ + b  (a = 0) ⇒ j = 0.
    // y² = x³ + ax  (b = 0) ⇒ j = 1728.
    (curve.a == 0 && curve.b != 0) || (curve.b == 0 && curve.a != 0)
}

/// Run Pollard rho on `E`'s additive group.  Picks a generator
/// `G` automatically (the first affine point of order `n`),
/// samples a private scalar `d ∈ [1, n − 1]`, and tries to
/// recover it.
///
/// Caps:
/// - `max_iters` — bound on rho steps before giving up.
/// - `seed`     — deterministic seed for reproducibility.
pub fn rho_on_curve(curve: &SmallCurve, max_iters: u64, seed: u64) -> (Option<RhoSolution>, u64) {
    let cm = cm_discriminant(curve);
    let n = cm.order as u64;
    if n < 4 {
        return (None, 0);
    }
    let cp = curve.to_curve_params();
    let a_fe = cp.a_fe();

    // Find a generator via Tonelli-Shanks: for each scanned x take
    // the explicit square root of rhs(x) rather than enumerating y.
    // Reduces the per-x cost from O(p) to O(log² p), so this loop
    // now finishes in O(p · log² p) worst case — but in practice
    // the first QR x usually wins after O(1) attempts.
    let p = curve.p;
    let mut generator: Option<Point> = None;
    let mut x = 1u64;
    while x < p {
        let rhs = curve.rhs(x);
        let y_opt = if rhs == 0 {
            Some(0u64)
        } else {
            match crate::isogeny::cm::legendre_u64(rhs, p) {
                1 => crate::isogeny::cm::tonelli_shanks_u64(rhs, p),
                _ => None,
            }
        };
        if let Some(y) = y_opt {
            let candidate = Point::Affine {
                x: cp.fe(BigUint::from(x)),
                y: cp.fe(BigUint::from(y)),
            };
            generator = Some(candidate);
            break;
        }
        x += 1;
    }
    let g = match generator {
        Some(p) => p,
        None => return (None, 0),
    };

    // Pick a private scalar d in [1, n−1].
    let d = ((seed.wrapping_mul(0x9E3779B97F4A7C15) % (n - 1)) + 1) as u64;
    let h = g.scalar_mul(&BigUint::from(d), &a_fe);

    let op_a = a_fe.clone();
    let part_p = p;
    let op = |x: &Point, y: &Point| -> Point { x.add(y, &op_a) };
    let eq = |x: &Point, y: &Point| -> bool { x == y };
    let partition = |x: &Point| -> u8 {
        match x {
            Point::Infinity => 0,
            Point::Affine { x, .. } => (x.value.iter_u64_digits().next().unwrap_or(0) % 3) as u8,
        }
    };
    let _ = part_p;
    let pow = |g: &Point, k: &BigUint| -> Point { g.scalar_mul(k, &op_a) };

    let opts = RhoOptions {
        max_iterations: max_iters,
        max_restarts: 8,
        seed: Some(seed),
    };
    let n_big = BigUint::from(n);
    let result = pollard_rho_dlp(&g, &h, &n_big, op, eq, partition, pow, &opts);
    match result {
        Ok(sol) => (Some(sol.clone()), sol.iterations),
        Err(_) => (None, max_iters),
    }
}

/// Top-level attack-suite runner.  Computes every feasibility
/// detector and runs a single rho attempt with `rho_max_iters`.
pub fn run_attack_suite(curve: &SmallCurve, rho_max_iters: u64, seed: u64) -> AttackReport {
    let cm = cm_discriminant(curve);
    let n = cm.order.unsigned_abs();
    let emb = embedding_degree(curve.p, n, 32);
    let mov = emb.map(|k| k <= 6).unwrap_or(false);
    let smart = cm.anomalous;
    let glv = glv_endomorphism_available(curve);

    let (sol, iters) = if BigUint::zero() < BigUint::from(n) {
        rho_on_curve(curve, rho_max_iters, seed)
    } else {
        (None, 0)
    };

    AttackReport {
        curve: (curve.p, curve.a, curve.b),
        cm,
        rho_iters: Some(iters),
        rho_success: sol.is_some(),
        embedding_degree: emb,
        mov_feasible: mov,
        smart_applies: smart,
        glv_speedup_available: glv,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::isogeny::toy_curve_b;

    #[test]
    fn embedding_degree_basic() {
        // Trivial: if n = p − 1 then k = 1 (n divides p − 1).
        let p = 101u64;
        let n = 100u64;
        assert_eq!(embedding_degree(p, n, 4), Some(1));
    }

    #[test]
    fn smart_returns_for_anomalous() {
        // The curve y² = x³ + x over a prime p with #E = p would
        // trip Smart's detector.  We don't know off the top whether
        // the toy curve is anomalous; just check the call doesn't
        // crash and returns a boolean of either polarity.
        let _ = smart_applies(&toy_curve_b());
    }

    #[test]
    fn glv_endomorphism_detects_j_zero() {
        let j0 = crate::isogeny::toy_curve_j0();
        assert!(glv_endomorphism_available(&j0));
    }
}
