/* fpmod.cuh -- arithmetic mod a small odd prime, for batched F_p linear
 * algebra.
 *
 * `p` is compiled in (MAC_P from params.h) and is under 2^31, which is
 * what the Macaulay matrices of `gaudry_cubic` need: that module runs
 * p = 271 .. 2083 and the method's `p` grows as n^{1/3}, so 2^31 covers
 * far more than it will ever reach.
 *
 * Multiplication is **Montgomery**, not `%`.  A 64-bit modulo compiles
 * to a multi-instruction sequence on every NVIDIA architecture, and it
 * is the inner operation of the whole kernel; Montgomery is two 32x32
 * multiplies and a conditional subtract.  Values live in Montgomery
 * form (`a * 2^32 mod p`) for the whole reduction and are converted back
 * once at the end, so the conversions do not appear in the inner loop.
 *
 * Compiles as plain C++ too (the __device__ macros vanish), which is
 * how test_cpu.cpp checks it without a GPU.
 */
#pragma once

#include <stdint.h>

#ifndef MAC_HD
#  ifdef __CUDACC__
#    define MAC_HD __host__ __device__ __forceinline__
#  else
#    define MAC_HD inline
#  endif
#endif

#ifndef MAC_P
#  error "include params.h (generated by mref.py) before fpmod.cuh"
#endif

/* Montgomery reduction of a 64-bit product: returns `t * 2^-32 mod p`.
 *
 * The standard REDC: `m = (t mod 2^32) * pinv mod 2^32` with
 * `pinv = -p^-1 mod 2^32`, then `(t + m*p) / 2^32`, which is exact
 * because the low word cancels by construction. */
MAC_HD uint32_t fp_redc(uint64_t t) {
    uint32_t m = (uint32_t)t * MAC_PINV;
    uint64_t s = t + (uint64_t)m * MAC_P;
    uint32_t r = (uint32_t)(s >> 32);
    return r >= MAC_P ? r - MAC_P : r;
}

/* Montgomery product: both operands and the result in Montgomery form. */
MAC_HD uint32_t fp_mul(uint32_t a, uint32_t b) {
    return fp_redc((uint64_t)a * b);
}

MAC_HD uint32_t fp_add(uint32_t a, uint32_t b) {
    uint32_t s = a + b;
    return s >= MAC_P ? s - MAC_P : s;
}

MAC_HD uint32_t fp_sub(uint32_t a, uint32_t b) {
    return a >= b ? a - b : a + MAC_P - b;
}

MAC_HD uint32_t fp_neg(uint32_t a) { return a ? MAC_P - a : 0u; }

/* Into and out of Montgomery form. */
MAC_HD uint32_t fp_to_mont(uint32_t a) { return fp_mul(a % MAC_P, MAC_R2); }
MAC_HD uint32_t fp_from_mont(uint32_t a) { return fp_redc((uint64_t)a); }

MAC_HD uint32_t fp_one_mont() { return MAC_RMOD; }

/* a^e, Montgomery form throughout. */
MAC_HD uint32_t fp_pow(uint32_t a, uint32_t e) {
    uint32_t r = fp_one_mont();
    while (e) {
        if (e & 1u) r = fp_mul(r, a);
        a = fp_mul(a, a);
        e >>= 1;
    }
    return r;
}

/* Inverse by Fermat.  One per pivot, so ~cols per matrix: a negligible
 * share of a rows*cols*rank elimination, and it avoids the divergent
 * branching of extended Euclid inside a warp. */
MAC_HD uint32_t fp_inv(uint32_t a) { return fp_pow(a, MAC_P - 2u); }
