#!/usr/bin/env python3
"""Oracle for gpu/macaulay: batched row reduction over F_p.

Generates the parameter header and the test vectors the CPU harness and
the device self-test check against.  Everything the kernels are compared
with is computed here, in plain Python, so the comparison is against an
independent implementation rather than against the kernel's own logic.

    python3 mref.py params  --p 2083 --rows 226 --cols 286 > params.h
    python3 mref.py vectors --p 2083 > vectors.h

## Why these shapes

`226 x 286 over F_p` is the Macaulay matrix of the symmetrised-`S4`
solve in `src/cryptanalysis/gaudry_cubic.rs`, at the degree-10
regularity bound and after Macaulay's row selection --- see
`RESEARCH_RESIDUAL_WALKS.md` 11.6.  One residual of an index-calculus
run produces exactly one such matrix, they are all the same shape over
the same `p`, and there are thousands of them per run and no data
dependence between them.  That is the batched-LU shape.

## How a large case is checked without a huge header

Small shapes ship as literal matrices and are compared entry by entry.
The real shape ships as a *seed*: both this oracle and the C++ harness
generate the matrix from the same splitmix64 stream, so the header
carries only the seed plus a digest of the expected reduced form and a
handful of spot entries.  A wrong kernel fails the digest; a wrong
generator fails the spot entries.
"""

import argparse
import sys

MASK64 = (1 << 64) - 1


def splitmix64(state):
    """The generator both sides share.  Returns (value, next_state)."""
    state = (state + 0x9E3779B97F4A7C15) & MASK64
    z = state
    z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & MASK64
    z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & MASK64
    return (z ^ (z >> 31)) & MASK64, state


def gen_matrix(rows, cols, p, seed, rank_deficit=0):
    """A `rows x cols` matrix over F_p from the shared stream.

    `rank_deficit` rows are replaced by combinations of earlier ones, so
    the harness exercises the rank-deficient path that a real Macaulay
    matrix always has (its rows carry syzygies).
    """
    st = seed
    m = []
    for _ in range(rows):
        row = []
        for _ in range(cols):
            v, st = splitmix64(st)
            row.append(v % p)
        m.append(row)
    for k in range(rank_deficit):
        r = rows - 1 - k
        v, st = splitmix64(st)
        src = v % (r if r > 0 else 1)
        v, st = splitmix64(st)
        c = v % p
        m[r] = [(c * x) % p for x in m[src]]
    return m


def rref(matrix, p):
    """Reduced row echelon form over F_p.

    Returns `(reduced, pivot_columns, rank)`.  Plain textbook Gauss-
    Jordan: the kernel is the thing being tested, so this stays as
    obvious as possible.
    """
    m = [row[:] for row in matrix]
    rows = len(m)
    cols = len(m[0]) if rows else 0
    pivots = []
    r = 0
    for c in range(cols):
        if r >= rows:
            break
        pr = next((i for i in range(r, rows) if m[i][c] % p), None)
        if pr is None:
            continue
        m[r], m[pr] = m[pr], m[r]
        inv = pow(m[r][c], p - 2, p)
        m[r] = [(x * inv) % p for x in m[r]]
        for i in range(rows):
            if i != r and m[i][c] % p:
                f = m[i][c]
                m[i] = [(a - f * b) % p for a, b in zip(m[i], m[r])]
        pivots.append(c)
        r += 1
    return m, pivots, r


def digest(matrix, p):
    """An order-sensitive rolling hash of a matrix, mod 2^64.

    Cheap to recompute on the device and strong enough that a wrong
    reduction will not collide with the right one.
    """
    h = 0xCBF29CE484222325
    for row in matrix:
        for x in row:
            h = ((h ^ (x % p)) * 0x100000001B3) & MASK64
    return h


def emit_params(args):
    print("/* generated by mref.py -- do not edit */")
    print("#pragma once")
    print("#include <stdint.h>")
    print(f"#define MAC_P        {args.p}u")
    print(f"#define MAC_ROWS     {args.rows}")
    print(f"#define MAC_COLS     {args.cols}")
    # -p^{-1} mod 2^32, for Montgomery multiplication.
    pinv = (-pow(args.p, -1, 1 << 32)) % (1 << 32)
    print(f"#define MAC_PINV     {pinv}u   /* -p^-1 mod 2^32 */")
    print(f"#define MAC_R2       {(1 << 64) % args.p}u   /* 2^64 mod p */")
    print(f"#define MAC_RMOD     {(1 << 32) % args.p}u   /* 2^32 mod p */")


def emit_small_case(name, rows, cols, p, seed, deficit):
    m = gen_matrix(rows, cols, p, seed, deficit)
    red, piv, rank = rref(m, p)
    flat = ",".join(str(x) for row in m for x in row)
    rflat = ",".join(str(x) for row in red for x in row)
    pflat = ",".join(str(x) for x in piv) if piv else "0"
    print(f"static const int      {name}_ROWS = {rows};")
    print(f"static const int      {name}_COLS = {cols};")
    print(f"static const int      {name}_RANK = {rank};")
    print(f"static const int      {name}_NPIV = {len(piv)};")
    print(f"static const uint32_t {name}_IN[]  = {{{flat}}};")
    print(f"static const uint32_t {name}_RREF[] = {{{rflat}}};")
    print(f"static const int      {name}_PIV[] = {{{pflat}}};")


def emit_vectors(args):
    print("/* generated by mref.py -- do not edit */")
    print("#pragma once")
    print("#include <stdint.h>")
    print()
    print("/* Small cases: literal matrices, compared entry by entry. */")
    emit_small_case("CASE_A", 8, 10, args.p, 0x1234, 0)
    emit_small_case("CASE_B", 12, 9, args.p, 0xBEEF, 0)
    print("/* Rank-deficient: real Macaulay rows carry syzygies. */")
    emit_small_case("CASE_C", 14, 14, args.p, 0xF00D, 4)
    print("/* Wider than tall, and taller than wide. */")
    emit_small_case("CASE_D", 6, 20, args.p, 0xACE1, 0)
    emit_small_case("CASE_E", 20, 6, args.p, 0x5EED, 2)
    print()
    print("/* The real shape: seed + digest, so the header stays small. */")
    big = gen_matrix(args.rows, args.cols, args.p, args.seed, args.deficit)
    red, piv, rank = rref(big, args.p)
    print(f"static const uint64_t BIG_SEED    = {args.seed}ull;")
    print(f"static const int      BIG_DEFICIT = {args.deficit};")
    print(f"static const int      BIG_RANK    = {rank};")
    print(f"static const uint64_t BIG_IN_DIG  = {digest(big, args.p)}ull;")
    print(f"static const uint64_t BIG_RREF_DIG= {digest(red, args.p)}ull;")
    # Spot entries, so a broken generator fails loudly rather than
    # agreeing with itself.
    spots = [(0, 0), (1, 5), (37, 61), (rank - 1 if rank else 0, args.cols - 1)]
    sflat = ",".join(f"{{{r},{c},{red[r][c]}}}" for r, c in spots)
    print(f"static const int BIG_SPOTS[][3] = {{{sflat}}};")
    print(f"static const int BIG_NSPOTS = {len(spots)};")
    pflat = ",".join(str(x) for x in piv)
    print(f"static const int BIG_PIV[] = {{{pflat}}};")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("params", "vectors"):
        s = sub.add_parser(name)
        s.add_argument("--p", type=int, default=2083)
        s.add_argument("--rows", type=int, default=226)
        s.add_argument("--cols", type=int, default=286)
        s.add_argument("--seed", type=lambda x: int(x, 0), default=0x9E3779B9)
        s.add_argument("--deficit", type=int, default=4)
    args = ap.parse_args()
    if args.p % 2 == 0:
        sys.exit("p must be odd (Montgomery)")
    if args.cmd == "params":
        emit_params(args)
    else:
        emit_vectors(args)


if __name__ == "__main__":
    main()
