// Generated by codegen/genpackedproduct.py; do not edit.
// Polynomial product and reduction modulo 0xd1d0d000d0000000d000000000000000d.
// Included inside eccPacked131. The normal-basis inverse path is separate.
#pragma once
ECC_HD P131 generatedProduct131(P131 a, P131 b) {
    const uint32_t v0 = a.v[0];
    const uint32_t v1 = a.v[1];
    const uint32_t v2 = a.v[2];
    const uint32_t v3 = a.v[3];
    const uint32_t v4 = a.v[4];
    const uint32_t v5 = b.v[0];
    const uint32_t v6 = b.v[1];
    const uint32_t v7 = b.v[2];
    const uint32_t v8 = b.v[3];
    const uint32_t v9 = b.v[4];
    const uint32_t v10 = v0 & 0x11111111u;
    const uint32_t v14 = v5 & 0x11111111u;
    // native wide event 0, coupled low/high
    const uint64_t w0 = uint64_t(v10) * uint64_t(v14);
    const uint32_t v18 = uint32_t(w0);
    const uint32_t v19 = uint32_t(w0 >> 32);
    const uint32_t v11 = v0 & 0x22222222u;
    const uint32_t v17 = v5 & 0x88888888u;
    // native wide event 1, coupled low/high
    const uint64_t w1 = uint64_t(v11) * uint64_t(v17);
    const uint32_t v20 = uint32_t(w1);
    const uint32_t v21 = uint32_t(w1 >> 32);
    const uint32_t v12 = v0 & 0x44444444u;
    const uint32_t v16 = v5 & 0x44444444u;
    // native wide event 2, coupled low/high
    const uint64_t w2 = uint64_t(v12) * uint64_t(v16);
    const uint32_t v22 = uint32_t(w2);
    const uint32_t v23 = uint32_t(w2 >> 32);
    const uint32_t v26 = v18 ^ v20 ^ v22;
    const uint32_t v29 = v19 ^ v21 ^ v23;
    const uint32_t v13 = v0 & 0x88888888u;
    const uint32_t v15 = v5 & 0x22222222u;
    // native wide event 3, coupled low/high
    const uint64_t w3 = uint64_t(v13) * uint64_t(v15);
    const uint32_t v24 = uint32_t(w3);
    const uint32_t v25 = uint32_t(w3 >> 32);
    const uint32_t v28 = (v24 ^ v26) & 0x11111111u;
    const uint32_t v31 = (v25 ^ v29) & 0x11111111u;
    // native wide event 4, coupled low/high
    const uint64_t w4 = uint64_t(v10) * uint64_t(v15);
    const uint32_t v32 = uint32_t(w4);
    const uint32_t v33 = uint32_t(w4 >> 32);
    // native wide event 5, coupled low/high
    const uint64_t w5 = uint64_t(v11) * uint64_t(v14);
    const uint32_t v34 = uint32_t(w5);
    const uint32_t v35 = uint32_t(w5 >> 32);
    // native wide event 6, coupled low/high
    const uint64_t w6 = uint64_t(v12) * uint64_t(v17);
    const uint32_t v36 = uint32_t(w6);
    const uint32_t v37 = uint32_t(w6 >> 32);
    const uint32_t v40 = v32 ^ v34 ^ v36;
    const uint32_t v43 = v33 ^ v35 ^ v37;
    // native wide event 7, coupled low/high
    const uint64_t w7 = uint64_t(v13) * uint64_t(v16);
    const uint32_t v38 = uint32_t(w7);
    const uint32_t v39 = uint32_t(w7 >> 32);
    const uint32_t v42 = (v38 ^ v40) & 0x22222222u;
    const uint32_t v45 = (v39 ^ v43) & 0x22222222u;
    // native wide event 8, coupled low/high
    const uint64_t w8 = uint64_t(v10) * uint64_t(v16);
    const uint32_t v46 = uint32_t(w8);
    const uint32_t v47 = uint32_t(w8 >> 32);
    // native wide event 9, coupled low/high
    const uint64_t w9 = uint64_t(v11) * uint64_t(v15);
    const uint32_t v48 = uint32_t(w9);
    const uint32_t v49 = uint32_t(w9 >> 32);
    // native wide event 10, coupled low/high
    const uint64_t w10 = uint64_t(v12) * uint64_t(v14);
    const uint32_t v50 = uint32_t(w10);
    const uint32_t v51 = uint32_t(w10 >> 32);
    const uint32_t v54 = v46 ^ v48 ^ v50;
    const uint32_t v57 = v47 ^ v49 ^ v51;
    // native wide event 11, coupled low/high
    const uint64_t w11 = uint64_t(v13) * uint64_t(v17);
    const uint32_t v52 = uint32_t(w11);
    const uint32_t v53 = uint32_t(w11 >> 32);
    const uint32_t v56 = (v52 ^ v54) & 0x44444444u;
    const uint32_t v74 = v28 ^ v42 ^ v56;
    const uint32_t v59 = (v53 ^ v57) & 0x44444444u;
    const uint32_t v76 = v31 ^ v45 ^ v59;
    // native wide event 12, coupled low/high
    const uint64_t w12 = uint64_t(v10) * uint64_t(v17);
    const uint32_t v60 = uint32_t(w12);
    const uint32_t v61 = uint32_t(w12 >> 32);
    // native wide event 13, coupled low/high
    const uint64_t w13 = uint64_t(v11) * uint64_t(v16);
    const uint32_t v62 = uint32_t(w13);
    const uint32_t v63 = uint32_t(w13 >> 32);
    // native wide event 14, coupled low/high
    const uint64_t w14 = uint64_t(v12) * uint64_t(v15);
    const uint32_t v64 = uint32_t(w14);
    const uint32_t v65 = uint32_t(w14 >> 32);
    const uint32_t v68 = v60 ^ v62 ^ v64;
    const uint32_t v71 = v61 ^ v63 ^ v65;
    // native wide event 15, coupled low/high
    const uint64_t w15 = uint64_t(v13) * uint64_t(v14);
    const uint32_t v66 = uint32_t(w15);
    const uint32_t v67 = uint32_t(w15 >> 32);
    const uint32_t v70 = (v66 ^ v68) & 0x88888888u;
    const uint32_t v73 = (v67 ^ v71) & 0x88888888u;
    const uint32_t v75 = v70 ^ v74;
    const uint32_t v77 = v73 ^ v76;
    const uint32_t v78 = v1 & 0x11111111u;
    const uint32_t v82 = v6 & 0x11111111u;
    // native wide event 16, coupled low/high
    const uint64_t w16 = uint64_t(v78) * uint64_t(v82);
    const uint32_t v86 = uint32_t(w16);
    const uint32_t v87 = uint32_t(w16 >> 32);
    const uint32_t v79 = v1 & 0x22222222u;
    const uint32_t v85 = v6 & 0x88888888u;
    // native wide event 17, coupled low/high
    const uint64_t w17 = uint64_t(v79) * uint64_t(v85);
    const uint32_t v88 = uint32_t(w17);
    const uint32_t v89 = uint32_t(w17 >> 32);
    const uint32_t v80 = v1 & 0x44444444u;
    const uint32_t v84 = v6 & 0x44444444u;
    // native wide event 18, coupled low/high
    const uint64_t w18 = uint64_t(v80) * uint64_t(v84);
    const uint32_t v90 = uint32_t(w18);
    const uint32_t v91 = uint32_t(w18 >> 32);
    const uint32_t v94 = v86 ^ v88 ^ v90;
    const uint32_t v97 = v87 ^ v89 ^ v91;
    const uint32_t v81 = v1 & 0x88888888u;
    const uint32_t v83 = v6 & 0x22222222u;
    // native wide event 19, coupled low/high
    const uint64_t w19 = uint64_t(v81) * uint64_t(v83);
    const uint32_t v92 = uint32_t(w19);
    const uint32_t v93 = uint32_t(w19 >> 32);
    const uint32_t v96 = (v92 ^ v94) & 0x11111111u;
    const uint32_t v99 = (v93 ^ v97) & 0x11111111u;
    // native wide event 20, coupled low/high
    const uint64_t w20 = uint64_t(v78) * uint64_t(v83);
    const uint32_t v100 = uint32_t(w20);
    const uint32_t v101 = uint32_t(w20 >> 32);
    // native wide event 21, coupled low/high
    const uint64_t w21 = uint64_t(v79) * uint64_t(v82);
    const uint32_t v102 = uint32_t(w21);
    const uint32_t v103 = uint32_t(w21 >> 32);
    // native wide event 22, coupled low/high
    const uint64_t w22 = uint64_t(v80) * uint64_t(v85);
    const uint32_t v104 = uint32_t(w22);
    const uint32_t v105 = uint32_t(w22 >> 32);
    const uint32_t v108 = v100 ^ v102 ^ v104;
    const uint32_t v111 = v101 ^ v103 ^ v105;
    // native wide event 23, coupled low/high
    const uint64_t w23 = uint64_t(v81) * uint64_t(v84);
    const uint32_t v106 = uint32_t(w23);
    const uint32_t v107 = uint32_t(w23 >> 32);
    const uint32_t v110 = (v106 ^ v108) & 0x22222222u;
    const uint32_t v113 = (v107 ^ v111) & 0x22222222u;
    // native wide event 24, coupled low/high
    const uint64_t w24 = uint64_t(v78) * uint64_t(v84);
    const uint32_t v114 = uint32_t(w24);
    const uint32_t v115 = uint32_t(w24 >> 32);
    // native wide event 25, coupled low/high
    const uint64_t w25 = uint64_t(v79) * uint64_t(v83);
    const uint32_t v116 = uint32_t(w25);
    const uint32_t v117 = uint32_t(w25 >> 32);
    // native wide event 26, coupled low/high
    const uint64_t w26 = uint64_t(v80) * uint64_t(v82);
    const uint32_t v118 = uint32_t(w26);
    const uint32_t v119 = uint32_t(w26 >> 32);
    const uint32_t v122 = v114 ^ v116 ^ v118;
    const uint32_t v125 = v115 ^ v117 ^ v119;
    // native wide event 27, coupled low/high
    const uint64_t w27 = uint64_t(v81) * uint64_t(v85);
    const uint32_t v120 = uint32_t(w27);
    const uint32_t v121 = uint32_t(w27 >> 32);
    const uint32_t v124 = (v120 ^ v122) & 0x44444444u;
    const uint32_t v142 = v96 ^ v110 ^ v124;
    const uint32_t v127 = (v121 ^ v125) & 0x44444444u;
    const uint32_t v144 = v99 ^ v113 ^ v127;
    // native wide event 28, coupled low/high
    const uint64_t w28 = uint64_t(v78) * uint64_t(v85);
    const uint32_t v128 = uint32_t(w28);
    const uint32_t v129 = uint32_t(w28 >> 32);
    // native wide event 29, coupled low/high
    const uint64_t w29 = uint64_t(v79) * uint64_t(v84);
    const uint32_t v130 = uint32_t(w29);
    const uint32_t v131 = uint32_t(w29 >> 32);
    // native wide event 30, coupled low/high
    const uint64_t w30 = uint64_t(v80) * uint64_t(v83);
    const uint32_t v132 = uint32_t(w30);
    const uint32_t v133 = uint32_t(w30 >> 32);
    const uint32_t v136 = v128 ^ v130 ^ v132;
    const uint32_t v139 = v129 ^ v131 ^ v133;
    // native wide event 31, coupled low/high
    const uint64_t w31 = uint64_t(v81) * uint64_t(v82);
    const uint32_t v134 = uint32_t(w31);
    const uint32_t v135 = uint32_t(w31 >> 32);
    const uint32_t v138 = (v134 ^ v136) & 0x88888888u;
    const uint32_t v141 = (v135 ^ v139) & 0x88888888u;
    const uint32_t v143 = v138 ^ v142;
    const uint32_t v145 = v141 ^ v144;
    const uint32_t v148 = (v0 ^ v1) & 0x11111111u;
    const uint32_t v152 = (v5 ^ v6) & 0x11111111u;
    // native wide event 32, coupled low/high
    const uint64_t w32 = uint64_t(v148) * uint64_t(v152);
    const uint32_t v156 = uint32_t(w32);
    const uint32_t v157 = uint32_t(w32 >> 32);
    const uint32_t v149 = (v0 ^ v1) & 0x22222222u;
    const uint32_t v155 = (v5 ^ v6) & 0x88888888u;
    // native wide event 33, coupled low/high
    const uint64_t w33 = uint64_t(v149) * uint64_t(v155);
    const uint32_t v158 = uint32_t(w33);
    const uint32_t v159 = uint32_t(w33 >> 32);
    const uint32_t v150 = (v0 ^ v1) & 0x44444444u;
    const uint32_t v154 = (v5 ^ v6) & 0x44444444u;
    // native wide event 34, coupled low/high
    const uint64_t w34 = uint64_t(v150) * uint64_t(v154);
    const uint32_t v160 = uint32_t(w34);
    const uint32_t v161 = uint32_t(w34 >> 32);
    const uint32_t v164 = v156 ^ v158 ^ v160;
    const uint32_t v167 = v157 ^ v159 ^ v161;
    const uint32_t v151 = (v0 ^ v1) & 0x88888888u;
    const uint32_t v153 = (v5 ^ v6) & 0x22222222u;
    // native wide event 35, coupled low/high
    const uint64_t w35 = uint64_t(v151) * uint64_t(v153);
    const uint32_t v162 = uint32_t(w35);
    const uint32_t v163 = uint32_t(w35 >> 32);
    const uint32_t v166 = (v162 ^ v164) & 0x11111111u;
    const uint32_t v169 = (v163 ^ v167) & 0x11111111u;
    // native wide event 36, coupled low/high
    const uint64_t w36 = uint64_t(v148) * uint64_t(v153);
    const uint32_t v170 = uint32_t(w36);
    const uint32_t v171 = uint32_t(w36 >> 32);
    // native wide event 37, coupled low/high
    const uint64_t w37 = uint64_t(v149) * uint64_t(v152);
    const uint32_t v172 = uint32_t(w37);
    const uint32_t v173 = uint32_t(w37 >> 32);
    // native wide event 38, coupled low/high
    const uint64_t w38 = uint64_t(v150) * uint64_t(v155);
    const uint32_t v174 = uint32_t(w38);
    const uint32_t v175 = uint32_t(w38 >> 32);
    const uint32_t v178 = v170 ^ v172 ^ v174;
    const uint32_t v181 = v171 ^ v173 ^ v175;
    // native wide event 39, coupled low/high
    const uint64_t w39 = uint64_t(v151) * uint64_t(v154);
    const uint32_t v176 = uint32_t(w39);
    const uint32_t v177 = uint32_t(w39 >> 32);
    const uint32_t v180 = (v176 ^ v178) & 0x22222222u;
    const uint32_t v183 = (v177 ^ v181) & 0x22222222u;
    // native wide event 40, coupled low/high
    const uint64_t w40 = uint64_t(v148) * uint64_t(v154);
    const uint32_t v184 = uint32_t(w40);
    const uint32_t v185 = uint32_t(w40 >> 32);
    // native wide event 41, coupled low/high
    const uint64_t w41 = uint64_t(v149) * uint64_t(v153);
    const uint32_t v186 = uint32_t(w41);
    const uint32_t v187 = uint32_t(w41 >> 32);
    // native wide event 42, coupled low/high
    const uint64_t w42 = uint64_t(v150) * uint64_t(v152);
    const uint32_t v188 = uint32_t(w42);
    const uint32_t v189 = uint32_t(w42 >> 32);
    const uint32_t v192 = v184 ^ v186 ^ v188;
    const uint32_t v195 = v185 ^ v187 ^ v189;
    // native wide event 43, coupled low/high
    const uint64_t w43 = uint64_t(v151) * uint64_t(v155);
    const uint32_t v190 = uint32_t(w43);
    const uint32_t v191 = uint32_t(w43 >> 32);
    const uint32_t v194 = (v190 ^ v192) & 0x44444444u;
    const uint32_t v212 = v166 ^ v180 ^ v194;
    const uint32_t v197 = (v191 ^ v195) & 0x44444444u;
    const uint32_t v214 = v169 ^ v183 ^ v197;
    // native wide event 44, coupled low/high
    const uint64_t w44 = uint64_t(v148) * uint64_t(v155);
    const uint32_t v198 = uint32_t(w44);
    const uint32_t v199 = uint32_t(w44 >> 32);
    // native wide event 45, coupled low/high
    const uint64_t w45 = uint64_t(v149) * uint64_t(v154);
    const uint32_t v200 = uint32_t(w45);
    const uint32_t v201 = uint32_t(w45 >> 32);
    // native wide event 46, coupled low/high
    const uint64_t w46 = uint64_t(v150) * uint64_t(v153);
    const uint32_t v202 = uint32_t(w46);
    const uint32_t v203 = uint32_t(w46 >> 32);
    const uint32_t v206 = v198 ^ v200 ^ v202;
    const uint32_t v209 = v199 ^ v201 ^ v203;
    // native wide event 47, coupled low/high
    const uint64_t w47 = uint64_t(v151) * uint64_t(v152);
    const uint32_t v204 = uint32_t(w47);
    const uint32_t v205 = uint32_t(w47 >> 32);
    const uint32_t v208 = (v204 ^ v206) & 0x88888888u;
    const uint32_t v211 = (v205 ^ v209) & 0x88888888u;
    const uint32_t v213 = v208 ^ v212;
    const uint32_t v215 = v211 ^ v214;
    const uint32_t v216 = v75 ^ v143 ^ v213;
    const uint32_t v217 = v77 ^ v145 ^ v215;
    const uint32_t v218 = v77 ^ v216;
    const uint32_t v219 = v143 ^ v217;
    const uint32_t v220 = v2 & 0x11111111u;
    const uint32_t v224 = v7 & 0x11111111u;
    // native wide event 48, coupled low/high
    const uint64_t w48 = uint64_t(v220) * uint64_t(v224);
    const uint32_t v228 = uint32_t(w48);
    const uint32_t v229 = uint32_t(w48 >> 32);
    const uint32_t v221 = v2 & 0x22222222u;
    const uint32_t v227 = v7 & 0x88888888u;
    // native wide event 49, coupled low/high
    const uint64_t w49 = uint64_t(v221) * uint64_t(v227);
    const uint32_t v230 = uint32_t(w49);
    const uint32_t v231 = uint32_t(w49 >> 32);
    const uint32_t v222 = v2 & 0x44444444u;
    const uint32_t v226 = v7 & 0x44444444u;
    // native wide event 50, coupled low/high
    const uint64_t w50 = uint64_t(v222) * uint64_t(v226);
    const uint32_t v232 = uint32_t(w50);
    const uint32_t v233 = uint32_t(w50 >> 32);
    const uint32_t v236 = v228 ^ v230 ^ v232;
    const uint32_t v239 = v229 ^ v231 ^ v233;
    const uint32_t v223 = v2 & 0x88888888u;
    const uint32_t v225 = v7 & 0x22222222u;
    // native wide event 51, coupled low/high
    const uint64_t w51 = uint64_t(v223) * uint64_t(v225);
    const uint32_t v234 = uint32_t(w51);
    const uint32_t v235 = uint32_t(w51 >> 32);
    const uint32_t v238 = (v234 ^ v236) & 0x11111111u;
    const uint32_t v241 = (v235 ^ v239) & 0x11111111u;
    // native wide event 52, coupled low/high
    const uint64_t w52 = uint64_t(v220) * uint64_t(v225);
    const uint32_t v242 = uint32_t(w52);
    const uint32_t v243 = uint32_t(w52 >> 32);
    // native wide event 53, coupled low/high
    const uint64_t w53 = uint64_t(v221) * uint64_t(v224);
    const uint32_t v244 = uint32_t(w53);
    const uint32_t v245 = uint32_t(w53 >> 32);
    // native wide event 54, coupled low/high
    const uint64_t w54 = uint64_t(v222) * uint64_t(v227);
    const uint32_t v246 = uint32_t(w54);
    const uint32_t v247 = uint32_t(w54 >> 32);
    const uint32_t v250 = v242 ^ v244 ^ v246;
    const uint32_t v253 = v243 ^ v245 ^ v247;
    // native wide event 55, coupled low/high
    const uint64_t w55 = uint64_t(v223) * uint64_t(v226);
    const uint32_t v248 = uint32_t(w55);
    const uint32_t v249 = uint32_t(w55 >> 32);
    const uint32_t v252 = (v248 ^ v250) & 0x22222222u;
    const uint32_t v255 = (v249 ^ v253) & 0x22222222u;
    // native wide event 56, coupled low/high
    const uint64_t w56 = uint64_t(v220) * uint64_t(v226);
    const uint32_t v256 = uint32_t(w56);
    const uint32_t v257 = uint32_t(w56 >> 32);
    // native wide event 57, coupled low/high
    const uint64_t w57 = uint64_t(v221) * uint64_t(v225);
    const uint32_t v258 = uint32_t(w57);
    const uint32_t v259 = uint32_t(w57 >> 32);
    // native wide event 58, coupled low/high
    const uint64_t w58 = uint64_t(v222) * uint64_t(v224);
    const uint32_t v260 = uint32_t(w58);
    const uint32_t v261 = uint32_t(w58 >> 32);
    const uint32_t v264 = v256 ^ v258 ^ v260;
    const uint32_t v267 = v257 ^ v259 ^ v261;
    // native wide event 59, coupled low/high
    const uint64_t w59 = uint64_t(v223) * uint64_t(v227);
    const uint32_t v262 = uint32_t(w59);
    const uint32_t v263 = uint32_t(w59 >> 32);
    const uint32_t v266 = (v262 ^ v264) & 0x44444444u;
    const uint32_t v284 = v238 ^ v252 ^ v266;
    const uint32_t v269 = (v263 ^ v267) & 0x44444444u;
    const uint32_t v286 = v241 ^ v255 ^ v269;
    // native wide event 60, coupled low/high
    const uint64_t w60 = uint64_t(v220) * uint64_t(v227);
    const uint32_t v270 = uint32_t(w60);
    const uint32_t v271 = uint32_t(w60 >> 32);
    // native wide event 61, coupled low/high
    const uint64_t w61 = uint64_t(v221) * uint64_t(v226);
    const uint32_t v272 = uint32_t(w61);
    const uint32_t v273 = uint32_t(w61 >> 32);
    // native wide event 62, coupled low/high
    const uint64_t w62 = uint64_t(v222) * uint64_t(v225);
    const uint32_t v274 = uint32_t(w62);
    const uint32_t v275 = uint32_t(w62 >> 32);
    const uint32_t v278 = v270 ^ v272 ^ v274;
    const uint32_t v281 = v271 ^ v273 ^ v275;
    // native wide event 63, coupled low/high
    const uint64_t w63 = uint64_t(v223) * uint64_t(v224);
    const uint32_t v276 = uint32_t(w63);
    const uint32_t v277 = uint32_t(w63 >> 32);
    const uint32_t v280 = (v276 ^ v278) & 0x88888888u;
    const uint32_t v283 = (v277 ^ v281) & 0x88888888u;
    const uint32_t v285 = v280 ^ v284;
    const uint32_t v287 = v283 ^ v286;
    const uint32_t v288 = v3 & 0x11111111u;
    const uint32_t v292 = v8 & 0x11111111u;
    // native wide event 64, coupled low/high
    const uint64_t w64 = uint64_t(v288) * uint64_t(v292);
    const uint32_t v296 = uint32_t(w64);
    const uint32_t v297 = uint32_t(w64 >> 32);
    const uint32_t v289 = v3 & 0x22222222u;
    const uint32_t v295 = v8 & 0x88888888u;
    // native wide event 65, coupled low/high
    const uint64_t w65 = uint64_t(v289) * uint64_t(v295);
    const uint32_t v298 = uint32_t(w65);
    const uint32_t v299 = uint32_t(w65 >> 32);
    const uint32_t v290 = v3 & 0x44444444u;
    const uint32_t v294 = v8 & 0x44444444u;
    // native wide event 66, coupled low/high
    const uint64_t w66 = uint64_t(v290) * uint64_t(v294);
    const uint32_t v300 = uint32_t(w66);
    const uint32_t v301 = uint32_t(w66 >> 32);
    const uint32_t v304 = v296 ^ v298 ^ v300;
    const uint32_t v307 = v297 ^ v299 ^ v301;
    const uint32_t v291 = v3 & 0x88888888u;
    const uint32_t v293 = v8 & 0x22222222u;
    // native wide event 67, coupled low/high
    const uint64_t w67 = uint64_t(v291) * uint64_t(v293);
    const uint32_t v302 = uint32_t(w67);
    const uint32_t v303 = uint32_t(w67 >> 32);
    const uint32_t v306 = (v302 ^ v304) & 0x11111111u;
    const uint32_t v309 = (v303 ^ v307) & 0x11111111u;
    // native wide event 68, coupled low/high
    const uint64_t w68 = uint64_t(v288) * uint64_t(v293);
    const uint32_t v310 = uint32_t(w68);
    const uint32_t v311 = uint32_t(w68 >> 32);
    // native wide event 69, coupled low/high
    const uint64_t w69 = uint64_t(v289) * uint64_t(v292);
    const uint32_t v312 = uint32_t(w69);
    const uint32_t v313 = uint32_t(w69 >> 32);
    // native wide event 70, coupled low/high
    const uint64_t w70 = uint64_t(v290) * uint64_t(v295);
    const uint32_t v314 = uint32_t(w70);
    const uint32_t v315 = uint32_t(w70 >> 32);
    const uint32_t v318 = v310 ^ v312 ^ v314;
    const uint32_t v321 = v311 ^ v313 ^ v315;
    // native wide event 71, coupled low/high
    const uint64_t w71 = uint64_t(v291) * uint64_t(v294);
    const uint32_t v316 = uint32_t(w71);
    const uint32_t v317 = uint32_t(w71 >> 32);
    const uint32_t v320 = (v316 ^ v318) & 0x22222222u;
    const uint32_t v323 = (v317 ^ v321) & 0x22222222u;
    // native wide event 72, coupled low/high
    const uint64_t w72 = uint64_t(v288) * uint64_t(v294);
    const uint32_t v324 = uint32_t(w72);
    const uint32_t v325 = uint32_t(w72 >> 32);
    // native wide event 73, coupled low/high
    const uint64_t w73 = uint64_t(v289) * uint64_t(v293);
    const uint32_t v326 = uint32_t(w73);
    const uint32_t v327 = uint32_t(w73 >> 32);
    // native wide event 74, coupled low/high
    const uint64_t w74 = uint64_t(v290) * uint64_t(v292);
    const uint32_t v328 = uint32_t(w74);
    const uint32_t v329 = uint32_t(w74 >> 32);
    const uint32_t v332 = v324 ^ v326 ^ v328;
    const uint32_t v335 = v325 ^ v327 ^ v329;
    // native wide event 75, coupled low/high
    const uint64_t w75 = uint64_t(v291) * uint64_t(v295);
    const uint32_t v330 = uint32_t(w75);
    const uint32_t v331 = uint32_t(w75 >> 32);
    const uint32_t v334 = (v330 ^ v332) & 0x44444444u;
    const uint32_t v352 = v306 ^ v320 ^ v334;
    const uint32_t v337 = (v331 ^ v335) & 0x44444444u;
    const uint32_t v354 = v309 ^ v323 ^ v337;
    // native wide event 76, coupled low/high
    const uint64_t w76 = uint64_t(v288) * uint64_t(v295);
    const uint32_t v338 = uint32_t(w76);
    const uint32_t v339 = uint32_t(w76 >> 32);
    // native wide event 77, coupled low/high
    const uint64_t w77 = uint64_t(v289) * uint64_t(v294);
    const uint32_t v340 = uint32_t(w77);
    const uint32_t v341 = uint32_t(w77 >> 32);
    // native wide event 78, coupled low/high
    const uint64_t w78 = uint64_t(v290) * uint64_t(v293);
    const uint32_t v342 = uint32_t(w78);
    const uint32_t v343 = uint32_t(w78 >> 32);
    const uint32_t v346 = v338 ^ v340 ^ v342;
    const uint32_t v349 = v339 ^ v341 ^ v343;
    // native wide event 79, coupled low/high
    const uint64_t w79 = uint64_t(v291) * uint64_t(v292);
    const uint32_t v344 = uint32_t(w79);
    const uint32_t v345 = uint32_t(w79 >> 32);
    const uint32_t v348 = (v344 ^ v346) & 0x88888888u;
    const uint32_t v351 = (v345 ^ v349) & 0x88888888u;
    const uint32_t v353 = v348 ^ v352;
    const uint32_t v355 = v351 ^ v354;
    const uint32_t v358 = (v2 ^ v3) & 0x11111111u;
    const uint32_t v362 = (v7 ^ v8) & 0x11111111u;
    // native wide event 80, coupled low/high
    const uint64_t w80 = uint64_t(v358) * uint64_t(v362);
    const uint32_t v366 = uint32_t(w80);
    const uint32_t v367 = uint32_t(w80 >> 32);
    const uint32_t v359 = (v2 ^ v3) & 0x22222222u;
    const uint32_t v365 = (v7 ^ v8) & 0x88888888u;
    // native wide event 81, coupled low/high
    const uint64_t w81 = uint64_t(v359) * uint64_t(v365);
    const uint32_t v368 = uint32_t(w81);
    const uint32_t v369 = uint32_t(w81 >> 32);
    const uint32_t v360 = (v2 ^ v3) & 0x44444444u;
    const uint32_t v364 = (v7 ^ v8) & 0x44444444u;
    // native wide event 82, coupled low/high
    const uint64_t w82 = uint64_t(v360) * uint64_t(v364);
    const uint32_t v370 = uint32_t(w82);
    const uint32_t v371 = uint32_t(w82 >> 32);
    const uint32_t v374 = v366 ^ v368 ^ v370;
    const uint32_t v377 = v367 ^ v369 ^ v371;
    const uint32_t v361 = (v2 ^ v3) & 0x88888888u;
    const uint32_t v363 = (v7 ^ v8) & 0x22222222u;
    // native wide event 83, coupled low/high
    const uint64_t w83 = uint64_t(v361) * uint64_t(v363);
    const uint32_t v372 = uint32_t(w83);
    const uint32_t v373 = uint32_t(w83 >> 32);
    const uint32_t v376 = (v372 ^ v374) & 0x11111111u;
    const uint32_t v379 = (v373 ^ v377) & 0x11111111u;
    // native wide event 84, coupled low/high
    const uint64_t w84 = uint64_t(v358) * uint64_t(v363);
    const uint32_t v380 = uint32_t(w84);
    const uint32_t v381 = uint32_t(w84 >> 32);
    // native wide event 85, coupled low/high
    const uint64_t w85 = uint64_t(v359) * uint64_t(v362);
    const uint32_t v382 = uint32_t(w85);
    const uint32_t v383 = uint32_t(w85 >> 32);
    // native wide event 86, coupled low/high
    const uint64_t w86 = uint64_t(v360) * uint64_t(v365);
    const uint32_t v384 = uint32_t(w86);
    const uint32_t v385 = uint32_t(w86 >> 32);
    const uint32_t v388 = v380 ^ v382 ^ v384;
    const uint32_t v391 = v381 ^ v383 ^ v385;
    // native wide event 87, coupled low/high
    const uint64_t w87 = uint64_t(v361) * uint64_t(v364);
    const uint32_t v386 = uint32_t(w87);
    const uint32_t v387 = uint32_t(w87 >> 32);
    const uint32_t v390 = (v386 ^ v388) & 0x22222222u;
    const uint32_t v393 = (v387 ^ v391) & 0x22222222u;
    // native wide event 88, coupled low/high
    const uint64_t w88 = uint64_t(v358) * uint64_t(v364);
    const uint32_t v394 = uint32_t(w88);
    const uint32_t v395 = uint32_t(w88 >> 32);
    // native wide event 89, coupled low/high
    const uint64_t w89 = uint64_t(v359) * uint64_t(v363);
    const uint32_t v396 = uint32_t(w89);
    const uint32_t v397 = uint32_t(w89 >> 32);
    // native wide event 90, coupled low/high
    const uint64_t w90 = uint64_t(v360) * uint64_t(v362);
    const uint32_t v398 = uint32_t(w90);
    const uint32_t v399 = uint32_t(w90 >> 32);
    const uint32_t v402 = v394 ^ v396 ^ v398;
    const uint32_t v405 = v395 ^ v397 ^ v399;
    // native wide event 91, coupled low/high
    const uint64_t w91 = uint64_t(v361) * uint64_t(v365);
    const uint32_t v400 = uint32_t(w91);
    const uint32_t v401 = uint32_t(w91 >> 32);
    const uint32_t v404 = (v400 ^ v402) & 0x44444444u;
    const uint32_t v422 = v376 ^ v390 ^ v404;
    const uint32_t v407 = (v401 ^ v405) & 0x44444444u;
    const uint32_t v424 = v379 ^ v393 ^ v407;
    // native wide event 92, coupled low/high
    const uint64_t w92 = uint64_t(v358) * uint64_t(v365);
    const uint32_t v408 = uint32_t(w92);
    const uint32_t v409 = uint32_t(w92 >> 32);
    // native wide event 93, coupled low/high
    const uint64_t w93 = uint64_t(v359) * uint64_t(v364);
    const uint32_t v410 = uint32_t(w93);
    const uint32_t v411 = uint32_t(w93 >> 32);
    // native wide event 94, coupled low/high
    const uint64_t w94 = uint64_t(v360) * uint64_t(v363);
    const uint32_t v412 = uint32_t(w94);
    const uint32_t v413 = uint32_t(w94 >> 32);
    const uint32_t v416 = v408 ^ v410 ^ v412;
    const uint32_t v419 = v409 ^ v411 ^ v413;
    // native wide event 95, coupled low/high
    const uint64_t w95 = uint64_t(v361) * uint64_t(v362);
    const uint32_t v414 = uint32_t(w95);
    const uint32_t v415 = uint32_t(w95 >> 32);
    const uint32_t v418 = (v414 ^ v416) & 0x88888888u;
    const uint32_t v421 = (v415 ^ v419) & 0x88888888u;
    const uint32_t v423 = v418 ^ v422;
    const uint32_t v425 = v421 ^ v424;
    const uint32_t v426 = v285 ^ v353 ^ v423;
    const uint32_t v427 = v287 ^ v355 ^ v425;
    const uint32_t v428 = v287 ^ v426;
    const uint32_t v429 = v353 ^ v427;
    const uint32_t v434 = (v0 ^ v2) & 0x11111111u;
    const uint32_t v438 = (v5 ^ v7) & 0x11111111u;
    // native wide event 96, coupled low/high
    const uint64_t w96 = uint64_t(v434) * uint64_t(v438);
    const uint32_t v442 = uint32_t(w96);
    const uint32_t v443 = uint32_t(w96 >> 32);
    const uint32_t v435 = (v0 ^ v2) & 0x22222222u;
    const uint32_t v441 = (v5 ^ v7) & 0x88888888u;
    // native wide event 97, coupled low/high
    const uint64_t w97 = uint64_t(v435) * uint64_t(v441);
    const uint32_t v444 = uint32_t(w97);
    const uint32_t v445 = uint32_t(w97 >> 32);
    const uint32_t v436 = (v0 ^ v2) & 0x44444444u;
    const uint32_t v440 = (v5 ^ v7) & 0x44444444u;
    // native wide event 98, coupled low/high
    const uint64_t w98 = uint64_t(v436) * uint64_t(v440);
    const uint32_t v446 = uint32_t(w98);
    const uint32_t v447 = uint32_t(w98 >> 32);
    const uint32_t v450 = v442 ^ v444 ^ v446;
    const uint32_t v453 = v443 ^ v445 ^ v447;
    const uint32_t v437 = (v0 ^ v2) & 0x88888888u;
    const uint32_t v439 = (v5 ^ v7) & 0x22222222u;
    // native wide event 99, coupled low/high
    const uint64_t w99 = uint64_t(v437) * uint64_t(v439);
    const uint32_t v448 = uint32_t(w99);
    const uint32_t v449 = uint32_t(w99 >> 32);
    const uint32_t v452 = (v448 ^ v450) & 0x11111111u;
    const uint32_t v455 = (v449 ^ v453) & 0x11111111u;
    // native wide event 100, coupled low/high
    const uint64_t w100 = uint64_t(v434) * uint64_t(v439);
    const uint32_t v456 = uint32_t(w100);
    const uint32_t v457 = uint32_t(w100 >> 32);
    // native wide event 101, coupled low/high
    const uint64_t w101 = uint64_t(v435) * uint64_t(v438);
    const uint32_t v458 = uint32_t(w101);
    const uint32_t v459 = uint32_t(w101 >> 32);
    // native wide event 102, coupled low/high
    const uint64_t w102 = uint64_t(v436) * uint64_t(v441);
    const uint32_t v460 = uint32_t(w102);
    const uint32_t v461 = uint32_t(w102 >> 32);
    const uint32_t v464 = v456 ^ v458 ^ v460;
    const uint32_t v467 = v457 ^ v459 ^ v461;
    // native wide event 103, coupled low/high
    const uint64_t w103 = uint64_t(v437) * uint64_t(v440);
    const uint32_t v462 = uint32_t(w103);
    const uint32_t v463 = uint32_t(w103 >> 32);
    const uint32_t v466 = (v462 ^ v464) & 0x22222222u;
    const uint32_t v469 = (v463 ^ v467) & 0x22222222u;
    // native wide event 104, coupled low/high
    const uint64_t w104 = uint64_t(v434) * uint64_t(v440);
    const uint32_t v470 = uint32_t(w104);
    const uint32_t v471 = uint32_t(w104 >> 32);
    // native wide event 105, coupled low/high
    const uint64_t w105 = uint64_t(v435) * uint64_t(v439);
    const uint32_t v472 = uint32_t(w105);
    const uint32_t v473 = uint32_t(w105 >> 32);
    // native wide event 106, coupled low/high
    const uint64_t w106 = uint64_t(v436) * uint64_t(v438);
    const uint32_t v474 = uint32_t(w106);
    const uint32_t v475 = uint32_t(w106 >> 32);
    const uint32_t v478 = v470 ^ v472 ^ v474;
    const uint32_t v481 = v471 ^ v473 ^ v475;
    // native wide event 107, coupled low/high
    const uint64_t w107 = uint64_t(v437) * uint64_t(v441);
    const uint32_t v476 = uint32_t(w107);
    const uint32_t v477 = uint32_t(w107 >> 32);
    const uint32_t v480 = (v476 ^ v478) & 0x44444444u;
    const uint32_t v498 = v452 ^ v466 ^ v480;
    const uint32_t v483 = (v477 ^ v481) & 0x44444444u;
    const uint32_t v500 = v455 ^ v469 ^ v483;
    // native wide event 108, coupled low/high
    const uint64_t w108 = uint64_t(v434) * uint64_t(v441);
    const uint32_t v484 = uint32_t(w108);
    const uint32_t v485 = uint32_t(w108 >> 32);
    // native wide event 109, coupled low/high
    const uint64_t w109 = uint64_t(v435) * uint64_t(v440);
    const uint32_t v486 = uint32_t(w109);
    const uint32_t v487 = uint32_t(w109 >> 32);
    // native wide event 110, coupled low/high
    const uint64_t w110 = uint64_t(v436) * uint64_t(v439);
    const uint32_t v488 = uint32_t(w110);
    const uint32_t v489 = uint32_t(w110 >> 32);
    const uint32_t v492 = v484 ^ v486 ^ v488;
    const uint32_t v495 = v485 ^ v487 ^ v489;
    // native wide event 111, coupled low/high
    const uint64_t w111 = uint64_t(v437) * uint64_t(v438);
    const uint32_t v490 = uint32_t(w111);
    const uint32_t v491 = uint32_t(w111 >> 32);
    const uint32_t v494 = (v490 ^ v492) & 0x88888888u;
    const uint32_t v497 = (v491 ^ v495) & 0x88888888u;
    const uint32_t v499 = v494 ^ v498;
    const uint32_t v501 = v497 ^ v500;
    const uint32_t v644 = v75 ^ v285 ^ v499;
    const uint32_t v502 = (v1 ^ v3) & 0x11111111u;
    const uint32_t v506 = (v6 ^ v8) & 0x11111111u;
    // native wide event 112, coupled low/high
    const uint64_t w112 = uint64_t(v502) * uint64_t(v506);
    const uint32_t v510 = uint32_t(w112);
    const uint32_t v511 = uint32_t(w112 >> 32);
    const uint32_t v503 = (v1 ^ v3) & 0x22222222u;
    const uint32_t v509 = (v6 ^ v8) & 0x88888888u;
    // native wide event 113, coupled low/high
    const uint64_t w113 = uint64_t(v503) * uint64_t(v509);
    const uint32_t v512 = uint32_t(w113);
    const uint32_t v513 = uint32_t(w113 >> 32);
    const uint32_t v504 = (v1 ^ v3) & 0x44444444u;
    const uint32_t v508 = (v6 ^ v8) & 0x44444444u;
    // native wide event 114, coupled low/high
    const uint64_t w114 = uint64_t(v504) * uint64_t(v508);
    const uint32_t v514 = uint32_t(w114);
    const uint32_t v515 = uint32_t(w114 >> 32);
    const uint32_t v518 = v510 ^ v512 ^ v514;
    const uint32_t v521 = v511 ^ v513 ^ v515;
    const uint32_t v505 = (v1 ^ v3) & 0x88888888u;
    const uint32_t v507 = (v6 ^ v8) & 0x22222222u;
    // native wide event 115, coupled low/high
    const uint64_t w115 = uint64_t(v505) * uint64_t(v507);
    const uint32_t v516 = uint32_t(w115);
    const uint32_t v517 = uint32_t(w115 >> 32);
    const uint32_t v520 = (v516 ^ v518) & 0x11111111u;
    const uint32_t v523 = (v517 ^ v521) & 0x11111111u;
    // native wide event 116, coupled low/high
    const uint64_t w116 = uint64_t(v502) * uint64_t(v507);
    const uint32_t v524 = uint32_t(w116);
    const uint32_t v525 = uint32_t(w116 >> 32);
    // native wide event 117, coupled low/high
    const uint64_t w117 = uint64_t(v503) * uint64_t(v506);
    const uint32_t v526 = uint32_t(w117);
    const uint32_t v527 = uint32_t(w117 >> 32);
    // native wide event 118, coupled low/high
    const uint64_t w118 = uint64_t(v504) * uint64_t(v509);
    const uint32_t v528 = uint32_t(w118);
    const uint32_t v529 = uint32_t(w118 >> 32);
    const uint32_t v532 = v524 ^ v526 ^ v528;
    const uint32_t v535 = v525 ^ v527 ^ v529;
    // native wide event 119, coupled low/high
    const uint64_t w119 = uint64_t(v505) * uint64_t(v508);
    const uint32_t v530 = uint32_t(w119);
    const uint32_t v531 = uint32_t(w119 >> 32);
    const uint32_t v534 = (v530 ^ v532) & 0x22222222u;
    const uint32_t v537 = (v531 ^ v535) & 0x22222222u;
    // native wide event 120, coupled low/high
    const uint64_t w120 = uint64_t(v502) * uint64_t(v508);
    const uint32_t v538 = uint32_t(w120);
    const uint32_t v539 = uint32_t(w120 >> 32);
    // native wide event 121, coupled low/high
    const uint64_t w121 = uint64_t(v503) * uint64_t(v507);
    const uint32_t v540 = uint32_t(w121);
    const uint32_t v541 = uint32_t(w121 >> 32);
    // native wide event 122, coupled low/high
    const uint64_t w122 = uint64_t(v504) * uint64_t(v506);
    const uint32_t v542 = uint32_t(w122);
    const uint32_t v543 = uint32_t(w122 >> 32);
    const uint32_t v546 = v538 ^ v540 ^ v542;
    const uint32_t v549 = v539 ^ v541 ^ v543;
    // native wide event 123, coupled low/high
    const uint64_t w123 = uint64_t(v505) * uint64_t(v509);
    const uint32_t v544 = uint32_t(w123);
    const uint32_t v545 = uint32_t(w123 >> 32);
    const uint32_t v548 = (v544 ^ v546) & 0x44444444u;
    const uint32_t v566 = v520 ^ v534 ^ v548;
    const uint32_t v551 = (v545 ^ v549) & 0x44444444u;
    const uint32_t v568 = v523 ^ v537 ^ v551;
    // native wide event 124, coupled low/high
    const uint64_t w124 = uint64_t(v502) * uint64_t(v509);
    const uint32_t v552 = uint32_t(w124);
    const uint32_t v553 = uint32_t(w124 >> 32);
    // native wide event 125, coupled low/high
    const uint64_t w125 = uint64_t(v503) * uint64_t(v508);
    const uint32_t v554 = uint32_t(w125);
    const uint32_t v555 = uint32_t(w125 >> 32);
    // native wide event 126, coupled low/high
    const uint64_t w126 = uint64_t(v504) * uint64_t(v507);
    const uint32_t v556 = uint32_t(w126);
    const uint32_t v557 = uint32_t(w126 >> 32);
    const uint32_t v560 = v552 ^ v554 ^ v556;
    const uint32_t v563 = v553 ^ v555 ^ v557;
    // native wide event 127, coupled low/high
    const uint64_t w127 = uint64_t(v505) * uint64_t(v506);
    const uint32_t v558 = uint32_t(w127);
    const uint32_t v559 = uint32_t(w127 >> 32);
    const uint32_t v562 = (v558 ^ v560) & 0x88888888u;
    const uint32_t v565 = (v559 ^ v563) & 0x88888888u;
    const uint32_t v567 = v562 ^ v566;
    const uint32_t v569 = v565 ^ v568;
    const uint32_t v430 = v0 ^ v2;
    const uint32_t v431 = v1 ^ v3;
    const uint32_t v572 = (v430 ^ v431) & 0x11111111u;
    const uint32_t v432 = v5 ^ v7;
    const uint32_t v433 = v6 ^ v8;
    const uint32_t v576 = (v432 ^ v433) & 0x11111111u;
    // native wide event 128, coupled low/high
    const uint64_t w128 = uint64_t(v572) * uint64_t(v576);
    const uint32_t v580 = uint32_t(w128);
    const uint32_t v581 = uint32_t(w128 >> 32);
    const uint32_t v573 = (v430 ^ v431) & 0x22222222u;
    const uint32_t v579 = (v432 ^ v433) & 0x88888888u;
    // native wide event 129, coupled low/high
    const uint64_t w129 = uint64_t(v573) * uint64_t(v579);
    const uint32_t v582 = uint32_t(w129);
    const uint32_t v583 = uint32_t(w129 >> 32);
    const uint32_t v574 = (v430 ^ v431) & 0x44444444u;
    const uint32_t v578 = (v432 ^ v433) & 0x44444444u;
    // native wide event 130, coupled low/high
    const uint64_t w130 = uint64_t(v574) * uint64_t(v578);
    const uint32_t v584 = uint32_t(w130);
    const uint32_t v585 = uint32_t(w130 >> 32);
    const uint32_t v588 = v580 ^ v582 ^ v584;
    const uint32_t v591 = v581 ^ v583 ^ v585;
    const uint32_t v575 = (v430 ^ v431) & 0x88888888u;
    const uint32_t v577 = (v432 ^ v433) & 0x22222222u;
    // native wide event 131, coupled low/high
    const uint64_t w131 = uint64_t(v575) * uint64_t(v577);
    const uint32_t v586 = uint32_t(w131);
    const uint32_t v587 = uint32_t(w131 >> 32);
    const uint32_t v590 = (v586 ^ v588) & 0x11111111u;
    const uint32_t v593 = (v587 ^ v591) & 0x11111111u;
    // native wide event 132, coupled low/high
    const uint64_t w132 = uint64_t(v572) * uint64_t(v577);
    const uint32_t v594 = uint32_t(w132);
    const uint32_t v595 = uint32_t(w132 >> 32);
    // native wide event 133, coupled low/high
    const uint64_t w133 = uint64_t(v573) * uint64_t(v576);
    const uint32_t v596 = uint32_t(w133);
    const uint32_t v597 = uint32_t(w133 >> 32);
    // native wide event 134, coupled low/high
    const uint64_t w134 = uint64_t(v574) * uint64_t(v579);
    const uint32_t v598 = uint32_t(w134);
    const uint32_t v599 = uint32_t(w134 >> 32);
    const uint32_t v602 = v594 ^ v596 ^ v598;
    const uint32_t v605 = v595 ^ v597 ^ v599;
    // native wide event 135, coupled low/high
    const uint64_t w135 = uint64_t(v575) * uint64_t(v578);
    const uint32_t v600 = uint32_t(w135);
    const uint32_t v601 = uint32_t(w135 >> 32);
    const uint32_t v604 = (v600 ^ v602) & 0x22222222u;
    const uint32_t v607 = (v601 ^ v605) & 0x22222222u;
    // native wide event 136, coupled low/high
    const uint64_t w136 = uint64_t(v572) * uint64_t(v578);
    const uint32_t v608 = uint32_t(w136);
    const uint32_t v609 = uint32_t(w136 >> 32);
    // native wide event 137, coupled low/high
    const uint64_t w137 = uint64_t(v573) * uint64_t(v577);
    const uint32_t v610 = uint32_t(w137);
    const uint32_t v611 = uint32_t(w137 >> 32);
    // native wide event 138, coupled low/high
    const uint64_t w138 = uint64_t(v574) * uint64_t(v576);
    const uint32_t v612 = uint32_t(w138);
    const uint32_t v613 = uint32_t(w138 >> 32);
    const uint32_t v616 = v608 ^ v610 ^ v612;
    const uint32_t v619 = v609 ^ v611 ^ v613;
    // native wide event 139, coupled low/high
    const uint64_t w139 = uint64_t(v575) * uint64_t(v579);
    const uint32_t v614 = uint32_t(w139);
    const uint32_t v615 = uint32_t(w139 >> 32);
    const uint32_t v618 = (v614 ^ v616) & 0x44444444u;
    const uint32_t v636 = v590 ^ v604 ^ v618;
    const uint32_t v621 = (v615 ^ v619) & 0x44444444u;
    const uint32_t v638 = v593 ^ v607 ^ v621;
    // native wide event 140, coupled low/high
    const uint64_t w140 = uint64_t(v572) * uint64_t(v579);
    const uint32_t v622 = uint32_t(w140);
    const uint32_t v623 = uint32_t(w140 >> 32);
    // native wide event 141, coupled low/high
    const uint64_t w141 = uint64_t(v573) * uint64_t(v578);
    const uint32_t v624 = uint32_t(w141);
    const uint32_t v625 = uint32_t(w141 >> 32);
    // native wide event 142, coupled low/high
    const uint64_t w142 = uint64_t(v574) * uint64_t(v577);
    const uint32_t v626 = uint32_t(w142);
    const uint32_t v627 = uint32_t(w142 >> 32);
    const uint32_t v630 = v622 ^ v624 ^ v626;
    const uint32_t v633 = v623 ^ v625 ^ v627;
    // native wide event 143, coupled low/high
    const uint64_t w143 = uint64_t(v575) * uint64_t(v576);
    const uint32_t v628 = uint32_t(w143);
    const uint32_t v629 = uint32_t(w143 >> 32);
    const uint32_t v632 = (v628 ^ v630) & 0x88888888u;
    const uint32_t v635 = (v629 ^ v633) & 0x88888888u;
    const uint32_t v637 = v632 ^ v636;
    const uint32_t v639 = v635 ^ v638;
    const uint32_t v640 = v499 ^ v567 ^ v637;
    const uint32_t v641 = v501 ^ v569 ^ v639;
    const uint32_t v642 = v501 ^ v640;
    const uint32_t v643 = v567 ^ v641;
    const uint32_t v645 = v218 ^ v428 ^ v642;
    const uint32_t v646 = v219 ^ v429 ^ v643;
    const uint32_t v648 = v219 ^ v644;
    const uint32_t v647 = v145 ^ v355 ^ v569;
    const uint32_t v649 = v145 ^ v645;
    const uint32_t v652 = v4 << 31;
    const uint32_t v653 = 0u - (v652 >> 31);
    const uint32_t v654 = v9 << 31;
    const uint32_t v655 = 0u - (v654 >> 31);
    const uint32_t v657 = v5 & v653;
    const uint32_t v658 = v657 ^ (v0 & v655);
    const uint32_t v660 = v6 & v653;
    const uint32_t v661 = v660 ^ (v1 & v655);
    const uint32_t v663 = v7 & v653;
    const uint32_t v664 = v663 ^ (v2 & v655);
    const uint32_t v666 = v8 & v653;
    const uint32_t v667 = v666 ^ (v3 & v655);
    const uint32_t v669 = v4 << 30;
    const uint32_t v670 = 0u - (v669 >> 31);
    const uint32_t v704 = v4 << 29;
    const uint32_t v705 = 0u - (v704 >> 31);
    const uint32_t v671 = v9 << 30;
    const uint32_t v672 = 0u - (v671 >> 31);
    const uint32_t v674 = v5 & v670;
    const uint32_t v675 = v674 ^ (v0 & v672);
    const uint32_t v709 = v5 & v705;
    const uint32_t v676 = v675 << 1;
    const uint32_t v678 = v675 >> 31;
    const uint32_t v681 = v6 & v670;
    const uint32_t v682 = v681 ^ (v1 & v672);
    const uint32_t v716 = v6 & v705;
    const uint32_t v683 = v682 << 1;
    const uint32_t v684 = v661 ^ v678 ^ v683;
    const uint32_t v685 = v682 >> 31;
    const uint32_t v688 = v7 & v670;
    const uint32_t v689 = v688 ^ (v2 & v672);
    const uint32_t v723 = v7 & v705;
    const uint32_t v690 = v689 << 1;
    const uint32_t v691 = v664 ^ v685 ^ v690;
    const uint32_t v692 = v689 >> 31;
    const uint32_t v695 = v8 & v670;
    const uint32_t v696 = v695 ^ (v3 & v672);
    const uint32_t v701 = v9 & v670;
    const uint32_t v702 = v701 << 1;
    const uint32_t v730 = v8 & v705;
    const uint32_t v736 = v9 & v705;
    const uint32_t v737 = v736 << 2;
    const uint32_t v697 = v696 << 1;
    const uint32_t v698 = v667 ^ v692 ^ v697;
    const uint32_t v699 = v696 >> 31;
    const uint32_t v700 = v699 ^ (v9 & v653);
    const uint32_t v706 = v9 << 29;
    const uint32_t v707 = 0u - (v706 >> 31);
    const uint32_t v710 = v709 ^ (v0 & v707);
    const uint32_t v717 = v716 ^ (v1 & v707);
    const uint32_t v724 = v723 ^ (v2 & v707);
    const uint32_t v731 = v730 ^ (v3 & v707);
    const uint32_t v711 = v710 << 2;
    const uint32_t v712 = v658 ^ v676 ^ v711;
    const uint32_t v739 = v285 ^ v646 ^ v712;
    const uint32_t v713 = v710 >> 30;
    const uint32_t v718 = v717 << 2;
    const uint32_t v719 = v684 ^ v713 ^ v718;
    const uint32_t v740 = v428 ^ v647 ^ v719;
    const uint32_t v720 = v717 >> 30;
    const uint32_t v725 = v724 << 2;
    const uint32_t v726 = v691 ^ v720 ^ v725;
    const uint32_t v741 = v429 ^ v726;
    const uint32_t v727 = v724 >> 30;
    const uint32_t v732 = v731 << 2;
    const uint32_t v733 = v698 ^ v727 ^ v732;
    const uint32_t v742 = v355 ^ v733;
    const uint32_t v734 = v731 >> 30;
    const uint32_t v735 = v700 ^ v702 ^ v734;
    const uint32_t v738 = v735 ^ v737;
    const uint32_t v743 = (v739 >> 3) | (v740 << 29);
    const uint32_t v744 = (v740 >> 3) | (v741 << 29);
    const uint32_t v745 = (v741 >> 3) | (v742 << 29);
    const uint32_t v746 = (v742 >> 3) | (v738 << 29);
    const uint32_t v747 = v738 >> 3;
    const uint32_t v748 = v747 & 0x3u;
    const uint32_t v749 = (v743 >> 1) | (v744 << 31);
    const uint32_t v750 = (v743 >> 3) | (v744 << 29);
    const uint32_t v751 = v743 ^ v749 ^ v750;
    const uint32_t v752 = (v744 >> 1) | (v745 << 31);
    const uint32_t v753 = (v744 >> 3) | (v745 << 29);
    const uint32_t v754 = v744 ^ v752 ^ v753;
    const uint32_t v755 = (v745 >> 1) | (v746 << 31);
    const uint32_t v756 = (v745 >> 3) | (v746 << 29);
    const uint32_t v757 = v745 ^ v755 ^ v756;
    const uint32_t v758 = (v746 >> 1) | (v748 << 31);
    const uint32_t v759 = (v746 >> 3) | (v748 << 29);
    const uint32_t v760 = v746 ^ v758 ^ v759;
    const uint32_t v761 = v748 >> 1;
    const uint32_t v762 = v748 ^ v761;
    const uint32_t v763 = (v751 >> 1) | (v754 << 31);
    const uint32_t v764 = (v751 >> 9) | (v754 << 23);
    const uint32_t v768 = v743 ^ v763 ^ v764;
    const uint32_t v765 = (v751 >> 25) | (v754 << 7);
    const uint32_t v766 = (v754 >> 25) | (v757 << 7);
    const uint32_t v767 = (v760 >> 25) | (v762 << 7);
    const uint32_t v769 = v765 ^ v766 ^ v767;
    const uint32_t v770 = v768 ^ v769;
    const uint32_t v771 = (v754 >> 1) | (v757 << 31);
    const uint32_t v774 = v744 ^ v766 ^ v771;
    const uint32_t v772 = (v754 >> 9) | (v757 << 23);
    const uint32_t v773 = (v757 >> 25) | (v760 << 7);
    const uint32_t v775 = v772 ^ v773 ^ v774;
    const uint32_t v778 = v745 ^ v767 ^ v773;
    const uint32_t v776 = (v757 >> 1) | (v760 << 31);
    const uint32_t v777 = (v757 >> 9) | (v760 << 23);
    const uint32_t v779 = v776 ^ v777 ^ v778;
    const uint32_t v780 = (v760 >> 1) | (v762 << 31);
    const uint32_t v782 = v746 ^ v767 ^ v780;
    const uint32_t v781 = (v760 >> 9) | (v762 << 23);
    const uint32_t v783 = v781 ^ v782;
    const uint32_t v784 = v762 >> 1;
    const uint32_t v785 = v748 ^ v784;
    const uint32_t v786 = v770 << 2;
    const uint32_t v787 = v770 << 3;
    const uint32_t v788 = v770 ^ v786 ^ v787;
    const uint32_t v801 = v75 ^ v788;
    const uint32_t v789 = (v775 << 2) | (v770 >> 30);
    const uint32_t v790 = (v775 << 3) | (v770 >> 29);
    const uint32_t v791 = v775 ^ v789 ^ v790;
    const uint32_t v802 = v218 ^ v791;
    const uint32_t v807 = v649 ^ v788 ^ v791;
    const uint32_t v813 = v739 ^ v788 ^ v791;
    const uint32_t v792 = (v779 << 2) | (v775 >> 30);
    const uint32_t v793 = (v779 << 3) | (v775 >> 29);
    const uint32_t v794 = v779 ^ v792 ^ v793;
    const uint32_t v803 = v648 ^ v788 ^ v794;
    const uint32_t v812 = (v775 << 28) | (v770 >> 4);
    const uint32_t v806 = v770 << 28;
    const uint32_t v795 = (v783 << 2) | (v779 >> 30);
    const uint32_t v796 = (v783 << 3) | (v779 >> 29);
    const uint32_t v797 = v783 ^ v795 ^ v796;
    const uint32_t v798 = (v785 << 2) | (v783 >> 30);
    const uint32_t v799 = (v785 << 3) | (v783 >> 29);
    const uint32_t v800 = v785 ^ v798 ^ v799;
    const uint32_t v804 = v788 << 16;
    const uint32_t v805 = v788 << 24;
    const uint32_t v808 = v797 ^ v804 ^ v805;
    const uint32_t v809 = v806 ^ v807 ^ v808;
    const uint32_t v810 = (v791 << 16) | (v788 >> 16);
    const uint32_t v814 = v794 ^ v800 ^ v810;
    const uint32_t v811 = (v791 << 24) | (v788 >> 8);
    const uint32_t v815 = v811 ^ v812 ^ v813;
    const uint32_t v817 = (v814 ^ v815) & 0x7u;
    P131 out;
    out.v[0] = v801;
    out.v[1] = v802;
    out.v[2] = v803;
    out.v[3] = v809;
    out.v[4] = v817;
    return out;
}
