use isogeny_algos::curve::*;
use isogeny_algos::field::{factor_u64, is_prime, Field, Rng, Zp2};
use isogeny_algos::genus2::{glue, ic_key, igusa_clebsch};
use isogeny_algos::kernel::velu::velu_cyclic;
use isogeny_algos::poly;
use isogeny_algos::theta::*;

type E2 = (u64, u64);

/// A point of exact order m (m | p + 1) on a supersingular curve over F_{p^2} with
/// E(F_{p^2}) = (Z/(p+1))^2.
fn point_of_order(f: &Zp2, e: &Curve<E2>, p: u64, m: u64, rng: &mut Rng) -> Pt<E2> {
    let fac = factor_u64(m);
    loop {
        let r = random_point_f(f, e, rng);
        let q = pmul(f, e, &r, ((p + 1) / m) as u128);
        if fac.iter().all(|&(l, _)| pmul(f, e, &q, (m / l) as u128) != Pt::Inf) {
            return q;
        }
    }
}

/// Basis of E[2^m].
fn basis2(f: &Zp2, e: &Curve<E2>, p: u64, m: u32, rng: &mut Rng) -> (Pt<E2>, Pt<E2>) {
    let n = 1u64 << m;
    let a = point_of_order(f, e, p, n, rng);
    let a2 = pmul(f, e, &a, (n / 2) as u128);
    loop {
        let b = point_of_order(f, e, p, n, rng);
        if pmul(f, e, &b, (n / 2) as u128) != a2 {
            return (a, b);
        }
    }
}

/// Isogeny with cyclic kernel <r> (order m) as a chain of prime-degree Velu steps; returns the
/// codomain and the images of `pts`.
fn chain_iso(f: &Zp2, e: &Curve<E2>, r: &Pt<E2>, m: u64, pts: &[Pt<E2>]) -> (Curve<E2>, Vec<Pt<E2>>) {
    let mut cur = *e;
    let mut ker = *r;
    let mut left = m;
    let mut pts = pts.to_vec();
    for (l, k) in factor_u64(m) {
        for _ in 0..k {
            let q = pmul(f, &cur, &ker, (left / l) as u128);
            let iso = velu_cyclic(f, &cur, &q, l);
            ker = iso.eval(f, &ker);
            for x in pts.iter_mut() {
                *x = iso.eval(f, x);
            }
            cur = iso.cod;
            left /= l;
        }
    }
    (cur, pts)
}

fn find_prime(base: u64) -> u64 {
    (1..).map(|c| base * c - 1).find(|&p| is_prime(p)).unwrap()
}

#[test]
fn theta_dimension_one() {
    let p = find_prime(1 << 6);
    let f = Zp2::new(p);
    let e = Curve::new(f.one(), f.zero());
    let mut rng = Rng::new(7);
    for _ in 0..5 {
        let (p4, q4) = basis2(&f, &e, p, 2, &mut rng);
        let t = theta1_structure(&f, &e, &p4, &q4).unwrap();
        assert_eq!(j_from_theta1(&f, &t.null(&f)), jinv(&f, &e));
        let s = t.s;
        let pr = |x: [E2; 2], y: [E2; 2]| f.mul(x[0], y[1]) == f.mul(x[1], y[0]);
        assert!(pr(t.point(&f, &pmul(&f, &e, &p4, 2)), [f.one(), f.neg(s)]));
        assert!(pr(t.point(&f, &pmul(&f, &e, &q4, 2)), [s, f.one()]));
        assert!(f.is_zero(t.point(&f, &p4)[1]));
        assert!(pr(t.point(&f, &q4), [f.one(), f.one()]));
    }
}

#[test]
fn theta_split_detection_and_gluing_vs_hlp() {
    let p = find_prime(3 * 5 * 7 * (1 << 5));
    let f = Zp2::new(p);
    let e0 = Curve::new(f.one(), f.zero());
    let mut rng = Rng::new(11);
    // two isogenous supersingular curves
    let r5 = point_of_order(&f, &e0, p, 5, &mut rng);
    let (e2, _) = chain_iso(&f, &e0, &r5, 5, &[]);
    let r7 = point_of_order(&f, &e0, p, 7, &mut rng);
    let (e1, _) = chain_iso(&f, &e0, &r7, 7, &[]);
    for _ in 0..12 {
        let (a, b) = basis2(&f, &e1, p, 3, &mut rng);
        let (c, d) = basis2(&f, &e2, p, 3, &mut rng);
        // product structure: a product null splits into the two j-invariants
        let th = ProductTheta {
            t1: theta1_structure(&f, &e1, &pmul(&f, &e1, &a, 2), &pmul(&f, &e1, &b, 2)).unwrap(),
            t2: theta1_structure(&f, &e2, &pmul(&f, &e2, &c, 2), &pmul(&f, &e2, &d, 2)).unwrap(),
        };
        let (j1, j2) = (jinv(&f, &e1), jinv(&f, &e2));
        let pn = th.product_point(&f, &Pt::Inf, &Pt::Inf);
        let s = split_j(&f, &pn).expect("product null splits");
        assert!(s == (j1, j2) || s == (j2, j1));
        let s = split_j(&f, &th.null(&f)).expect("glue-change null splits");
        assert!(s == (j1, j2) || s == (j2, j1));
        // gluing along 2a <-> 2c... (kernel generated by 4(a, c), 4(b, d))
        let res = chain(&f, &e1, &e2, [(a, c), (b, d)], 1, &[]).expect("gluing");
        assert!(res.split.is_none());
        let rh = rosenhain(&f, &res.nulls[0]).unwrap();
        // HLP gluing of the same 2-torsion identification
        let x = |pt: Pt<E2>| match pt {
            Pt::Aff(x, _) => x,
            Pt::Inf => panic!(),
        };
        let (a4, b4, c4, d4) = (pmul(&f, &e1, &a, 4), pmul(&f, &e1, &b, 4), pmul(&f, &e2, &c, 4), pmul(&f, &e2, &d, 4));
        let ra = [x(a4), x(b4), x(padd(&f, &e1, &a4, &b4))];
        let rb = [x(c4), x(d4), x(padd(&f, &e2, &c4, &d4))];
        let sext = glue(&f, ra, rb).unwrap();
        let roots = poly::roots(&f, &sext, &mut rng);
        assert_eq!(roots.len(), 6);
        let key_hlp = ic_key(&f, &igusa_clebsch(&f, sext[6], &[roots[0], roots[1], roots[2], roots[3], roots[4], roots[5]]));
        // Rosenhain model, moved to six finite roots by x -> 1/(x - t)
        let t = f.from_u64(12345);
        let fin = [f.zero(), f.one(), rh[0], rh[1], rh[2]].map(|r| f.inv(f.sub(r, t)));
        let key_th = ic_key(&f, &igusa_clebsch(&f, f.one(), &[fin[0], fin[1], fin[2], fin[3], fin[4], f.zero()]));
        assert_eq!(key_th, key_hlp);
    }
}

/// Kani's lemma: for phi: E0 -> E (degree d1) and gamma: E0 -> C (degree d2) with
/// d1 + d2 = 2^a, the (2^a, 2^a)-isogeny of C x E with kernel {(gamma P, phi P) : P in E0[2^a]}
/// has codomain E0 x X, X = E0 / (ker phi + ker gamma). The theta chain must split there, with
/// the j-invariants of E0 and of X computed independently by Velu.
#[test]
fn theta_kani_chain_splits_at_e0_times_x() {
    for &(a, b) in &[(8u32, 4u32), (8, 5), (10, 6), (12, 7), (16, 10)] {
        let d1 = 3u64.pow(b);
        let d2 = (1u64 << a) - d1;
        let p = find_prime((1u64 << (a + 2)) * d1 * d2);
        let f = Zp2::new(p);
        let e0 = Curve::new(f.one(), f.zero());
        let mut rng = Rng::new(a as u64 * 100 + b as u64);
        let (pp, qq) = basis2(&f, &e0, p, a + 2, &mut rng);
        let kphi = point_of_order(&f, &e0, p, d1, &mut rng);
        let kgam = point_of_order(&f, &e0, p, d2, &mut rng);
        let (e, im_phi) = chain_iso(&f, &e0, &kphi, d1, &[pp, qq, kgam]);
        let (c, im_gam) = chain_iso(&f, &e0, &kgam, d2, &[pp, qq]);
        let (x, _) = chain_iso(&f, &e, &im_phi[2], d2, &[]);
        let res = chain(&f, &c, &e, [(im_gam[0], im_phi[0]), (im_gam[1], im_phi[1])], a, &[]).expect("chain");
        assert_eq!(res.nulls.len(), a as usize);
        // intermediate codomains are Jacobians
        for nl in &res.nulls[..res.nulls.len() - 1] {
            assert!(split_j(&f, nl).is_none());
        }
        // the strategy (theta doublings) and pushing every multiple give the same codomains
        let naive = chain_opts(&f, &c, &e, [(im_gam[0], im_phi[0]), (im_gam[1], im_phi[1])], a, &[], false).expect("chain");
        assert_eq!(naive.nulls.len(), res.nulls.len());
        for (x, y) in naive.nulls.iter().zip(res.nulls.iter()) {
            assert!(proj_eq(&f, x, y));
        }
        let (j1, j2) = res.split.expect("Kani chain splits");
        let (ja, jb) = (jinv(&f, &e0), jinv(&f, &x));
        assert!((j1, j2) == (ja, jb) || (j1, j2) == (jb, ja), "a = {a}, b = {b}");
        // a kernel of the same shape but twisted by M = [[1, 2], [0, 1]] (det 1, so still
        // isotropic, and the same gluing step) does not come from a diamond: no split
        let q2 = padd(&f, &e, &im_phi[1], &pmul(&f, &e, &im_phi[0], 2));
        let res2 = chain(&f, &c, &e, [(im_gam[0], im_phi[0]), (im_gam[1], q2)], a, &[]).expect("chain");
        assert!(res2.split.is_none(), "a = {a}, b = {b}");
    }
}

/// IC key of the Rosenhain curve of a theta null (moved to six finite roots).
fn key_of_null(f: &Zp2, n: &Th<E2>) -> ((u8, Vec<E2>), [E2; 6]) {
    let rh = rosenhain(f, n).unwrap();
    let t = f.from_u64(12345);
    let fin = [f.zero(), f.one(), rh[0], rh[1], rh[2]].map(|r| f.inv(f.sub(r, t)));
    let roots = [fin[0], fin[1], fin[2], fin[3], fin[4], f.zero()];
    (ic_key(f, &igusa_clebsch(f, f.one(), &roots)), roots)
}

/// A generic theta (2,2)-step between Jacobians lands on one of the 15 Richelot neighbours of
/// the domain (Richelot computed in Mumford/curve form from the Rosenhain model).
#[test]
fn theta_step_is_a_richelot_neighbour() {
    use isogeny_algos::genus2::{matchings6, richelot};
    let (a, b) = (10u32, 6u32);
    let d1 = 3u64.pow(b);
    let d2 = (1u64 << a) - d1;
    let p = find_prime((1u64 << (a + 2)) * d1 * d2);
    let f = Zp2::new(p);
    let e0 = Curve::new(f.one(), f.zero());
    let mut rng = Rng::new(99);
    for _ in 0..3 {
        let (pp, qq) = basis2(&f, &e0, p, a + 2, &mut rng);
        let kphi = point_of_order(&f, &e0, p, d1, &mut rng);
        let kgam = point_of_order(&f, &e0, p, d2, &mut rng);
        let (e, im_phi) = chain_iso(&f, &e0, &kphi, d1, &[pp, qq]);
        let (c, im_gam) = chain_iso(&f, &e0, &kgam, d2, &[pp, qq]);
        let res = chain(&f, &c, &e, [(im_gam[0], im_phi[0]), (im_gam[1], im_phi[1])], a, &[]).unwrap();
        for s in 0..4 {
            let (_, roots) = key_of_null(&f, &res.nulls[s]);
            let (want, _) = key_of_null(&f, &res.nulls[s + 1]);
            let mut found = false;
            for ((i, j), (k, l), (m, n)) in matchings6() {
                let q = |u: usize, v: usize| poly::from_roots(&f, &[roots[u], roots[v]]);
                let g = [q(i, j), q(k, l), q(m, n)];
                let r = richelot(&f, &g);
                if f.is_zero(r.delta) {
                    continue;
                }
                let cod = r.codomain(&f);
                let cr = poly::roots(&f, &cod, &mut rng);
                if cr.len() != 6 {
                    continue;
                }
                let key = ic_key(&f, &igusa_clebsch(&f, cod[6], &[cr[0], cr[1], cr[2], cr[3], cr[4], cr[5]]));
                found |= key == want;
            }
            assert!(found, "step {s}");
        }
    }
}

/// Kani with an endomorphism of E0: y^2 = x^3 + x as the auxiliary isogeny (no smoothness needed
/// for its degree): a = 64, b = 35, p = 2^66 3^35 15 - 1 (126 bits), 2^64 - 3^35 = u^2 + v^2.
/// The chain must split with a factor of j-invariant 1728 (E0); the twisted kernel must not.
#[test]
fn theta_kani_endomorphism_126_bit() {
    use isogeny_algos::bigint::Big;
    use isogeny_algos::fp2::Fp2;
    use isogeny_algos::fpm::FpM;
    use isogeny_algos::testdata::kani_endomorphism_instance;
    let (a, b, c) = (64u32, 35u32, 15u64);
    let three_b = (0..b).fold(Big::from_u64(1), |acc, _| acc.mul(&Big::from_u64(3)));
    let p1 = Big::from_u64(1).shl((a + 2) as usize).mul(&three_b).mul(&Big::from_u64(c));
    let p = p1.sub_small(1);
    let f = Fp2::new(FpM::<2>::new(&p));
    let iota = (f.base.zero(), f.base.one());
    let (u, v) = (Big::from_u64(3132210735), Big::from_u64(2930182322));
    let mut rng = Rng::new(64);
    for _ in 0..2 {
        let inst = kani_endomorphism_instance(&f, &p1, a, b, &u, &v, iota, &mut rng);
        let res = chain(&f, &inst.e0, &inst.e, inst.k, a, &[]).expect("chain");
        let (j1, j2) = res.split.expect("splits");
        let j1728 = f.from_u64(1728);
        assert!(j1 == j1728 || j2 == j1728);
        let res2 = chain(&f, &inst.e0, &inst.e, inst.k_twisted, a, &[]).expect("chain");
        assert!(res2.split.is_none());
    }
}

/// Round-trip: factor a product theta point back to the two x-coordinates.
#[test]
fn theta_factor_point_roundtrip() {
    let p = find_prime(3 * 5 * 7 * (1 << 5));
    let f = Zp2::new(p);
    let e0 = Curve::new(f.one(), f.zero());
    let mut rng = Rng::new(123);
    let r5 = point_of_order(&f, &e0, p, 5, &mut rng);
    let e1 = chain_iso(&f, &e0, &r5, 5, &[]).0;
    let r7 = point_of_order(&f, &e0, p, 7, &mut rng);
    let e2 = chain_iso(&f, &e0, &r7, 7, &[]).0;
    let (a, b) = basis2(&f, &e1, p, 3, &mut rng);
    let (c, d) = basis2(&f, &e2, p, 3, &mut rng);
    let th = ProductTheta {
        t1: theta1_structure(&f, &e1, &pmul(&f, &e1, &a, 2), &pmul(&f, &e1, &b, 2)).unwrap(),
        t2: theta1_structure(&f, &e2, &pmul(&f, &e2, &c, 2), &pmul(&f, &e2, &d, 2)).unwrap(),
    };
    let mut checked = 0;
    for _ in 0..40 {
        let p1 = pmul(&f, &e1, &a, rng.below(243) as u128);
        let p1 = padd(&f, &e1, &p1, &pmul(&f, &e1, &b, rng.below(243) as u128));
        let p2 = pmul(&f, &e2, &c, rng.below(243) as u128);
        let p2 = padd(&f, &e2, &p2, &pmul(&f, &e2, &d, rng.below(243) as u128));
        let g = th.point(&f, &p1, &p2);
        let (x1, x2) = th.factor_point(&f, &g);
        let want = |p: &Pt<(u64, u64)>| match p {
            Pt::Aff(x, _) => Some(*x),
            Pt::Inf => None,
        };
        if let (Some(e), Some(w)) = (x1, want(&p1)) {
            assert_eq!(e, w);
            checked += 1;
        }
        if let (Some(e), Some(w)) = (x2, want(&p2)) {
            assert_eq!(e, w);
            checked += 1;
        }
    }
    assert!(checked >= 30, "only {checked}");
}
