"""Generate nibble/byte maps for D_j(a)=a+a^(2^j) in the existing polynomial basis."""
import argparse
from pathlib import Path
import random
from genpolyreduce import polynomial,reference

F=polynomial()
def square(a):
    return reference(sum(((a>>i)&1)<<(2*i) for i in range(131)),F)
def delta(a,power):
    b=a
    for _ in range(power): b=square(b)
    return a^b

def generate():
    columns=[[delta(1<<i,j) for i in range(131)] for j in range(3,11)]
    rng=random.Random(10000000000)
    for _ in range(256):
        a=rng.getrandbits(131)
        for j in range(8):
            mapped=0
            for i,c in enumerate(columns[j]):
                if (a>>i)&1: mapped^=c
            assert mapped==delta(a,j+3)
    out=['// Generated by codegen/genfusedsigma.py. Included inside eccPacked131.', '#pragma once', '#if ECC_PACKED_FUSED_SIGMA', '#if defined(__CUDACC__)']
    for mode,bits in ((1,4),(2,8),(3,3)):
        chunks=(131+bits-1)//bits;values=1<<bits
        out += [f'#if ECC_PACKED_FUSED_SIGMA == {mode}',f'static __device__ const uint4 fusedSigmaLow131[{chunks}][{values*8}] = {{']
        tables=[]
        for chunk in range(chunks):
            entries=[]
            for value in range(values):
                for j in range(8):
                    x=0
                    for bit in range(bits):
                        i=chunk*bits+bit
                        if i<131 and ((value>>bit)&1): x^=columns[j][i]
                    entries.append(x)
            tables.append(entries)
            out.append('    {')
            for i in range(0,len(entries),4):
                out.append('        '+','.join('{'+','.join(f'0x{(x>>(32*w))&0xffffffff:08x}u' for w in range(4))+'}' for x in entries[i:i+4])+',')
            out.append('    },')
        out += ['};',f'static __device__ const unsigned char fusedSigmaHigh131[{chunks}][{values*8}] = {{']
        for entries in tables:
            out += ['    {']+['        '+','.join(str(x>>128) for x in entries[i:i+64])+',' for i in range(0,len(entries),64)]+['    },']
        out += ['};',f'static constexpr int fusedSigmaBits131={bits};',f'static constexpr int fusedSigmaChunks131={chunks};','#endif']
    out += ['''#if ECC_PACKED_FUSED_SIGMA == 3
static __shared__ uint4 fusedSharedLow131[44][64];
static __shared__ unsigned char fusedSharedHigh131[44][64];
#endif''', '#endif','''static ECC_HD void initFusedDelta131() {
#if defined(__CUDA_ARCH__) && ECC_PACKED_FUSED_SIGMA == 3
    for(unsigned i=threadIdx.x;i<44u*64u;i+=blockDim.x) {
        fusedSharedLow131[i/64][i%64]=__ldg(&fusedSigmaLow131[i/64][i%64]);
        fusedSharedHigh131[i/64][i%64]=__ldg(&fusedSigmaHigh131[i/64][i%64]);
    }
    __syncthreads();
#endif
}
static ECC_BIG PolynomialPair fusedDeltaPair131(P131 a,P131 b,int index) {
#if defined(__CUDA_ARCH__)
    P131 x{},y{};
#pragma unroll
    for(int chunk=0;chunk<fusedSigmaChunks131;chunk++) {
        const int word=(chunk*fusedSigmaBits131)/32;
        const int shift=(chunk*fusedSigmaBits131)%32;
        const unsigned mask=(1u<<fusedSigmaBits131)-1;
        const unsigned av=(a.v[word]>>shift) | ((shift+fusedSigmaBits131>32 && word<4) ? a.v[word+1]<<(32-shift) : 0u);
        const unsigned bv=(b.v[word]>>shift) | ((shift+fusedSigmaBits131>32 && word<4) ? b.v[word+1]<<(32-shift) : 0u);
        const unsigned ai=((av&mask)<<3)|unsigned(index);
        const unsigned bi=((bv&mask)<<3)|unsigned(index);
#if ECC_PACKED_FUSED_SIGMA == 3
        const uint4 ax=fusedSharedLow131[chunk][ai];
        const uint4 by=fusedSharedLow131[chunk][bi];
#else
        const uint4 ax=__ldg(&fusedSigmaLow131[chunk][ai]);
        const uint4 by=__ldg(&fusedSigmaLow131[chunk][bi]);
#endif
        x.v[0]^=ax.x;x.v[1]^=ax.y;x.v[2]^=ax.z;x.v[3]^=ax.w;
        y.v[0]^=by.x;y.v[1]^=by.y;y.v[2]^=by.z;y.v[3]^=by.w;
#if ECC_PACKED_FUSED_SIGMA == 3
        x.v[4]^=fusedSharedHigh131[chunk][ai];
        y.v[4]^=fusedSharedHigh131[chunk][bi];
#else
        x.v[4]^=__ldg(&fusedSigmaHigh131[chunk][ai]);
        y.v[4]^=__ldg(&fusedSigmaHigh131[chunk][bi]);
#endif
    }
    return PolynomialPair{x,y};
#else
    const P131 x=fromPolynomial131(a),y=fromPolynomial131(b);
    return PolynomialPair{toPolynomial131(add131(x,sigma131(x,index+3))),
                          toPolynomial131(add131(y,sigma131(y,index+3)))};
#endif
}
#endif''']
    return '\n'.join(out)+'\n'

if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--out',default='include/packedfusedsigma131.h');ap.add_argument('--check',action='store_true');a=ap.parse_args()
    text=generate();p=Path(a.out)
    if a.check: assert p.read_text()==text
    else: p.write_text(text)
    print('PASS: fused maps generated and verified against repeated polynomial squaring')
