//! **Emit `gpu/ecc2k/vec_fold.h`: a folded pair table the CPU built,
//! word for word, and the plan it was built from.**
//!
//! `gpu/ecc2k/pairtable.cuh`'s `pairtable_fold_kernel` stores one entry
//! per signed Frobenius orbit of pairs, the way
//! `PairSumTable::build_folded_within` does, and a table built on a
//! device is only useful if the CPU can probe it — so the two have to
//! produce *the same table*, not merely tables that answer alike.  The
//! strongest check of that is the CPU's own stored state: the bucket
//! offsets, the tagged words in each bucket and the presence filter,
//! exactly as the build left them.  That is what this dumps, beside the
//! inputs the kernel needs to rebuild it: the base sorted by signed
//! orbit, one representative per orbit, and where each orbit's suffix
//! begins — the plan from `PairSumTable::folded_rows`, which is the
//! build's own, not a second derivation of it.
//!
//! The curves are `KoblitzCurve::new(0, n)` at `n = 23` and `n = 41`,
//! which use the same defining trinomials as `gpu/ecc2k`'s `k23` and
//! `k41` (`t²³ + t⁵ + 1`, `t⁴¹ + t³ + 1`), so a point here is the same
//! bits there.  The test checks that rather than trusting it: every
//! dumped point has to lie on the device's curve.
//!
//! Regenerate with
//! `cargo run --release --example dump_fold_vectors > gpu/ecc2k/vec_fold.h`.
use crypto_lib::cryptanalysis::koblitz_fast::{FastCurve, FrobeniusCanon};
use crypto_lib::cryptanalysis::koblitz_index_calculus::{
    build_subgroup_orbit_factor_base, FoldedRows, KoblitzCurve, PairSumTable,
};

fn emit_u64(name: &str, values: &[u64]) {
    println!("static const uint64_t {name}[{}] = {{", values.len().max(1));
    for chunk in values.chunks(4) {
        let row: Vec<String> = chunk.iter().map(|v| format!("{v}ull")).collect();
        println!("    {},", row.join(", "));
    }
    if values.is_empty() {
        println!("    0ull,");
    }
    println!("}};");
}

fn emit_u32(name: &str, values: &[u32]) {
    println!("static const uint32_t {name}[{}] = {{", values.len().max(1));
    for chunk in values.chunks(8) {
        let row: Vec<String> = chunk.iter().map(|v| format!("{v}u")).collect();
        println!("    {},", row.join(", "));
    }
    if values.is_empty() {
        println!("    0u,");
    }
    println!("}};");
}

fn main() {
    // `(degree, base size)`.  The selection adds eight signed orbits at
    // a time, `2n` points each, so these ask for sixteen orbits: enough
    // rows that the suffixes are of many lengths and the buckets fill.
    let cases = [(23u32, 700usize), (41, 1300)];
    let seed = 0x5eed_f01d;

    println!("/* vec_fold.h -- generated by `examples/dump_fold_vectors.rs`.");
    println!(" *");
    println!(" * A folded pair table `PairSumTable::build_folded_within` built,");
    println!(" * as stored, and the row plan it was built from.");
    println!(" * `pairtable_fold_kernel` in `pairtable.cuh` must rebuild it");
    println!(" * from the plan: the same bucket offsets, the same presence");
    println!(" * words, and the same multiset of tagged words in every bucket.");
    println!(" *");
    println!(" * Do not edit.  Regenerate with");
    println!(" *   cargo run --release --example dump_fold_vectors \\\\");
    println!(" *     > gpu/ecc2k/vec_fold.h");
    println!(" */");
    println!("#ifndef GPU_ECC2K_VEC_FOLD_H");
    println!("#define GPU_ECC2K_VEC_FOLD_H");
    println!();
    println!("#include <stdint.h>");
    println!();
    println!("struct FoldVectors {{");
    println!("    int n;                     /* field degree */");
    println!("    int n_points;");
    println!("    const uint64_t *x, *y;     /* the base, sorted by signed orbit */");
    println!("    const uint64_t *canon;     /* FrobeniusCanon::canon(x) + 1, per point */");
    println!("    int n_orbits;              /* signed orbits, empty ones included */");
    println!("    const uint32_t *suffix;    /* n_orbits + 1: where orbit o begins */");
    println!("    int n_reps;                /* rows: one per non-empty orbit */");
    println!("    const uint32_t *rep_orbit;");
    println!("    const uint64_t *rep_x, *rep_y;");
    println!("    int canon_bytes;");
    println!("    const uint64_t *canon_tables; /* canon_bytes * 256, flattened */");
    println!("    /* The CPU's table, as stored. */");
    println!("    int bucket_shift;");
    println!("    int buckets;");
    println!("    const uint32_t *bucket_start; /* buckets + 1 */");
    println!("    const uint32_t *words;        /* bucket_start[buckets] */");
    println!("    int present_words;");
    println!("    const uint64_t *present;");
    println!("    uint64_t present_mask;");
    println!("    int tagged;");
    println!("}};");
    println!();

    let mut rows = Vec::new();
    for (n, want) in cases {
        let kc = KoblitzCurve::new(0, n).expect("Koblitz curve");
        let fb = build_subgroup_orbit_factor_base(&kc, seed, want).expect("factor base");
        let table = PairSumTable::build_folded_within(&kc, &fb, u128::MAX).expect("folded table");
        let storage = table.folded_storage().expect("a folded table");
        let curve = FastCurve::new(&kc.curve).expect("single-word curve");
        // The basis the table named its keys in.  The search for a
        // normal element is deterministic, so building it again finds
        // the same one — asserted, because the per-point keys below
        // are computed from this copy.
        let canon = FrobeniusCanon::new(&curve.field, n).expect("normal element");
        assert_eq!(
            canon.tables(),
            storage.canon_tables,
            "table's basis is reproducible"
        );

        let FoldedRows {
            reps,
            order,
            suffix,
        } = PairSumTable::folded_rows(&fb);
        let points: Vec<_> = fb.points.iter().map(|p| curve.lift(p)).collect();
        let by_orbit: Vec<_> = order.iter().map(|&i| points[i as usize]).collect();
        assert!(
            by_orbit.iter().all(|p| !p.infinity),
            "a subgroup base has no O"
        );

        emit_u64(
            &format!("fold_x_{n}"),
            &by_orbit.iter().map(|p| p.x).collect::<Vec<_>>(),
        );
        emit_u64(
            &format!("fold_y_{n}"),
            &by_orbit.iter().map(|p| p.y).collect::<Vec<_>>(),
        );
        emit_u64(
            &format!("fold_canon_{n}"),
            &by_orbit
                .iter()
                .map(|p| canon.canon(p.x) + 1)
                .collect::<Vec<_>>(),
        );
        emit_u32(&format!("fold_suffix_{n}"), &suffix);
        emit_u32(
            &format!("fold_rep_orbit_{n}"),
            &reps.iter().map(|&(o, _)| o).collect::<Vec<_>>(),
        );
        emit_u64(
            &format!("fold_rep_x_{n}"),
            &reps.iter().map(|&(_, i)| points[i].x).collect::<Vec<_>>(),
        );
        emit_u64(
            &format!("fold_rep_y_{n}"),
            &reps.iter().map(|&(_, i)| points[i].y).collect::<Vec<_>>(),
        );
        let flat: Vec<u64> = storage.canon_tables.iter().flatten().copied().collect();
        emit_u64(&format!("fold_canon_tables_{n}"), &flat);
        emit_u32(&format!("fold_bucket_start_{n}"), storage.bucket_start);
        emit_u32(&format!("fold_words_{n}"), storage.words);
        emit_u64(&format!("fold_present_{n}"), storage.present);
        println!();

        eprintln!(
            "n = {n}: {} points in {} signed orbits, {} rows, {} stored words \
             (unfolded: {}), {} buckets",
            by_orbit.len(),
            fb.signed_orbits.len(),
            reps.len(),
            storage.words.len(),
            by_orbit.len() * (by_orbit.len() + 1) / 2,
            storage.bucket_start.len() - 1,
        );
        rows.push(format!(
            "    {{ {n}, {}, fold_x_{n}, fold_y_{n}, fold_canon_{n}, {}, fold_suffix_{n}, \
             {}, fold_rep_orbit_{n}, fold_rep_x_{n}, fold_rep_y_{n}, {}, \
             fold_canon_tables_{n}, {}, {}, fold_bucket_start_{n}, fold_words_{n}, {}, \
             fold_present_{n}, {}ull, {} }},",
            by_orbit.len(),
            fb.signed_orbits.len(),
            reps.len(),
            storage.canon_tables.len(),
            storage.bucket_shift,
            storage.bucket_start.len() - 1,
            storage.present.len(),
            storage.present_mask,
            u8::from(storage.tagged),
        ));
    }

    // The bucket width is chosen from a pair *estimate* before anything
    // is summed, and one table exercises that formula at one point.  A
    // grid pins it everywhere that matters — small bases where the
    // `+ |F|` term moves the width, wide ones where the 26-bit cap
    // binds, low degrees where the key's own width does — through
    // `folded_byte_size`, which is public and is a function of exactly
    // the estimate and the width.
    println!("struct FoldGeometryVector {{");
    println!("    uint32_t orbits, points, degree;");
    println!("    uint64_t bytes; /* PairSumTable::folded_byte_size */");
    println!("}};");
    println!("static const struct FoldGeometryVector fold_geometry_vectors[] = {{");
    let mut geometry = 0usize;
    for degree in [3u32, 5, 8, 13, 23, 41, 53, 61] {
        for orbits in [1usize, 2, 3, 7, 16, 100, 1456, 10000] {
            for points in [1usize, 15, 16, 31, 736, 1312, 20000, 177632, 3_000_000] {
                let bytes = PairSumTable::folded_byte_size(orbits, points, degree);
                println!("    {{ {orbits}u, {points}u, {degree}u, {bytes}ull }},");
                geometry += 1;
            }
        }
    }
    println!("}};");
    println!("static const int fold_geometry_vectors_count = {geometry};");
    println!();

    println!("static const struct FoldVectors fold_vectors[] = {{");
    for row in &rows {
        println!("{row}");
    }
    println!("}};");
    println!("static const int fold_vectors_count = {};", rows.len());
    println!();
    println!("#endif /* GPU_ECC2K_VEC_FOLD_H */");
}
