//! **Emit `gpu/ecc2k/vec_canon.h`: the basis change and the keys it
//! must produce.**
//!
//! `gpu/ecc2k/pairtable.cuh`'s `pt_canon` and
//! `koblitz_fast::FrobeniusCanon::canon` have to agree *bit for bit*,
//! the way `pt_pack` and `FastPoint::pack` already do — a table one
//! builds has to be probeable by the other, and a key computed one way
//! and looked up another is a silent false "no" from an oracle rather
//! than a crash.
//!
//! Agreement cannot come from both sides searching for a normal
//! element: the search is randomised, so two independent searches find
//! two different bases, each naming the same orbits perfectly well and
//! incompatibly.  The basis is host data, uploaded.  What is left to
//! check is that the *algorithm* applied to it matches, which is what
//! these vectors pin.
//!
//! Regenerate with
//! `cargo run --release --example dump_canon_vectors > gpu/ecc2k/vec_canon.h`.
use crypto_lib::cryptanalysis::koblitz_fast::FrobeniusCanon;
use crypto_lib::cryptanalysis::koblitz_index_calculus::find_irreducible_sparse;
use crypto_lib::cryptanalysis::semaev_decomp::Gf2;

fn main() {
    // One composite degree and one prime one.  The composite is the
    // case that matters — in a proper subfield an orbit is shorter than
    // `n` and its coordinate word is a repeating pattern fixed by its
    // own rotation — and 23 is `k23`'s own degree.
    let degrees = [20u32, 23];
    println!("/* vec_canon.h -- generated by `examples/dump_canon_vectors.rs`.");
    println!(" *");
    println!(" * The change of basis `FrobeniusCanon` built, and the keys");
    println!(" * `FrobeniusCanon::canon` produces from it.  `pt_canon` in");
    println!(" * `pairtable.cuh` must reproduce them exactly from the same");
    println!(" * tables: that is the contract that lets a table built on a");
    println!(" * device be probed on a host.");
    println!(" *");
    println!(" * Do not edit.  Regenerate with");
    println!(" *   cargo run --release --example dump_canon_vectors \\\\");
    println!(" *     > gpu/ecc2k/vec_canon.h");
    println!(" */");
    println!("#ifndef GPU_ECC2K_VEC_CANON_H");
    println!("#define GPU_ECC2K_VEC_CANON_H");
    println!();
    println!("#include <stdint.h>");
    println!();
    println!("struct CanonVectors {{");
    println!("    int n;");
    println!("    int bytes;");
    println!("    const uint64_t *tables; /* bytes * 256, flattened */");
    println!("    int count;");
    println!("    const uint64_t *x;");
    println!("    const uint64_t *canon; /* FrobeniusCanon::canon(x) + 1 */");
    println!("}};");
    println!();

    let mut names = Vec::new();
    for n in degrees {
        let irr = find_irreducible_sparse(n).expect("irreducible");
        let field = Gf2::new(&irr);
        let canon = FrobeniusCanon::new(&field, n).expect("normal element");
        let tables = canon.tables();
        let bytes = tables.len();
        let mask = (1u64 << n) - 1;

        println!(
            "static const uint64_t canon_tables_{n}[{}] = {{",
            bytes * 256
        );
        for table in tables {
            for chunk in table.chunks(4) {
                let row: Vec<String> = chunk.iter().map(|v| format!("{v}ull")).collect();
                println!("    {},", row.join(", "));
            }
        }
        println!("}};");

        // A spread of abscissae, plus the first few elements — small
        // values are where a repeating coordinate word is most likely.
        let mut xs: Vec<u64> = (0..16u64).collect();
        let mut v = 0x9e37_79b9_7f4a_7c15u64;
        while xs.len() < 256 {
            v = v.wrapping_mul(0x9e37_79b9_7f4a_7c15) ^ (v >> 29);
            let x = v & mask;
            if !xs.contains(&x) {
                xs.push(x);
            }
        }
        println!("static const uint64_t canon_x_{n}[{}] = {{", xs.len());
        for chunk in xs.chunks(4) {
            let row: Vec<String> = chunk.iter().map(|x| format!("{x}ull")).collect();
            println!("    {},", row.join(", "));
        }
        println!("}};");
        println!("static const uint64_t canon_key_{n}[{}] = {{", xs.len());
        for chunk in xs.chunks(4) {
            let row: Vec<String> = chunk
                .iter()
                .map(|&x| format!("{}ull", canon.canon(x) + 1))
                .collect();
            println!("    {},", row.join(", "));
        }
        println!("}};");
        println!();
        names.push((n, bytes, xs.len()));
    }

    println!("static const struct CanonVectors canon_vectors[] = {{");
    for (n, bytes, count) in &names {
        println!("    {{ {n}, {bytes}, canon_tables_{n}, {count}, canon_x_{n}, canon_key_{n} }},");
    }
    println!("}};");
    println!("static const int canon_vectors_count = {};", names.len());
    println!();
    println!("#endif /* GPU_ECC2K_VEC_CANON_H */");
}
