#!/usr/bin/env python3
"""Instrument the frozen workload identically for every source revision."""
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[2]
BASE = 'a2963f0d6fb5cb74a20e678cf4def0c7cbafa1d9'
source = subprocess.check_output(['git', 'show', BASE+':examples/weil_factor_composition.rs'], cwd=ROOT, text=True)
source = source.replace('//! Frozen complete-cover experiment; truth tables are never supplied to solvers.',
                        '//! Generated by research/rho_parity_20260915/make_cost_harness.py.\n//! Same frozen DLP with exclusive Callgrind instruction-count scopes.')

markers = r'''
// The documented x86-64 Valgrind client-request ABI. Ordinary execution is a
// no-op. Explicit asm memory effects prevent motion across the cost boundary.
#[cfg(target_arch = "x86_64")]
#[inline(never)]
fn request(code: u64, arg: u64) {
    let args = [code, arg, 0, 0, 0, 0];
    unsafe {
        std::arch::asm!(
            "rol rdi, 3", "rol rdi, 13", "rol rdi, 61", "rol rdi, 51",
            "xchg rbx, rbx",
            in("rax") args.as_ptr(), inout("rdx") 0u64 => _,
            inout("rdi") 0u64 => _, options(nostack),
        );
    }
}
#[cfg(not(target_arch = "x86_64"))]
fn request(_: u64, _: u64) { panic!("instruction-count harness requires x86-64"); }
fn cost_start() { request(0x43540004, 0); }
fn cost_end(label: &'static [u8]) {
    request(0x43540005, 0);
    request(0x43540003, label.as_ptr() as u64);
}

fn calibrate(kc: &KoblitzCurve, empty: bool) {
    let fc = FastCurve::new(&kc.curve).unwrap();
    let g = fc.lift(kc.generator());
    let mut rng = StdRng::seed_from_u64(0x4144444954494f4e);
    let n = kc.subgroup_order.to_u64().unwrap();
    let pairs: Vec<_> = (0..4096).map(|_| (
        fc.mul_u64(g, rng.gen_range(1..n)), fc.mul_u64(g, rng.gen_range(1..n))
    )).collect();
    let mut checksum = 0;
    cost_start();
    if empty {
        for &(a, b) in std::hint::black_box(&pairs) {
            let p = std::hint::black_box(a);
            checksum ^= std::hint::black_box(p).x ^ b.x;
        }
    } else {
        for &(a, b) in std::hint::black_box(&pairs) {
            let p = fc.add(std::hint::black_box(a), b);
            checksum ^= std::hint::black_box(p).x ^ b.x;
        }
    }
    std::hint::black_box(checksum);
    cost_end(b"calibration_loop\0");
    println!("{}", json!({"phase":"calibration", "pairs":pairs.len(), "empty":empty, "checksum":checksum}));
}
'''
source = source.replace('fn main() {', markers+'\nfn main() {', 1)

def replace(before, after):
    global source
    assert source.count(before) == 1, before
    source = source.replace(before, after)

replace('    let cold = Instant::now();', '    cost_start();\n    let cold = Instant::now();')
replace('    let curve_ns = cold.elapsed().as_nanos();',
        '    let curve_ns = cold.elapsed().as_nanos();\n    cost_end(b"curve_setup\\0");\n'
        '    if mode == "calibrate" || mode == "calibrate_empty" { calibrate(&kc, mode == "calibrate_empty"); return; }\n    cost_start();')
replace('    let target_ns = started.elapsed().as_nanos();',
        '    let target_ns = started.elapsed().as_nanos();\n    cost_end(b"target_generation\\0");')
replace('    if mode == "rho" {', '    if mode == "rho" {\n        cost_start();')
replace('        let opts = KoblitzSignedRhoOptions {', '        let opts = KoblitzSignedRhoOptions {')
replace('        println!(\n            "{}",\n            json!({"phase":"rho"',
        '        cost_end(b"rho_and_final_verification\\0");\n        println!(\n            "{}",\n            json!({"phase":"rho"')
replace('    let basis = seed_basis(&kc, c, seed);', '    cost_start();\n    let basis = seed_basis(&kc, c, seed);')
replace('    let setup_ns = cold.elapsed().as_nanos();', '    let setup_ns = cold.elapsed().as_nanos();\n    cost_end(b"factor_base_plan_index\\0");')
replace('    if mode == "dlp" {', '    if mode == "dlp" {\n        cost_start();')
replace('        let cold_ns = setup_ns + driver_ns + verification_ns;',
        '        let cold_ns = setup_ns + driver_ns + verification_ns;\n        cost_end(b"driver_and_final_verification\\0");')
(ROOT/'examples/rho_parity_cost.rs').write_text(source)
