cmake_minimum_required(VERSION 3.20)
project(mlwe_cuda LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
add_executable(mlwe_cpu_check cpu_check.cpp)
enable_testing()
add_test(NAME mlwe_cpu_check COMMAND mlwe_cpu_check)
include(CheckLanguage)
check_language(CUDA)
if(CMAKE_CUDA_COMPILER)
  enable_language(CUDA)
  add_executable(mlwe_cuda_check mlwe_cuda.cu)
  set_target_properties(mlwe_cuda_check PROPERTIES CUDA_STANDARD 17)
endif()
