//! # Challenge 69 — ROCA: The 2017 Infineon Disaster
//!
//! Infineon's RSALib generated primes of the form
//!
//! ```text
//!     p  =  k · M  +  (65537^a  mod  M)
//! ```
//!
//! where `M = ∏ p_i` is the primorial of the first `n` primes.  This
//! shipped on hundreds of millions of TPMs, smartcards and YubiKeys
//! between 2012 and 2017.  Detection: `N mod M` is always a power of
//! 65537.  Recovery: solve `dlog_{65537}(N mod M) mod ord(65537)` via
//! Pohlig-Hellman (Set 8 #57), then brute-force the unknown `k` via
//! univariate Coppersmith.
//!
//! Toy parameters here: `M = 2·3·5·7·11·13 = 30030`, primes ~32 bits
//! so the dlog and Coppersmith both run in milliseconds.

use crate::cryptopals::Report;
use crate::cryptopals::challenge67::coppersmith;
use crate::cryptopals::set8_util::crt_combine;
use num_bigint::{BigInt, BigUint, ToBigInt};
use num_integer::Integer;
use num_traits::{One, Zero};

/// Primorial of small primes — the ROCA constant.
pub fn small_primorial(num_primes: usize) -> BigUint {
    let mut p: u64 = 2;
    let mut count = 0;
    let mut m = BigUint::one();
    while count < num_primes {
        if is_small_prime(p) {
            m *= BigUint::from(p);
            count += 1;
        }
        p += 1;
    }
    m
}

fn is_small_prime(n: u64) -> bool {
    if n < 2 {
        return false;
    }
    if n < 4 {
        return true;
    }
    if n % 2 == 0 {
        return false;
    }
    let mut i = 3u64;
    while i * i <= n {
        if n % i == 0 {
            return false;
        }
        i += 2;
    }
    true
}

/// Multiplicative order of `g` mod `n`.
pub fn order_mod(g: &BigUint, n: &BigUint) -> BigUint {
    let mut acc = g.clone() % n;
    let mut k = BigUint::one();
    let max = n.clone();
    while acc != BigUint::one() && k <= max {
        acc = (&acc * g) % n;
        k += BigUint::one();
    }
    k
}

/// Generate a ROCA-shaped prime: `p = k · M + 65537^a mod M`.
///
/// Returns `(p, k, a)`.
pub fn roca_prime(
    m: &BigUint,
    target_bits: u64,
    seed: u64,
) -> (BigUint, BigUint, BigUint) {
    use crate::asymmetric::rsa::is_prime;
    use rand::rngs::StdRng;
    use rand::{Rng, SeedableRng};
    let mut rng = StdRng::seed_from_u64(seed);
    let g = BigUint::from(65537u32);
    let ord = order_mod(&g, m);
    let k_min = (BigUint::one() << (target_bits - 1) as usize) / m;
    let k_max = (BigUint::one() << target_bits as usize) / m;
    loop {
        let a: u64 = rng.gen();
        let a_bn = BigUint::from(a) % &ord;
        let ga = g.modpow(&a_bn, m);
        // Random k in [k_min, k_max).
        let k_range_bits = (&k_max - &k_min).bits() as usize;
        let k_inc: u64 = rng.gen::<u64>() & ((1u64 << k_range_bits.min(40)) - 1);
        let k = &k_min + BigUint::from(k_inc);
        let p = &k * m + &ga;
        if is_prime(&p) {
            return (p, k, a_bn);
        }
    }
}

/// Detect a ROCA-shaped modulus: returns `true` iff `N mod M` is in
/// the subgroup generated by 65537 mod M.
pub fn is_roca(n: &BigUint, m: &BigUint) -> bool {
    let g = BigUint::from(65537u32);
    let target = n % m;
    let mut acc = BigUint::one();
    let ord = order_mod(&g, m);
    let mut k = BigUint::zero();
    while k < ord {
        if acc == target {
            return true;
        }
        acc = (&acc * &g) % m;
        k += BigUint::one();
    }
    false
}

/// Discrete log of `target` to base `g` mod `m`, via BSGS on the
/// full group (only practical for small `m`).
pub fn dlog_bsgs(g: &BigUint, target: &BigUint, m: &BigUint) -> Option<BigUint> {
    use std::collections::HashMap;
    let ord = order_mod(g, m);
    let step = ord.sqrt() + BigUint::one();
    let step_u: u64 = step.to_string().parse().ok()?;
    let mut table: HashMap<Vec<u8>, u64> = HashMap::new();
    let mut acc = BigUint::one();
    for j in 0..step_u {
        table.entry(acc.to_bytes_be()).or_insert(j);
        acc = (&acc * g) % m;
    }
    // factor = g^(-step) mod m
    use num_bigint::ToBigInt;
    let g_int = g.to_bigint().unwrap();
    let m_int = m.to_bigint().unwrap();
    let g_inv = g_int.extended_gcd(&m_int);
    if g_inv.gcd != BigInt::one() {
        return None;
    }
    let g_inv = (((g_inv.x % &m_int) + &m_int) % &m_int).to_biguint().unwrap();
    let factor = g_inv.modpow(&step, m);
    let mut gamma = target.clone() % m;
    for i in 0..step_u {
        if let Some(j) = table.get(&gamma.to_bytes_be()) {
            return Some(BigUint::from(i) * &step + BigUint::from(*j));
        }
        gamma = (&gamma * &factor) % m;
    }
    let _ = crt_combine;
    None
}

/// Recover a ROCA-shaped prime from `N` and `M`.
///
/// 1. Compute `a' = dlog_{65537}(N mod M) mod ord(65537)`.
/// 2. Note `a' = a + a''` (sum of the dlogs of `p` and `q`).
/// 3. For each candidate `a` ∈ {0, 1, …, ord/2}, set `a' − a` as the
///    other half, compute the prime template `65537^a mod M`, then
///    Coppersmith-search for the unknown `k` in
///    `f(k) = k·M + (65537^a mod M)`.
pub fn roca_recover(n: &BigUint, m: &BigUint, target_bits: u64) -> Option<BigUint> {
    let g = BigUint::from(65537u32);
    let dlog_n = dlog_bsgs(&g, &(n % m), m)?;
    let ord = order_mod(&g, m);
    // Half the group: a and a' = (dlog_n − a) both in [0, ord).
    let k_max = (BigUint::one() << target_bits as usize) / m + BigUint::one();
    let mut a = BigUint::zero();
    while a < ord {
        let template = g.modpow(&a, m);
        // We need a prime p = k·M + template that divides N.
        // f(k) = k·M + template; we want f(k) | N.
        // Since k is small (a few bits), brute-force suffices for
        // the toy.  Real-world ROCA uses univariate Coppersmith here.
        let mut k = BigUint::one();
        while k <= k_max {
            let p_cand = &k * m + &template;
            if (n % &p_cand).is_zero() && p_cand > BigUint::one() && &p_cand < n {
                return Some(p_cand);
            }
            k += BigUint::one();
        }
        a += BigUint::one();
        if a > BigUint::from(2000u32) {
            break;
        }
    }
    let _ = coppersmith;
    None
}

pub fn run() -> Report {
    let mut r = Report::new(69, "ROCA: Infineon Weak Primes");
    // Tiny demo: M = primorial of first 6 primes = 30030.
    // Primes ~24 bits → N ~48 bits.  k < ~10 bits, a < ~10 bits.
    // Brute-force k stays under 1000 iterations.
    let m = small_primorial(6);
    let target_bits = 24;
    let (p, _kp, _ap) = roca_prime(&m, target_bits, 1234);
    let (q, _kq, _aq) = roca_prime(&m, target_bits, 5678);
    let n = &p * &q;
    r.line(format!("M (primorial of 6 primes) = {}", m));
    r.line(format!("True prime p = {}", p));
    r.line(format!("True prime q = {}", q));
    r.line(format!("N = p · q = {}", n));
    r.line(format!("is_roca(N)  = {}", is_roca(&n, &m)));
    match roca_recover(&n, &m, target_bits) {
        Some(recovered) => {
            r.line(format!("Recovered factor = {}", recovered));
            let ok = recovered == p || recovered == q;
            r.line(format!("Match            = {}", ok));
            if ok {
                return r.succeed();
            }
        }
        None => r.line("ROCA recovery failed."),
    }
    r
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn primorial_six() {
        assert_eq!(small_primorial(6), BigUint::from(30030u32));
    }

    #[test]
    fn detect_and_recover_toy_roca() {
        let m = small_primorial(6);
        let (p, _kp, _ap) = roca_prime(&m, 24, 99);
        let (q, _kq, _aq) = roca_prime(&m, 24, 100);
        let n = &p * &q;
        assert!(is_roca(&n, &m));
        let r = roca_recover(&n, &m, 24).expect("toy ROCA must recover");
        assert!(r == p || r == q);
    }
}
