//! CGA-HNC — Class-Group-Amortized Hidden-Number Cryptanalysis.
//!
//! Research module pursuing the proposal made in this library's
//! cryptanalysis-survey thread: use the `Cl(O)`-action on ordinary
//! curves to aggregate partial DLP information across an isogeny
//! orbit, then attack via lattice (HNP-style) reduction on the
//! residual unrecovered scalar bits.
//!
//! # Phase 1 (this code): empirical orbit characterisation
//!
//! Implements the building blocks needed to test the proposal's
//! prediction P1: enumerate the 2-isogeny graph of an ordinary curve,
//! count points on each curve in the orbit, and measure the
//! cumulative smoothness — the "CRT-coverage" of the secret `d`
//! across the orbit, which dictates whether the technique can
//! recover non-trivially many bits of `d` for free.
//!
//! # Building blocks
//!
//! - [`j_invariant`] — j(E) for a short Weierstrass curve
//! - [`curve_from_j_invariant`] — choose a curve with a given j
//! - [`phi_2_evaluate`] — evaluate Φ_2(X, j_0) as a polynomial in X
//! - [`two_isogeny_neighbors`] — j-invariants of E's 2-isogeny neighbours
//! - [`bfs_two_isogeny_orbit`] — BFS traversal of the 2-isogeny graph
//! - [`count_points_brute`] — exhaustive |E(F_p)| for p ≤ ~10^6
//! - [`orbit_smoothness_report`] — distribution of smooth-part sizes
//!
//! # 2-isogeny modular polynomial
//!
//! Φ_2(X, Y) is the symmetric integer polynomial whose vanishing on
//! `(j(E), j(E'))` characterises E and E' being 2-isogenous:
//!
//! ```text
//! Φ_2 = X³ + Y³ − X²·Y²
//!     + 1488·(X²·Y + X·Y²)
//!     − 162000·(X² + Y²)
//!     + 40773375·X·Y
//!     + 8748000000·(X + Y)
//!     − 157464000000000
//! ```
//!
//! These coefficients are standard (see, e.g., Bröker–Lauter–Sutherland,
//! "Modular polynomials via isogeny volcanoes," Math. Comp. 2012).
//!
//! # Applicability to cryptographic curves
//!
//! **CGA-HNC is structurally inapplicable to all standard cryptographic
//! curves currently deployed**:
//!
//! | Curve | `n` (point order) | Cofactor | CGA-HNC applies? |
//! |---|---|---|---|
//! | secp256k1 | 256-bit prime | 1 | **No** |
//! | NIST P-256 | 256-bit prime | 1 | **No** |
//! | NIST P-224 | 224-bit prime | 1 | **No** |
//! | NIST P-384 | 384-bit prime | 1 | **No** |
//! | NIST P-521 | 521-bit prime | 1 | **No** |
//! | brainpoolP256r1 | 256-bit prime | 1 | **No** |
//! | Curve25519 | prime · 8 | 8 | Trivially (≤ 3 bits leak) |
//! | Curve448 | prime · 4 | 4 | Trivially (≤ 2 bits leak) |
//!
//! **The reason**: Pohlig-Hellman needs smooth factors of `#E(F_p)`.
//! Standard NIST/secp curves have prime order with cofactor 1 by
//! design — explicitly chosen to prevent this attack family.  No
//! orbit-CRT amortisation can recover any bits of `d` because there
//! are no smooth subgroups to amortise into.
//!
//! For Curve25519/Curve448, the cofactor (8 or 4) admits a few bits
//! of leak, but any responsible implementation either clamps `d` to
//! reside in the prime-order subgroup, or the leaked bits are
//! deliberately public (e.g., the Edwards-form encoding).
//!
//! **What this module is for**: characterising weak *non-standard*
//! curves — composite-order curves used in legacy systems, curves
//! generated by third-party processes whose order properties are
//! not vetted, or research-grade curve families where the technique
//! might inform the safety analysis.
//!
//! # Scope
//!
//! - **Implemented**: 2-isogeny graph traversal, point transport,
//!   per-curve Pohlig-Hellman, CRT aggregation, BSGS residual cleanup.
//! - **Not implemented**: 3-, 5-, …-isogeny graphs, full Schoof for
//!   point counting at non-toy scales, HNP-lattice residual cleanup
//!   (the *novel* contribution proposed but not yet tested at scale).

use num_bigint::{BigInt, Sign, ToBigInt};
use num_traits::{One, Signed, Zero};

use crate::utils::mod_inverse;

// ── Modular-polynomial Φ_2 coefficients ────────────────────────────────────

/// `(coeff, exp_X, exp_Y)` for every monomial of Φ_2.
const PHI_2_COEFFS: &[(i128, u32, u32)] = &[
    (1, 3, 0),
    (1, 0, 3),
    (-1, 2, 2),
    (1488, 2, 1),
    (1488, 1, 2),
    (-162000, 2, 0),
    (-162000, 0, 2),
    (40773375, 1, 1),
    (8748000000, 1, 0),
    (8748000000, 0, 1),
    (-157464000000000, 0, 0),
];

// ── j-invariant ↔ curve coefficients ───────────────────────────────────────

/// Compute `j(E)` for `E: y² = x³ + a·x + b (mod p)`.  Returns
/// `None` if the curve is singular (`4a³ + 27b² ≡ 0 (mod p)`).
pub fn j_invariant(a: &BigInt, b: &BigInt, p: &BigInt) -> Option<BigInt> {
    let four_a3 = (BigInt::from(4) * a.pow(3)) % p;
    let twentyseven_b2 = (BigInt::from(27) * b.pow(2)) % p;
    let denom = ((&four_a3 + &twentyseven_b2) % p + p) % p;
    if denom.is_zero() {
        return None;
    }
    let denom_u = denom.to_biguint().unwrap();
    let p_u = p.to_biguint().unwrap();
    let denom_inv_u = mod_inverse(&denom_u, &p_u)?;
    let denom_inv = denom_inv_u.to_bigint().unwrap();
    let four_a3_pos = ((&four_a3 % p) + p) % p;
    let j = (BigInt::from(1728) * &four_a3_pos * &denom_inv) % p;
    Some(((j % p) + p) % p)
}

/// Construct a curve `E_j: y² = x³ + a·x + b` with `j(E_j) ≡ j (mod p)`.
///
/// Standard construction:
/// - `j ≡ 0` (mod p): use `(a, b) = (0, 1)` → `y² = x³ + 1`
/// - `j ≡ 1728` (mod p): use `(a, b) = (-1, 0)` → `y² = x³ − x`
/// - otherwise: `k = j/(1728 − j) mod p`, return `(a, b) = (3k, 2k)`
///
/// Returns `None` only if `(1728 − j)` is not invertible mod p (which
/// requires `p | (1728 − j)` — handled by the special-case branch).
pub fn curve_from_j_invariant(j: &BigInt, p: &BigInt) -> Option<(BigInt, BigInt)> {
    let zero = BigInt::zero();
    let one = BigInt::one();
    let v_1728 = BigInt::from(1728);
    let j_red = ((j % p) + p) % p;

    if j_red == zero {
        return Some((zero, one));
    }
    if j_red == (v_1728.clone() % p + p) % p {
        // y² = x³ − x — return the two coefficients reduced mod p
        let neg_one = ((-BigInt::one()) % p + p) % p;
        return Some((neg_one, zero));
    }

    let denom = ((&v_1728 - &j_red) % p + p) % p;
    if denom.is_zero() {
        return None;
    }
    let denom_u = denom.to_biguint().unwrap();
    let p_u = p.to_biguint().unwrap();
    let denom_inv_u = mod_inverse(&denom_u, &p_u)?;
    let denom_inv = denom_inv_u.to_bigint().unwrap();

    let k = (&j_red * &denom_inv) % p;
    let a = ((BigInt::from(3) * &k) % p + p) % p;
    let b = ((BigInt::from(2) * &k) % p + p) % p;
    Some((a, b))
}

// ── 2-isogeny graph ────────────────────────────────────────────────────────

/// Evaluate `Φ_2(X, j_0) (mod p)` as a polynomial in `X`.  Returns
/// the four coefficients `[c_0, c_1, c_2, c_3]` of
/// `c_0 + c_1·X + c_2·X² + c_3·X³`.
pub fn phi_2_evaluate(j_0: &BigInt, p: &BigInt) -> [BigInt; 4] {
    let mut coeffs = [
        BigInt::zero(),
        BigInt::zero(),
        BigInt::zero(),
        BigInt::zero(),
    ];
    for &(c, ex, ey) in PHI_2_COEFFS {
        let c_mod = ((BigInt::from(c) % p) + p) % p;
        let j_pow = j_0.modpow(&BigInt::from(ey), p);
        let term = (&c_mod * &j_pow) % p;
        coeffs[ex as usize] = (&coeffs[ex as usize] + &term) % p;
    }
    for c in &mut coeffs {
        *c = ((c.clone() % p) + p) % p;
    }
    coeffs
}

/// Find every `x ∈ F_p` with `c_0 + c_1·x + c_2·x² + c_3·x³ ≡ 0 (mod p)`
/// by exhaustive scan.  Suitable for `p ≤ 10⁶`-ish; above that, switch
/// to Cantor–Zassenhaus polynomial factorisation (not implemented).
pub fn cubic_roots_brute(coeffs: &[BigInt; 4], p: &BigInt) -> Vec<BigInt> {
    let mut roots = Vec::new();
    let p_u64 = p.to_u64_digits().1[0];
    for x_u in 0..p_u64 {
        let x = BigInt::from(x_u);
        let val =
            (&coeffs[0] + &coeffs[1] * &x + &coeffs[2] * x.pow(2) + &coeffs[3] * x.pow(3)) % p;
        let val_pos = ((val % p) + p) % p;
        if val_pos.is_zero() {
            roots.push(x);
        }
    }
    roots
}

/// j-invariants of curves 2-isogenous to a curve with `j(E) = j_0`.
/// Up to three neighbours over `F_p`; can be fewer if the cubic
/// `Φ_2(X, j_0)` has repeated roots (volcano-floor structure) or
/// fewer F_p-rational roots than its degree.
pub fn two_isogeny_neighbors(j_0: &BigInt, p: &BigInt) -> Vec<BigInt> {
    let coeffs = phi_2_evaluate(j_0, p);
    cubic_roots_brute(&coeffs, p)
}

/// Breadth-first traversal of the 2-isogeny graph starting from
/// `(a_0, b_0)`.  Visits curves up to `max_curves` in total (cap
/// to prevent runaway on large connected components).  Returns
/// the list of `(j-invariant, depth)` pairs visited.
pub fn bfs_two_isogeny_orbit(
    a_0: &BigInt,
    b_0: &BigInt,
    p: &BigInt,
    max_curves: usize,
) -> Vec<(BigInt, u32)> {
    let mut visited: Vec<(BigInt, u32)> = Vec::new();
    let mut seen: std::collections::HashSet<Vec<u8>> = std::collections::HashSet::new();

    let j0 = match j_invariant(a_0, b_0, p) {
        Some(j) => j,
        None => return visited,
    };
    let mut queue: std::collections::VecDeque<(BigInt, u32)> = std::collections::VecDeque::new();
    queue.push_back((j0.clone(), 0));
    seen.insert(j0.to_signed_bytes_be());

    while let Some((j, depth)) = queue.pop_front() {
        visited.push((j.clone(), depth));
        if visited.len() >= max_curves {
            break;
        }
        for n in two_isogeny_neighbors(&j, p) {
            let key = n.to_signed_bytes_be();
            if seen.insert(key) {
                queue.push_back((n, depth + 1));
            }
        }
    }
    visited
}

// ── Brute-force point counting ─────────────────────────────────────────────

/// `|E(F_p)|` by exhaustive enumeration over `x ∈ F_p`, counting `y`
/// such that `y² ≡ x³ + a·x + b (mod p)`.  Cost: `O(p · log p)`
/// from per-point QR tests via Euler's criterion.  Use only for
/// `p ≤ ~10⁶`.
pub fn count_points_brute(a: &BigInt, b: &BigInt, p: &BigInt) -> u64 {
    let p_u64 = p.to_u64_digits().1[0];
    let mut count: u64 = 1; // point at infinity
    for x_u in 0..p_u64 {
        let x = BigInt::from(x_u);
        let rhs = ((x.pow(3) + a * &x + b) % p + p) % p;
        if rhs.is_zero() {
            count += 1; // y = 0 (single root, 2-torsion)
            continue;
        }
        // Test if rhs is a QR mod p via Euler's criterion: rhs^((p-1)/2) mod p.
        let exp = (p - BigInt::one()) >> 1;
        let leg = rhs.modpow(&exp, p);
        if leg == BigInt::one() {
            count += 2;
        }
    }
    count
}

// ── Smoothness / CRT-coverage measurement ─────────────────────────────────

/// Per-orbit-curve smoothness statistics.  `total_points` is `#E_i`,
/// `smooth_part` is the largest `B`-smooth divisor of `#E_i` for the
/// configured smoothness bound `B`, and `bits_recoverable` is
/// `log_2(smooth_part)` (the bits of `d (mod smooth_part)` that
/// Pohlig-Hellman would extract from this curve).
#[derive(Clone, Debug, PartialEq)]
pub struct CurveSmoothnessRow {
    pub j_invariant: BigInt,
    pub total_points: u64,
    pub smooth_part: u64,
    pub bits_recoverable: f64,
}

/// Aggregate report across an orbit.  `total_bits_naive` is the sum
/// of per-curve bits (over-counts when factors repeat across curves);
/// `total_bits_crt` is `log_2(lcm(smooth_parts))` — the actual
/// CRT-coverage of `d` (in bits) across the orbit.
#[derive(Clone, Debug)]
pub struct OrbitSmoothnessReport {
    pub rows: Vec<CurveSmoothnessRow>,
    pub total_bits_naive: f64,
    pub total_bits_crt: f64,
    pub p: BigInt,
}

/// Largest `B`-smooth divisor of `n`.  `B` should be small (≤ 10⁵ or so)
/// for performance.
fn largest_smooth_divisor(n: u64, b: u64) -> u64 {
    let mut residue = n;
    let mut smooth: u64 = 1;
    let mut p: u64 = 2;
    while p <= b && p.saturating_mul(p) <= residue {
        while residue % p == 0 {
            smooth = smooth.saturating_mul(p);
            residue /= p;
        }
        p = if p == 2 { 3 } else { p + 2 };
    }
    if residue > 1 && residue <= b {
        smooth = smooth.saturating_mul(residue);
    }
    smooth
}

/// Build an [`OrbitSmoothnessReport`] for a starting curve.
pub fn orbit_smoothness_report(
    a_0: &BigInt,
    b_0: &BigInt,
    p: &BigInt,
    smoothness_bound: u64,
    max_curves: usize,
) -> OrbitSmoothnessReport {
    let orbit = bfs_two_isogeny_orbit(a_0, b_0, p, max_curves);
    let mut rows = Vec::with_capacity(orbit.len());
    for (j, _depth) in &orbit {
        let (a, b) = match curve_from_j_invariant(j, p) {
            Some(v) => v,
            None => continue,
        };
        let n_pts = count_points_brute(&a, &b, p);
        let smooth = largest_smooth_divisor(n_pts, smoothness_bound);
        rows.push(CurveSmoothnessRow {
            j_invariant: j.clone(),
            total_points: n_pts,
            smooth_part: smooth,
            bits_recoverable: (smooth as f64).log2(),
        });
    }
    let total_bits_naive: f64 = rows.iter().map(|r| r.bits_recoverable).sum();
    // CRT-coverage: lcm of all smooth_parts.  For small u64 we can do
    // this incrementally with overflow guard.
    let mut crt_lcm: u128 = 1;
    let mut overflow = false;
    for r in &rows {
        if overflow {
            break;
        }
        let g = gcd_u64(crt_lcm as u64, r.smooth_part) as u128;
        let next = crt_lcm.saturating_mul((r.smooth_part as u128) / g.max(1));
        if next > (1u128 << 100) {
            overflow = true;
            crt_lcm = 1u128 << 100;
        } else {
            crt_lcm = next;
        }
    }
    let total_bits_crt = (crt_lcm as f64).log2();
    OrbitSmoothnessReport {
        rows,
        total_bits_naive,
        total_bits_crt,
        p: p.clone(),
    }
}

fn gcd_u64(mut a: u64, mut b: u64) -> u64 {
    while b != 0 {
        let r = a % b;
        a = b;
        b = r;
    }
    a
}

// ── Phase 2: Point operations + 2-isogeny transport + Pohlig-Hellman ──────
//
// Phase 2 builds on the Phase 1 measurement infrastructure to actually
// run the CGA-HNC attack: transport a target Q = d·P across the
// 2-isogeny orbit, run Pohlig-Hellman on each curve's smooth subgroup,
// CRT-combine partial recoveries, verify recovery of `d`.

/// Affine point on a short-Weierstrass curve `y² = x³ + a·x + b`,
/// or the point at infinity.  Bigint coordinates over F_p.
#[derive(Clone, Debug, PartialEq)]
pub enum Pt2 {
    Inf,
    Aff(BigInt, BigInt),
}

fn mod_pos(x: BigInt, p: &BigInt) -> BigInt {
    ((x % p) + p) % p
}

fn modular_inverse(x: &BigInt, p: &BigInt) -> Option<BigInt> {
    let x_pos = mod_pos(x.clone(), p);
    let xu = x_pos.to_biguint()?;
    let pu = p.to_biguint()?;
    let inv_u = mod_inverse(&xu, &pu)?;
    Some(inv_u.to_bigint().unwrap())
}

/// `2·P` on `E: y² = x³ + a·x + b (mod p)`.
pub fn pt_double(p: &Pt2, a: &BigInt, p_mod: &BigInt) -> Pt2 {
    match p {
        Pt2::Inf => Pt2::Inf,
        Pt2::Aff(x, y) => {
            if y.is_zero() {
                return Pt2::Inf;
            }
            let two_y = mod_pos(BigInt::from(2) * y, p_mod);
            let inv = match modular_inverse(&two_y, p_mod) {
                Some(v) => v,
                None => return Pt2::Inf,
            };
            let lam = mod_pos((BigInt::from(3) * x.pow(2) + a) * inv, p_mod);
            let x3 = mod_pos(lam.pow(2) - BigInt::from(2) * x, p_mod);
            let y3 = mod_pos(&lam * (x - &x3) - y, p_mod);
            Pt2::Aff(x3, y3)
        }
    }
}

/// `P + Q` on `E: y² = x³ + a·x + b (mod p)`.
pub fn pt_add(p: &Pt2, q: &Pt2, a: &BigInt, p_mod: &BigInt) -> Pt2 {
    match (p, q) {
        (Pt2::Inf, x) | (x, Pt2::Inf) => x.clone(),
        (Pt2::Aff(x1, y1), Pt2::Aff(x2, y2)) => {
            if x1 == x2 {
                if y1 == y2 {
                    return pt_double(p, a, p_mod);
                }
                return Pt2::Inf;
            }
            let dx = mod_pos(x2 - x1, p_mod);
            let inv = match modular_inverse(&dx, p_mod) {
                Some(v) => v,
                None => return Pt2::Inf,
            };
            let lam = mod_pos((y2 - y1) * inv, p_mod);
            let x3 = mod_pos(lam.pow(2) - x1 - x2, p_mod);
            let y3 = mod_pos(&lam * (x1 - &x3) - y1, p_mod);
            Pt2::Aff(x3, y3)
        }
    }
}

/// `k·P` via double-and-add.
pub fn pt_scalar_mul(p: &Pt2, k: &BigInt, a: &BigInt, p_mod: &BigInt) -> Pt2 {
    let mut result = Pt2::Inf;
    let mut addend = p.clone();
    let k_abs = k.magnitude().clone();
    for i in 0..k_abs.bits() {
        if k_abs.bit(i) {
            result = pt_add(&result, &addend, a, p_mod);
        }
        addend = pt_double(&addend, a, p_mod);
    }
    if k.sign() == Sign::Minus {
        // Negate the result: (x, y) → (x, -y).
        match result {
            Pt2::Aff(x, y) => Pt2::Aff(x, mod_pos(-y, p_mod)),
            Pt2::Inf => Pt2::Inf,
        }
    } else {
        result
    }
}

/// **2-isogeny point transport** in short Weierstrass form.
///
/// Given source curve `E: y² = x³ + a·x + b (mod p)`, a 2-torsion
/// `x`-coordinate `α` (root of `x³ + a·x + b = 0` in `F_p`), and a
/// point `(x, y)` on `E`, return the image `φ(x, y)` on the codomain
///
/// ```text
/// E': y² = x'³ + a'·x' + b'   with   a' = −15α² − 4a,  b' = −22α³ − 8αa
/// ```
///
/// derived from Vélu's formula composed with the Weierstrass-form
/// translations.  Verified by Φ_2(j(E), j(E')) ≡ 0 on round-trip
/// tests.
pub fn two_isogeny_transport_point(pt: &Pt2, alpha: &BigInt, a: &BigInt, p_mod: &BigInt) -> Pt2 {
    match pt {
        Pt2::Inf => Pt2::Inf,
        Pt2::Aff(x, y) => {
            // 2-torsion point maps to identity.
            if x == alpha && y.is_zero() {
                return Pt2::Inf;
            }
            // x'_short = (x² − 4αx + 6α² + a) / (x − α)
            let num_x = mod_pos(
                x.pow(2) - BigInt::from(4) * alpha * x + BigInt::from(6) * alpha.pow(2) + a,
                p_mod,
            );
            let dx = mod_pos(x - alpha, p_mod);
            let dx_inv = match modular_inverse(&dx, p_mod) {
                Some(v) => v,
                None => return Pt2::Inf,
            };
            let x_new = mod_pos(num_x * &dx_inv, p_mod);
            // y'_short = y · (x² − 2αx − 2α² − a) / (x − α)²
            let num_y = mod_pos(
                x.pow(2) - BigInt::from(2) * alpha * x - BigInt::from(2) * alpha.pow(2) - a,
                p_mod,
            );
            let dx_sq_inv = mod_pos(dx_inv.pow(2), p_mod);
            let y_new = mod_pos(y * num_y * dx_sq_inv, p_mod);
            Pt2::Aff(x_new, y_new)
        }
    }
}

/// Codomain coefficients `(a', b')` for the 2-isogeny with kernel
/// `{O, (α, 0)}` on `E: y² = x³ + a·x + b`.
pub fn two_isogeny_codomain(alpha: &BigInt, a: &BigInt, p_mod: &BigInt) -> (BigInt, BigInt) {
    let a_new = mod_pos(
        BigInt::from(-15) * alpha.pow(2) - BigInt::from(4) * a,
        p_mod,
    );
    let b_new = mod_pos(
        BigInt::from(-22) * alpha.pow(3) - BigInt::from(8) * alpha * a,
        p_mod,
    );
    (a_new, b_new)
}

/// Find all 2-torsion x-coordinates of `E: y² = x³ + a·x + b (mod p)`
/// — the roots of `x³ + a·x + b ≡ 0 (mod p)` in F_p.  Brute-force.
pub fn two_torsion_x_coords(a: &BigInt, b: &BigInt, p_mod: &BigInt) -> Vec<BigInt> {
    let mut out = Vec::new();
    let p_u64 = p_mod.to_u64_digits().1[0];
    for x_u in 0..p_u64 {
        let x = BigInt::from(x_u);
        let val = mod_pos(x.pow(3) + a * &x + b, p_mod);
        if val.is_zero() {
            out.push(x);
        }
    }
    out
}

/// Compute the order of `p` on `E` given that `n_curve = #E(F_p)` is
/// known (so the order divides `n_curve`).  Returns the smallest `d`
/// with `d·P = O`.  Tries divisors of `n_curve` in increasing order.
pub fn point_order(p: &Pt2, n_curve: u64, a: &BigInt, p_mod: &BigInt) -> u64 {
    if matches!(p, Pt2::Inf) {
        return 1;
    }
    // Find divisors of n_curve in increasing order via trial division.
    let mut divisors: Vec<u64> = Vec::new();
    let mut d = 1u64;
    while d * d <= n_curve {
        if n_curve % d == 0 {
            divisors.push(d);
            if d != n_curve / d {
                divisors.push(n_curve / d);
            }
        }
        d += 1;
    }
    divisors.sort();
    for div in divisors {
        let mul = pt_scalar_mul(p, &BigInt::from(div), a, p_mod);
        if matches!(mul, Pt2::Inf) {
            return div;
        }
    }
    n_curve
}

/// **Pohlig-Hellman** ECDLP recovery on a smooth subgroup.
///
/// Given `P` (with order `n_p` known and `n_p`-smooth ≤ `B`) and
/// `Q = d·P`, recover `d (mod n_p)` via:
/// 1. Factor `n_p = ∏ ℓ_i^{e_i}` (trial division up to `B`).
/// 2. For each prime power `ℓ_i^{e_i}`, project `P, Q` onto the
///    subgroup of order `ℓ_i^{e_i}` and solve via brute-force scan.
/// 3. CRT-combine.  Returns `None` if any step fails (e.g. `n_p`
///    is not smooth ≤ `B`).
pub fn pohlig_hellman_dlp(
    p: &Pt2,
    q: &Pt2,
    n_p: u64,
    a: &BigInt,
    p_mod: &BigInt,
    smoothness_bound: u64,
) -> Option<BigInt> {
    if matches!(p, Pt2::Inf) {
        return None;
    }
    // Factor n_p, requiring all prime factors ≤ smoothness_bound.
    let mut residue = n_p;
    let mut factors: Vec<(u64, u32)> = Vec::new();
    let mut prime: u64 = 2;
    while prime <= smoothness_bound && prime * prime <= residue {
        let mut e = 0u32;
        while residue % prime == 0 {
            residue /= prime;
            e += 1;
        }
        if e > 0 {
            factors.push((prime, e));
        }
        prime += if prime == 2 { 1 } else { 2 };
    }
    if residue > 1 {
        if residue > smoothness_bound {
            return None; // not B-smooth
        }
        factors.push((residue, 1));
    }
    // Solve in each prime-power subgroup.
    let mut crt_pairs: Vec<(u64, u64)> = Vec::new();
    for (ell, e) in &factors {
        let pe = ell.pow(*e);
        let cofactor = n_p / pe;
        let p_sub = pt_scalar_mul(p, &BigInt::from(cofactor), a, p_mod);
        let q_sub = pt_scalar_mul(q, &BigInt::from(cofactor), a, p_mod);
        // Brute-force DLP in subgroup of order pe (small).
        let d_sub = brute_dlp(&p_sub, &q_sub, pe, a, p_mod)?;
        crt_pairs.push((d_sub, pe));
    }
    // CRT.
    Some(crt_combine(&crt_pairs))
}

/// Brute-force DLP scan: find `d ∈ [0, m)` with `d·p = q`.
fn brute_dlp(p: &Pt2, q: &Pt2, m: u64, a: &BigInt, p_mod: &BigInt) -> Option<u64> {
    let mut acc = Pt2::Inf;
    for d in 0..m {
        if &acc == q {
            return Some(d);
        }
        acc = pt_add(&acc, p, a, p_mod);
    }
    None
}

/// CRT-combine `(d_i mod m_i)` pairs into `d mod ∏ m_i`.  Assumes
/// `m_i` pairwise coprime (true when each `m_i` is a distinct prime
/// power factor of a single integer).
fn crt_combine(pairs: &[(u64, u64)]) -> BigInt {
    let mut x: BigInt = BigInt::zero();
    let mut m: BigInt = BigInt::one();
    for &(r, mi) in pairs {
        let mi_bi = BigInt::from(mi);
        let r_bi = BigInt::from(r);
        // Solve x_new = x + m · k such that x_new ≡ r (mod mi).
        // ⇔ m · k ≡ (r − x) (mod mi)
        // ⇔ k ≡ m⁻¹ · (r − x) (mod mi)
        let diff = mod_pos(r_bi - &x, &mi_bi);
        let m_red = mod_pos(m.clone(), &mi_bi);
        let m_inv = modular_inverse(&m_red, &mi_bi).unwrap_or(BigInt::one());
        let k = mod_pos(m_inv * diff, &mi_bi);
        x = &x + &m * &k;
        m = m * mi_bi;
    }
    x
}

/// Result of a CGA-HNC attack run.
#[derive(Clone, Debug)]
pub struct CgaHncResult {
    /// CRT-combined recovery: `(d, M)` where `d ≡ true_d (mod M)`.
    /// If `M ≥ true_d`, full recovery.
    pub d_known: BigInt,
    pub modulus: BigInt,
    /// Number of orbit curves where Pohlig-Hellman returned a valid
    /// partial recovery.
    pub useful_curves: usize,
    /// Number of orbit curves whose PH info **strictly extended**
    /// the running CRT modulus (i.e., contributed cross-curve
    /// cooperation beyond the first useful curve).
    pub cooperative_curves: usize,
    /// Total orbit curves visited.
    pub orbit_size: usize,
    /// If non-`None`, the BSGS residual cleanup recovered the full
    /// secret as `Some(d)`.  Cost reported as the BSGS table size.
    pub residual_recovered_d: Option<BigInt>,
    pub residual_bsgs_cost: Option<u64>,
}

/// **End-to-end CGA-HNC attack** on a small curve.
///
/// Walks the 2-isogeny orbit of `(a_0, b_0)/F_p` from depth 0 up to
/// `max_depth`, transports the target `(P, Q)` to each curve via
/// composed 2-isogenies, runs Pohlig-Hellman on each curve's smooth
/// subgroup, and CRT-aggregates the per-prime best-known partial
/// recoveries.  Optionally runs a BSGS-style residual cleanup on the
/// original curve to complete the recovery if the orbit-CRT modulus
/// is short of the point order.
///
/// Phase 3+ demonstration — for `p ≤ ~10⁵` and depth ≤ ~20.  The
/// `residual_bsgs_max` parameter caps the residual-search size; if
/// `n_curve / M` exceeds this, the cleanup is skipped (caller can
/// then post-process from the returned `(d_known, modulus)`).
pub fn cga_hnc_attack(
    a_0: &BigInt,
    b_0: &BigInt,
    p_mod: &BigInt,
    p_pt: &Pt2,
    q_pt: &Pt2,
    smoothness_bound: u64,
    max_depth: u32,
    residual_bsgs_max: u64,
) -> CgaHncResult {
    cga_hnc_attack_verbose(
        a_0,
        b_0,
        p_mod,
        p_pt,
        q_pt,
        smoothness_bound,
        max_depth,
        residual_bsgs_max,
        false,
    )
}

#[doc(hidden)]
pub fn cga_hnc_attack_verbose(
    a_0: &BigInt,
    b_0: &BigInt,
    p_mod: &BigInt,
    p_pt: &Pt2,
    q_pt: &Pt2,
    smoothness_bound: u64,
    max_depth: u32,
    residual_bsgs_max: u64,
    verbose: bool,
) -> CgaHncResult {
    use std::collections::HashMap;

    let mut crt_pairs: HashMap<u64, (u64, u64)> = HashMap::new();
    let mut useful = 0usize;
    let mut cooperative = 0usize;
    let mut last_modulus: BigInt = BigInt::one();

    // BFS over the 2-isogeny graph, tracking (curve coefficients,
    // current point pair on that curve, depth).
    let mut queue: std::collections::VecDeque<(BigInt, BigInt, Pt2, Pt2, u32)> =
        std::collections::VecDeque::new();
    let mut seen: std::collections::HashSet<Vec<u8>> = std::collections::HashSet::new();
    queue.push_back((a_0.clone(), b_0.clone(), p_pt.clone(), q_pt.clone(), 0));

    let mut orbit_size = 0usize;

    while let Some((a, b, p_curve, q_curve, depth)) = queue.pop_front() {
        let j = match j_invariant(&a, &b, p_mod) {
            Some(j) => j,
            None => continue,
        };
        let key = j.to_signed_bytes_be();
        if !seen.insert(key) {
            continue;
        }
        orbit_size += 1;

        let n_curve = count_points_brute(&a, &b, p_mod);
        let p_order = point_order(&p_curve, n_curve, &a, p_mod);
        if p_order > 1 {
            if let Some(d_partial) =
                pohlig_hellman_dlp(&p_curve, &q_curve, p_order, &a, p_mod, smoothness_bound)
            {
                // **Sanity-check the PH recovery before trusting it**: verify
                // d_partial · P_curve = Q_curve.  If not, the per-curve PH
                // returned a wrong value — most often because we used a
                // factor of `p_order` that only divides #E_i, not ord(P_i)
                // exactly.  Rather than poison the CRT state, skip this
                // curve.  Originally this manifested as `d=14, d_known=0`
                // due to an off-by-one in ord(P_i) propagation through
                // composed isogenies.
                let d_partial_p = pt_scalar_mul(&p_curve, &d_partial, &a, p_mod);
                if &d_partial_p == &q_curve {
                    let prev_modulus = combined_modulus(&crt_pairs);
                    add_crt_factors(&mut crt_pairs, &d_partial, p_order, smoothness_bound);
                    let new_modulus = combined_modulus(&crt_pairs);
                    useful += 1;
                    if new_modulus > prev_modulus {
                        cooperative += 1;
                    }
                    last_modulus = new_modulus;
                    if verbose {
                        eprintln!(
                            "    [curve@depth={}] (a={}, b={}) ord(P_i)={} → d≡{} (mod {})",
                            depth, a, b, p_order, d_partial, p_order
                        );
                    }
                } else if verbose {
                    eprintln!(
                        "    [curve@depth={}] (a={}, b={}) ord(P_i)={} PH gave d_partial={} \
                         but verification FAILED — skipping",
                        depth, a, b, p_order, d_partial
                    );
                }
            }
        }

        if depth >= max_depth {
            continue;
        }
        let alphas = two_torsion_x_coords(&a, &b, p_mod);
        for alpha in alphas {
            let (a_new, b_new) = two_isogeny_codomain(&alpha, &a, p_mod);
            let p_new = two_isogeny_transport_point(&p_curve, &alpha, &a, p_mod);
            let q_new = two_isogeny_transport_point(&q_curve, &alpha, &a, p_mod);
            queue.push_back((a_new, b_new, p_new, q_new, depth + 1));
        }
    }

    let (d_known, modulus) = crt_combine_map(&crt_pairs);
    let _ = last_modulus; // keep for potential future use
    debug_assert!(&modulus == &combined_modulus(&crt_pairs));

    // ── Residual cleanup via BSGS on the original curve ────────────
    //
    // After CRT we know `d ≡ d_known (mod M)`.  Define
    // `R = Q − d_known · P` on the original curve E.  Then
    // `R = (M · u) · P` for some `u ∈ [0, ord(P)/M)`.  Solve via
    // BSGS in `O(√(ord(P)/M))` ops — the proposal's residual-cleanup
    // angle in its simplest form.  When `M` is comparable to
    // `ord(P)`, this is much cheaper than plain BSGS on the full
    // `[0, ord(P))` range.
    let mut residual_recovered_d = None;
    let mut residual_bsgs_cost = None;
    if modulus > BigInt::zero() {
        let n_curve = count_points_brute(a_0, b_0, p_mod);
        let p_order_full = point_order(p_pt, n_curve, a_0, p_mod);
        let p_order_bi = BigInt::from(p_order_full);

        // Fast path: if the CRT modulus already exceeds `ord(P)`, then
        // `d_known mod ord(P)` IS the secret (when consistent).
        let d_candidate = mod_pos(d_known.clone(), &p_order_bi);
        let recomputed_q = pt_scalar_mul(p_pt, &d_candidate, a_0, p_mod);
        if &recomputed_q == q_pt {
            residual_recovered_d = Some(d_candidate);
            residual_bsgs_cost = Some(0);
        } else if let Some(m) = modulus_to_u64(&modulus) {
            // Slow path: residual BSGS for u ∈ [0, ord(P)/M).
            if m > 0 && p_order_full % m == 0 {
                let u_range = p_order_full / m;
                if u_range > 1 && u_range <= residual_bsgs_max {
                    let dknown_p = pt_scalar_mul(p_pt, &d_known, a_0, p_mod);
                    let neg_dknown_p = match dknown_p {
                        Pt2::Aff(x, y) => Pt2::Aff(x, mod_pos(-y, p_mod)),
                        Pt2::Inf => Pt2::Inf,
                    };
                    let r_pt = pt_add(q_pt, &neg_dknown_p, a_0, p_mod);
                    let mp = pt_scalar_mul(p_pt, &BigInt::from(m), a_0, p_mod);
                    if let Some(u) = bsgs_dlp(&mp, &r_pt, u_range, a_0, p_mod) {
                        let d = &d_known + &modulus * BigInt::from(u);
                        let d_mod = mod_pos(d, &p_order_bi);
                        // Verify.
                        let test_q = pt_scalar_mul(p_pt, &d_mod, a_0, p_mod);
                        if &test_q == q_pt {
                            residual_recovered_d = Some(d_mod);
                            residual_bsgs_cost = Some(((u_range as f64).sqrt().ceil()) as u64);
                        }
                    }
                }
            }
        }
    }

    CgaHncResult {
        d_known,
        modulus,
        useful_curves: useful,
        cooperative_curves: cooperative,
        orbit_size,
        residual_recovered_d,
        residual_bsgs_cost,
    }
}

fn combined_modulus(pairs: &std::collections::HashMap<u64, (u64, u64)>) -> BigInt {
    let mut m = BigInt::one();
    for &(_, pe) in pairs.values() {
        m = m * BigInt::from(pe);
    }
    m
}

fn crt_combine_map(pairs: &std::collections::HashMap<u64, (u64, u64)>) -> (BigInt, BigInt) {
    let mut d = BigInt::zero();
    let mut m = BigInt::one();
    // Distinct primes ⇒ pairwise coprime moduli.
    for &(r, mi) in pairs.values() {
        let mi_bi = BigInt::from(mi);
        let diff = mod_pos(BigInt::from(r) - &d, &mi_bi);
        let m_red = mod_pos(m.clone(), &mi_bi);
        let m_inv = modular_inverse(&m_red, &mi_bi).unwrap_or(BigInt::one());
        let k = mod_pos(m_inv * diff, &mi_bi);
        d = &d + &m * &k;
        m = m * mi_bi;
    }
    (d, m)
}

fn modulus_to_u64(m: &BigInt) -> Option<u64> {
    m.to_u64_digits().1.first().copied().or(Some(1))
}

/// Baby-step giant-step DLP on an affine curve.  Searches for `d ∈
/// [0, n)` such that `d · base = target`.  `O(√n)` time and memory.
fn bsgs_dlp(base: &Pt2, target: &Pt2, n: u64, a: &BigInt, p_mod: &BigInt) -> Option<u64> {
    use std::collections::HashMap;
    let m = (n as f64).sqrt().ceil() as u64;
    if m == 0 {
        return None;
    }
    // Baby steps: store {j · base : j = 0..m}.
    let mut table: HashMap<Vec<u8>, u64> = HashMap::with_capacity(m as usize + 1);
    let mut p = Pt2::Inf;
    for j in 0..=m {
        table.insert(serialise_pt(&p), j);
        p = pt_add(&p, base, a, p_mod);
    }
    // Giant step: M = m · base; search target − i · M for i ∈ [0, m].
    let m_step = pt_scalar_mul(base, &BigInt::from(m), a, p_mod);
    let neg_m_step = match m_step {
        Pt2::Aff(x, y) => Pt2::Aff(x, mod_pos(-y, p_mod)),
        Pt2::Inf => Pt2::Inf,
    };
    let mut current = target.clone();
    for i in 0..=m {
        if let Some(&j) = table.get(&serialise_pt(&current)) {
            let d = i.checked_mul(m).and_then(|v| v.checked_add(j))?;
            if d < n {
                return Some(d);
            }
        }
        current = pt_add(&current, &neg_m_step, a, p_mod);
    }
    None
}

fn serialise_pt(p: &Pt2) -> Vec<u8> {
    match p {
        Pt2::Inf => vec![0u8],
        Pt2::Aff(x, y) => {
            let mut out = vec![1u8];
            let mut xb = x.to_signed_bytes_be();
            let mut yb = y.to_signed_bytes_be();
            out.extend_from_slice(&(xb.len() as u32).to_be_bytes());
            out.append(&mut xb);
            out.extend_from_slice(&(yb.len() as u32).to_be_bytes());
            out.append(&mut yb);
            out
        }
    }
}

/// Add the factors of a partial-recovery `(d_partial, m)` to the
/// running per-prime "best-known" map.  For each prime `ℓ` dividing
/// `m` (and ≤ `smoothness_bound`), we keep a single best-known pair
/// `(r, ℓᵉ)` per prime — replacing the existing pair iff the new
/// `ℓᵉ` is strictly larger AND the partial recovery is consistent
/// (i.e., agrees with the existing one on `gcd(ℓᵉ, ℓᵉ_existing)`).
///
/// **Correctness fix from Phase 2 demo**: the prior implementation
/// suppressed strictly-larger prime-power info from later orbit
/// curves on the grounds that "we already have this prime."  Cross-
/// curve cooperation requires *replacement*, not suppression.
fn add_crt_factors(
    pairs: &mut std::collections::HashMap<u64, (u64, u64)>,
    d_partial: &BigInt,
    m: u64,
    smoothness_bound: u64,
) {
    let mut residue = m;
    let mut prime: u64 = 2;
    while prime <= smoothness_bound && prime * prime <= residue {
        let mut e = 0u32;
        while residue % prime == 0 {
            residue /= prime;
            e += 1;
        }
        if e > 0 {
            let pe = prime.pow(e);
            let r = mod_pos(d_partial.clone(), &BigInt::from(pe))
                .to_u64_digits()
                .1
                .first()
                .copied()
                .unwrap_or(0);
            update_prime_pair(pairs, prime, r, pe);
        }
        prime += if prime == 2 { 1 } else { 2 };
    }
    if residue > 1 && residue <= smoothness_bound {
        let r = mod_pos(d_partial.clone(), &BigInt::from(residue))
            .to_u64_digits()
            .1
            .first()
            .copied()
            .unwrap_or(0);
        update_prime_pair(pairs, residue, r, residue);
    }
}

/// Update `pairs[prime]` with `(r_new, pe_new)`, keeping the strictly-
/// larger prime power on consistency.  Inconsistent pairs (same prime,
/// disagreeing residues on the gcd) are discarded — they imply one of
/// the per-curve recoveries was wrong, but at toy scale this rarely
/// happens; at scale, this is where one would log/audit.
fn update_prime_pair(
    pairs: &mut std::collections::HashMap<u64, (u64, u64)>,
    prime: u64,
    r_new: u64,
    pe_new: u64,
) {
    match pairs.get(&prime) {
        None => {
            pairs.insert(prime, (r_new, pe_new));
        }
        Some(&(r_old, pe_old)) => {
            let g = gcd_u64(pe_old, pe_new);
            if r_old % g != r_new % g {
                // Inconsistent — keep existing, skip new.  Deleting
                // the existing pair would lose previously-good info,
                // which surfaced as a regression on `d=14, 15` in the
                // first 3.1 sweep.  A future improvement: track all
                // candidate residues per prime and run a Bleichenbacher-
                // style majority vote.
                return;
            }
            if pe_new > pe_old {
                pairs.insert(prime, (r_new, pe_new));
            }
        }
    }
}

/// CRT-combine list of `(remainder, modulus)` pairs into a single
/// `(d, M)` where `d ≡ remainder_i (mod modulus_i)` for every pair
/// and `M = lcm(modulus_i)`.  Inconsistent pairs (same prime power
/// with different remainders) are silently skipped on a first-come-
/// first-served basis.
#[allow(dead_code)] // legacy; the HashMap-based version is preferred
fn crt_combine_pairs(pairs: &[(u64, u64)]) -> (BigInt, BigInt) {
    let mut d = BigInt::zero();
    let mut m = BigInt::one();
    for &(r, mi) in pairs {
        let mi_bi = BigInt::from(mi);
        let g = gcd_bi(&m, &mi_bi);
        if g != BigInt::one() {
            // Already have info on overlapping factor; check consistency.
            let r_existing = mod_pos(d.clone(), &g);
            let r_new = mod_pos(BigInt::from(r), &g);
            if r_existing != r_new {
                continue; // inconsistent; skip
            }
            // Reduce mi by gcd; CRT only the new part.
            let mi_reduced = &mi_bi / &g;
            if mi_reduced == BigInt::one() {
                continue;
            }
            // (skip for simplicity — full impl would extend)
            continue;
        }
        // Pairwise coprime; standard CRT.
        let diff = mod_pos(BigInt::from(r) - &d, &mi_bi);
        let m_red = mod_pos(m.clone(), &mi_bi);
        let m_inv = modular_inverse(&m_red, &mi_bi).unwrap_or(BigInt::one());
        let k = mod_pos(m_inv * diff, &mi_bi);
        d = &d + &m * &k;
        m = m * mi_bi;
    }
    (d, m)
}

fn gcd_bi(a: &BigInt, b: &BigInt) -> BigInt {
    let mut x = a.clone();
    let mut y = b.clone();
    while !y.is_zero() {
        let r = &x % &y;
        x = y;
        y = r;
    }
    x.abs()
}

#[cfg(test)]
mod tests {
    use super::*;
    use num_bigint::BigInt;

    /// j(y² = x³ + 1) ≡ 0.
    #[test]
    fn j_invariant_x3_plus_1() {
        let p = BigInt::from(101);
        let j = j_invariant(&BigInt::zero(), &BigInt::one(), &p).unwrap();
        assert_eq!(j, BigInt::zero());
    }

    /// j(y² = x³ − x) ≡ 1728.
    #[test]
    fn j_invariant_x3_minus_x() {
        let p = BigInt::from(2017);
        let neg_one = (BigInt::from(-1) % &p + &p) % &p;
        let j = j_invariant(&neg_one, &BigInt::zero(), &p).unwrap();
        assert_eq!(j, BigInt::from(1728) % &p);
    }

    /// `curve_from_j_invariant` round-trips: j(curve(j)) = j.
    #[test]
    fn j_curve_roundtrip() {
        let p = BigInt::from(2017);
        for raw_j in [0i64, 1, 2, 100, 500, 1000, 1727, 1728, 1729, 2016] {
            let j = (BigInt::from(raw_j) % &p + &p) % &p;
            let (a, b) = curve_from_j_invariant(&j, &p).unwrap();
            let j2 = j_invariant(&a, &b, &p).expect("non-singular");
            assert_eq!(j2, j, "round-trip failed for j = {}", raw_j);
        }
    }

    /// Φ_2(j, j) for j(E) ≠ j(E·2) is non-zero (no self-loop in 2-iso graph
    /// for a generic E).  Sanity check that Φ_2 is not the zero polynomial.
    #[test]
    fn phi_2_nonzero() {
        let p = BigInt::from(1009);
        let j = BigInt::from(123);
        let coeffs = phi_2_evaluate(&j, &p);
        // At least one coefficient should be non-zero.
        assert!(coeffs.iter().any(|c| !c.is_zero()));
    }

    /// Brute-force point count: y² = x³ + 1 over F_5 has 6 points.
    /// (1 at infinity + (0, ±1), (4, ±2), and two more).  Standard
    /// reference value: |E(F_5)| = 6 for E: y² = x³ + 1.
    #[test]
    fn point_count_x3_plus_1_f5() {
        let p = BigInt::from(5);
        let n = count_points_brute(&BigInt::zero(), &BigInt::one(), &p);
        assert_eq!(n, 6, "|y² = x³ + 1 over F_5| = 6");
    }

    /// Hasse bound smoke test: |#E(F_p) - (p+1)| ≤ 2√p.
    #[test]
    fn point_count_satisfies_hasse() {
        let p = BigInt::from(101);
        for a in [1, 2, 3, 4, 5] {
            for b in [1, 2, 3] {
                let a_bi = BigInt::from(a);
                let b_bi = BigInt::from(b);
                if j_invariant(&a_bi, &b_bi, &p).is_none() {
                    continue; // singular
                }
                let n = count_points_brute(&a_bi, &b_bi, &p);
                let p_u: i64 = 101;
                let expected = p_u + 1;
                let dev = (n as i64 - expected).abs();
                let bound = (2.0 * (p_u as f64).sqrt()).ceil() as i64 + 1;
                assert!(
                    dev <= bound,
                    "Hasse violated for a={}, b={}: n={}, expected~{}, dev={}",
                    a,
                    b,
                    n,
                    expected,
                    dev
                );
            }
        }
    }

    /// Smoothness: 720 = 2⁴ · 3² · 5 has 720-smooth-part = 720, but
    /// with bound B=5 only the 2,3,5 factors count → smooth_part = 720.
    /// With B=4: 2⁴·3² = 144, 5 excluded → smooth_part = 144.
    #[test]
    fn smoothness_decomposition() {
        assert_eq!(largest_smooth_divisor(720, 5), 720);
        assert_eq!(largest_smooth_divisor(720, 4), 144);
        assert_eq!(
            largest_smooth_divisor(101, 100),
            1,
            "101 prime, no small factor"
        );
        assert_eq!(
            largest_smooth_divisor(101, 101),
            101,
            "with bound = 101 itself"
        );
    }

    /// Orbit traversal terminates and returns at least the start curve.
    #[test]
    fn orbit_bfs_terminates() {
        let p = BigInt::from(101);
        let a = BigInt::from(1);
        let b = BigInt::from(1);
        let orbit = bfs_two_isogeny_orbit(&a, &b, &p, 50);
        assert!(orbit.len() >= 1, "orbit must contain start curve");
        let starting_j = j_invariant(&a, &b, &p).unwrap();
        assert_eq!(orbit[0].0, starting_j, "first visited = start");
    }

    /// Smoothness report runs end-to-end on a small curve.
    #[test]
    fn orbit_smoothness_report_runs() {
        let p = BigInt::from(101);
        let report = orbit_smoothness_report(&BigInt::from(1), &BigInt::from(1), &p, 50, 20);
        assert!(!report.rows.is_empty(), "should visit ≥ 1 curve");
        // Sanity: total_bits_crt ≤ log₂(p) · |orbit| (not tight, just a bound)
        let p_bits = (p.bits() as f64) * (report.rows.len() as f64);
        assert!(report.total_bits_crt <= p_bits + 1.0);
    }

    /// **Experiment P1.1**: Across 12 random small ordinary curves
    /// over `F_p` for `p = 1009` (10-bit prime), measure CRT-coverage
    /// of `d` from the 2-isogeny orbit using smoothness bound `B = 50`.
    /// Print the distribution.  This tests the proposal's quantitative
    /// claim — we want to see whether typical curves have orbit
    /// CRT-coverage near `log_2(p)` (good for the attack) or near `0`
    /// (bad for the attack).
    #[test]
    #[ignore = "experimental: runs ~30s of orbit walks; --ignored to opt in"]
    fn experiment_p1_smoothness_at_p_1009() {
        let p = BigInt::from(1009);
        let p_bits = p.bits() as f64;
        println!();
        println!("== CGA-HNC Experiment P1.1: p = 1009 (10-bit) ==");
        println!("| start curve   | #orbit | naive bits | CRT bits  | CRT/log₂(p) |");
        println!("|---------------|--------|------------|-----------|-------------|");

        let mut totals: Vec<f64> = Vec::new();
        for &(a, b) in &[
            (1i64, 1i64),
            (1, 2),
            (2, 3),
            (3, 1),
            (5, 7),
            (7, 11),
            (11, 13),
            (13, 1),
            (17, 1),
            (23, 5),
            (29, 31),
            (37, 1),
        ] {
            let a_bi = BigInt::from(a);
            let b_bi = BigInt::from(b);
            if j_invariant(&a_bi, &b_bi, &p).is_none() {
                continue;
            }
            let report = orbit_smoothness_report(&a_bi, &b_bi, &p, 50, 100);
            let frac = report.total_bits_crt / p_bits;
            println!(
                "| ({:>3}, {:>3})    | {:>6} | {:>10.2} | {:>9.2} | {:>11.3} |",
                a,
                b,
                report.rows.len(),
                report.total_bits_naive,
                report.total_bits_crt,
                frac
            );
            totals.push(frac);
        }

        if !totals.is_empty() {
            let mean = totals.iter().sum::<f64>() / totals.len() as f64;
            let max = totals.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
            let min = totals.iter().cloned().fold(f64::INFINITY, f64::min);
            println!();
            println!(
                "Across {} curves: mean CRT/log₂(p) = {:.3}, min = {:.3}, max = {:.3}",
                totals.len(),
                mean,
                min,
                max
            );
            println!();
            println!("Interpretation: a value near 1.0 means the orbit fully covers the");
            println!("256-bit-equivalent secret via CRT alone (no rho needed); a value");
            println!("near 0.0 means the orbit gives no useful CRT amortisation.  Mid-");
            println!("values indicate the proposal's HNP-residual-cleanup angle is");
            println!("where the action is.");
        }
    }

    /// **Experiment P1.2**: Same as P1.1 but with a smaller smoothness
    /// bound (B = 10) — measures how aggressively the orbit covers
    /// only-very-small-prime factors.
    #[test]
    #[ignore = "experimental: runs ~30s of orbit walks; --ignored to opt in"]
    fn experiment_p1_smoothness_at_p_1009_b10() {
        let p = BigInt::from(1009);
        let p_bits = p.bits() as f64;
        println!();
        println!("== CGA-HNC Experiment P1.2: p = 1009, B = 10 ==");
        let mut totals: Vec<f64> = Vec::new();
        for &(a, b) in &[
            (1i64, 1i64),
            (1, 2),
            (2, 3),
            (3, 1),
            (5, 7),
            (7, 11),
            (11, 13),
            (13, 1),
            (17, 1),
            (23, 5),
            (29, 31),
            (37, 1),
        ] {
            let a_bi = BigInt::from(a);
            let b_bi = BigInt::from(b);
            if j_invariant(&a_bi, &b_bi, &p).is_none() {
                continue;
            }
            let report = orbit_smoothness_report(&a_bi, &b_bi, &p, 10, 100);
            totals.push(report.total_bits_crt / p_bits);
        }
        if !totals.is_empty() {
            let mean = totals.iter().sum::<f64>() / totals.len() as f64;
            let max = totals.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
            let min = totals.iter().cloned().fold(f64::INFINITY, f64::min);
            println!(
                "Across {} curves at B=10: mean CRT/log₂(p) = {:.3}, min = {:.3}, max = {:.3}",
                totals.len(),
                mean,
                min,
                max
            );
        }
    }

    // ── Phase 2 tests ───────────────────────────────────────────────

    /// 2-isogeny codomain: verify `Φ_2(j(E), j(E')) ≡ 0 (mod p)` for
    /// a randomly chosen curve and 2-torsion point.
    #[test]
    fn two_isogeny_codomain_verified_by_phi_2() {
        let p_mod = BigInt::from(101);
        // E: y² = x³ + 1, 2-torsion at x = 100 (since 100³ + 1 ≡ 0 mod 101).
        let a = BigInt::from(0);
        let b = BigInt::from(1);
        let alpha = BigInt::from(100);
        // Verify alpha is 2-torsion: alpha³ + a·alpha + b ≡ 0.
        let lhs = mod_pos(alpha.pow(3) + &a * &alpha + &b, &p_mod);
        assert!(lhs.is_zero(), "alpha must be 2-torsion");
        let (a_new, b_new) = two_isogeny_codomain(&alpha, &a, &p_mod);
        let j_src = j_invariant(&a, &b, &p_mod).unwrap();
        let j_dst = j_invariant(&a_new, &b_new, &p_mod).unwrap();
        // Φ_2(j_src, j_dst) ≡ 0 mod p
        let coeffs = phi_2_evaluate(&j_src, &p_mod);
        let val = mod_pos(
            &coeffs[0]
                + &coeffs[1] * &j_dst
                + &coeffs[2] * j_dst.pow(2)
                + &coeffs[3] * j_dst.pow(3),
            &p_mod,
        );
        assert!(val.is_zero(), "Φ_2(j_src, j_dst) ≢ 0 (got {})", val);
    }

    /// Point operations: 2·P should equal P + P.
    #[test]
    fn double_equals_self_plus_self() {
        let p_mod = BigInt::from(101);
        let a = BigInt::from(1);
        let b = BigInt::from(1);
        // Find a point on E by trying x = 0, 1, 2, ...
        let mut found: Option<Pt2> = None;
        for x_u in 0u64..101 {
            let x = BigInt::from(x_u);
            let rhs = mod_pos(x.pow(3) + &a * &x + &b, &p_mod);
            // Find y such that y² = rhs.
            for y_u in 0u64..101 {
                if mod_pos(BigInt::from(y_u).pow(2), &p_mod) == rhs {
                    found = Some(Pt2::Aff(x.clone(), BigInt::from(y_u)));
                    break;
                }
            }
            if found.is_some() {
                break;
            }
        }
        let pt = found.expect("a curve point");
        let dbl = pt_double(&pt, &a, &p_mod);
        let add = pt_add(&pt, &pt, &a, &p_mod);
        assert_eq!(dbl, add, "2P ≠ P + P");
    }

    /// Scalar multiplication: n·P = O where n = #E(F_p).
    #[test]
    fn point_order_divides_curve_order() {
        let p_mod = BigInt::from(101);
        let a = BigInt::from(1);
        let b = BigInt::from(1);
        let n_curve = count_points_brute(&a, &b, &p_mod);
        // Find a point.
        let pt = (|| {
            for x_u in 0u64..101 {
                let x = BigInt::from(x_u);
                let rhs = mod_pos(x.pow(3) + &a * &x + &b, &p_mod);
                for y_u in 0u64..101 {
                    if mod_pos(BigInt::from(y_u).pow(2), &p_mod) == rhs {
                        return Some(Pt2::Aff(x, BigInt::from(y_u)));
                    }
                }
            }
            None
        })()
        .unwrap();
        let n_p = pt_scalar_mul(&pt, &BigInt::from(n_curve), &a, &p_mod);
        assert_eq!(n_p, Pt2::Inf, "n_curve · P should be infinity");
    }

    /// Pohlig-Hellman: plant d, recover it.
    #[test]
    fn pohlig_hellman_recovers_planted_d() {
        let p_mod = BigInt::from(1009);
        let a = BigInt::from(1);
        let b = BigInt::from(2);
        let n_curve = count_points_brute(&a, &b, &p_mod);
        // Find a point of full curve order.
        let mut pt = None;
        for x_u in 0u64..1009 {
            let x = BigInt::from(x_u);
            let rhs = mod_pos(x.pow(3) + &a * &x + &b, &p_mod);
            // Check y² = rhs.
            for y_u in 1u64..1009 {
                if mod_pos(BigInt::from(y_u).pow(2), &p_mod) == rhs {
                    let candidate = Pt2::Aff(x.clone(), BigInt::from(y_u));
                    let order = point_order(&candidate, n_curve, &a, &p_mod);
                    if order > 1 {
                        pt = Some((candidate, order));
                        break;
                    }
                }
            }
            if pt.is_some() {
                break;
            }
        }
        let (p_pt, p_ord) = pt.expect("a non-identity point");
        // Plant d, ensure d < p_ord.
        let d_true = BigInt::from(7);
        let q_pt = pt_scalar_mul(&p_pt, &d_true, &a, &p_mod);
        let recovered = pohlig_hellman_dlp(&p_pt, &q_pt, p_ord, &a, &p_mod, 1000)
            .expect("PH recovery should succeed");
        // Recovery is mod p_ord.
        let r = mod_pos(recovered, &BigInt::from(p_ord));
        assert_eq!(r, d_true, "PH recovered wrong d");
    }

    /// **Phase 2 end-to-end demo**: planted-d recovery on the
    /// brittle (a=1, b=2) / F_1009 curve from the P1.1 experiment
    /// (CRT/log₂(p) = 1.796).  Walk the orbit, transport target,
    /// run Pohlig-Hellman + CRT.  Verify recovery.
    #[test]
    #[ignore = "experimental Phase-2 demo; --ignored to opt in"]
    fn phase_2_end_to_end_recovery_on_brittle_curve() {
        let p_mod = BigInt::from(1009);
        let a = BigInt::from(1);
        let b = BigInt::from(2);
        let n_curve = count_points_brute(&a, &b, &p_mod);
        // Find a point of order > 1 on E.
        let p_pt = (|| {
            for x_u in 0u64..1009 {
                let x = BigInt::from(x_u);
                let rhs = mod_pos(x.pow(3) + &a * &x + &b, &p_mod);
                for y_u in 1u64..1009 {
                    if mod_pos(BigInt::from(y_u).pow(2), &p_mod) == rhs {
                        let p = Pt2::Aff(x.clone(), BigInt::from(y_u));
                        if point_order(&p, n_curve, &a, &p_mod) > 1 {
                            return Some(p);
                        }
                    }
                }
            }
            None
        })()
        .unwrap();
        let p_order = point_order(&p_pt, n_curve, &a, &p_mod);

        // Plant d, ensure d < p_order so it's recoverable mod p_order.
        let d_true = BigInt::from(73 % (p_order as i64));
        let q_pt = pt_scalar_mul(&p_pt, &d_true, &a, &p_mod);

        println!();
        println!("== Phase 2 demo: (a=1, b=2) / F_1009 ==");
        println!(
            "  n_curve = {}, p_order = {}, planted d = {}",
            n_curve, p_order, d_true
        );

        let result = cga_hnc_attack(&a, &b, &p_mod, &p_pt, &q_pt, 100, 8, 100);
        println!(
            "  attack: orbit_size = {}, useful_curves = {}, cooperative = {}",
            result.orbit_size, result.useful_curves, result.cooperative_curves
        );
        let modulus_clone = result.modulus.clone();
        let modulus_for_div = if modulus_clone > BigInt::zero() {
            modulus_clone.clone()
        } else {
            BigInt::one()
        };
        println!(
            "  CRT: d_known = {} (mod {}); residual u-range = {}",
            result.d_known,
            result.modulus,
            BigInt::from(p_order) / &modulus_for_div,
        );
        if let (Some(d_full), Some(cost)) =
            (&result.residual_recovered_d, result.residual_bsgs_cost)
        {
            println!(
                "  BSGS residual cleanup recovered d = {} at cost {} ops",
                d_full, cost
            );
            assert_eq!(
                mod_pos(d_full.clone(), &BigInt::from(p_order)),
                d_true,
                "BSGS-cleaned recovery mismatched plant"
            );
            return; // success
        }

        // Verify recovery is consistent with planted d (mod the recovered modulus).
        let p_order_bi = BigInt::from(p_order);
        let m_gcd = gcd_bi(&result.modulus, &p_order_bi);
        let d_known_mod_g = mod_pos(result.d_known.clone(), &m_gcd);
        let d_true_mod_g = mod_pos(d_true.clone(), &m_gcd);
        println!(
            "  consistency check (mod gcd({}, {}) = {}): recovered = {}, true = {}",
            result.modulus, p_order, m_gcd, d_known_mod_g, d_true_mod_g
        );
        assert_eq!(
            d_known_mod_g, d_true_mod_g,
            "CGA-HNC recovered d inconsistent with planted d"
        );
    }

    /// **Phase 3 Experiment 3.1**: Sweep many planted `d` values on
    /// the brittle (a=1, b=2)/F_1009 curve.  Measure the distribution
    /// of `useful_curves`, `cooperative_curves`, and BSGS-residual
    /// cost.  The goal: test whether cross-curve cooperation
    /// (`cooperative_curves > 1`) happens for a non-trivial fraction
    /// of `d` values, or whether `useful_curves = 1` was the typical
    /// case in the Phase 2 demo.
    #[test]
    #[ignore = "Phase-3 experimental sweep; --ignored to opt in"]
    fn experiment_3_1_useful_curves_distribution() {
        let p_mod = BigInt::from(1009);
        let a = BigInt::from(1);
        let b = BigInt::from(2);
        let n_curve = count_points_brute(&a, &b, &p_mod);

        // Pick a fixed point P of large order on E.
        let (p_pt, p_order) = (|| {
            for x_u in 0u64..1009 {
                let x = BigInt::from(x_u);
                let rhs = mod_pos(x.pow(3) + &a * &x + &b, &p_mod);
                for y_u in 1u64..1009 {
                    if mod_pos(BigInt::from(y_u).pow(2), &p_mod) == rhs {
                        let pt = Pt2::Aff(x.clone(), BigInt::from(y_u));
                        let ord = point_order(&pt, n_curve, &a, &p_mod);
                        if ord >= 28 {
                            return Some((pt, ord));
                        }
                    }
                }
            }
            None
        })()
        .unwrap();

        println!();
        println!("== Phase 3 Experiment 3.1: useful_curves distribution ==");
        println!(
            "  curve (a=1, b=2) / F_1009: n_curve = {}, ord(P) = {}",
            n_curve, p_order
        );
        println!(
            "| d_planted | useful | cooperative | CRT-mod | residual range | BSGS ops | recovered? |"
        );
        println!(
            "|-----------|--------|-------------|---------|----------------|----------|------------|"
        );

        let mut full_recoveries = 0;
        let mut total = 0;
        let mut cooperative_total = 0;
        let mut bsgs_total: u64 = 0;
        let mut bsgs_max: u64 = 0;

        // Sample 24 planted d values across [1, p_order).
        let sample: Vec<u64> = (1..p_order)
            .step_by(((p_order / 24).max(1)) as usize)
            .collect();
        for &d_u in &sample {
            let d_planted = BigInt::from(d_u);
            let q_pt = pt_scalar_mul(&p_pt, &d_planted, &a, &p_mod);
            let result = cga_hnc_attack(
                &a, &b, &p_mod, &p_pt, &q_pt, 100,     // smoothness bound
                8,       // depth
                p_order, // residual_bsgs_max — allow full BSGS
            );
            let m_u = modulus_to_u64(&result.modulus).unwrap_or(1);
            let residual_range = if m_u > 0 { p_order / m_u } else { p_order };
            let bsgs_ops = result
                .residual_bsgs_cost
                .unwrap_or(((residual_range as f64).sqrt().ceil()) as u64);
            let recovered = result.residual_recovered_d.is_some();
            println!(
                "| {:>9} | {:>6} | {:>11} | {:>7} | {:>14} | {:>8} | {:>10} |  d_known={}",
                d_u,
                result.useful_curves,
                result.cooperative_curves,
                m_u,
                residual_range,
                bsgs_ops,
                if recovered { "yes" } else { "no" },
                result.d_known,
            );
            total += 1;
            cooperative_total += result.cooperative_curves;
            bsgs_total += bsgs_ops;
            bsgs_max = bsgs_max.max(bsgs_ops);
            if recovered {
                full_recoveries += 1;
            }
        }

        let plain_rho_cost = ((p_order as f64).sqrt().ceil()) as u64;
        let mean_bsgs = bsgs_total as f64 / total as f64;
        println!();
        println!(
            "Across {} planted d values: full recoveries = {}/{} ({:.0}%)",
            total,
            full_recoveries,
            total,
            100.0 * full_recoveries as f64 / total as f64
        );
        println!(
            "  Mean cooperative_curves = {:.2}, mean BSGS cost = {:.1} ops, max = {}",
            cooperative_total as f64 / total as f64,
            mean_bsgs,
            bsgs_max
        );
        println!(
            "  Plain rho on this curve: ~{} ops.  CGA-HNC mean: {} ops.",
            plain_rho_cost, mean_bsgs
        );
        if mean_bsgs < plain_rho_cost as f64 {
            println!(
                "  ✓ CGA-HNC beat plain rho by factor {:.2} on average for this curve.",
                plain_rho_cost as f64 / mean_bsgs
            );
        } else {
            println!(
                "  ✗ CGA-HNC did not beat plain rho on average ({:.2}× rho cost).",
                mean_bsgs / plain_rho_cost as f64
            );
        }
    }

    /// **Phase 3 Experiment 3.3 — the key one**: Force PH-on-original
    /// to be insufficient by using a tight smoothness bound, then
    /// measure whether orbit cooperation closes the gap.  At
    /// `B = 5`, PH on `(a=1, b=2)/F_1009` (ord(P) = 28 = 2²·7)
    /// recovers only `d mod 4` from the original curve (the 7-part
    /// requires orbit help).
    #[test]
    #[ignore = "Phase-3 experimental sweep; --ignored to opt in"]
    fn experiment_3_3_cross_curve_necessity() {
        let p_mod = BigInt::from(1009);
        let a = BigInt::from(1);
        let b = BigInt::from(2);
        let n_curve = count_points_brute(&a, &b, &p_mod);

        let (p_pt, p_order) = (|| {
            for x_u in 0u64..1009 {
                let x = BigInt::from(x_u);
                let rhs = mod_pos(x.pow(3) + &a * &x + &b, &p_mod);
                for y_u in 1u64..1009 {
                    if mod_pos(BigInt::from(y_u).pow(2), &p_mod) == rhs {
                        let pt = Pt2::Aff(x.clone(), BigInt::from(y_u));
                        let ord = point_order(&pt, n_curve, &a, &p_mod);
                        if ord >= 28 {
                            return Some((pt, ord));
                        }
                    }
                }
            }
            None
        })()
        .unwrap();

        println!();
        println!("== Phase 3 Experiment 3.3: cross-curve necessity (B=5) ==");
        println!(
            "  (a=1, b=2) / F_1009: n_curve = {}, ord(P) = {}",
            n_curve, p_order
        );
        println!("  At B=5, prime 7 in ord(P) = 28 is NOT recoverable from the");
        println!("  original curve alone — the orbit must contribute.");
        println!();

        let mut full_recoveries_orbit = 0;
        let mut full_recoveries_no_orbit = 0;
        let mut total = 0;

        let sample: Vec<u64> = (1..p_order)
            .step_by(((p_order / 14).max(1)) as usize)
            .collect();
        for &d_u in &sample {
            let d_planted = BigInt::from(d_u);
            let q_pt = pt_scalar_mul(&p_pt, &d_planted, &a, &p_mod);

            // (a) With orbit (depth=8): orbit can supply d mod 7.
            let with_orbit = cga_hnc_attack(
                &a, &b, &p_mod, &p_pt, &q_pt, 5, // tight smoothness bound
                8, // full orbit
                p_order,
            );
            // (b) Without orbit (depth=0): just PH on original curve.
            let no_orbit = cga_hnc_attack(
                &a, &b, &p_mod, &p_pt, &q_pt, 5, // tight smoothness bound
                0, // no orbit walk
                p_order,
            );

            let r_orbit = with_orbit.residual_recovered_d.is_some();
            let r_no = no_orbit.residual_recovered_d.is_some();
            total += 1;
            if r_orbit {
                full_recoveries_orbit += 1;
            }
            if r_no {
                full_recoveries_no_orbit += 1;
            }
            println!(
                "  d={:>3}: with-orbit recovery = {} (mod {}), no-orbit recovery = {} (mod {})",
                d_u,
                if r_orbit { "✓" } else { "✗" },
                with_orbit.modulus,
                if r_no { "✓" } else { "✗" },
                no_orbit.modulus,
            );
        }

        println!();
        println!(
            "  WITH orbit: {}/{} ({:.0}%) recovered",
            full_recoveries_orbit,
            total,
            100.0 * full_recoveries_orbit as f64 / total as f64
        );
        println!(
            "  WITHOUT orbit (single-curve PH only): {}/{} ({:.0}%) recovered",
            full_recoveries_no_orbit,
            total,
            100.0 * full_recoveries_no_orbit as f64 / total as f64
        );
        if full_recoveries_orbit > full_recoveries_no_orbit {
            println!(
                "  ✓ ORBIT COOPERATION DEMONSTRATED: +{} recoveries from cross-curve info",
                full_recoveries_orbit - full_recoveries_no_orbit
            );
        }
    }

    /// **Phase 3 Experiment 3.2**: Same sweep but on a curve from
    /// the Phase-1 "non-brittle" tail — `(a=7, b=11)/F_1009` had
    /// CRT/log₂(p) ≈ 0.317 (low orbit info).  We expect CGA-HNC to
    /// degenerate to plain BSGS / rho cost on this curve.
    #[test]
    #[ignore = "Phase-3 experimental sweep; --ignored to opt in"]
    fn experiment_3_2_useful_curves_on_non_brittle() {
        let p_mod = BigInt::from(1009);
        let a = BigInt::from(7);
        let b = BigInt::from(11);
        let n_curve = count_points_brute(&a, &b, &p_mod);

        let (p_pt, p_order) = (|| {
            for x_u in 0u64..1009 {
                let x = BigInt::from(x_u);
                let rhs = mod_pos(x.pow(3) + &a * &x + &b, &p_mod);
                for y_u in 1u64..1009 {
                    if mod_pos(BigInt::from(y_u).pow(2), &p_mod) == rhs {
                        let pt = Pt2::Aff(x.clone(), BigInt::from(y_u));
                        let ord = point_order(&pt, n_curve, &a, &p_mod);
                        if ord >= 28 {
                            return Some((pt, ord));
                        }
                    }
                }
            }
            None
        })()
        .unwrap();

        println!();
        println!("== Phase 3 Experiment 3.2: non-brittle curve ==");
        println!(
            "  (a=7, b=11) / F_1009: n_curve = {}, ord(P) = {}",
            n_curve, p_order
        );

        let mut total = 0;
        let mut cooperative_total = 0;
        let mut full_recoveries = 0;
        let sample: Vec<u64> = (1..p_order)
            .step_by(((p_order / 16).max(1)) as usize)
            .collect();
        for &d_u in &sample {
            let d_planted = BigInt::from(d_u);
            let q_pt = pt_scalar_mul(&p_pt, &d_planted, &a, &p_mod);
            let result = cga_hnc_attack(&a, &b, &p_mod, &p_pt, &q_pt, 100, 8, p_order);
            total += 1;
            cooperative_total += result.cooperative_curves;
            if result.residual_recovered_d.is_some() {
                full_recoveries += 1;
            }
        }
        println!(
            "  {} d values: full recoveries = {}/{}, mean cooperative = {:.2}",
            total,
            full_recoveries,
            total,
            cooperative_total as f64 / total as f64
        );
    }

    /// **Experiment P1.3**: Larger field `p = 10007` (14-bit prime),
    /// fewer curves, smoothness bound matching ~log p.  This is closer
    /// to the regime where Pohlig-Hellman is non-trivial.
    #[test]
    #[ignore = "experimental: ~2 min of orbit walks; --ignored to opt in"]
    fn experiment_p1_at_p_10007() {
        let p = BigInt::from(10_007);
        let p_bits = p.bits() as f64;
        println!();
        println!("== CGA-HNC Experiment P1.3: p = 10007 (14-bit), B = 100 ==");
        let mut totals: Vec<f64> = Vec::new();
        for &(a, b) in &[
            (1i64, 1i64),
            (1, 2),
            (2, 3),
            (3, 1),
            (5, 7),
            (7, 11),
            (11, 13),
            (17, 1),
        ] {
            let a_bi = BigInt::from(a);
            let b_bi = BigInt::from(b);
            if j_invariant(&a_bi, &b_bi, &p).is_none() {
                continue;
            }
            let report = orbit_smoothness_report(&a_bi, &b_bi, &p, 100, 60);
            let frac = report.total_bits_crt / p_bits;
            println!(
                "(a={:>3}, b={:>3}): orbit={}, CRT bits = {:.2}, fraction = {:.3}",
                a,
                b,
                report.rows.len(),
                report.total_bits_crt,
                frac
            );
            totals.push(frac);
        }
        if !totals.is_empty() {
            let mean = totals.iter().sum::<f64>() / totals.len() as f64;
            let max = totals.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
            println!(
                "Mean CRT/log₂(p) = {:.3}, max = {:.3} across {} curves",
                mean,
                max,
                totals.len()
            );
        }
    }
}
