//! # Coordinate search: an algorithmic hunt for point representations that
//! make decomposition relations cheaper.
//!
//! Index calculus on an elliptic curve spends its time on the *point
//! decomposition problem*: given `R`, find factor-base points with
//! `P_1 + ⋯ + P_m = R`.  Every solver in this repository asks that question
//! through Semaev's summation polynomial in the Weierstrass `x`-coordinate.
//! The `x`-coordinate is one function on the curve among many, and the
//! literature has a handful of others that were found by hand — the
//! `y`-coordinate of a twisted Edwards curve (Faugère–Gaudry–Huot–Renault),
//! the coordinates of Kohel's `μ₄`-normal form, `λ`-coordinates on binary
//! curves, Jacobi quartics, Huff and Hessian models.  This module replaces
//! the hand search with an algorithm.
//!
//! ## What the algorithm knows before it starts
//!
//! Two structural facts prune the search from "all rational functions on
//! `E`" to something finite, and both are checked numerically rather than
//! trusted.
//!
//! 1. **A degree-2 coordinate is a Möbius frame on the `x`-line.**  A
//!    separable degree-2 map `E → P¹` is the quotient by an involution
//!    `P ↦ T' − P`; conjugating by a translation moves `T'` to `O`, so every
//!    degree-2 coordinate is `N(x(P + S))` for a Möbius map `N ∈ PGL₂(K)`.
//!    The translation only shifts the factor base, so the search over
//!    coordinates of degree 2 *is* the search over frames `N`.
//! 2. **A coordinate invariant under a translation subgroup factors through
//!    an isogeny**, and the discrete logarithm is isogeny-invariant.  Being
//!    invariant under `E[ℓ]` buys exactly nothing beyond working on `E/E[ℓ]`.
//!    What buys something is a symmetry that acts *linearly* on a degree-2
//!    coordinate: then the summation polynomial is an invariant of a linear
//!    group action, and invariant theory lowers its degree.
//!
//! So the objects to enumerate are the symmetries of the relation
//! `P_1 + ⋯ + P_{m+1} = O` that descend to the `x`-line as Möbius maps:
//! translation by rational 2-torsion, the automorphisms of `E`, and — on a
//! subfield curve — the Frobenius.  Each is *detected* by fitting a Möbius
//! map to `(x(P), x(γP))` pairs and verifying it on every point.  Each is
//! then *classified by scope*, again by experiment: a translation by
//! 2-torsion may be applied to any even number of the points and the
//! relation survives (`Σ(P_i + k_i T) = ΣP_i + (Σk_i)T`); an automorphism
//! or the Frobenius must be applied to all of them at once.  Only the
//! pairwise ones lower the degree of the polynomial; the global ones
//! collapse factor-base orbits in the linear algebra, which
//! [`crate::cryptanalysis::koblitz_index_calculus`] already exploits.
//!
//! ## What it does
//!
//! For each pairwise symmetry `g` it computes the frame that makes `g`
//! linear: over odd characteristic an involution with rational fixed points
//! becomes `t ↦ −t` after sending the fixed points to `0` and `∞`; in
//! characteristic 2 an involution of `P¹` is unipotent with a single fixed
//! point, and sending it to `∞` gives `t ↦ t + 1`.  In that frame the
//! relation-preserving group acts on `(P¹)^{m+1}` by even-weight sign flips
//! or even-weight translations, whose invariant ring is generated by
//! `w_i = u_i²` and `Π u_i` (respectively `w_i = u_i² + u_i` and `Σ u_i`).
//! It then **interpolates** the summation polynomial in those invariants
//! from random relation tuples — no symbolic algebra, no formulas, just a
//! kernel computation over the field — and measures the result:
//!
//! - degree in each variable and number of monomials, against the same
//!   numbers for the plain Semaev polynomial in the same frame;
//! - the **collapse factor**: how many relation tuples map to one point of
//!   the invariant coordinates, computed by enumerating the fibre rather
//!   than by counting group elements;
//! - whether the coordinate commutes with the Frobenius, i.e. whether the
//!   factor base can stay Frobenius-invariant (the Koblitz constraint);
//! - a Weil-descent cost model for a factor base cut out by a subspace.
//!
//! Every interpolated polynomial is verified on fresh relation tuples and
//! checked to be non-zero on random non-relations before it is reported.
//!
//! ## Honest scope
//!
//! Toy fields only: `F_p` with `p < 2²²` and `F_{2^n}` with `n ≤ 22`.  The
//! polynomials are specialised to one curve, which is all the shape
//! measurements need.  Nothing here solves a decomposition; it produces the
//! system the solvers would have to solve and says how big it is.  See
//! `RESEARCH_EXOTIC_COORDINATES.md` for the measurements and for what they
//! do and do not imply.
//!
//! ## References
//!
//! - I. Semaev, *Summation polynomials and the discrete logarithm problem
//!   on elliptic curves*, ePrint 2004/031.
//! - J.-C. Faugère, P. Gaudry, L. Huot, G. Renault, *Using symmetries in
//!   the index calculus for elliptic curves discrete logarithm*,
//!   J. Cryptology 27 (2014).
//! - J.-C. Faugère, L. Huot, A. Joux, G. Renault, V. Vitse, *Symmetrized
//!   summation polynomials: using small order torsion points to speed up
//!   elliptic curve index calculus*, EUROCRYPT 2014.
//! - S. D. Galbraith, S. W. Gebregiyorgis, *Summation polynomial algorithms
//!   for elliptic curves in characteristic two*, INDOCRYPT 2014.
//! - D. Kohel, *Efficient arithmetic on elliptic curves in characteristic
//!   2*, INDOCRYPT 2012 (the `μ₄`-normal form).

use std::collections::HashMap;
use std::fmt::Write as _;

use super::koblitz_index_calculus::find_irreducible;
use crate::binary_ecc::f2m::IrreduciblePoly;

/// The point at infinity of the projective line `P¹(K) = K ∪ {∞}`.
pub const INF: u64 = u64::MAX;

const NONE32: u32 = u32::MAX;

// ---------------------------------------------------------------------------
// Deterministic RNG
// ---------------------------------------------------------------------------

/// xorshift64* — deterministic, seedable, dependency-free.
#[derive(Clone, Debug)]
pub struct Rng64(u64);

impl Rng64 {
    pub fn new(seed: u64) -> Self {
        Rng64(seed.wrapping_mul(0x9E37_79B9_7F4A_7C15) | 1)
    }
    pub fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }
    pub fn below(&mut self, n: u64) -> u64 {
        self.next_u64() % n
    }
}

// ---------------------------------------------------------------------------
// Small finite fields: F_p (p odd prime) and F_{2^n}, elements as u64
// ---------------------------------------------------------------------------

/// A finite field of order `q = p^n` small enough to tabulate square roots:
/// either a prime field (`n = 1`) or a binary field `F_{2^n}` in polynomial
/// basis.  Elements are `u64` in `[0, q)`; for binary fields the integer is
/// the coefficient bit-vector.
#[derive(Clone, Debug)]
pub struct Gf {
    pub p: u64,
    pub n: u32,
    pub q: u64,
    poly: u64,
    sqrt_tab: Vec<u32>,
    as_tab: Vec<u32>,
    /// Binary fields: `log_tab[a] = k` with `g^k = a`, `exp_tab[k] = g^k`
    /// (doubled so that `exp_tab[i + j]` needs no reduction).
    log_tab: Vec<u32>,
    exp_tab: Vec<u32>,
}

impl Gf {
    /// Prime field `F_p`, `p` an odd prime `< 2²²`.
    pub fn prime(p: u64) -> Self {
        assert!(p >= 5 && p < (1 << 22), "prime field out of toy range");
        assert!(is_prime_u64(p), "{p} is not prime");
        let mut sqrt_tab = vec![NONE32; p as usize];
        for a in 0..p {
            let sq = ((a as u128 * a as u128) % p as u128) as usize;
            if sqrt_tab[sq] == NONE32 {
                sqrt_tab[sq] = a as u32;
            }
        }
        Gf {
            p,
            n: 1,
            q: p,
            poly: 0,
            sqrt_tab,
            as_tab: Vec::new(),
            log_tab: Vec::new(),
            exp_tab: Vec::new(),
        }
    }

    /// Binary field `F_{2^n}` with the same irreducible polynomial the
    /// Koblitz index-calculus module uses, so element encodings agree.
    pub fn binary(n: u32) -> Self {
        let irr = find_irreducible(n).expect("irreducible polynomial");
        Self::binary_with(&irr)
    }

    /// Binary field with an explicit irreducible polynomial.
    pub fn binary_with(irr: &IrreduciblePoly) -> Self {
        let n = irr.degree;
        assert!((2..=22).contains(&n), "binary field out of toy range");
        let mut poly = 1u64 << n;
        for &t in &irr.low_terms {
            poly |= 1 << t;
        }
        let q = 1u64 << n;
        let mut f = Gf {
            p: 2,
            n,
            q,
            poly,
            sqrt_tab: Vec::new(),
            as_tab: Vec::new(),
            log_tab: Vec::new(),
            exp_tab: Vec::new(),
        };
        // Discrete-log tables from a generator of the multiplicative group.
        let order = q - 1;
        let mut gen = 2u64;
        loop {
            let mut exp_tab = vec![0u32; 2 * order as usize];
            let mut log_tab = vec![NONE32; q as usize];
            let mut v = 1u64;
            let mut ok = true;
            for k in 0..order {
                if log_tab[v as usize] != NONE32 {
                    ok = false;
                    break;
                }
                log_tab[v as usize] = k as u32;
                exp_tab[k as usize] = v as u32;
                exp_tab[(k + order) as usize] = v as u32;
                v = f.clmul_reduce(v, gen);
            }
            if ok {
                f.log_tab = log_tab;
                f.exp_tab = exp_tab;
                break;
            }
            gen += 1;
        }
        let mut sqrt_tab = vec![NONE32; q as usize];
        let mut as_tab = vec![NONE32; q as usize];
        for a in 0..q {
            let sq = f.mul(a, a);
            sqrt_tab[sq as usize] = a as u32;
            let asv = sq ^ a;
            if as_tab[asv as usize] == NONE32 {
                as_tab[asv as usize] = a as u32;
            }
        }
        f.sqrt_tab = sqrt_tab;
        f.as_tab = as_tab;
        f
    }

    pub fn is_binary(&self) -> bool {
        self.p == 2
    }

    pub fn add(&self, a: u64, b: u64) -> u64 {
        if self.p == 2 {
            a ^ b
        } else {
            let s = a + b;
            if s >= self.q {
                s - self.q
            } else {
                s
            }
        }
    }
    pub fn sub(&self, a: u64, b: u64) -> u64 {
        if self.p == 2 {
            a ^ b
        } else if a >= b {
            a - b
        } else {
            a + self.q - b
        }
    }
    pub fn neg(&self, a: u64) -> u64 {
        if self.p == 2 || a == 0 {
            a
        } else {
            self.q - a
        }
    }
    /// Carry-less product reduced modulo the field polynomial (no tables).
    fn clmul_reduce(&self, a: u64, b: u64) -> u64 {
        let mut r = 0u64;
        let mut x = a;
        let mut y = b;
        while y != 0 {
            if y & 1 == 1 {
                r ^= x;
            }
            x <<= 1;
            y >>= 1;
        }
        let n = self.n;
        for i in (n..2 * n).rev() {
            if (r >> i) & 1 == 1 {
                r ^= self.poly << (i - n);
            }
        }
        r
    }

    pub fn mul(&self, a: u64, b: u64) -> u64 {
        if self.p == 2 {
            if a == 0 || b == 0 {
                return 0;
            }
            if !self.log_tab.is_empty() {
                let k = self.log_tab[a as usize] as usize + self.log_tab[b as usize] as usize;
                return self.exp_tab[k] as u64;
            }
            let mut r = 0u64;
            let mut x = a;
            let mut y = b;
            while y != 0 {
                if y & 1 == 1 {
                    r ^= x;
                }
                x <<= 1;
                y >>= 1;
            }
            let n = self.n;
            for i in (n..2 * n).rev() {
                if (r >> i) & 1 == 1 {
                    r ^= self.poly << (i - n);
                }
            }
            r
        } else {
            ((a as u128 * b as u128) % self.q as u128) as u64
        }
    }
    pub fn pow(&self, mut a: u64, mut e: u64) -> u64 {
        let mut r = 1u64;
        while e > 0 {
            if e & 1 == 1 {
                r = self.mul(r, a);
            }
            a = self.mul(a, a);
            e >>= 1;
        }
        r
    }
    pub fn inv(&self, a: u64) -> u64 {
        assert!(a != 0, "inverse of zero");
        if self.p == 2 && !self.log_tab.is_empty() {
            let order = (self.q - 1) as usize;
            let k = self.log_tab[a as usize] as usize;
            return self.exp_tab[(order - k) % order] as u64;
        }
        self.pow(a, self.q - 2)
    }
    pub fn div(&self, a: u64, b: u64) -> u64 {
        self.mul(a, self.inv(b))
    }
    /// A square root of `a`, if one exists.
    pub fn sqrt(&self, a: u64) -> Option<u64> {
        let v = self.sqrt_tab[a as usize];
        (v != NONE32).then_some(v as u64)
    }
    /// A solution `t` of `t² + t = c` (binary fields only).
    pub fn artin_schreier(&self, c: u64) -> Option<u64> {
        assert!(self.p == 2);
        let v = self.as_tab[c as usize];
        (v != NONE32).then_some(v as u64)
    }
    /// `a ↦ a^p`, the absolute Frobenius (identity on a prime field).
    pub fn frob(&self, a: u64) -> u64 {
        if self.p == 2 {
            self.mul(a, a)
        } else {
            a
        }
    }
    /// `a ↦ a^{p^d}`.
    pub fn frob_pow(&self, mut a: u64, d: u32) -> u64 {
        for _ in 0..d {
            a = self.frob(a);
        }
        a
    }
    /// Does `a` lie in the subfield `F_{p^d}`?
    pub fn in_subfield(&self, a: u64, d: u32) -> bool {
        self.frob_pow(a, d) == a
    }
    /// The elements of the subfield `F_{p^d}` (`d | n`).
    pub fn subfield_elements(&self, d: u32) -> Vec<u64> {
        (0..self.q).filter(|&a| self.in_subfield(a, d)).collect()
    }
    /// Uniformly random element.
    pub fn random(&self, rng: &mut Rng64) -> u64 {
        rng.below(self.q)
    }
    /// Display an element: decimal for prime fields, hex bit-vector for
    /// binary ones.
    pub fn show(&self, a: u64) -> String {
        if a == INF {
            "∞".to_string()
        } else if self.p == 2 {
            format!("0x{a:x}")
        } else {
            a.to_string()
        }
    }
    pub fn name(&self) -> String {
        if self.p == 2 {
            format!("F_2^{}", self.n)
        } else {
            format!("F_{}", self.p)
        }
    }
}

fn is_prime_u64(n: u64) -> bool {
    if n < 2 {
        return false;
    }
    let mut d = 2;
    while d * d <= n {
        if n % d == 0 {
            return false;
        }
        d += 1;
    }
    true
}

// ---------------------------------------------------------------------------
// Curves in long Weierstrass form (any characteristic)
// ---------------------------------------------------------------------------

/// A point on the curve.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Pt {
    Inf,
    Aff(u64, u64),
}

impl Pt {
    /// `x(P)`, with `x(O) = ∞`.
    pub fn x(&self) -> u64 {
        match self {
            Pt::Inf => INF,
            Pt::Aff(x, _) => *x,
        }
    }
}

/// An automorphism of `E` fixing `O`, in the shapes that occur over the
/// fields handled here.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Auto {
    /// `P ↦ −P`.
    Neg,
    /// `(x, y) ↦ (u² x, u³ y)` on a short Weierstrass curve.
    Scale(u64),
}

/// `E : y² + a₁xy + a₃y = x³ + a₂x² + a₄x + a₆` over [`Gf`].
#[derive(Clone, Debug)]
pub struct Curve {
    pub f: Gf,
    pub a1: u64,
    pub a2: u64,
    pub a3: u64,
    pub a4: u64,
    pub a6: u64,
    pub label: String,
}

impl Curve {
    /// `y² = x³ + a x + b` over an odd-characteristic field.
    pub fn short_weierstrass(f: Gf, a: u64, b: u64, label: &str) -> Self {
        assert!(f.p != 2);
        Curve {
            f,
            a1: 0,
            a2: 0,
            a3: 0,
            a4: a,
            a6: b,
            label: label.to_string(),
        }
    }

    /// `y² + xy = x³ + a₂x² + a₆` over a binary field.
    pub fn binary(f: Gf, a2: u64, a6: u64, label: &str) -> Self {
        assert!(f.p == 2);
        Curve {
            f,
            a1: 1,
            a2,
            a3: 0,
            a4: 0,
            a6,
            label: label.to_string(),
        }
    }

    /// The Koblitz curve `K_a : y² + xy = x³ + a x² + 1` over `F_{2^n}`.
    pub fn koblitz(a: u8, n: u32) -> Self {
        Self::binary(Gf::binary(n), a as u64, 1, &format!("K_{a}/F_2^{n}"))
    }

    pub fn is_on(&self, p: Pt) -> bool {
        match p {
            Pt::Inf => true,
            Pt::Aff(x, y) => {
                let f = &self.f;
                let lhs = f.add(
                    f.add(f.mul(y, y), f.mul(f.mul(self.a1, x), y)),
                    f.mul(self.a3, y),
                );
                let x2 = f.mul(x, x);
                let rhs = f.add(
                    f.add(f.mul(x2, x), f.mul(self.a2, x2)),
                    f.add(f.mul(self.a4, x), self.a6),
                );
                lhs == rhs
            }
        }
    }

    pub fn neg(&self, p: Pt) -> Pt {
        match p {
            Pt::Inf => Pt::Inf,
            Pt::Aff(x, y) => {
                let f = &self.f;
                Pt::Aff(x, f.neg(f.add(f.add(y, f.mul(self.a1, x)), self.a3)))
            }
        }
    }

    pub fn add(&self, p: Pt, q: Pt) -> Pt {
        let f = &self.f;
        let (x1, y1) = match p {
            Pt::Inf => return q,
            Pt::Aff(x, y) => (x, y),
        };
        let (x2, y2) = match q {
            Pt::Inf => return p,
            Pt::Aff(x, y) => (x, y),
        };
        let lambda = if x1 != x2 {
            f.div(f.sub(y2, y1), f.sub(x2, x1))
        } else {
            if self.neg(p) == q {
                return Pt::Inf;
            }
            // doubling: λ = (3x² + 2a₂x + a₄ − a₁y) / (2y + a₁x + a₃)
            let three = f.add(f.add(1, 1), 1);
            let two = f.add(1, 1);
            let num = f.sub(
                f.add(
                    f.add(f.mul(three, f.mul(x1, x1)), f.mul(f.mul(two, self.a2), x1)),
                    self.a4,
                ),
                f.mul(self.a1, y1),
            );
            let den = f.add(f.add(f.mul(two, y1), f.mul(self.a1, x1)), self.a3);
            if den == 0 {
                return Pt::Inf;
            }
            f.div(num, den)
        };
        let nu = f.sub(y1, f.mul(lambda, x1));
        let x3 = f.sub(
            f.sub(
                f.add(f.mul(lambda, lambda), f.mul(self.a1, lambda)),
                self.a2,
            ),
            f.add(x1, x2),
        );
        let y3 = f.sub(f.sub(f.neg(f.mul(f.add(lambda, self.a1), x3)), nu), self.a3);
        Pt::Aff(x3, y3)
    }

    pub fn sub(&self, p: Pt, q: Pt) -> Pt {
        self.add(p, self.neg(q))
    }

    pub fn mul(&self, p: Pt, mut k: u64) -> Pt {
        let mut r = Pt::Inf;
        let mut b = p;
        while k > 0 {
            if k & 1 == 1 {
                r = self.add(r, b);
            }
            b = self.add(b, b);
            k >>= 1;
        }
        r
    }

    /// The affine points with abscissa `x`.
    pub fn lift_x(&self, x: u64) -> Vec<Pt> {
        let f = &self.f;
        let x2 = f.mul(x, x);
        let rhs = f.add(
            f.add(f.mul(x2, x), f.mul(self.a2, x2)),
            f.add(f.mul(self.a4, x), self.a6),
        );
        // y² + B y − rhs = 0 with B = a₁x + a₃
        let bb = f.add(f.mul(self.a1, x), self.a3);
        if f.p == 2 {
            if bb == 0 {
                return vec![Pt::Aff(x, f.sqrt(rhs).expect("squaring is bijective"))];
            }
            // y = B t, t² + t = rhs / B²
            let c = f.div(rhs, f.mul(bb, bb));
            match f.artin_schreier(c) {
                Some(t) => vec![Pt::Aff(x, f.mul(bb, t)), Pt::Aff(x, f.mul(bb, t ^ 1))],
                None => vec![],
            }
        } else {
            let disc = f.add(f.mul(bb, bb), f.mul(f.add(f.add(1, 1), f.add(1, 1)), rhs));
            match f.sqrt(disc) {
                None => vec![],
                Some(s) => {
                    let inv2 = f.inv(f.add(1, 1));
                    let y1 = f.mul(f.sub(s, bb), inv2);
                    let y2 = f.mul(f.sub(f.neg(s), bb), inv2);
                    if y1 == y2 {
                        vec![Pt::Aff(x, y1)]
                    } else {
                        vec![Pt::Aff(x, y1), Pt::Aff(x, y2)]
                    }
                }
            }
        }
    }

    /// All affine points, in abscissa order.
    pub fn affine_points(&self) -> Vec<Pt> {
        (0..self.f.q).flat_map(|x| self.lift_x(x)).collect()
    }

    /// `#E(K)`.
    pub fn order(&self) -> u64 {
        self.affine_points().len() as u64 + 1
    }

    /// The non-trivial rational 2-torsion points.
    pub fn two_torsion(&self) -> Vec<Pt> {
        self.affine_points()
            .into_iter()
            .filter(|&p| self.neg(p) == p)
            .collect()
    }

    /// The `j`-invariant, or `None` for a singular curve.
    pub fn j_invariant(&self) -> Option<u64> {
        let f = &self.f;
        let (a1, a2, a3, a4, a6) = (self.a1, self.a2, self.a3, self.a4, self.a6);
        let c = |k: u64| f.pow(f.add(1, 1), 0).wrapping_mul(0) + (k % f.p); // small integer as field elt
        let int = |k: u64| -> u64 {
            let mut r = 0;
            for _ in 0..(k % f.p) {
                r = f.add(r, 1);
            }
            r
        };
        let _ = c;
        let b2 = f.add(f.mul(a1, a1), f.mul(int(4), a2));
        let b4 = f.add(f.mul(int(2), a4), f.mul(a1, a3));
        let b6 = f.add(f.mul(a3, a3), f.mul(int(4), a6));
        let b8 = f.sub(
            f.add(
                f.add(f.mul(f.mul(a1, a1), a6), f.mul(f.mul(int(4), a2), a6)),
                f.add(f.mul(f.mul(a2, a3), a3), f.neg(f.mul(f.mul(a1, a3), a4))),
            ),
            f.mul(a4, a4),
        );
        let c4 = f.sub(f.mul(b2, b2), f.mul(int(24), b4));
        let disc = f.sub(
            f.sub(
                f.add(
                    f.neg(f.mul(f.mul(b2, b2), b8)),
                    f.mul(f.mul(int(9), b2), f.mul(b4, b6)),
                ),
                f.mul(int(8), f.pow(b4, 3)),
            ),
            f.mul(int(27), f.mul(b6, b6)),
        );
        if disc == 0 {
            None
        } else {
            Some(f.div(f.pow(c4, 3), disc))
        }
    }

    /// The automorphisms of `E` fixing `O`, as far as this module's curve
    /// shapes go: `±1` always; `(x, y) ↦ (u²x, u³y)` for every `u` that
    /// preserves a short Weierstrass equation.
    pub fn automorphisms(&self) -> Vec<Auto> {
        let mut out = vec![Auto::Scale(1), Auto::Neg];
        if self.f.p != 2 && self.a1 == 0 && self.a2 == 0 && self.a3 == 0 {
            let f = &self.f;
            for u in 2..f.q {
                let u2 = f.mul(u, u);
                let u4 = f.mul(u2, u2);
                let u6 = f.mul(u4, u2);
                if u == f.neg(1) {
                    continue;
                }
                if f.mul(u4, self.a4) == self.a4 && f.mul(u6, self.a6) == self.a6 {
                    out.push(Auto::Scale(u));
                }
            }
        }
        out
    }

    pub fn apply_auto(&self, a: Auto, p: Pt) -> Pt {
        match (a, p) {
            (_, Pt::Inf) => Pt::Inf,
            (Auto::Neg, _) => self.neg(p),
            (Auto::Scale(u), Pt::Aff(x, y)) => {
                let f = &self.f;
                let u2 = f.mul(u, u);
                Pt::Aff(f.mul(u2, x), f.mul(f.mul(u2, u), y))
            }
        }
    }

    /// Smallest `d | n` with all coefficients in `F_{p^d}`, i.e. the degree
    /// of the field the curve is really defined over; `None` on a prime
    /// field, where there is no proper subfield to speak of.
    pub fn subfield_degree(&self) -> Option<u32> {
        if self.f.n == 1 {
            return None;
        }
        (1..=self.f.n).filter(|d| self.f.n % d == 0).find(|&d| {
            [self.a1, self.a2, self.a3, self.a4, self.a6]
                .iter()
                .all(|&a| self.f.in_subfield(a, d))
        })
    }

    /// `(x, y) ↦ (x^{p^d}, y^{p^d})`.
    pub fn frobenius(&self, p: Pt, d: u32) -> Pt {
        match p {
            Pt::Inf => Pt::Inf,
            Pt::Aff(x, y) => Pt::Aff(self.f.frob_pow(x, d), self.f.frob_pow(y, d)),
        }
    }
}

// ---------------------------------------------------------------------------
// Möbius transformations of P¹(K)
// ---------------------------------------------------------------------------

/// `t ↦ (a t + b) / (c t + d)`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct Mobius {
    pub a: u64,
    pub b: u64,
    pub c: u64,
    pub d: u64,
}

/// The shape of a Möbius map, up to the frame it is written in.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MobiusKind {
    Identity,
    /// `t ↦ c t`.
    Scaling(u64),
    /// `t ↦ c / t`.
    Inversion(u64),
    /// `t ↦ t + c`.
    Translation(u64),
    General,
}

impl Mobius {
    pub fn identity() -> Self {
        Mobius {
            a: 1,
            b: 0,
            c: 0,
            d: 1,
        }
    }

    pub fn apply(&self, f: &Gf, t: u64) -> u64 {
        if t == INF {
            if self.c == 0 {
                INF
            } else {
                f.div(self.a, self.c)
            }
        } else {
            let den = f.add(f.mul(self.c, t), self.d);
            if den == 0 {
                INF
            } else {
                f.div(f.add(f.mul(self.a, t), self.b), den)
            }
        }
    }

    /// `self ∘ other`.
    pub fn compose(&self, f: &Gf, other: &Mobius) -> Mobius {
        Mobius {
            a: f.add(f.mul(self.a, other.a), f.mul(self.b, other.c)),
            b: f.add(f.mul(self.a, other.b), f.mul(self.b, other.d)),
            c: f.add(f.mul(self.c, other.a), f.mul(self.d, other.c)),
            d: f.add(f.mul(self.c, other.b), f.mul(self.d, other.d)),
        }
        .normalise(f)
    }

    pub fn inverse(&self, f: &Gf) -> Mobius {
        Mobius {
            a: self.d,
            b: f.neg(self.b),
            c: f.neg(self.c),
            d: self.a,
        }
        .normalise(f)
    }

    /// `n ∘ self ∘ n⁻¹`: the same map written in the frame `n`.
    pub fn conjugate_by(&self, f: &Gf, n: &Mobius) -> Mobius {
        n.compose(f, self).compose(f, &n.inverse(f))
    }

    /// Scale so the first non-zero entry is `1`; makes projective equality
    /// plain equality.
    pub fn normalise(&self, f: &Gf) -> Mobius {
        let lead = [self.a, self.b, self.c, self.d]
            .into_iter()
            .find(|&v| v != 0)
            .expect("zero matrix");
        let inv = f.inv(lead);
        Mobius {
            a: f.mul(self.a, inv),
            b: f.mul(self.b, inv),
            c: f.mul(self.c, inv),
            d: f.mul(self.d, inv),
        }
    }

    pub fn is_identity(&self, f: &Gf) -> bool {
        let m = self.normalise(f);
        m.b == 0 && m.c == 0 && m.a == m.d
    }

    /// Multiplicative order, if it is at most `cap`.
    pub fn order(&self, f: &Gf, cap: u32) -> Option<u32> {
        let mut m = *self;
        for k in 1..=cap {
            if m.is_identity(f) {
                return Some(k);
            }
            m = m.compose(f, self);
        }
        None
    }

    /// The rational fixed points, solving `c t² + (d − a) t − b = 0`
    /// (and `∞` when `c = 0`).
    pub fn fixed_points(&self, f: &Gf) -> Vec<u64> {
        let mut out = Vec::new();
        if self.c == 0 {
            out.push(INF);
            // (d − a) t = b
            let k = f.sub(self.d, self.a);
            if k != 0 {
                out.push(f.div(self.b, k));
            }
            return out;
        }
        for t in 0..f.q {
            let v = f.sub(
                f.add(f.mul(f.mul(self.c, t), t), f.mul(f.sub(self.d, self.a), t)),
                self.b,
            );
            if v == 0 {
                out.push(t);
            }
        }
        out
    }

    pub fn kind(&self, f: &Gf) -> MobiusKind {
        let m = self.normalise(f);
        if m.is_identity(f) {
            MobiusKind::Identity
        } else if m.b == 0 && m.c == 0 {
            MobiusKind::Scaling(f.div(m.a, m.d))
        } else if m.a == 0 && m.d == 0 {
            MobiusKind::Inversion(f.div(m.b, m.c))
        } else if m.c == 0 && m.a == m.d {
            MobiusKind::Translation(f.div(m.b, m.d))
        } else {
            MobiusKind::General
        }
    }

    /// All four coefficients in `F_{p^d}`?
    pub fn in_subfield(&self, f: &Gf, d: u32) -> bool {
        let m = self.normalise(f);
        [m.a, m.b, m.c, m.d].iter().all(|&v| f.in_subfield(v, d))
    }

    /// Fit a Möbius map through `(t, s)` pairs; needs three in general
    /// position.  Returns `None` if the pairs are inconsistent or do not
    /// determine the map.
    pub fn fit(f: &Gf, pairs: &[(u64, u64)]) -> Option<Mobius> {
        let mut rows = Vec::new();
        for &(t, s) in pairs {
            let row = match (t == INF, s == INF) {
                (false, false) => vec![t, 1, f.neg(f.mul(s, t)), f.neg(s)],
                (true, false) => vec![1, 0, f.neg(s), 0],
                (false, true) => vec![0, 0, t, 1],
                (true, true) => vec![0, 0, 1, 0],
            };
            rows.push(row);
        }
        let ker = kernel(f, rows, 4);
        if ker.len() != 1 {
            return None;
        }
        let v = &ker[0];
        let m = Mobius {
            a: v[0],
            b: v[1],
            c: v[2],
            d: v[3],
        };
        let det = f.sub(f.mul(m.a, m.d), f.mul(m.b, m.c));
        (det != 0).then(|| m.normalise(f))
    }

    pub fn describe(&self, f: &Gf) -> String {
        let m = self.normalise(f);
        match m.kind(f) {
            MobiusKind::Identity => "t".to_string(),
            MobiusKind::Scaling(c) => format!("{}·t", f.show(c)),
            MobiusKind::Inversion(c) => format!("{}/t", f.show(c)),
            MobiusKind::Translation(c) => format!("t + {}", f.show(c)),
            MobiusKind::General => {
                let lin = |a: u64, b: u64| -> String {
                    match (a, b) {
                        (0, b) => f.show(b),
                        (1, 0) => "t".to_string(),
                        (a, 0) => format!("{}·t", f.show(a)),
                        (1, b) => format!("t + {}", f.show(b)),
                        (a, b) => format!("{}·t + {}", f.show(a), f.show(b)),
                    }
                };
                if m.c == 0 {
                    lin(f.div(m.a, m.d), f.div(m.b, m.d))
                } else {
                    format!("({})/({})", lin(m.a, m.b), lin(m.c, m.d))
                }
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Linear algebra: kernel over Gf
// ---------------------------------------------------------------------------

/// Basis of `{v : M v = 0}` for the row-major matrix `rows` with `ncols`
/// columns, by reduced row echelon form.
pub fn kernel(f: &Gf, mut rows: Vec<Vec<u64>>, ncols: usize) -> Vec<Vec<u64>> {
    let nrows = rows.len();
    let mut pivots: Vec<usize> = Vec::new();
    let mut r = 0;
    for c in 0..ncols {
        if r == nrows {
            break;
        }
        let Some(pi) = (r..nrows).find(|&i| rows[i][c] != 0) else {
            continue;
        };
        rows.swap(r, pi);
        let inv = f.inv(rows[r][c]);
        for cc in c..ncols {
            rows[r][cc] = f.mul(rows[r][cc], inv);
        }
        let pivot_row = rows[r].clone();
        for (i, row) in rows.iter_mut().enumerate() {
            if i == r || row[c] == 0 {
                continue;
            }
            let factor = row[c];
            for cc in c..ncols {
                if pivot_row[cc] != 0 {
                    row[cc] = f.sub(row[cc], f.mul(factor, pivot_row[cc]));
                }
            }
        }
        pivots.push(c);
        r += 1;
    }
    let mut is_pivot = vec![false; ncols];
    for &c in &pivots {
        is_pivot[c] = true;
    }
    let mut basis = Vec::new();
    for fc in 0..ncols {
        if is_pivot[fc] {
            continue;
        }
        let mut v = vec![0u64; ncols];
        v[fc] = 1;
        for (i, &pc) in pivots.iter().enumerate() {
            v[pc] = f.neg(rows[i][fc]);
        }
        basis.push(v);
    }
    basis
}

// ---------------------------------------------------------------------------
// Relation symmetries
// ---------------------------------------------------------------------------

/// What kind of map on `E` a symmetry comes from.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SymmetryKind {
    /// Translation by a rational point of order 2.
    TwoTorsion(Pt),
    /// An automorphism other than `±1`.
    Automorphism(Auto),
    /// The `p^d`-power Frobenius of a curve defined over `F_{p^d}`.
    Frobenius(u32),
}

/// How the symmetry may be applied to a relation tuple without breaking it.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Scope {
    /// To any even number of the points (translation type).  These lower
    /// the degree of the summation polynomial.
    Pairwise,
    /// Only to all points at once (automorphism / Frobenius type).  These
    /// collapse factor-base orbits but leave the polynomial alone.
    Global,
    /// Neither test passed.
    None,
}

/// A symmetry of the relation `P_1 + ⋯ + P_{m+1} = O` that descends to the
/// `x`-line.
#[derive(Clone, Debug)]
pub struct Symmetry {
    pub kind: SymmetryKind,
    /// Its action on `x`, when that action is a Möbius map (the Frobenius
    /// acts semilinearly, `x ↦ x^{p^d}`, and gets `None`).
    pub mobius: Option<Mobius>,
    pub scope: Scope,
}

impl Symmetry {
    pub fn describe(&self, f: &Gf) -> String {
        let what = match &self.kind {
            SymmetryKind::TwoTorsion(Pt::Aff(x, y)) => {
                format!("translation by T = ({}, {})", f.show(*x), f.show(*y))
            }
            SymmetryKind::TwoTorsion(Pt::Inf) => "translation by O".to_string(),
            SymmetryKind::Automorphism(Auto::Scale(u)) => {
                format!("automorphism (x,y) ↦ (u²x, u³y), u = {}", f.show(*u))
            }
            SymmetryKind::Automorphism(Auto::Neg) => "negation".to_string(),
            SymmetryKind::Frobenius(d) => format!("{}^{}-Frobenius", f.p, d),
        };
        let act = match self.mobius {
            Some(m) => format!("x ↦ {}", m.describe(f)),
            None => match self.kind {
                SymmetryKind::Frobenius(d) => format!("x ↦ x^{}", f.p.pow(d)),
                _ => "?".to_string(),
            },
        };
        format!("{what}; {act}; scope {:?}", self.scope)
    }
}

fn apply_symmetry(curve: &Curve, s: &Symmetry, p: Pt) -> Pt {
    match &s.kind {
        SymmetryKind::TwoTorsion(t) => curve.add(p, *t),
        SymmetryKind::Automorphism(a) => curve.apply_auto(*a, p),
        SymmetryKind::Frobenius(d) => curve.frobenius(p, *d),
    }
}

/// Fit the Möbius map with `x(γP) = M(x(P))` and verify it on every point.
fn mobius_of_map(curve: &Curve, pts: &[Pt], gamma: impl Fn(Pt) -> Pt) -> Option<Mobius> {
    let f = &curve.f;
    let mut pairs: Vec<(u64, u64)> = Vec::new();
    let mut seen = std::collections::HashSet::new();
    for &p in pts {
        let (t, s) = (p.x(), gamma(p).x());
        if t != INF && seen.insert(t) {
            pairs.push((t, s));
        }
        if pairs.len() == 3 {
            break;
        }
    }
    let m = Mobius::fit(f, &pairs)?;
    let ok = pts.iter().chain(std::iter::once(&Pt::Inf)).all(|&p| {
        let (t, s) = (p.x(), gamma(p).x());
        m.apply(f, t) == s
    });
    ok.then_some(m)
}

/// Random relation tuple `(P_1, …, P_{m+1})` with `Σ P_i = O`, all affine.
pub fn relation_tuple(curve: &Curve, pts: &[Pt], m: usize, rng: &mut Rng64) -> Vec<Pt> {
    loop {
        let mut tuple: Vec<Pt> = (0..m)
            .map(|_| pts[rng.below(pts.len() as u64) as usize])
            .collect();
        let sum = tuple.iter().fold(Pt::Inf, |acc, &p| curve.add(acc, p));
        let last = curve.neg(sum);
        if last != Pt::Inf {
            tuple.push(last);
            return tuple;
        }
    }
}

/// Is some signed combination `Σ ±Q_i` zero?  (The `x`-coordinate forgets
/// the sign, so this is the right notion of "still a relation".)
fn signed_relation(curve: &Curve, tuple: &[Pt]) -> bool {
    let n = tuple.len();
    for mask in 0..(1u32 << (n - 1)) {
        let mut sum = Pt::Inf;
        for (i, &q) in tuple.iter().enumerate() {
            let q = if i > 0 && (mask >> (i - 1)) & 1 == 1 {
                curve.neg(q)
            } else {
                q
            };
            sum = curve.add(sum, q);
        }
        if sum == Pt::Inf {
            return true;
        }
    }
    false
}

fn scope_of(curve: &Curve, pts: &[Pt], s: &Symmetry, rng: &mut Rng64) -> Scope {
    let trials = 24;
    let mut pairwise = true;
    let mut global = true;
    for _ in 0..trials {
        let tuple = relation_tuple(curve, pts, 2, rng);
        let mut pair = tuple.clone();
        pair[0] = apply_symmetry(curve, s, pair[0]);
        pair[1] = apply_symmetry(curve, s, pair[1]);
        if !signed_relation(curve, &pair) {
            pairwise = false;
        }
        let all: Vec<Pt> = tuple.iter().map(|&p| apply_symmetry(curve, s, p)).collect();
        if !signed_relation(curve, &all) {
            global = false;
        }
        if !pairwise && !global {
            break;
        }
    }
    if pairwise {
        Scope::Pairwise
    } else if global {
        Scope::Global
    } else {
        Scope::None
    }
}

/// Every symmetry of the relation that descends to the `x`-line, each one
/// fitted from data and verified on all points, with its scope measured.
pub fn detect_symmetries(curve: &Curve, pts: &[Pt], rng: &mut Rng64) -> Vec<Symmetry> {
    let mut out = Vec::new();
    for t in curve.two_torsion() {
        let mobius = mobius_of_map(curve, pts, |p| curve.add(p, t));
        let mut s = Symmetry {
            kind: SymmetryKind::TwoTorsion(t),
            mobius,
            scope: Scope::None,
        };
        s.scope = scope_of(curve, pts, &s, rng);
        out.push(s);
    }
    for a in curve.automorphisms() {
        if matches!(a, Auto::Neg | Auto::Scale(1)) {
            continue;
        }
        let mobius = mobius_of_map(curve, pts, |p| curve.apply_auto(a, p));
        let mut s = Symmetry {
            kind: SymmetryKind::Automorphism(a),
            mobius,
            scope: Scope::None,
        };
        s.scope = scope_of(curve, pts, &s, rng);
        out.push(s);
    }
    if let Some(d) = curve.subfield_degree() {
        if d < curve.f.n {
            let mut s = Symmetry {
                kind: SymmetryKind::Frobenius(d),
                mobius: None,
                scope: Scope::None,
            };
            s.scope = scope_of(curve, pts, &s, rng);
            out.push(s);
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Frames
// ---------------------------------------------------------------------------

/// What a frame does to the involution it was built for.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum FrameKind {
    /// The Weierstrass `x`-line itself.
    Weierstrass,
    /// The involution becomes `t ↦ −t` (odd characteristic, rational fixed
    /// points).
    Sign,
    /// The involution becomes `t ↦ t + 1` (characteristic 2).
    Additive,
    /// No rational linearising frame exists; the involution is used as is,
    /// through its trace and norm invariants.
    Trace,
}

/// A Möbius change of coordinate on the `x`-line together with what it
/// achieves.
#[derive(Clone, Debug)]
pub struct Frame {
    pub name: String,
    pub mob: Mobius,
    pub kind: FrameKind,
}

impl Frame {
    pub fn weierstrass() -> Self {
        Frame {
            name: "x".to_string(),
            mob: Mobius::identity(),
            kind: FrameKind::Weierstrass,
        }
    }
}

/// The frame in which the involution `g` of `P¹` acts linearly: `t ↦ −t`
/// over odd characteristic, `t ↦ t + 1` in characteristic 2.  Returns a
/// [`FrameKind::Trace`] identity frame when the fixed points are not
/// rational, since then no such frame exists over `K`.
pub fn linearising_frame(f: &Gf, g: &Mobius) -> Frame {
    let fps = g.fixed_points(f);
    // Möbius map sending t ↦ ∞ for a given point.
    let send_to_inf = |t: u64| -> Mobius {
        if t == INF {
            Mobius::identity()
        } else {
            // 1 / (t − t₀)
            Mobius {
                a: 0,
                b: 1,
                c: 1,
                d: f.neg(t),
            }
        }
    };
    if f.p == 2 {
        // unipotent: exactly one fixed point
        let Some(&t0) = fps.first() else {
            return Frame {
                name: "x (no rational fixed point)".to_string(),
                mob: Mobius::identity(),
                kind: FrameKind::Trace,
            };
        };
        let n0 = send_to_inf(t0);
        let g1 = g.conjugate_by(f, &n0);
        if let MobiusKind::Translation(c) = g1.kind(f) {
            // rescale so the translation is by 1
            let scale = Mobius {
                a: f.inv(c),
                b: 0,
                c: 0,
                d: 1,
            };
            let n = scale.compose(f, &n0);
            debug_assert_eq!(g.conjugate_by(f, &n).kind(f), MobiusKind::Translation(1));
            return Frame {
                name: format!("u = {}", n.describe(f)),
                mob: n,
                kind: FrameKind::Additive,
            };
        }
        Frame {
            name: "x (involution not unipotent?)".to_string(),
            mob: Mobius::identity(),
            kind: FrameKind::Trace,
        }
    } else {
        let mut distinct = fps.clone();
        distinct.dedup();
        if distinct.len() < 2 {
            return Frame {
                name: "x (fixed points irrational)".to_string(),
                mob: Mobius::identity(),
                kind: FrameKind::Trace,
            };
        }
        let (f1, f2) = (distinct[0], distinct[1]);
        // t ↦ (t − f1)/(t − f2), with the ∞ conventions
        let n = match (f1 == INF, f2 == INF) {
            (false, false) => Mobius {
                a: 1,
                b: f.neg(f1),
                c: 1,
                d: f.neg(f2),
            },
            (true, false) => Mobius {
                a: 0,
                b: 1,
                c: 1,
                d: f.neg(f2),
            },
            (false, true) => Mobius {
                a: 1,
                b: f.neg(f1),
                c: 0,
                d: 1,
            },
            (true, true) => unreachable!(),
        };
        let g1 = g.conjugate_by(f, &n);
        if g1.kind(f) == MobiusKind::Scaling(f.neg(1)) {
            Frame {
                name: format!("u = {}", n.describe(f)),
                mob: n,
                kind: FrameKind::Sign,
            }
        } else {
            Frame {
                name: "x (involution not diagonalisable?)".to_string(),
                mob: Mobius::identity(),
                kind: FrameKind::Trace,
            }
        }
    }
}

/// Brute-force scan of every frame with coefficients in `F_{p^d}`: which
/// of them turn `g` into a scaling, inversion or translation?  Only for
/// tiny subfields (`p^d ≤ 8`); this is the check that the constructive
/// frame is not missing anything a Frobenius-compatible frame could do.
pub fn scan_subfield_frames(f: &Gf, d: u32, g: &Mobius) -> Vec<(Mobius, MobiusKind)> {
    let elems = f.subfield_elements(d);
    assert!(elems.len() <= 8, "frame scan only for tiny subfields");
    let mut seen = std::collections::HashSet::new();
    let mut out = Vec::new();
    for &a in &elems {
        for &b in &elems {
            for &c in &elems {
                for &dd in &elems {
                    if f.sub(f.mul(a, dd), f.mul(b, c)) == 0 {
                        continue;
                    }
                    let n = Mobius { a, b, c, d: dd }.normalise(f);
                    if !seen.insert(n) {
                        continue;
                    }
                    let k = g.conjugate_by(f, &n).kind(f);
                    if !matches!(k, MobiusKind::General | MobiusKind::Identity) {
                        out.push((n, k));
                    }
                }
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Coordinate systems on relation tuples
// ---------------------------------------------------------------------------

/// How the involution's invariants are formed from the per-point value `u`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum InvariantRule {
    /// `w = u²`, `s = Π u_i` (sign frame).
    Sign,
    /// `w = u² + u`, `s = Σ u_i` (additive frame).
    Additive,
    /// `w = u + g(u)` (or `u·g(u)` when that is constant), `s` the sum over
    /// even-weight orbit representatives — works for any involution.
    Generic,
}

/// A coordinate system on the relation tuple: a frame on the `x`-line,
/// optionally an involution to quotient by, optionally the elementary
/// symmetric functions of the summands.
#[derive(Clone, Debug)]
pub struct CoordinateSystem {
    pub name: String,
    pub frame: Mobius,
    /// The involution written in the frame (already conjugated).
    pub involution: Option<Mobius>,
    pub rule: InvariantRule,
    /// Replace `(w_1, …, w_m)` by `e_1, …, e_m` — valid because the
    /// summands are interchangeable.
    pub symmetric: bool,
}

impl CoordinateSystem {
    pub fn plain(frame: &Frame, symmetric: bool) -> Self {
        CoordinateSystem {
            name: format!("{}{}", frame.name, if symmetric { ", e_k" } else { "" }),
            frame: frame.mob,
            involution: None,
            rule: InvariantRule::Generic,
            symmetric,
        }
    }

    /// Quotient by the involution `g_x` (given on the `x`-line) in `frame`.
    pub fn with_involution(f: &Gf, frame: &Frame, g_x: &Mobius, symmetric: bool) -> Self {
        let g = g_x.conjugate_by(f, &frame.mob);
        let rule = match frame.kind {
            FrameKind::Sign => InvariantRule::Sign,
            FrameKind::Additive => InvariantRule::Additive,
            _ => InvariantRule::Generic,
        };
        let inv_name = match rule {
            InvariantRule::Sign => "w = u², s = Πu",
            InvariantRule::Additive => "w = u² + u, s = Σu",
            InvariantRule::Generic => "w = u + g(u), s = σ_even",
        };
        CoordinateSystem {
            name: format!(
                "{} / {}{}",
                frame.name,
                inv_name,
                if symmetric { ", e_k" } else { "" }
            ),
            frame: frame.mob,
            involution: Some(g),
            rule,
            symmetric,
        }
    }

    /// Per-point coordinate: `u`, or the involution invariant `w` of `u`.
    pub fn point_value(&self, f: &Gf, p: Pt) -> u64 {
        let u = self.frame.apply(f, p.x());
        if u == INF {
            return INF;
        }
        match (&self.involution, self.rule) {
            (None, _) => u,
            (Some(_), InvariantRule::Sign) => f.mul(u, u),
            (Some(_), InvariantRule::Additive) => f.add(f.mul(u, u), u),
            (Some(g), InvariantRule::Generic) => {
                let gu = g.apply(f, u);
                if gu == INF {
                    return INF;
                }
                if self.generic_uses_product(f) {
                    f.mul(u, gu)
                } else {
                    f.add(u, gu)
                }
            }
        }
    }

    fn generic_uses_product(&self, f: &Gf) -> bool {
        // `u + g(u)` is constant exactly when g(u) = c − u.
        let g = self.involution.as_ref().unwrap();
        let vals: Vec<u64> = [0u64, 1, 2 % f.q]
            .iter()
            .filter_map(|&t| {
                let gt = g.apply(f, t);
                (gt != INF).then(|| f.add(t, gt))
            })
            .collect();
        vals.len() >= 2 && vals.iter().all(|&v| v == vals[0])
    }

    /// The extra invariant `s` of the even-weight subgroup.
    fn extra_invariant(&self, f: &Gf, us: &[u64]) -> Option<u64> {
        let g = self.involution.as_ref()?;
        Some(match self.rule {
            InvariantRule::Sign => us.iter().fold(1, |acc, &u| f.mul(acc, u)),
            InvariantRule::Additive => us.iter().fold(0, |acc, &u| f.add(acc, u)),
            InvariantRule::Generic => {
                let n = us.len();
                let gus: Vec<u64> = us.iter().map(|&u| g.apply(f, u)).collect();
                if gus.iter().any(|&v| v == INF) {
                    return None;
                }
                let mut total = 0;
                for mask in 0..(1u32 << n) {
                    if mask.count_ones() % 2 != 0 {
                        continue;
                    }
                    let mut prod = 1;
                    for i in 0..n {
                        prod = f.mul(prod, if (mask >> i) & 1 == 1 { gus[i] } else { us[i] });
                    }
                    total = f.add(total, prod);
                }
                total
            }
        })
    }

    pub fn var_names(&self, m: usize) -> Vec<String> {
        let base = if self.involution.is_some() { "w" } else { "u" };
        let mut names = Vec::new();
        if self.symmetric {
            for k in 1..=m {
                names.push(format!("e{k}"));
            }
        } else {
            for i in 1..=m {
                names.push(format!("{base}{i}"));
            }
        }
        names.push(format!("{base}R"));
        if self.involution.is_some() {
            names.push("s".to_string());
        }
        names
    }

    /// Per-variable degree bounds for the summation polynomial of `m + 1`
    /// points: `2^{m−1}` in a degree-2 coordinate, halved by the involution.
    pub fn bounds(&self, m: usize) -> Vec<u32> {
        let base = if self.involution.is_some() {
            1u32 << (m - 2)
        } else {
            1u32 << (m - 1)
        };
        let mut b = Vec::new();
        if self.symmetric {
            b.extend(std::iter::repeat(base).take(m));
        } else {
            b.extend(std::iter::repeat(base).take(m));
        }
        b.push(base);
        if self.involution.is_some() {
            b.push(if self.rule == InvariantRule::Generic {
                2
            } else {
                1
            });
        }
        b
    }

    /// Admissible exponent vectors: within the bounds, and for the
    /// symmetric variables `e_k` (of degree `k`) also of bounded total and
    /// weighted degree so that the degree in each hidden `w_i` stays within
    /// the bound.
    pub fn monomials(&self, m: usize) -> Vec<Vec<u32>> {
        let bounds = self.bounds(m);
        let all = enumerate_monomials(&bounds);
        if !self.symmetric {
            return all;
        }
        let base = bounds[0];
        all.into_iter()
            .filter(|e| {
                let total: u32 = e[..m].iter().sum();
                total <= base
            })
            .collect()
    }

    /// Coordinates of a relation tuple, `None` if any coordinate is `∞`.
    pub fn evaluate(&self, f: &Gf, tuple: &[Pt]) -> Option<Vec<u64>> {
        let m = tuple.len() - 1;
        let us: Vec<u64> = tuple.iter().map(|&p| self.frame.apply(f, p.x())).collect();
        if us.iter().any(|&u| u == INF) {
            return None;
        }
        let ws: Vec<u64> = tuple.iter().map(|&p| self.point_value(f, p)).collect();
        if ws.iter().any(|&w| w == INF) {
            return None;
        }
        let mut vals = Vec::new();
        if self.symmetric {
            vals.extend(elementary_symmetric_values(f, &ws[..m]));
        } else {
            vals.extend_from_slice(&ws[..m]);
        }
        vals.push(ws[m]);
        if self.involution.is_some() {
            vals.push(self.extra_invariant(f, &us)?);
        }
        Some(vals)
    }
}

fn elementary_symmetric_values(f: &Gf, xs: &[u64]) -> Vec<u64> {
    let m = xs.len();
    // e[k] after processing each x: e_k ← e_k + x·e_{k−1}
    let mut e = vec![0u64; m + 1];
    e[0] = 1;
    for &x in xs {
        for k in (1..=m).rev() {
            e[k] = f.add(e[k], f.mul(x, e[k - 1]));
        }
    }
    e[1..].to_vec()
}

/// All exponent vectors `0 ≤ e_i ≤ bounds[i]`.
pub fn enumerate_monomials(bounds: &[u32]) -> Vec<Vec<u32>> {
    let mut out = vec![vec![]];
    for &b in bounds {
        let mut next = Vec::new();
        for e in &out {
            for k in 0..=b {
                let mut e2 = e.clone();
                e2.push(k);
                next.push(e2);
            }
        }
        out = next;
    }
    out
}

// ---------------------------------------------------------------------------
// Interpolation of the relation polynomial
// ---------------------------------------------------------------------------

/// A polynomial over `Gf` in named variables, sparse.
#[derive(Clone, Debug)]
pub struct RelationPolynomial {
    pub var_names: Vec<String>,
    pub terms: Vec<(Vec<u32>, u64)>,
}

impl RelationPolynomial {
    pub fn n_terms(&self) -> usize {
        self.terms.len()
    }
    pub fn degrees(&self) -> Vec<u32> {
        let n = self.var_names.len();
        (0..n)
            .map(|i| self.terms.iter().map(|(e, _)| e[i]).max().unwrap_or(0))
            .collect()
    }
    pub fn total_degree(&self) -> u32 {
        self.terms
            .iter()
            .map(|(e, _)| e.iter().sum::<u32>())
            .max()
            .unwrap_or(0)
    }
    pub fn eval(&self, f: &Gf, vals: &[u64]) -> u64 {
        let mut acc = 0;
        for (e, c) in &self.terms {
            let mut t = *c;
            for (i, &k) in e.iter().enumerate() {
                if k > 0 {
                    t = f.mul(t, f.pow(vals[i], k as u64));
                }
            }
            acc = f.add(acc, t);
        }
        acc
    }
    /// Human-readable, monomials sorted by degree.
    pub fn render(&self, f: &Gf, max_terms: usize) -> String {
        let mut terms = self.terms.clone();
        terms.sort_by(|a, b| {
            let da: u32 = a.0.iter().sum();
            let db: u32 = b.0.iter().sum();
            db.cmp(&da).then(b.0.cmp(&a.0))
        });
        let mut parts = Vec::new();
        for (e, c) in terms.iter().take(max_terms) {
            let mut mono = String::new();
            for (i, &k) in e.iter().enumerate() {
                if k == 1 {
                    let _ = write!(mono, "·{}", self.var_names[i]);
                } else if k > 1 {
                    let _ = write!(mono, "·{}^{}", self.var_names[i], k);
                }
            }
            let coef = if *c == 1 && !mono.is_empty() {
                String::new()
            } else {
                f.show(*c)
            };
            parts.push(format!("{coef}{mono}").trim_start_matches('·').to_string());
        }
        let mut s = parts.join(" + ");
        if terms.len() > max_terms {
            let _ = write!(s, " + … ({} more)", terms.len() - max_terms);
        }
        s
    }
}

/// Outcome of interpolating one coordinate system.
#[derive(Clone, Debug)]
pub struct InterpolationResult {
    pub poly: RelationPolynomial,
    /// Kernel dimension at the final degree box (1 = unique polynomial).
    pub kernel_dim: usize,
    pub samples: usize,
    /// Fresh relation tuples the polynomial vanished on.
    pub verified_on: usize,
    /// Fraction of random non-relation tuples it also vanished on (should
    /// be about `deg/q`).
    pub false_positive_rate: f64,
}

fn build_rows(f: &Gf, samples: &[Vec<u64>], monos: &[Vec<u32>]) -> Vec<Vec<u64>> {
    samples
        .iter()
        .map(|vals| {
            monos
                .iter()
                .map(|e| {
                    let mut t = 1;
                    for (i, &k) in e.iter().enumerate() {
                        if k > 0 {
                            t = f.mul(t, f.pow(vals[i], k as u64));
                        }
                    }
                    t
                })
                .collect()
        })
        .collect()
}

/// Interpolate the summation polynomial of `m + 1` points in the given
/// coordinates, from random relation tuples, and verify it.
pub fn interpolate_relation(
    curve: &Curve,
    pts: &[Pt],
    cs: &CoordinateSystem,
    m: usize,
    rng: &mut Rng64,
) -> Result<InterpolationResult, String> {
    let f = &curve.f;
    let monos = cs.monomials(m);
    let need = monos.len() + monos.len() / 4 + 40;
    let mut samples: Vec<Vec<u64>> = Vec::new();
    let mut attempts = 0;
    while samples.len() < need {
        attempts += 1;
        if attempts > 50 * need {
            return Err("could not sample enough finite relation tuples".to_string());
        }
        let tuple = relation_tuple(curve, pts, m, rng);
        if let Some(v) = cs.evaluate(f, &tuple) {
            samples.push(v);
        }
    }
    let rows = build_rows(f, &samples, &monos);
    let ker = kernel(f, rows, monos.len());
    if ker.is_empty() {
        return Err(format!(
            "no polynomial within the degree box {:?} vanishes on the relation samples",
            cs.bounds(m)
        ));
    }
    // If the kernel is not one-dimensional the box is loose: shrink it
    // variable by variable while a solution survives.
    let mut chosen_monos = monos.clone();
    let mut chosen_ker = ker;
    if chosen_ker.len() > 1 {
        let mut bounds = cs.bounds(m);
        loop {
            let mut improved = false;
            for i in 0..bounds.len() {
                if bounds[i] == 0 {
                    continue;
                }
                let mut trial = bounds.clone();
                trial[i] -= 1;
                let tmonos: Vec<Vec<u32>> = monos
                    .iter()
                    .filter(|e| e.iter().zip(&trial).all(|(&k, &b)| k <= b))
                    .cloned()
                    .collect();
                if tmonos.is_empty() {
                    continue;
                }
                let rows = build_rows(f, &samples, &tmonos);
                let k = kernel(f, rows, tmonos.len());
                if !k.is_empty() {
                    bounds = trial;
                    chosen_monos = tmonos;
                    chosen_ker = k;
                    improved = true;
                    if chosen_ker.len() == 1 {
                        break;
                    }
                }
            }
            if !improved || chosen_ker.len() == 1 {
                break;
            }
        }
    }
    let kernel_dim = chosen_ker.len();
    let v = &chosen_ker[0];
    let mut terms: Vec<(Vec<u32>, u64)> = chosen_monos
        .iter()
        .zip(v.iter())
        .filter(|(_, &c)| c != 0)
        .map(|(e, &c)| (e.clone(), c))
        .collect();
    // normalise leading coefficient to 1 (last monomial in the list order)
    if let Some(&(_, lead)) = terms.last() {
        let inv = f.inv(lead);
        for (_, c) in terms.iter_mut() {
            *c = f.mul(*c, inv);
        }
    }
    let poly = RelationPolynomial {
        var_names: cs.var_names(m),
        terms,
    };
    // Verification on fresh relations and on random non-relations.
    let mut verified_on = 0;
    let mut checked = 0;
    while verified_on < 200 && checked < 4000 {
        checked += 1;
        let tuple = relation_tuple(curve, pts, m, rng);
        if let Some(vals) = cs.evaluate(f, &tuple) {
            if poly.eval(f, &vals) != 0 {
                return Err(format!(
                    "interpolated polynomial does not vanish on a fresh relation ({})",
                    cs.name
                ));
            }
            verified_on += 1;
        }
    }
    let mut fp = 0;
    let mut tested = 0;
    while tested < 300 {
        let mut tuple: Vec<Pt> = (0..=m)
            .map(|_| pts[rng.below(pts.len() as u64) as usize])
            .collect();
        // make sure it is not accidentally a relation
        if signed_relation(curve, &tuple) {
            continue;
        }
        tuple.truncate(m + 1);
        if let Some(vals) = cs.evaluate(f, &tuple) {
            tested += 1;
            if poly.eval(f, &vals) == 0 {
                fp += 1;
            }
        }
    }
    Ok(InterpolationResult {
        poly,
        kernel_dim,
        samples: samples.len(),
        verified_on,
        false_positive_rate: fp as f64 / tested as f64,
    })
}

// ---------------------------------------------------------------------------
// Collapse factor: how many relation tuples share one coordinate vector
// ---------------------------------------------------------------------------

/// Generic number of relation tuples `(P_1, …, P_{m+1})`, `Σ P_i = O`, that
/// map to the same coordinate vector: the median over random samples of
/// the fibre size, computed by enumerating the fibre of the per-point
/// coordinate on the curve.  It is the effective symmetry the coordinates
/// quotient out, measured rather than counted from a group; the median
/// rather than the mean because a sample through a 2-torsion point or a
/// fixed point of the involution has a smaller fibre.  Permutations of the
/// summands are not included (multiply by `m!` for a symmetric system).
pub fn collapse_factor(
    curve: &Curve,
    pts: &[Pt],
    cs: &CoordinateSystem,
    m: usize,
    rng: &mut Rng64,
    samples: usize,
) -> f64 {
    let f = &curve.f;
    // fibre table: coordinate value → points
    let mut fibre: HashMap<u64, Vec<Pt>> = HashMap::new();
    for &p in pts {
        let v = cs.point_value(f, p);
        if v != INF {
            fibre.entry(v).or_default().push(p);
        }
    }
    let mut sizes: Vec<usize> = Vec::new();
    while sizes.len() < samples {
        let tuple = relation_tuple(curve, pts, m, rng);
        let Some(vals) = cs.evaluate(f, &tuple) else {
            continue;
        };
        let per_point: Vec<&Vec<Pt>> = tuple
            .iter()
            .map(|&p| &fibre[&cs.point_value(f, p)])
            .collect();
        let size: usize = per_point.iter().map(|v| v.len()).product();
        if size > 1 << 16 {
            continue;
        }
        // enumerate the product
        let mut hits = 0;
        let mut idx = vec![0usize; m + 1];
        loop {
            let cand: Vec<Pt> = (0..=m).map(|i| per_point[i][idx[i]]).collect();
            let sum = cand.iter().fold(Pt::Inf, |acc, &p| curve.add(acc, p));
            if sum == Pt::Inf {
                if let Some(cv) = cs.evaluate(f, &cand) {
                    if cv == vals {
                        hits += 1;
                    }
                }
            }
            // increment
            let mut i = 0;
            loop {
                if i > m {
                    break;
                }
                idx[i] += 1;
                if idx[i] < per_point[i].len() {
                    break;
                }
                idx[i] = 0;
                i += 1;
            }
            if i > m {
                break;
            }
        }
        sizes.push(hits);
    }
    sizes.sort_unstable();
    sizes[sizes.len() / 2] as f64
}

// ---------------------------------------------------------------------------
// Weil-descent cost model
// ---------------------------------------------------------------------------

/// Size of the Boolean system a factor base cut out by an `F_2`-subspace of
/// dimension `l` would produce, for a binary field of degree `n`.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DescentModel {
    pub factor_base_dim: u32,
    pub unknowns: u32,
    pub equations: u32,
    /// Degree of the descended Boolean system, read off the interpolated
    /// polynomial: a monomial `Π v_i^{e_i}` has bit-degree `Σ popcount(e_i)`
    /// because `v ↦ v^{2^k}` is `F_2`-linear.
    pub boolean_degree: u32,
}

/// Bit-degree of the descended polynomial: `Σ_i popcount(e_i)` maximised
/// over the monomials, since every `2^k`-th power is linear over `F_2`.
pub fn boolean_degree(poly: &RelationPolynomial) -> u32 {
    poly.terms
        .iter()
        .map(|(e, _)| e.iter().map(|k| k.count_ones()).sum::<u32>())
        .max()
        .unwrap_or(0)
}

/// The model behind the numbers in [`Candidate::descent`].  Without an
/// involution each summand coordinate carries `l` bits.  With the additive
/// involution and `1 ∈ V`, each `w_i = u_i² + u_i` lies in the image of `V`
/// under the Artin–Schreier map, which is `F_2`-linear with kernel `{0, 1}`,
/// so `w_i` carries `l − 1` bits; the extra invariant `s = Σ u_i` satisfies
/// `s² + s = Σ w_i`, again linear in the bits, so it contributes one free
/// bit after linear elimination.  (A solve that lands on `R + T` is the
/// same projected relation as one on `R`, since the cofactor kills `T`;
/// an earlier version counted it as a second target.)
pub fn descent_model(
    cs: &CoordinateSystem,
    poly: &RelationPolynomial,
    m: usize,
    n: u32,
    l: u32,
) -> DescentModel {
    let m32 = m as u32;
    if cs.involution.is_some() {
        DescentModel {
            factor_base_dim: l,
            unknowns: m32 * (l - 1) + 1,
            equations: n,
            boolean_degree: boolean_degree(poly),
        }
    } else {
        DescentModel {
            factor_base_dim: l,
            unknowns: m32 * l,
            equations: n,
            boolean_degree: boolean_degree(poly),
        }
    }
}

// ---------------------------------------------------------------------------
// Search driver
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
pub struct SearchOptions {
    /// Number of summands.
    pub m: usize,
    pub seed: u64,
    /// Factor-base subspace dimension for the descent model (binary fields).
    pub factor_base_dim: Option<u32>,
    /// Relation samples for the collapse-factor measurement.
    pub collapse_samples: usize,
}

impl Default for SearchOptions {
    fn default() -> Self {
        SearchOptions {
            m: 3,
            seed: 0x5EED,
            factor_base_dim: None,
            collapse_samples: 16,
        }
    }
}

/// One coordinate system and everything measured about it.
#[derive(Clone, Debug)]
pub struct Candidate {
    pub system: CoordinateSystem,
    /// Which symmetry it quotients by, if any.
    pub symmetry: Option<String>,
    pub frame_kind: FrameKind,
    /// `coord(πP) = coord(P)^{p^d}` on every point (measured).
    pub frobenius_compatible: Option<bool>,
    pub result: Result<InterpolationResult, String>,
    pub collapse: Option<f64>,
    pub descent: Option<DescentModel>,
}

/// The whole search on one curve.
#[derive(Clone, Debug)]
pub struct SearchReport {
    pub curve: String,
    pub field: String,
    pub order: u64,
    pub j: Option<u64>,
    pub two_torsion: usize,
    pub aut_order: usize,
    pub subfield_degree: Option<u32>,
    pub m: usize,
    pub symmetries: Vec<Symmetry>,
    pub candidates: Vec<Candidate>,
}

fn frobenius_compatible(curve: &Curve, pts: &[Pt], cs: &CoordinateSystem) -> Option<bool> {
    let d = curve.subfield_degree()?;
    if d == curve.f.n {
        return None;
    }
    let f = &curve.f;
    Some(pts.iter().all(|&p| {
        let v = cs.point_value(f, p);
        let w = cs.point_value(f, curve.frobenius(p, d));
        v == INF || w == INF || w == f.frob_pow(v, d)
    }))
}

/// Run the search: detect symmetries, build frames, interpolate and measure
/// every candidate coordinate system.
pub fn search(curve: &Curve, opts: &SearchOptions) -> SearchReport {
    let f = &curve.f;
    let m = opts.m;
    assert!(m >= 2, "need at least two summands");
    let mut rng = Rng64::new(opts.seed);
    let pts = curve.affine_points();
    let symmetries = detect_symmetries(curve, &pts, &mut rng);
    let l = opts
        .factor_base_dim
        .unwrap_or_else(|| ((f.n as usize + m - 1) / m).max(2) as u32);

    let mut systems: Vec<(CoordinateSystem, Option<String>, FrameKind)> = Vec::new();
    let wx = Frame::weierstrass();
    systems.push((
        CoordinateSystem::plain(&wx, false),
        None,
        FrameKind::Weierstrass,
    ));
    systems.push((
        CoordinateSystem::plain(&wx, true),
        None,
        FrameKind::Weierstrass,
    ));
    for s in &symmetries {
        let (Some(g), Scope::Pairwise) = (s.mobius, s.scope) else {
            continue;
        };
        let frame = linearising_frame(f, &g);
        let label = s.describe(f);
        if frame.kind != FrameKind::Trace {
            systems.push((CoordinateSystem::plain(&frame, false), None, frame.kind));
        }
        systems.push((
            CoordinateSystem::with_involution(f, &frame, &g, false),
            Some(label.clone()),
            frame.kind,
        ));
        systems.push((
            CoordinateSystem::with_involution(f, &frame, &g, true),
            Some(label),
            frame.kind,
        ));
    }

    let mut candidates = Vec::new();
    for (cs, symmetry, frame_kind) in systems {
        let result = interpolate_relation(curve, &pts, &cs, m, &mut rng);
        let collapse = result
            .as_ref()
            .ok()
            .filter(|_| !cs.symmetric)
            .map(|_| collapse_factor(curve, &pts, &cs, m, &mut rng, opts.collapse_samples));
        // The bit-degree model needs per-point variables; the elementary
        // symmetric functions are not linear in the bits.
        let descent = match (&result, f.is_binary(), cs.symmetric) {
            (Ok(res), true, false) => Some(descent_model(&cs, &res.poly, m, f.n, l)),
            _ => None,
        };
        candidates.push(Candidate {
            frobenius_compatible: frobenius_compatible(curve, &pts, &cs),
            symmetry,
            frame_kind,
            result,
            collapse,
            descent,
            system: cs,
        });
    }
    SearchReport {
        curve: curve.label.clone(),
        field: f.name(),
        order: pts.len() as u64 + 1,
        j: curve.j_invariant(),
        two_torsion: curve.two_torsion().len(),
        aut_order: curve.automorphisms().len(),
        subfield_degree: curve.subfield_degree(),
        m,
        symmetries,
        candidates,
    }
}

/// Plain-text rendering of a report.
pub fn format_report(f: &Gf, r: &SearchReport) -> String {
    let mut s = String::new();
    let _ = writeln!(
        s,
        "== {} over {}: #E = {}, j = {}, rational 2-torsion points = {}, |Aut| = {}, defined over {}",
        r.curve,
        r.field,
        r.order,
        r.j.map(|j| f.show(j)).unwrap_or_else(|| "singular".to_string()),
        r.two_torsion,
        r.aut_order,
        match r.subfield_degree {
            Some(d) => format!("F_{}^{}", f.p, d),
            None => r.field.clone(),
        }
    );
    let _ = writeln!(s, "   relation symmetries on the x-line (m = {}):", r.m);
    if r.symmetries.is_empty() {
        let _ = writeln!(s, "     (none beyond ±1)");
    }
    for sym in &r.symmetries {
        let _ = writeln!(s, "     - {}", sym.describe(f));
    }
    let _ = writeln!(
        s,
        "   {:<44} {:>5} {:>14} {:>6} {:>8} {:>5} {:>21}",
        "coordinates", "vars", "degrees", "terms", "collapse", "Frob", "descent unk/eq/bitdeg"
    );
    for c in &r.candidates {
        let (vars, degs, terms) = match &c.result {
            Ok(res) => (
                res.poly.var_names.len().to_string(),
                format!("{:?}", res.poly.degrees()),
                res.poly.n_terms().to_string(),
            ),
            Err(_) => ("-".into(), "-".into(), "-".into()),
        };
        let collapse = c
            .collapse
            .map(|v| format!("{v:.1}"))
            .unwrap_or_else(|| "-".to_string());
        let frob = match c.frobenius_compatible {
            Some(true) => "yes",
            Some(false) => "NO",
            None => "n/a",
        };
        let descent = c
            .descent
            .as_ref()
            .map(|d| format!("{}/{}/{}", d.unknowns, d.equations, d.boolean_degree))
            .unwrap_or_else(|| "-".to_string());
        let _ = writeln!(
            s,
            "   {:<44} {:>5} {:>14} {:>6} {:>8} {:>5} {:>21}",
            truncate(&c.system.name, 44),
            vars,
            degs,
            terms,
            collapse,
            frob,
            descent
        );
        if let Err(e) = &c.result {
            let _ = writeln!(s, "        ! {e}");
        }
    }
    s
}

fn truncate(s: &str, n: usize) -> String {
    if s.chars().count() <= n {
        s.to_string()
    } else {
        let t: String = s.chars().take(n - 1).collect();
        format!("{t}…")
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::binary_ecc::f2m::F2mElement;
    use crate::cryptanalysis::binary_semaev::binary_semaev_s3;

    fn prime_curve(p: u64, a: u64, b: u64) -> Curve {
        Curve::short_weierstrass(Gf::prime(p), a, b, &format!("y²=x³+{a}x+{b}/F_{p}"))
    }

    #[test]
    fn prime_field_arithmetic() {
        let f = Gf::prime(1009);
        for a in 1..1009 {
            assert_eq!(f.mul(a, f.inv(a)), 1);
        }
        let mut squares = 0;
        for a in 0..1009 {
            if let Some(r) = f.sqrt(a) {
                assert_eq!(f.mul(r, r), a);
                squares += 1;
            }
        }
        assert_eq!(squares, 505); // (p+1)/2 squares including 0
    }

    #[test]
    fn binary_field_arithmetic_and_artin_schreier() {
        let f = Gf::binary(7);
        for a in 1..128 {
            assert_eq!(f.mul(a, f.inv(a)), 1);
            let sq = f.mul(a, a);
            assert_eq!(f.sqrt(sq), Some(a));
        }
        let mut solvable = 0;
        for c in 0..128 {
            if let Some(t) = f.artin_schreier(c) {
                assert_eq!(f.add(f.mul(t, t), t), c);
                solvable += 1;
            }
        }
        assert_eq!(solvable, 64); // trace-zero elements
                                  // Frobenius fixes exactly F_2
        assert_eq!(f.subfield_elements(1), vec![0, 1]);
    }

    #[test]
    fn koblitz_orders_match_known_counts() {
        // From RESEARCH_KOBLITZ_INDEX_CALCULUS.md: K_1/F_2^7 has 142 points,
        // K_0/F_2^9 has 508.
        assert_eq!(Curve::koblitz(1, 7).order(), 142);
        assert_eq!(Curve::koblitz(0, 9).order(), 508);
        let k = Curve::koblitz(1, 7);
        assert_eq!(k.two_torsion(), vec![Pt::Aff(0, 1)]);
        assert_eq!(k.subfield_degree(), Some(1));
    }

    #[test]
    fn group_law_is_a_group_on_both_characteristics() {
        for curve in [prime_curve(1009, 3, 7), Curve::koblitz(0, 7)] {
            let pts = curve.affine_points();
            let order = pts.len() as u64 + 1;
            let mut rng = Rng64::new(7);
            for _ in 0..200 {
                let p = pts[rng.below(pts.len() as u64) as usize];
                let q = pts[rng.below(pts.len() as u64) as usize];
                let r = pts[rng.below(pts.len() as u64) as usize];
                assert!(curve.is_on(curve.add(p, q)));
                assert_eq!(curve.add(curve.add(p, q), r), curve.add(p, curve.add(q, r)));
                assert_eq!(curve.add(p, curve.neg(p)), Pt::Inf);
                assert_eq!(curve.mul(p, order), Pt::Inf);
            }
        }
    }

    #[test]
    fn mobius_fit_recovers_a_map() {
        let f = Gf::prime(101);
        let m = Mobius {
            a: 3,
            b: 5,
            c: 7,
            d: 11,
        }
        .normalise(&f);
        let pairs: Vec<(u64, u64)> = [2u64, 9, 40].iter().map(|&t| (t, m.apply(&f, t))).collect();
        assert_eq!(Mobius::fit(&f, &pairs), Some(m));
        assert!(m.compose(&f, &m.inverse(&f)).is_identity(&f));
        let pairs_inf = vec![
            (INF, m.apply(&f, INF)),
            (2, m.apply(&f, 2)),
            (9, m.apply(&f, 9)),
        ];
        assert_eq!(Mobius::fit(&f, &pairs_inf), Some(m));
    }

    #[test]
    fn koblitz_two_torsion_acts_as_inversion_and_linearises_additively() {
        let k = Curve::koblitz(1, 7);
        let f = &k.f;
        let pts = k.affine_points();
        let mut rng = Rng64::new(1);
        let syms = detect_symmetries(&k, &pts, &mut rng);
        let t2 = syms
            .iter()
            .find(|s| matches!(s.kind, SymmetryKind::TwoTorsion(_)))
            .expect("2-torsion symmetry");
        let g = t2.mobius.expect("Möbius action");
        // x(P + T) = 1/x for b = 1
        assert_eq!(g.kind(f), MobiusKind::Inversion(1));
        assert_eq!(t2.scope, Scope::Pairwise);
        let frame = linearising_frame(f, &g);
        assert_eq!(frame.kind, FrameKind::Additive);
        assert_eq!(
            g.conjugate_by(f, &frame.mob).kind(f),
            MobiusKind::Translation(1)
        );
        // the frame is over F_2, hence Frobenius-compatible
        assert!(frame.mob.in_subfield(f, 1));
        // and the brute-force scan over PGL_2(F_2) finds exactly the two
        // frames that send the fixed point 1 to ∞
        let found = scan_subfield_frames(f, 1, &g);
        let additive: Vec<_> = found
            .iter()
            .filter(|(_, k)| matches!(k, MobiusKind::Translation(_)))
            .collect();
        assert_eq!(additive.len(), 2);
        // Frobenius is global, not pairwise
        let fr = syms
            .iter()
            .find(|s| matches!(s.kind, SymmetryKind::Frobenius(_)))
            .expect("Frobenius");
        assert_eq!(fr.scope, Scope::Global);
    }

    #[test]
    fn interpolated_s3_matches_closed_form_binary() {
        let k = Curve::koblitz(0, 9);
        let f = &k.f;
        let pts = k.affine_points();
        let mut rng = Rng64::new(3);
        let cs = CoordinateSystem::plain(&Frame::weierstrass(), false);
        let res = interpolate_relation(&k, &pts, &cs, 2, &mut rng).unwrap();
        assert_eq!(res.kernel_dim, 1);
        assert_eq!(res.poly.degrees(), vec![2, 2, 2]);
        // S₃ = (x₁+x₂)²x₃² + x₁x₂x₃ + (x₁x₂)² + b : 6 monomials... compare
        // by proportionality on random triples against the closed form.
        let irr = find_irreducible(9).unwrap();
        let to_el = |v: u64| F2mElement::from_biguint(&num_bigint::BigUint::from(v), 9);
        let mut ratio = None;
        for _ in 0..50 {
            let vals: Vec<u64> = (0..3).map(|_| f.random(&mut rng)).collect();
            let mine = res.poly.eval(f, &vals);
            let theirs = binary_semaev_s3(
                &to_el(vals[0]),
                &to_el(vals[1]),
                &to_el(vals[2]),
                &to_el(1),
                &irr,
            );
            let theirs = theirs
                .to_biguint()
                .to_u64_digits()
                .first()
                .copied()
                .unwrap_or(0);
            if theirs == 0 {
                assert_eq!(mine, 0);
                continue;
            }
            let r = f.div(mine, theirs);
            match ratio {
                None => ratio = Some(r),
                Some(r0) => assert_eq!(r, r0),
            }
        }
    }

    #[test]
    fn interpolated_s3_matches_closed_form_prime() {
        let c = prime_curve(1009, 3, 7);
        let f = &c.f;
        let pts = c.affine_points();
        let mut rng = Rng64::new(5);
        let cs = CoordinateSystem::plain(&Frame::weierstrass(), false);
        let res = interpolate_relation(&c, &pts, &cs, 2, &mut rng).unwrap();
        assert_eq!(res.kernel_dim, 1);
        // S₃ = (x₁−x₂)²x₃² − 2((x₁+x₂)(x₁x₂+a)+2b)x₃ + (x₁x₂−a)² − 4b(x₁+x₂)
        let (a, b) = (3u64, 7u64);
        let s3 = |x1: u64, x2: u64, x3: u64| -> u64 {
            let two = f.add(1, 1);
            let four = f.add(two, two);
            let d = f.sub(x1, x2);
            let t1 = f.mul(f.mul(d, d), f.mul(x3, x3));
            let inner = f.add(f.mul(f.add(x1, x2), f.add(f.mul(x1, x2), a)), f.mul(two, b));
            let t2 = f.mul(f.mul(two, inner), x3);
            let e = f.sub(f.mul(x1, x2), a);
            let t3 = f.sub(f.mul(e, e), f.mul(f.mul(four, b), f.add(x1, x2)));
            f.add(f.sub(t1, t2), t3)
        };
        let mut ratio = None;
        for _ in 0..50 {
            let v: Vec<u64> = (0..3).map(|_| f.random(&mut rng)).collect();
            let mine = res.poly.eval(f, &v);
            let theirs = s3(v[0], v[1], v[2]);
            if theirs == 0 {
                assert_eq!(mine, 0);
                continue;
            }
            let r = f.div(mine, theirs);
            match ratio {
                None => ratio = Some(r),
                Some(r0) => assert_eq!(r, r0),
            }
        }
    }

    #[test]
    fn additive_symmetrisation_halves_degree_and_quadruples_collapse() {
        let k = Curve::koblitz(1, 7);
        let f = &k.f;
        let pts = k.affine_points();
        let mut rng = Rng64::new(11);
        let syms = detect_symmetries(&k, &pts, &mut rng);
        let g = syms
            .iter()
            .find(|s| matches!(s.kind, SymmetryKind::TwoTorsion(_)))
            .unwrap()
            .mobius
            .unwrap();
        let frame = linearising_frame(f, &g);
        let plain = CoordinateSystem::plain(&Frame::weierstrass(), false);
        let sym = CoordinateSystem::with_involution(f, &frame, &g, false);
        for m in [2usize, 3] {
            let r0 = interpolate_relation(&k, &pts, &plain, m, &mut rng).unwrap();
            let r1 = interpolate_relation(&k, &pts, &sym, m, &mut rng).unwrap();
            let d0 = r0.poly.degrees();
            let d1 = r1.poly.degrees();
            for i in 0..=m {
                assert_eq!(d0[i], 1 << (m - 1));
                assert_eq!(d1[i], 1 << (m - 2), "m = {m}, var {i}: {d1:?}");
            }
            assert_eq!(*d1.last().unwrap(), 1, "s appears linearly");
            assert!(r1.verified_on >= 100);
            let c0 = collapse_factor(&k, &pts, &plain, m, &mut rng, 8);
            let c1 = collapse_factor(&k, &pts, &sym, m, &mut rng, 8);
            assert!((c0 - 2.0).abs() < 0.5, "plain collapse {c0}");
            assert!(
                (c1 - (1 << (m + 1)) as f64).abs() < 1.0,
                "symmetrised collapse {c1}"
            );
        }
        assert_eq!(frobenius_compatible(&k, &pts, &sym), Some(true));
    }

    #[test]
    fn sign_symmetrisation_on_a_prime_curve_with_rational_halving() {
        // Find a small prime curve whose 2-torsion translation has rational
        // fixed points on the x-line, and check the sign frame.
        let mut found = false;
        for b in 1..60u64 {
            let c = prime_curve(1009, 1, b);
            if c.j_invariant().is_none() {
                continue;
            }
            let pts = c.affine_points();
            let mut rng = Rng64::new(b);
            let syms = detect_symmetries(&c, &pts, &mut rng);
            for s in &syms {
                let (Some(g), SymmetryKind::TwoTorsion(_)) = (s.mobius, &s.kind) else {
                    continue;
                };
                assert_eq!(s.scope, Scope::Pairwise);
                let frame = linearising_frame(&c.f, &g);
                if frame.kind != FrameKind::Sign {
                    continue;
                }
                assert_eq!(
                    g.conjugate_by(&c.f, &frame.mob).kind(&c.f),
                    MobiusKind::Scaling(1008)
                );
                let cs = CoordinateSystem::with_involution(&c.f, &frame, &g, false);
                let r = interpolate_relation(&c, &pts, &cs, 2, &mut rng).unwrap();
                assert_eq!(r.poly.degrees(), vec![1, 1, 1, 1]);
                let col = collapse_factor(&c, &pts, &cs, 2, &mut rng, 8);
                assert!((col - 8.0).abs() < 1.0, "collapse {col}");
                found = true;
                break;
            }
            if found {
                break;
            }
        }
        assert!(found, "no curve with a sign frame among the candidates");
    }

    #[test]
    fn j0_automorphism_is_global_not_pairwise() {
        // p ≡ 1 mod 3 so that ω ∈ F_p: y² = x³ + 7 (secp256k1's shape).
        let c = prime_curve(1009, 0, 7);
        let pts = c.affine_points();
        let mut rng = Rng64::new(2);
        assert_eq!(c.automorphisms().len(), 6);
        let syms = detect_symmetries(&c, &pts, &mut rng);
        let auts: Vec<_> = syms
            .iter()
            .filter(|s| matches!(s.kind, SymmetryKind::Automorphism(_)))
            .collect();
        assert!(!auts.is_empty());
        for a in auts {
            assert_eq!(a.scope, Scope::Global);
            assert!(matches!(
                a.mobius.unwrap().kind(&c.f),
                MobiusKind::Scaling(_)
            ));
        }
    }

    #[test]
    fn additive_frame_factor_base_needs_the_x_minus_1_factor() {
        // The symmetrised system needs a factor base closed under
        // u ↦ u + 1, i.e. 1 ∈ V.  For the repo's Frobenius-invariant bases
        // V = roots of a linearised divisor of x^n − 1, and 1 is a root iff
        // the divisor contains the factor x − 1.
        use crate::cryptanalysis::koblitz_index_calculus::{
            all_factors_of_x_n_minus_1, subspace_basis_for_divisor,
        };
        let n = 7;
        let irr = find_irreducible(n).unwrap();
        let f = Gf::binary_with(&irr);
        let factors = all_factors_of_x_n_minus_1(n);
        let x_minus_1 = factors
            .iter()
            .position(|&p| p == 0b11)
            .expect("x − 1 factor");
        let other = (0..factors.len()).find(|&i| i != x_minus_1).unwrap();
        let to_u64 = |e: &F2mElement| e.to_biguint().to_u64_digits().first().copied().unwrap_or(0);
        let contains_one = |idx: &[usize]| {
            let basis = subspace_basis_for_divisor(n, idx, &irr).unwrap();
            let elems: Vec<u64> = basis.iter().map(to_u64).collect();
            // span contains 1?
            (0..(1u32 << elems.len())).any(|mask| {
                let v = (0..elems.len())
                    .filter(|&i| (mask >> i) & 1 == 1)
                    .fold(0u64, |acc, i| f.add(acc, elems[i]));
                v == 1
            })
        };
        assert!(
            !contains_one(&[other]),
            "a base without x − 1 must not contain 1"
        );
        assert!(contains_one(&[x_minus_1, other]), "with x − 1 it must");
    }

    #[test]
    fn search_report_runs_end_to_end_on_a_koblitz_toy() {
        let k = Curve::koblitz(0, 7);
        let r = search(
            &k,
            &SearchOptions {
                m: 2,
                seed: 9,
                factor_base_dim: Some(3),
                collapse_samples: 4,
            },
        );
        assert_eq!(r.order, 142 - 142 + k.order());
        assert!(
            r.candidates.iter().all(|c| c.result.is_ok()),
            "{}",
            format_report(&k.f, &r)
        );
        let text = format_report(&k.f, &r);
        assert!(text.contains("w = u² + u"));
    }
}
