//! # Descent of quotient coordinates to `F_p`: the Klein invariants in
//! Gaudry's setting.
//!
//! §10.3 of `RESEARCH_EXOTIC_COORDINATES.md` ended on "bits, not degrees":
//! the full 2-torsion group `E[2] ≅ (Z/2)²` quadruples the collapse but
//! does not halve the per-point degree twice, and whether its invariants
//! give a *cheaper system* is a question about the descended equations,
//! not about degrees in the field.  On a prime field there is no subspace
//! factor base to descend to.  Over `F_{p^k}` there is: Gaudry's base
//! `{P : x(P) ∈ F_p}`, and if the frame and the involutions are
//! `F_p`-rational then every invariant of a factor-base point is in `F_p`
//! too, so one `F_{p^k}`-equation in `F_p`-unknowns is `k` equations over
//! `F_p` — read off the digits of the coefficients — and the repo's `F_p`
//! Buchberger engine can solve it.
//!
//! ## Fixed-target quotients
//!
//! The decomposition problem fixes the target `R`.  The symmetries that
//! remain are the elements of the relation subgroup `Γ` whose last
//! component is the identity, `Γ₀ = Γ ∩ (G^m × {id})`; the seeds are
//! functions of the summands only (`u(P_i)`, `Σu`, `Πu` over the
//! summands); the invariants are the orbit-set symmetric functions under
//! `Γ₀`; and the relation is interpolated from pairs `(P_1, …, P_m)` with
//! `Σ P_i = R` for *that* `R`, with the identities among the invariants
//! quotiented out as in [`crate::cryptanalysis::coordinate_quotients`].
//! The polynomial's coefficients depend on `R`, which is fine: `R` is
//! known.
//!
//! ## What is compared
//!
//! On the same curve, same target, same base: (a) Gaudry's `x`-system,
//! `S_{m+1}` in `x_i ∈ F_p`; (b) the sign-symmetrised system in
//! `w_i = u_i²` and `s' = Π u_i` (one involution, `T`); (c) the Klein
//! system, `Γ₀` generated by all of `E[2]`.  For each: `F_p`-unknowns,
//! `F_p`-equations (`k` per field equation), degrees, monomials, and the
//! wall-clock of a reduced Gröbner basis by Buchberger.  Every invariant
//! is checked to be `F_p`-valued on the factor base before anything is
//! timed.
//!
//! ## Honest scope
//!
//! Toy `p^k ≲ 5000`, `m = 2`, and the repo's textbook Buchberger, which
//! is the right algorithm and the wrong constant; the numbers rank the
//! three systems against each other on the same engine, nothing more.

use std::collections::HashMap;
use std::time::{Duration, Instant};

use num_bigint::BigUint;

use super::coordinate_quotients::{
    group_closure, monomials_up_to_total_degree, relation_subgroup, torsion_points,
    two_torsion_frame, Chart, PointMap, Seed,
};
use super::coordinate_search::{kernel, Curve, Gf, Mobius, Pt, Rng64, INF};
use super::f4_fp::{self, F4Options, Verdict};
use super::groebner_f4::{buchberger, reduce_basis, Ordering};
use super::symmetrized_semaev::MPoly;
use crate::ecc::field::FieldElement;

/// A fixed-target quotient system: `Γ₀`, the frame, the summand seeds and
/// their orbit-set invariants.
#[derive(Clone, Debug)]
pub struct FixedTargetSystem {
    pub gamma0: Vec<Vec<PointMap>>,
    pub chart: Chart,
    pub seeds: Vec<Seed>,
    /// `(seed index, orbit size, k)` for each invariant `e_k` of the seed's
    /// orbit set.
    pub invariants: Vec<(usize, usize, usize)>,
    pub m: usize,
    pub target: Pt,
}

fn elementary_symmetric(f: &Gf, xs: &[u64]) -> Vec<u64> {
    let m = xs.len();
    let mut e = vec![0u64; m + 1];
    e[0] = 1;
    for &x in xs {
        for k in (1..=m).rev() {
            e[k] = f.add(e[k], f.mul(x, e[k - 1]));
        }
    }
    e[1..].to_vec()
}

impl FixedTargetSystem {
    fn seed_value(&self, curve: &Curve, seed: &Seed, summands: &[Pt]) -> Option<u64> {
        let f = &curve.f;
        let u = |p: Pt| -> Option<u64> {
            let v = self.chart.apply(f, p);
            (v != INF).then_some(v)
        };
        match seed {
            Seed::Point(i) => u(summands[*i]),
            Seed::Sum => summands
                .iter()
                .try_fold(0u64, |acc, &p| Some(f.add(acc, u(p)?))),
            Seed::Product => summands
                .iter()
                .try_fold(1u64, |acc, &p| Some(f.mul(acc, u(p)?))),
            Seed::PairSum(i, j) => u(curve.add(summands[*i], summands[*j])),
            Seed::PairDiff(i, j) => u(curve.sub(summands[*i], summands[*j])),
        }
    }

    fn orbit_set(&self, curve: &Curve, seed: &Seed, summands: &[Pt]) -> Option<Vec<u64>> {
        let mut vals = Vec::with_capacity(self.gamma0.len());
        for g in &self.gamma0 {
            let moved: Vec<Pt> = summands
                .iter()
                .zip(g)
                .map(|(&p, gm)| gm.apply(curve, p))
                .collect();
            vals.push(self.seed_value(curve, seed, &moved)?);
        }
        vals.sort_unstable();
        vals.dedup();
        Some(vals)
    }

    /// Invariant vector of a summand tuple; `None` at a pole or on a
    /// degenerate tuple.
    pub fn evaluate(&self, curve: &Curve, summands: &[Pt]) -> Option<Vec<u64>> {
        let f = &curve.f;
        let mut cache: HashMap<usize, Vec<u64>> = HashMap::new();
        let mut out = Vec::with_capacity(self.invariants.len());
        for &(si, size, k) in &self.invariants {
            if !cache.contains_key(&si) {
                let set = self.orbit_set(curve, &self.seeds[si], summands)?;
                if set.len() != size {
                    return None;
                }
                cache.insert(si, elementary_symmetric(f, &set));
            }
            out.push(cache[&si][k - 1]);
        }
        Some(out)
    }

    pub fn names(&self) -> Vec<String> {
        self.invariants
            .iter()
            .map(|&(si, size, k)| {
                if size == 1 {
                    self.seeds[si].name()
                } else {
                    format!("e{}[{}]", k, self.seeds[si].name())
                }
            })
            .collect()
    }
}

/// Random summands with `Σ P_i = target`.
fn summands_for(curve: &Curve, pts: &[Pt], m: usize, target: Pt, rng: &mut Rng64) -> Vec<Pt> {
    loop {
        let mut tuple: Vec<Pt> = (0..m - 1)
            .map(|_| pts[rng.below(pts.len() as u64) as usize])
            .collect();
        let partial = tuple.iter().fold(Pt::Inf, |acc, &p| curve.add(acc, p));
        let last = curve.sub(target, partial);
        if last != Pt::Inf {
            tuple.push(last);
            return tuple;
        }
    }
}

/// Build the fixed-target system for `target`, `m` summands, group
/// generators and summand seeds.
pub fn build_fixed_target_system(
    curve: &Curve,
    pts: &[Pt],
    generators: &[PointMap],
    chart: impl Into<Chart>,
    seeds: &[Seed],
    m: usize,
    target: Pt,
    rng: &mut Rng64,
) -> Option<FixedTargetSystem> {
    let group = group_closure(curve, generators, 512)?;
    let gamma = relation_subgroup(curve, pts, &group, m, 12, rng);
    let identity = PointMap::identity();
    let gamma0: Vec<Vec<PointMap>> = gamma
        .into_iter()
        .filter(|g| g[m] == identity)
        .map(|g| g[..m].to_vec())
        .collect();
    if gamma0.is_empty() {
        return None;
    }
    let mut sys = FixedTargetSystem {
        gamma0,
        chart: chart.into(),
        seeds: seeds.to_vec(),
        invariants: Vec::new(),
        m,
        target,
    };
    let f = &curve.f;
    let probes: Vec<Vec<Pt>> = (0..24)
        .map(|_| summands_for(curve, pts, m, target, rng))
        .collect();
    let mut seen: Vec<Vec<u64>> = Vec::new();
    for (si, seed) in seeds.iter().enumerate() {
        let sets: Vec<Vec<u64>> = probes
            .iter()
            .filter_map(|t| sys.orbit_set(curve, seed, t))
            .collect();
        if sets.len() < 8 {
            continue;
        }
        let size = sets.iter().map(|s| s.len()).max().unwrap();
        let generic: Vec<&Vec<u64>> = sets.iter().filter(|s| s.len() == size).collect();
        for k in 1..=size.min(4) {
            let vector: Vec<u64> = generic
                .iter()
                .map(|s| elementary_symmetric(f, s)[k - 1])
                .collect();
            if vector.iter().all(|&v| v == vector[0]) || seen.contains(&vector) {
                continue;
            }
            seen.push(vector);
            sys.invariants.push((si, size, k));
        }
    }
    (!sys.invariants.is_empty()).then_some(sys)
}

/// A polynomial over `F_{p^k}` in the invariants, and its descent.
#[derive(Clone, Debug)]
pub struct DescendedSystem {
    pub var_names: Vec<String>,
    /// The `F_{p^k}` relation: exponent vectors and coefficients.
    pub relation: Vec<(Vec<u32>, u64)>,
    pub total_degree: u32,
    /// The `k` polynomials over `F_p` (digit `j` of each coefficient).
    pub equations: Vec<Vec<(Vec<u32>, u64)>>,
    /// Identities among the invariants at the relation's degree, also
    /// descended (they constrain the unknowns and belong in the system).
    pub identities: Vec<Vec<(Vec<u32>, u64)>>,
    pub fp_unknowns: usize,
    pub fp_equations: usize,
    pub monomials: usize,
    /// Every invariant of every factor-base tuple sampled was in `F_p`.
    pub fp_valued: bool,
}

fn eval_terms(f: &Gf, terms: &[(Vec<u32>, u64)], vals: &[u64]) -> u64 {
    let mut acc = 0;
    for (e, c) in terms {
        let mut t = *c;
        for (i, &k) in e.iter().enumerate() {
            if k > 0 {
                t = f.mul(t, f.pow(vals[i], k as u64));
            }
        }
        acc = f.add(acc, t);
    }
    acc
}

/// Interpolate the fixed-target relation at minimal total degree, with
/// identities quotiented out, then descend it and the identities to `F_p`.
pub fn interpolate_and_descend(
    curve: &Curve,
    pts: &[Pt],
    factor_base: &[Pt],
    sys: &FixedTargetSystem,
    max_total_degree: u32,
    rng: &mut Rng64,
) -> Result<DescendedSystem, String> {
    interpolate_and_descend_boxed(curve, pts, factor_base, sys, max_total_degree, None, rng)
}

/// [`interpolate_and_descend`] with a per-variable degree cap `(point,
/// tuple)` on top of the total degree, as in
/// `coordinate_quotients::interpolate_quotient_boxed`; needed at `m = 3`,
/// where Semaev's `S₄` has total degree 12 but degree 4 in each point.
pub fn interpolate_and_descend_boxed(
    curve: &Curve,
    pts: &[Pt],
    factor_base: &[Pt],
    sys: &FixedTargetSystem,
    max_total_degree: u32,
    caps: Option<(u32, u32)>,
    rng: &mut Rng64,
) -> Result<DescendedSystem, String> {
    let f = &curve.f;
    let nv = sys.invariants.len();
    let m = sys.m;
    let var_caps: Vec<u32> = sys
        .invariants
        .iter()
        .map(|&(si, _, _)| match (caps, &sys.seeds[si]) {
            (None, _) => u32::MAX,
            (Some((p, _)), Seed::Point(_)) => p,
            (Some((_, t)), _) => t,
        })
        .collect();
    let mut last_len = 0usize;
    let mut rel_samples: Vec<Vec<u64>> = Vec::new();
    let mut all_samples: Vec<Vec<u64>> = Vec::new();
    // F_p-valuedness on the factor base
    let mut fp_valued = true;
    let mut checked = 0;
    let mut attempts = 0;
    while checked < 40 && attempts < 4000 {
        attempts += 1;
        let tuple: Vec<Pt> = (0..m)
            .map(|_| factor_base[rng.below(factor_base.len() as u64) as usize])
            .collect();
        if let Some(v) = sys.evaluate(curve, &tuple) {
            checked += 1;
            if !v.iter().all(|&x| f.in_subfield(x, 1)) {
                fp_valued = false;
            }
        }
    }
    for d in 1..=max_total_degree {
        let monos: Vec<Vec<u32>> = monomials_up_to_total_degree(nv, d)
            .into_iter()
            .filter(|e| e.iter().zip(&var_caps).all(|(k, c)| k <= c))
            .collect();
        if monos.len() == last_len {
            continue; // box saturated at this total degree
        }
        last_len = monos.len();
        if monos.len() > 3000 {
            return Err(format!("degree {d} needs {} monomials", monos.len()));
        }
        let need = monos.len() + monos.len() / 4 + 40;
        let mut attempts = 0;
        while rel_samples.len() < need || all_samples.len() < need {
            attempts += 1;
            if attempts > 60 * need + 400 {
                return Err("could not sample enough tuples".to_string());
            }
            if rel_samples.len() < need {
                if let Some(v) = sys.evaluate(curve, &summands_for(curve, pts, m, sys.target, rng))
                {
                    rel_samples.push(v);
                }
            }
            if all_samples.len() < need {
                let tuple: Vec<Pt> = (0..m)
                    .map(|_| pts[rng.below(pts.len() as u64) as usize])
                    .collect();
                if let Some(v) = sys.evaluate(curve, &tuple) {
                    all_samples.push(v);
                }
            }
        }
        let rows = |samples: &[Vec<u64>]| -> Vec<Vec<u64>> {
            samples
                .iter()
                .map(|vals| {
                    monos
                        .iter()
                        .map(|e| {
                            let mut t = 1;
                            for (i, &k) in e.iter().enumerate() {
                                if k > 0 {
                                    t = f.mul(t, f.pow(vals[i], k as u64));
                                }
                            }
                            t
                        })
                        .collect()
                })
                .collect()
        };
        let k_rel = kernel(f, rows(&rel_samples), monos.len());
        if k_rel.is_empty() {
            continue;
        }
        let k_all = kernel(f, rows(&all_samples), monos.len());
        // echelon of identities with pivot on the highest-index monomial
        let mut basis: Vec<(usize, Vec<u64>)> = Vec::new();
        let reduce = |v: &[u64], basis: &[(usize, Vec<u64>)]| -> Vec<u64> {
            let mut v = v.to_vec();
            for (lead, b) in basis {
                if v[*lead] != 0 {
                    let c = v[*lead];
                    for (x, y) in v.iter_mut().zip(b) {
                        *x = f.sub(*x, f.mul(c, *y));
                    }
                }
            }
            v
        };
        for v in &k_all {
            let r = reduce(v, &basis);
            if let Some(lead) = (0..r.len()).rev().find(|&i| r[i] != 0) {
                let inv = f.inv(r[lead]);
                basis.push((lead, r.iter().map(|&c| f.mul(c, inv)).collect()));
            }
        }
        let mut candidates: Vec<Vec<u64>> = k_rel
            .iter()
            .map(|v| reduce(v, &basis))
            .filter(|v| v.iter().any(|&c| c != 0))
            .collect();
        if candidates.is_empty() {
            continue;
        }
        candidates.sort_by_key(|v| v.iter().filter(|&&c| c != 0).count());
        let to_terms = |v: &[u64]| -> Vec<(Vec<u32>, u64)> {
            monos
                .iter()
                .zip(v)
                .filter(|(_, &c)| c != 0)
                .map(|(e, &c)| (e.clone(), c))
                .collect()
        };
        let relation = to_terms(&candidates[0]);
        // verify
        for _ in 0..100 {
            if let Some(v) = sys.evaluate(curve, &summands_for(curve, pts, m, sys.target, rng)) {
                if eval_terms(f, &relation, &v) != 0 {
                    return Err("candidate failed on a fresh relation".to_string());
                }
            }
        }
        let identities: Vec<Vec<(Vec<u32>, u64)>> =
            basis.iter().map(|(_, b)| to_terms(b)).collect();
        // descend: digit j of every coefficient
        let k = f.n as usize;
        let descend = |terms: &[(Vec<u32>, u64)]| -> Vec<Vec<(Vec<u32>, u64)>> {
            (0..k)
                .map(|j| {
                    terms
                        .iter()
                        .filter_map(|(e, c)| {
                            let dj = f.digits(*c)[j];
                            (dj != 0).then(|| (e.clone(), dj))
                        })
                        .collect()
                })
                .filter(|eq: &Vec<(Vec<u32>, u64)>| !eq.is_empty())
                .collect()
        };
        let equations = descend(&relation);
        let descended_identities: Vec<Vec<(Vec<u32>, u64)>> =
            identities.iter().flat_map(|i| descend(i)).collect();
        let monomials = relation.len();
        return Ok(DescendedSystem {
            var_names: sys.names(),
            relation,
            total_degree: d,
            fp_unknowns: nv,
            fp_equations: equations.len() + descended_identities.len(),
            equations,
            identities: descended_identities,
            monomials,
            fp_valued,
        });
    }
    Err(format!("no relation up to total degree {max_total_degree}"))
}

/// Convert descended equations to the Gröbner engine's `MPoly` over `F_p`.
pub fn to_mpolys(p: u64, n_vars: usize, eqs: &[Vec<(Vec<u32>, u64)>]) -> Vec<MPoly> {
    let pb = BigUint::from(p);
    eqs.iter()
        .map(|eq| {
            let mut poly = MPoly::zero(n_vars, pb.clone());
            for (e, c) in eq {
                poly.terms.insert(
                    e.clone(),
                    FieldElement {
                        value: BigUint::from(*c),
                        modulus: pb.clone(),
                    },
                );
            }
            poly
        })
        .collect()
}

/// Gröbner-basis timing of a descended system: `(reduced basis size,
/// milliseconds, basis is {1})`.
pub fn groebner_time(p: u64, sys: &DescendedSystem) -> (usize, f64, bool) {
    let mut eqs = sys.equations.clone();
    eqs.extend(sys.identities.iter().cloned());
    let polys = to_mpolys(p, sys.fp_unknowns, &eqs);
    let t0 = Instant::now();
    let gb = buchberger(&polys, Ordering::Grevlex);
    let red = reduce_basis(&gb, Ordering::Grevlex);
    let ms = t0.elapsed().as_secs_f64() * 1e3;
    let inconsistent = red
        .iter()
        .any(|g| g.terms.len() == 1 && g.terms.keys().next().unwrap().iter().all(|&e| e == 0));
    (red.len(), ms, inconsistent)
}

/// Wall-clock budget for one Buchberger run in [`compare_arms`]: the
/// `GB_BUDGET_SECS` environment variable, default 120 s.  Buchberger on a
/// descended degree-12 `S₄` system does not return in any useful time,
/// and a comparison must be able to say so rather than hang.
pub fn groebner_budget() -> Duration {
    std::env::var("GB_BUDGET_SECS")
        .ok()
        .and_then(|v| v.parse::<u64>().ok())
        .map(Duration::from_secs)
        .unwrap_or(Duration::from_secs(120))
}

/// [`groebner_time`] on its own thread, `None` if it exceeds `budget`
/// (the thread is left to finish on its own; the process does not wait).
pub fn groebner_time_bounded(
    p: u64,
    sys: &DescendedSystem,
    budget: Duration,
) -> Option<(usize, f64, bool)> {
    let sys = sys.clone();
    let (tx, rx) = std::sync::mpsc::channel();
    std::thread::spawn(move || {
        let r = groebner_time(p, &sys);
        let _ = tx.send(r);
    });
    rx.recv_timeout(budget).ok()
}

/// One arm of the comparison.
#[derive(Clone, Debug)]
pub struct DescentArm {
    pub label: String,
    pub gamma0_order: usize,
    pub invariants: Vec<String>,
    pub total_degree: u32,
    pub monomials: usize,
    pub fp_unknowns: usize,
    pub fp_equations: usize,
    pub fp_valued: bool,
    pub basis_size: usize,
    pub groebner_ms: f64,
    pub inconsistent: bool,
    /// Buchberger exceeded [`groebner_budget`]; `groebner_ms` is `+∞`.
    pub timed_out: bool,
    /// Degree-bounded F4 ([`f4_fp`]): milliseconds, solving degree,
    /// verdict, number of solutions (all checked against the system),
    /// and the largest matrix.
    pub f4_ms: f64,
    pub f4_degree: u32,
    pub f4_verdict: F4Verdict,
    pub f4_solutions: usize,
    pub f4_matrix: (usize, usize),
    pub error: Option<String>,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum F4Verdict {
    NotRun,
    Found,
    Refuted,
    /// Degree bound or budget reached first.
    Undetermined,
    /// A reported solution did not satisfy the system.
    Wrong,
}

impl F4Verdict {
    pub fn short(&self) -> &'static str {
        match self {
            F4Verdict::NotRun => "–",
            F4Verdict::Found => "found",
            F4Verdict::Refuted => "refuted",
            F4Verdict::Undetermined => "undet.",
            F4Verdict::Wrong => "WRONG",
        }
    }
}

/// Which Gröbner engines [`compare_arms`] times: `GB_ENGINE` = `both`
/// (default), `f4`, or `buchberger`.
pub fn engines() -> (bool, bool) {
    match std::env::var("GB_ENGINE").as_deref() {
        Ok("f4") => (false, true),
        Ok("buchberger") => (true, false),
        _ => (true, true),
    }
}

/// Degree bound for the F4 runs: `F4_MAX_DEGREE`, default 24.
pub fn f4_max_degree() -> u32 {
    std::env::var("F4_MAX_DEGREE")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(24)
}

/// Solve a descended system with the degree-bounded F4 under the same
/// budget as Buchberger; every solution is checked against the system.
pub fn f4_time(p: u64, sys: &DescendedSystem) -> (f64, u32, F4Verdict, usize, (usize, usize)) {
    let mut eqs: Vec<f4_fp::Poly> = sys.equations.clone();
    eqs.extend(sys.identities.iter().cloned());
    let opts = F4Options::new(Ordering::Grevlex, f4_max_degree()).with_budget(groebner_budget());
    let r = f4_fp::solve(&eqs, sys.fp_unknowns, p, &opts);
    let (verdict, n) = match &r.verdict {
        Verdict::Inconsistent => (F4Verdict::Refuted, 0),
        Verdict::Undetermined => (F4Verdict::Undetermined, 0),
        Verdict::Solutions(sols) => {
            let ok = sols
                .iter()
                .all(|x| eqs.iter().all(|f| f4_fp::eval(f, x, p) == 0));
            (
                if ok {
                    F4Verdict::Found
                } else {
                    F4Verdict::Wrong
                },
                sols.len(),
            )
        }
    };
    (r.ms, r.solving_degree, verdict, n, (r.max_rows, r.max_cols))
}

/// One candidate coordinate system for [`compare_arms`]: label, group
/// generators, chart, summand seeds.
pub type Arm = (String, Vec<PointMap>, Chart, Vec<Seed>);

/// Run the three standard arms (Gaudry's `x`, one 2-torsion involution,
/// the full 2-torsion group) on one curve and target.
pub fn compare_descents(
    curve: &Curve,
    pts: &[Pt],
    target: Pt,
    m: usize,
    rng: &mut Rng64,
) -> Vec<DescentArm> {
    let (base, arms) = standard_arms(curve, pts, m, rng);
    compare_arms(curve, pts, target, m, base, arms, rng)
}

/// The interpolation degree box for `m` summands: total degree and
/// `(point, tuple)` caps.  Semaev's relation has degree `2^{m−1}` in each
/// point; the quotient invariants have at most that, the tuple invariants
/// at most twice it, and the total degree is bounded by their sum.
pub fn degree_box(m: usize) -> (u32, Option<(u32, u32)>) {
    if m <= 2 {
        (6, None)
    } else {
        let d = 1u32 << (m - 1);
        (d * m as u32 + 2 * d, Some((d, 2 * d)))
    }
}

/// The three standard arms and the base chart they share (the 2-torsion
/// sign frame on the `x`-line).
pub fn standard_arms(curve: &Curve, pts: &[Pt], m: usize, rng: &mut Rng64) -> (Chart, Vec<Arm>) {
    let t2 = torsion_points(curve, pts, 2);
    let frame = two_torsion_frame(curve, pts, rng);
    let point_seeds: Vec<Seed> = (0..m).map(Seed::Point).collect();
    let mut with_product = point_seeds.clone();
    with_product.push(Seed::Product);
    let mut with_extras = with_product.clone();
    with_extras.push(Seed::Sum);
    let mut arms: Vec<Arm> = Vec::new();
    arms.push((
        "x (Gaudry)".into(),
        vec![PointMap::negate()],
        Chart::x(Mobius::identity()),
        point_seeds.clone(),
    ));
    if let Some(&t) = t2.first() {
        arms.push((
            "one T, sign frame: w, Πu".into(),
            vec![PointMap::translate(t), PointMap::negate()],
            Chart::x(frame),
            with_product,
        ));
    }
    if t2.len() == 3 {
        let mut gens: Vec<PointMap> = t2.iter().map(|&t| PointMap::translate(t)).collect();
        gens.push(PointMap::negate());
        arms.push((
            "E[2] (Klein): orbit invariants".into(),
            gens,
            Chart::x(frame),
            with_extras,
        ));
    }
    (Chart::x(frame), arms)
}

/// Run arbitrary arms on one curve and target.  The factor base is the
/// set of points whose `base_chart` coordinate is finite and lies in
/// `F_p`; every arm is interpolated on that same base so the arms are
/// comparable.
pub fn compare_arms(
    curve: &Curve,
    pts: &[Pt],
    target: Pt,
    m: usize,
    base_chart: Chart,
    arms: Vec<Arm>,
    rng: &mut Rng64,
) -> Vec<DescentArm> {
    let f = &curve.f;
    let factor_base: Vec<Pt> = pts
        .iter()
        .copied()
        .filter(|&p| {
            let u = base_chart.apply(f, p);
            u != INF && f.in_subfield(u, 1)
        })
        .collect();
    let mut out = Vec::new();
    for (label, gens, fr, seeds) in arms {
        let Some(sys) = build_fixed_target_system(curve, pts, &gens, fr, &seeds, m, target, rng)
        else {
            out.push(DescentArm {
                label,
                gamma0_order: 0,
                invariants: vec![],
                total_degree: 0,
                monomials: 0,
                fp_unknowns: 0,
                fp_equations: 0,
                fp_valued: false,
                basis_size: 0,
                groebner_ms: f64::NAN,
                inconsistent: false,
                timed_out: false,
                f4_ms: f64::NAN,
                f4_degree: 0,
                f4_verdict: F4Verdict::NotRun,
                f4_solutions: 0,
                f4_matrix: (0, 0),
                error: Some("no system".into()),
            });
            continue;
        };
        let (max_deg, caps) = degree_box(m);
        match interpolate_and_descend_boxed(curve, pts, &factor_base, &sys, max_deg, caps, rng) {
            Ok(d) => {
                // A system whose unknowns are not F_p-valued on the base
                // has no descent; do not time a meaningless basis.
                let (run_bb, run_f4) = engines();
                let (basis_size, ms, inconsistent, timed_out) = if d.fp_valued && run_bb {
                    match groebner_time_bounded(f.p, &d, groebner_budget()) {
                        Some((b, ms, inc)) => (b, ms, inc, false),
                        None => (0, f64::INFINITY, false, true),
                    }
                } else {
                    (0, f64::NAN, false, false)
                };
                let (f4_ms, f4_degree, f4_verdict, f4_solutions, f4_matrix) =
                    if d.fp_valued && run_f4 {
                        f4_time(f.p, &d)
                    } else {
                        (f64::NAN, 0, F4Verdict::NotRun, 0, (0, 0))
                    };
                out.push(DescentArm {
                    label,
                    gamma0_order: sys.gamma0.len(),
                    invariants: d.var_names.clone(),
                    total_degree: d.total_degree,
                    monomials: d.monomials,
                    fp_unknowns: d.fp_unknowns,
                    fp_equations: d.fp_equations,
                    fp_valued: d.fp_valued,
                    basis_size,
                    groebner_ms: ms,
                    inconsistent,
                    timed_out,
                    f4_ms,
                    f4_degree,
                    f4_verdict,
                    f4_solutions,
                    f4_matrix,
                    error: None,
                });
            }
            Err(e) => out.push(DescentArm {
                label,
                gamma0_order: sys.gamma0.len(),
                invariants: sys.names(),
                total_degree: 0,
                monomials: 0,
                fp_unknowns: sys.invariants.len(),
                fp_equations: 0,
                fp_valued: false,
                basis_size: 0,
                groebner_ms: f64::NAN,
                inconsistent: false,
                timed_out: false,
                f4_ms: f64::NAN,
                f4_degree: 0,
                f4_verdict: F4Verdict::NotRun,
                f4_solutions: 0,
                f4_matrix: (0, 0),
                error: Some(e),
            }),
        }
    }
    out
}

pub fn format_arms(arms: &[DescentArm]) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "   {:<34} {:>4} {:>6} {:>6} {:>6} {:>5} {:>4} {:>8} {:>8} {:>8} {:>4} {:>8} {:>3} {:>11}  {}\n",
        "arm", "|Γ₀|", "F_p-unk", "F_p-eq", "deg", "terms", "F_p?", "GB ms", "basis", "F4 ms", "sdeg", "verdict", "#", "matrix", "invariants"
    ));
    for a in arms {
        if let Some(e) = &a.error {
            s.push_str(&format!("   {:<34} {:>4}  {e}\n", a.label, a.gamma0_order));
            continue;
        }
        s.push_str(&format!(
            "   {:<34} {:>4} {:>6} {:>6} {:>6} {:>5} {:>4} {:>8.1} {:>8} {:>8.1} {:>4} {:>8} {:>3} {:>11}  {}\n",
            a.label,
            a.gamma0_order,
            a.fp_unknowns,
            a.fp_equations,
            a.total_degree,
            a.monomials,
            if a.fp_valued { "yes" } else { "NO" },
            a.groebner_ms,
            if a.timed_out {
                "> budget".to_string()
            } else if a.inconsistent {
                "{1}".to_string()
            } else {
                a.basis_size.to_string()
            },
            a.f4_ms,
            a.f4_degree,
            a.f4_verdict.short(),
            a.f4_solutions,
            format!("{}×{}", a.f4_matrix.0, a.f4_matrix.1),
            a.invariants.join(", ")
        ));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `y² = x(x² − αx + 1)` with `α ∉ F_p` and `α² − 4` a square: not
    /// over `F_p`, full rational 2-torsion, `T = (0, 0)` with `x(P + T) =
    /// 1/x` whose fixed points `±1` give an `F_p`-rational sign frame.
    fn alpha_curve(f: Gf) -> Curve {
        let four = f.add(f.add(1, 1), f.add(1, 1));
        let alpha = (f.p..f.q)
            .find(|&a| {
                !f.in_subfield(a, 1) && {
                    let disc = f.sub(f.mul(a, a), four);
                    disc != 0 && f.sqrt(disc).is_some()
                }
            })
            .unwrap();
        Curve {
            a1: 0,
            a2: f.neg(alpha),
            a3: 0,
            a4: 1,
            a6: 0,
            label: "α-curve".into(),
            f,
        }
    }

    #[test]
    fn in_gaudrys_setting_one_involution_descends_and_the_klein_group_does_not() {
        let c = alpha_curve(Gf::extension(29, 3));
        let pts = c.affine_points();
        assert_eq!(c.two_torsion().len(), 3);
        assert_eq!(c.subfield_degree(), Some(3), "not defined over F_p");
        let mut rng = Rng64::new(8);
        let base: Vec<Pt> = pts
            .iter()
            .copied()
            .filter(|p| c.f.in_subfield(p.x(), 1))
            .collect();
        assert!(base.len() >= 8);
        // a decomposable target with x(R) ∉ F_p — the base is not a subgroup
        let target = (0..base.len())
            .flat_map(|i| (i + 1..base.len()).map(move |j| (i, j)))
            .map(|(i, j)| c.add(base[i], base[j]))
            .find(|r| matches!(r, Pt::Aff(x, _) if !c.f.in_subfield(*x, 1)))
            .expect("a target outside E(F_p)");
        let arms = compare_descents(&c, &pts, target, 2, &mut rng);
        assert_eq!(arms.len(), 3, "{}", format_arms(&arms));
        let text = format_arms(&arms);
        // Gaudry: 2 unknowns, k = 3 equations, S₃ of total degree 4
        assert!(arms[0].error.is_none() && arms[0].fp_valued, "{text}");
        assert_eq!(arms[0].fp_unknowns, 2);
        assert_eq!(arms[0].fp_equations, 3);
        assert_eq!(arms[0].total_degree, 4);
        assert!(!arms[0].inconsistent, "{text}");
        // one involution: F_p-valued, descends, does not refute
        assert!(arms[1].error.is_none() && arms[1].fp_valued, "{text}");
        assert!(!arms[1].inconsistent, "{text}");
        assert_eq!(arms[1].total_degree, 2, "{text}");
        // the Klein group: larger Γ₀, but its invariants leave F_p on the base
        assert!(arms[2].gamma0_order > arms[1].gamma0_order);
        assert!(!arms[2].fp_valued, "{text}");
        // the degree-bounded F4 agrees with Buchberger on both descended
        // systems and finds the decomposition (checked against the system)
        for a in &arms[..2] {
            assert_eq!(a.f4_verdict, F4Verdict::Found, "{text}");
            assert!(a.f4_solutions >= 1, "{text}");
            assert!(a.f4_ms.is_finite() && a.f4_ms < 30_000.0, "{text}");
        }
        // a random target off the base is refuted by both engines the
        // same way (or found by both)
        let random = pts
            .iter()
            .copied()
            .find(|&r| matches!(r, Pt::Aff(x, _) if !c.f.in_subfield(x, 1)) && !base.contains(&r))
            .unwrap();
        let arms2 = compare_descents(&c, &pts, random, 2, &mut rng);
        let text2 = format_arms(&arms2);
        for a in &arms2[..2] {
            assert_ne!(a.f4_verdict, F4Verdict::Undetermined, "{text2}");
            assert_ne!(a.f4_verdict, F4Verdict::Wrong, "{text2}");
            assert_eq!(
                a.f4_verdict == F4Verdict::Refuted,
                a.inconsistent,
                "{text2}"
            );
        }
    }
}
