//! # Signature-based F4 over the tower quotient ring.
//!
//! [`f4_fp_tower`](super::f4_fp_tower) spends most of a large run on rows
//! that reduce to zero: in round 3's `m = 4`, `N = 16` system, 88% of the
//! last step's rows (`research/notes/index-calculus/RESEARCH_PKM_TOWER_ORACLE.md`
//! §12.7). Signature-based algorithms (F5, GVW, Roune–Stillman's signature
//! bases) predict most such rows from syzygies and never build them. This
//! is that algorithm on the same ring `R = F_p[y, u] / (towers)`, in the
//! matrix (F4) form.
//!
//! ## Signatures live in the polynomial ring
//!
//! The boolean engine's note (`matrix_f5_f2.rs`) shows why the textbook
//! criterion is unsound in a quotient ring: multiplying by a monomial is not
//! order-compatible there (`y·(y + …)` rewrites to a smaller monomial). This
//! engine never multiplies signatures in `R`. The module is `P^k` over the
//! polynomial ring `P = F_p[y, u]`, generated by the inputs `f_1, …, f_k`,
//! and the tower relations `T_j = y_j² − rule_j` are generators of lower
//! index, a Gröbner basis already (Lemma 1 of the note).
//! - A signature is a `P`-monomial times `e_i`. The principal syzygy of
//!   `f_i` with `T_j` has signature `y_j²·e_i`, so every signature with a
//!   squared tower variable is a syzygy signature and is never processed.
//!   Live signatures are therefore square-free in the tower variables.
//! - Reducing by `T_j` never changes a signature (its component is lower),
//!   so polynomials stay in normal form in `R`.
//! - A *tower pair* `(g, y_j)`, `y_j | LM(g)`, is the S-pair of `g` with
//!   `T_j`: the row `NF(y_j·g)` with signature `y_j·sig(g)`, dropped when
//!   `y_j` already divides `sig(g)`.
//!
//! ## The algorithm
//! - **Module order** ([`ModuleOrder`]): by default position over term
//!   (every signature of `e_i` before any of `e_{i+1}`, F5's incremental
//!   order), then signature degree `deg t + deg f_i` (the sugar), then
//!   grevlex on `t`; or signature degree first, then the index. Both are
//!   compatible with multiplication by monomials of `P`, which is all the
//!   theory asks.
//! - **Steps** take every pair of the lowest signature degree. The rows (the
//!   larger half of each critical pair, each tower row, and each generator
//!   the first time) are joined by one reducer per monomial with a divisor:
//!   among the basis elements whose leading monomial divides it, the one
//!   whose multiple has the smallest signature.
//! - **Elimination** takes the rows in increasing signature. A row is
//!   top-reduced only by rows of strictly smaller signature (regular
//!   reduction); one whose leading monomial meets a row of equal signature
//!   is singular and dropped. A row reduced to zero gives a syzygy
//!   signature.
//! - **New elements** are the S-rows that survive, and the reducer rows
//!   whose leading monomial moved, with square-free signatures.
//! - **Criteria**, applied when a step takes its pairs:
//!   - *syzygy*: the signature is divisible by a known syzygy signature:
//!     those of zero reductions, the Koszul signatures
//!     `max(LM(f_j)·sig(h), LM(h)·e_j)` of every element `h` against every
//!     input `f_j`, and the Koszul signature of a pair with coprime leading
//!     monomials, which is the pair's own (such pairs are never stored);
//!   - *rewrite*: one row per signature, built from the element that
//!     stands for it among those whose signature divides it ([`Rewrite`]:
//!     the largest `sig/LM` by default, or the latest), whichever pairs
//!     produced the signature (Roune–Stillman).
//!
//! A signature equal to an element's own is not skipped: the element is
//! rebuilt as a row and reduced again. A row becomes an element with only
//! the reducers its step had, so an element found earlier in the same step,
//! of smaller signature, may still reduce its lead. The pair between the two
//! has the later element's signature, and skipping it lost those reductions
//! (a build that did returned bases without them).
//!
//! Correctness does not rest on this text: the tests compare the basis with
//! `f4_fp_tower`'s on random systems and refutations with exhaustive
//! search, and the example checks every row with `verify.py`.
//!
//! ## What it measures
//! - `solving_degree_max`: the highest degree of a row that yielded a new
//!   element. A row's degree is its nominal one, `deg t + deg LM(g)`, which
//!   for an S-row is the lcm degree `f4_fp_tower` reports.
//! - The signature degree of each step, the rows reduced to zero, the rows
//!   the criteria skipped, and `F_p` multiply-adds, the same unit.
//!
//! Steps take pairs by signature degree, and a step's new elements can
//! create pairs of the same degree with smaller signatures than rows the
//! step already reduced ("late" pairs). They are processed in the next
//! step and counted: the theory asks for increasing signatures, so the
//! tests are what vouches for a run that has them.

use std::cmp::Ordering;
use std::collections::{HashMap, HashSet};
use std::hash::BuildHasherDefault;
use std::sync::Arc;
use std::time::Instant;

use rayon::prelude::*;

use super::f4_fp_tower::{
    coprime, degree_of, free_of, lcm, mask_of, mono, quotient, staircase_at_most, Acc, Fp, Mono,
    MonoHasher, MonoMap, RPoly, Row, TowerF4Options, TowerF4Report, TowerRing, MAX_FREE, NONE, ONE,
};

// ── Signatures ───────────────────────────────────────────────────────

/// A module term `t·e_i`, `t` a monomial of `P` whose tower exponents are
/// at most 2: `ones` holds the tower variables of exponent ≥ 1, `twos`
/// those of exponent 2. `sugar = deg t + deg f_i`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
struct PSig {
    sugar: u32,
    idx: u32,
    ones: u64,
    twos: u64,
    free: [u8; MAX_FREE],
}

impl PSig {
    fn square_free(self) -> bool {
        self.twos == 0
    }

    /// The monomial `t` as a key of `R`, when it is square-free.
    fn mono(self) -> Mono {
        debug_assert!(self.square_free());
        mono(self.ones, self.free)
    }

    fn of(m: Mono, idx: u32, d: u32) -> PSig {
        PSig {
            sugar: degree_of(m) + d,
            idx,
            ones: mask_of(m),
            twos: 0,
            free: free_of(m),
        }
    }

    /// `u · self`, for a monomial `u` of `R` and a square-free `self`.
    fn times(self, u: Mono) -> PSig {
        debug_assert!(self.square_free());
        let um = mask_of(u);
        let uf = free_of(u);
        let mut free = self.free;
        for (a, b) in free.iter_mut().zip(uf) {
            *a += b;
        }
        PSig {
            sugar: self.sugar + degree_of(u),
            idx: self.idx,
            ones: self.ones | um,
            twos: self.ones & um,
            free,
        }
    }
}

impl Ord for PSig {
    /// The module order: sugar, then index, then grevlex on `t` with tower
    /// variable 0 largest and the free variables smallest (the order of
    /// [`Mono`] keys, extended to exponent 2).
    fn cmp(&self, o: &Self) -> Ordering {
        self.sugar
            .cmp(&o.sugar)
            .then(self.idx.cmp(&o.idx))
            .then_with(|| {
                // Same sugar and index, hence the same degree of `t`: the
                // last differing variable decides, the smaller exponent
                // making the larger monomial.
                for k in (0..MAX_FREE).rev() {
                    if self.free[k] != o.free[k] {
                        return o.free[k].cmp(&self.free[k]);
                    }
                }
                let diff = (self.ones ^ o.ones) | (self.twos ^ o.twos);
                if diff == 0 {
                    return Ordering::Equal;
                }
                let j = 63 - diff.leading_zeros();
                let e = |s: &PSig| ((s.ones >> j) & 1) + ((s.twos >> j) & 1);
                e(o).cmp(&e(self))
            })
    }
}

impl PartialOrd for PSig {
    fn partial_cmp(&self, o: &Self) -> Option<Ordering> {
        Some(self.cmp(o))
    }
}

/// Every divisor of `m` (tower submasks times free vectors below `m`'s),
/// passed to `f` until it returns `true`; returns whether one did.
fn any_divisor(m: Mono, mut f: impl FnMut(Mono) -> bool) -> bool {
    let mask = mask_of(m);
    let fm = free_of(m);
    let mut s = mask;
    loop {
        let mut fv = [0u8; MAX_FREE];
        loop {
            if f(mono(s, fv)) {
                return true;
            }
            let mut k = 0;
            while k < MAX_FREE {
                if fv[k] < fm[k] {
                    fv[k] += 1;
                    break;
                }
                fv[k] = 0;
                k += 1;
            }
            if k == MAX_FREE {
                break;
            }
        }
        if s == 0 {
            return false;
        }
        s = (s - 1) & mask;
    }
}

// ── Elements and pairs ───────────────────────────────────────────────

/// A basis element: its signature `sig_m · e_idx`, square-free, and its
/// terms, the columns `pos` of a column list it may share with others.
struct SElem {
    sig: PSig,
    lm: Mono,
    cols: Arc<[Mono]>,
    pos: Vec<u32>,
    vals: Vec<u32>,
}

impl SElem {
    fn terms(&self) -> impl Iterator<Item = (Mono, u32)> + '_ {
        self.pos
            .iter()
            .zip(&self.vals)
            .map(|(&c, &v)| (self.cols[c as usize], v))
    }

    fn to_rpoly(&self) -> RPoly {
        let (monos, coefs) = self.terms().unzip();
        RPoly { monos, coefs }
    }
}

#[derive(Clone, Copy, Debug)]
enum Source {
    /// Input `i`, signature `e_i`.
    Gen(u32),
    /// The larger half `t·g` of a critical pair.
    Crit(Mono, u32),
    /// `y_v·g`, the pair of `g` with `T_v`.
    Tower(u32, u8),
}

#[derive(Clone, Copy, Debug)]
struct Pair {
    sig: PSig,
    src: Source,
    /// `deg t + deg LM(g)`: the lcm degree of a critical pair, `deg LM + 1`
    /// for a tower pair, the input's degree for a generator.
    nominal: u32,
}

/// The engine's counters beyond [`TowerF4Report`].
#[derive(Clone, Debug, Default, serde::Serialize)]
pub struct SigStats {
    pub pairs_formed: u64,
    pub pairs_coprime: u64,
    pub pairs_tower_square: u64,
    pub pairs_singular: u64,
    pub skipped_syzygy: u64,
    pub skipped_rewrite: u64,
    pub s_rows: u64,
    pub reducer_rows: u64,
    pub zero_rows: u64,
    pub singular_rows: u64,
    pub late_pairs: u64,
    pub elements: u64,
    /// Highest signature degree of a step that gained an element.
    pub sig_degree_max: u32,
}

/// One step, for traces.
#[derive(Clone, Debug, Default, serde::Serialize)]
pub struct SigStep {
    /// The step's signature degree, and under position over term the input
    /// its signatures belong to.
    pub sugar: u32,
    pub position: u32,
    pub pairs: usize,
    pub skipped_syzygy: usize,
    pub skipped_rewrite: usize,
    /// Rows built from a rewriter that none of the signature's pairs used.
    pub rewritten_rows: usize,
    pub gen_rows: usize,
    pub crit_rows: usize,
    pub tower_rows: usize,
    pub reducer_rows: usize,
    pub cols: usize,
    pub nnz: u64,
    pub zero_rows: usize,
    pub singular_rows: usize,
    pub fresh: usize,
    pub fresh_min_degree: u32,
    pub fresh_max_nominal: u32,
    pub late_pairs: usize,
    pub muladds: u64,
    pub elements: usize,
    pub pairs_left: usize,
    pub ms: f64,
    pub ms_rows: f64,
    pub ms_reduce: f64,
}

pub struct SigReport {
    pub report: TowerF4Report,
    pub stats: SigStats,
    pub steps: Vec<SigStep>,
}

struct State {
    elems: Vec<SElem>,
    /// Leading monomial → the element with it of smallest signature.
    lm_min: MonoMap<u32>,
    /// Signature (square-free `t`, index) → the latest element with it.
    by_sig: HashMap<(Mono, u32), u32, BuildHasherDefault<MonoHasher>>,
    syz: HashSet<(Mono, u32), BuildHasherDefault<MonoHasher>>,
    pairs: Vec<Pair>,
    /// Leading monomials of the inputs, and their degrees.
    gen_lm: Vec<Mono>,
    gen_deg: Vec<u32>,
    n_tower: usize,
    rewrite: Rewrite,
    /// Take one signature per step instead of a whole signature degree.
    one_signature: bool,
}

/// Which element stands for a signature when several could (the rewrite
/// criterion): Roune–Stillman's two orders.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Rewrite {
    /// The latest element.
    Insertion,
    /// The element of largest `sig/LM`.
    Ratio,
}

impl State {
    fn syzygy_covered(&self, s: PSig) -> bool {
        let i = s.idx;
        any_divisor(s.mono(), |d| self.syz.contains(&(d, i)))
    }

    /// Whether element `a` rewrites before element `b`: under the ratio
    /// order, the larger `sig/LM` (compared as `sig(a)·LM(b)` against
    /// `sig(b)·LM(a)`), the later element on a tie; under the insertion
    /// order, the later element. Either way an element whose signature a
    /// multiple of another's is and which was reduced from it wins, as a
    /// rewrite order must (Eder–Roune).
    fn prefer(&self, a: u32, b: u32) -> bool {
        if self.rewrite == Rewrite::Ratio {
            let (ea, eb) = (&self.elems[a as usize], &self.elems[b as usize]);
            match ea.sig.times(eb.lm).cmp(&eb.sig.times(ea.lm)) {
                Ordering::Greater => return true,
                Ordering::Less => return false,
                Ordering::Equal => {}
            }
        }
        a > b
    }

    /// The element that stands for signature `s`: among those whose
    /// signature divides it, the first in the rewrite order.
    fn rewriter(&self, s: PSig) -> Option<u32> {
        let i = s.idx;
        let mut best: Option<u32> = None;
        any_divisor(s.mono(), |d| {
            if let Some(&e) = self.by_sig.get(&(d, i)) {
                if best.is_none_or(|b| self.prefer(e, b)) {
                    best = Some(e);
                }
            }
            false
        });
        best
    }

    fn add_syzygy(&mut self, s: PSig) {
        if s.square_free() {
            self.syz.insert((s.mono(), s.idx));
        }
    }

    /// Adds element `h`, its Koszul syzygies against the inputs, and its
    /// pairs.
    fn insert(&mut self, e: SElem, st: &mut SigStats) {
        let h = self.elems.len() as u32;
        let (sh, lh) = (e.sig, e.lm);
        self.elems.push(e);
        st.elements += 1;
        match self.lm_min.get(&lh) {
            Some(&g) if self.elems[g as usize].sig <= sh => {}
            _ => {
                self.lm_min.insert(lh, h);
            }
        }
        match self.by_sig.get(&(sh.mono(), sh.idx)) {
            Some(&e) if !self.prefer(h, e) => {}
            _ => {
                self.by_sig.insert((sh.mono(), sh.idx), h);
            }
        }
        // Koszul against each input f_j: f_j·H − h·e_j.
        for j in 0..self.gen_lm.len() {
            let a = sh.times(self.gen_lm[j]);
            let b = PSig::of(lh, j as u32, self.gen_deg[j]);
            match a.cmp(&b) {
                Ordering::Greater => self.add_syzygy(a),
                Ordering::Less => self.add_syzygy(b),
                Ordering::Equal => {}
            }
        }
        // Tower pairs.
        let mut bits = mask_of(lh);
        while bits != 0 {
            let v = bits.trailing_zeros();
            bits &= bits - 1;
            if sh.ones >> v & 1 == 1 {
                st.pairs_tower_square += 1;
                continue;
            }
            let y = mono(1u64 << v, [0; MAX_FREE]);
            st.pairs_formed += 1;
            self.pairs.push(Pair {
                sig: sh.times(y),
                src: Source::Tower(h, v as u8),
                nominal: degree_of(lh) + 1,
            });
        }
        // Critical pairs with every earlier element.
        let new_pairs: Vec<Pair> = (0..h)
            .into_par_iter()
            .filter_map(|g| {
                let eg = &self.elems[g as usize];
                if coprime(eg.lm, lh) {
                    return None;
                }
                let l = lcm(eg.lm, lh);
                let (tg, th) = (quotient(l, eg.lm), quotient(l, lh));
                let (a, b) = (eg.sig.times(tg), sh.times(th));
                let (sig, src) = match a.cmp(&b) {
                    Ordering::Greater => (a, Source::Crit(tg, g)),
                    Ordering::Less => (b, Source::Crit(th, h)),
                    Ordering::Equal => return None,
                };
                if !sig.square_free() {
                    return None;
                }
                Some(Pair {
                    sig,
                    src,
                    nominal: degree_of(l),
                })
            })
            .collect();
        let formed = u64::from(h);
        let kept = new_pairs.len() as u64;
        st.pairs_formed += kept;
        // The rest were coprime, singular or squared: counted together.
        st.pairs_coprime += formed - kept;
        self.pairs.extend(new_pairs);
    }

    /// The multiple of an element with leading monomial `m` of smallest
    /// signature, if any element's leading monomial divides `m`.
    fn reducer_for(&self, m: Mono) -> Option<(Mono, u32, PSig)> {
        let mut best: Option<(Mono, u32, PSig)> = None;
        any_divisor(m, |d| {
            if let Some(&g) = self.lm_min.get(&d) {
                let t = quotient(m, d);
                let s = self.elems[g as usize].sig.times(t);
                if best.is_none_or(|b| s < b.2) {
                    best = Some((t, g, s));
                }
            }
            false
        });
        best
    }
}

/// One row of a step: its source, signature and polynomial.
struct SRow {
    sig: PSig,
    /// Critical, tower or generator (`true`), or a reducer.
    is_s: bool,
    /// The row is `t·g` with leading monomial `t·LM(g)`: if nothing of
    /// smaller signature reduces that lead, `g` itself singularly
    /// top-reduces the row and it is not new (Roune–Stillman).
    exact: bool,
    nominal: u32,
    poly: RPoly,
}

/// **Signature-based F4 on `R`** for the ideal generated by `input`
/// (tower normal forms). The options are those of
/// [`f4_tower`](super::f4_fp_tower::f4_tower): `max_degree` bounds the
/// signature degree, and the staircase stop, the deadline and the size
/// cap (`max_nnz`, on a step's nonzeros) apply as there.
pub fn sig_f4_tower(input: &[RPoly], ring: &TowerRing, opts: &TowerF4Options) -> SigReport {
    sig_f4_tower_with(input, ring, opts, SigOptions::default())
}

/// The module order signatures are compared in.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ModuleOrder {
    /// Position over term: every signature of input `i` before any of
    /// input `i + 1` (F5's incremental order), then degree, then grevlex.
    PositionFirst,
    /// Signature degree first, then position, then grevlex.
    DegreeFirst,
}

/// The engine's choices.
#[derive(Clone, Copy, Debug)]
pub struct SigOptions {
    pub order: ModuleOrder,
    pub rewrite: Rewrite,
    /// Take the pairs of one signature per step, not of one degree.
    pub one_signature: bool,
}

impl Default for SigOptions {
    /// Position over term with the ratio rewrite order: the best of the
    /// four on the pilot's `m = 3` and `m = 4` systems (note §13).
    fn default() -> Self {
        SigOptions {
            order: ModuleOrder::PositionFirst,
            rewrite: Rewrite::Ratio,
            one_signature: false,
        }
    }
}

/// [`sig_f4_tower`] with chosen orders.
pub fn sig_f4_tower_with(
    input: &[RPoly],
    ring: &TowerRing,
    opts: &TowerF4Options,
    so: SigOptions,
) -> SigReport {
    ring.check();
    let started = Instant::now();
    let fp = Fp::new(ring.p);
    let mut rep = TowerF4Report::default();
    let mut st = SigStats::default();
    let mut steps: Vec<SigStep> = Vec::new();
    let unit = || {
        vec![RPoly {
            monos: vec![ONE],
            coefs: vec![1],
        }]
    };
    let done = |mut rep: TowerF4Report, st: SigStats, steps: Vec<SigStep>| {
        rep.ms = started.elapsed().as_secs_f64() * 1e3;
        SigReport {
            report: rep,
            stats: st,
            steps,
        }
    };

    // Inputs, monic.
    let gens: Vec<RPoly> = input
        .iter()
        .filter(|p| !p.is_empty())
        .map(|p| {
            let inv = fp.inv(u64::from(p.coefs[0]));
            RPoly {
                monos: p.monos.clone(),
                coefs: p
                    .coefs
                    .iter()
                    .map(|&c| fp.mul(u64::from(c), inv) as u32)
                    .collect(),
            }
        })
        .collect();
    if gens.iter().any(|p| p.is_unit()) {
        rep.inconsistent = true;
        rep.basis = unit();
        return done(rep, st, steps);
    }
    let mut s = State {
        elems: Vec::new(),
        lm_min: MonoMap::default(),
        by_sig: HashMap::default(),
        syz: HashSet::default(),
        pairs: Vec::new(),
        gen_lm: gens.iter().map(|p| p.monos[0]).collect(),
        // Position over term: input i's signatures all come after input
        // i − 1's, by a stride in the key the steps are taken by.
        gen_deg: gens
            .iter()
            .enumerate()
            .map(|(i, g)| {
                g.degree()
                    + match so.order {
                        ModuleOrder::PositionFirst => POT_STRIDE * i as u32,
                        ModuleOrder::DegreeFirst => 0,
                    }
            })
            .collect(),
        n_tower: ring.n_tower(),
        rewrite: so.rewrite,
        one_signature: so.one_signature,
    };
    for (i, g) in gens.iter().enumerate() {
        s.pairs.push(Pair {
            sig: PSig::of(ONE, i as u32, s.gen_deg[i]),
            src: Source::Gen(i as u32),
            nominal: g.degree(),
        });
    }
    // Principal syzygies of the inputs: f_j·e_i − f_i·e_j.
    for i in 0..gens.len() {
        for j in 0..i {
            let a = PSig::of(s.gen_lm[j], i as u32, s.gen_deg[i]);
            let b = PSig::of(s.gen_lm[i], j as u32, s.gen_deg[j]);
            match a.cmp(&b) {
                Ordering::Greater => s.add_syzygy(a),
                Ordering::Less => s.add_syzygy(b),
                Ordering::Equal => {}
            }
        }
    }

    let mut learned = (0u32, 0usize, 0usize);
    while !s.pairs.is_empty() {
        if opts.deadline.is_some_and(|d| Instant::now() >= d) {
            rep.timed_out = true;
            break;
        }
        let d = s.pairs.iter().map(|p| p.sig.sugar).min().unwrap();
        if d % POT_STRIDE > opts.max_degree {
            rep.pairs_above_bound = s.pairs.len();
            break;
        }
        let step_started = Instant::now();
        let (mut sel, rest): (Vec<Pair>, Vec<Pair>) = if s.one_signature {
            // Only the pairs of the smallest signature: the order of the
            // theory, one signature per step.
            let low = s.pairs.iter().map(|p| p.sig).min().unwrap();
            s.pairs.drain(..).partition(|p| p.sig == low)
        } else {
            s.pairs.drain(..).partition(|p| p.sig.sugar == d)
        };
        s.pairs = rest;
        rep.steps += 1;
        rep.degree_reached = rep.degree_reached.max(d % POT_STRIDE);
        let mut tr = SigStep {
            sugar: d % POT_STRIDE,
            position: d / POT_STRIDE,
            pairs: sel.len(),
            ..Default::default()
        };

        // Criteria, in signature order; one row per signature, built from
        // the element that stands for it (Roune–Stillman): the syzygy
        // criterion drops the signature, and otherwise its rewriter's
        // multiple is the row, whichever pairs produced the signature.
        sel.sort_by(|a, b| a.sig.cmp(&b.sig));
        let mut chosen: Vec<Pair> = Vec::with_capacity(sel.len());
        let mut k = 0;
        while k < sel.len() {
            let sig = sel[k].sig;
            let mut end = k + 1;
            while end < sel.len() && sel[end].sig == sig {
                end += 1;
            }
            let group = &sel[k..end];
            k = end;
            if s.syzygy_covered(sig) {
                tr.skipped_syzygy += group.len();
                continue;
            }
            tr.skipped_rewrite += group.len() - 1;
            if let Some(p) = group.iter().find(|p| matches!(p.src, Source::Gen(_))) {
                chosen.push(*p);
                continue;
            }
            let r = s
                .rewriter(sig)
                .expect("a pair's own element divides its signature");
            let e = &s.elems[r as usize];
            // `t = 1` rebuilds the element itself. That is not redundant: a
            // row becomes an element with only the reducers its step had,
            // so an element found earlier in the same step, of smaller
            // signature, may still reduce its lead. The pair between them
            // has this element's signature, and the rebuilt row is reduced
            // with that element among the reducers. A row that does not
            // move is exact and is not new.
            let t = quotient(sig.mono(), e.sig.mono());
            if group.iter().all(|p| src_elem(p.src) != Some(r)) {
                tr.rewritten_rows += 1;
            }
            chosen.push(Pair {
                sig,
                src: Source::Crit(t, r),
                nominal: degree_of(t) + degree_of(e.lm),
            });
        }
        st.skipped_syzygy += tr.skipped_syzygy as u64;
        st.skipped_rewrite += tr.skipped_rewrite as u64;

        // The S-rows.
        let elems = &s.elems;
        let mut rows: Vec<SRow> = chosen
            .par_iter()
            .map(|p| {
                let poly = match p.src {
                    Source::Gen(i) => gens[i as usize].clone(),
                    Source::Crit(t, g) => mul_elem(ring, fp, &elems[g as usize], t),
                    Source::Tower(g, v) => {
                        mul_elem(ring, fp, &elems[g as usize], mono(1u64 << v, [0; MAX_FREE]))
                    }
                };
                let exact = match p.src {
                    Source::Gen(_) => false,
                    Source::Crit(t, g) => {
                        let e = &elems[g as usize];
                        poly.monos.first() == Some(&mono_mul(t, e.lm))
                    }
                    Source::Tower(..) => false,
                };
                SRow {
                    sig: p.sig,
                    is_s: true,
                    exact,
                    nominal: p.nominal,
                    poly,
                }
            })
            .filter(|r| !r.poly.is_empty())
            .collect();
        for p in &chosen {
            match p.src {
                Source::Gen(_) => tr.gen_rows += 1,
                Source::Crit(..) => tr.crit_rows += 1,
                Source::Tower(..) => tr.tower_rows += 1,
            }
        }
        st.s_rows += rows.len() as u64;

        // Symbolic preprocessing: one reducer per monomial with a divisor,
        // the multiple of smallest signature.
        let mut examined: MonoMap<()> = MonoMap::default();
        let mut frontier: Vec<Mono> = Vec::new();
        for r in &rows {
            for &m in &r.poly.monos {
                if examined.insert(m, ()).is_none() {
                    frontier.push(m);
                }
            }
        }
        let mut nnz: u64 = rows.iter().map(|r| r.poly.len() as u64).sum();
        let mut aborted = false;
        while !frontier.is_empty() {
            let found: Vec<(Mono, u32, PSig)> = frontier
                .par_iter()
                .filter_map(|&m| s.reducer_for(m))
                .collect();
            frontier.clear();
            let elems = &s.elems;
            let new: Vec<SRow> = found
                .par_iter()
                .map(|&(t, g, sig)| {
                    let e = &elems[g as usize];
                    let poly = mul_elem(ring, fp, e, t);
                    SRow {
                        sig,
                        is_s: false,
                        exact: true,
                        nominal: degree_of(t) + degree_of(e.lm),
                        poly,
                    }
                })
                .collect();
            for r in new {
                nnz += r.poly.len() as u64;
                for &m in &r.poly.monos[1..] {
                    if examined.insert(m, ()).is_none() {
                        frontier.push(m);
                    }
                }
                rows.push(r);
            }
            if opts.max_nnz.is_some_and(|cap| nnz > cap) {
                rep.oversize = true;
                aborted = true;
                break;
            }
            if opts.deadline.is_some_and(|dl| Instant::now() >= dl) {
                rep.timed_out = true;
                aborted = true;
                break;
            }
        }
        if aborted {
            s.pairs.extend(chosen);
            break;
        }
        tr.reducer_rows = rows.iter().filter(|r| !r.is_s).count();
        st.reducer_rows += tr.reducer_rows as u64;

        // Columns, descending, and the rows as sparse rows over them, in
        // signature order (S-rows before reducers of the same signature).
        let mut cols: Vec<Mono> = examined.keys().copied().collect();
        drop(examined);
        cols.par_sort_unstable_by(|a, b| b.cmp(a));
        let col_of: MonoMap<u32> = cols
            .iter()
            .enumerate()
            .map(|(i, &m)| (m, i as u32))
            .collect();
        rows.par_sort_by(|a, b| a.sig.cmp(&b.sig).then(b.is_s.cmp(&a.is_s)));
        let sparse: Vec<Row> = rows
            .par_iter()
            .map(|r| Row {
                cols: r.poly.monos.iter().map(|m| col_of[m]).collect(),
                vals: r.poly.coefs.clone(),
            })
            .collect();
        let n_cols = cols.len();
        tr.cols = n_cols;
        tr.nnz = nnz;
        rep.max_rows = rep.max_rows.max(rows.len());
        rep.max_cols = rep.max_cols.max(n_cols);
        rep.max_nnz = rep.max_nnz.max(nnz);
        tr.ms_rows = step_started.elapsed().as_secs_f64() * 1e3;

        // Signature-ordered elimination.
        let reduce_started = Instant::now();
        let mut pivot_of = vec![NONE; n_cols];
        let mut pivots: Vec<(Row, PSig)> = Vec::new();
        let mut acc = Acc::new(n_cols);
        // (row, reduced row) of the rows that give new elements.
        let mut fresh: Vec<(usize, Row)> = Vec::new();
        let mut muladds = 0u64;
        let mut expired = false;
        for (k, row) in sparse.into_iter().enumerate() {
            if k % 256 == 0 && opts.deadline.is_some_and(|dl| Instant::now() >= dl) {
                expired = true;
                break;
            }
            let sig = rows[k].sig;
            let lead0 = row.cols[0];
            let out = reduce_row(fp, &mut acc, row, sig, &pivot_of, &pivots, &mut muladds);
            match out {
                Reduced::Zero => {
                    tr.zero_rows += 1;
                    s.add_syzygy(sig);
                }
                Reduced::Singular => tr.singular_rows += 1,
                Reduced::Pivot(r) => {
                    let lead = r.cols[0];
                    pivot_of[lead as usize] = pivots.len() as u32;
                    // New: a reducer or an exact S-row only if something
                    // reduced its lead; any other S-row.
                    let moved = lead != lead0;
                    let is_new = sig.square_free() && (moved || (rows[k].is_s && !rows[k].exact));
                    if is_new {
                        fresh.push((k, r.clone()));
                    }
                    pivots.push((r, sig));
                }
            }
        }
        if expired {
            rep.timed_out = true;
            s.pairs.extend(chosen);
            break;
        }
        drop(pivots);
        tr.muladds = muladds;
        rep.muladds += muladds;
        st.zero_rows += tr.zero_rows as u64;
        st.singular_rows += tr.singular_rows as u64;
        tr.ms_reduce = reduce_started.elapsed().as_secs_f64() * 1e3;

        // New elements, in signature order.
        tr.fresh = fresh.len();
        let cols: Arc<[Mono]> = cols.into();
        let max_sig_done = rows.last().map(|r| r.sig);
        let before = s.pairs.len();
        let mut unit_found = false;
        tr.fresh_min_degree = fresh
            .iter()
            .map(|(_, r)| degree_of(cols[r.cols[0] as usize]))
            .min()
            .unwrap_or(0);
        for (k, r) in fresh {
            let lm = cols[r.cols[0] as usize];
            tr.fresh_max_nominal = tr.fresh_max_nominal.max(rows[k].nominal);
            if lm == ONE {
                unit_found = true;
            }
            s.insert(
                SElem {
                    sig: rows[k].sig,
                    lm,
                    cols: cols.clone(),
                    pos: r.cols,
                    vals: r.vals,
                },
                &mut st,
            );
        }
        if let Some(mx) = max_sig_done {
            tr.late_pairs = s.pairs[before..]
                .iter()
                .filter(|p| p.sig.sugar == d && p.sig < mx)
                .count();
            st.late_pairs += tr.late_pairs as u64;
        }
        if tr.fresh > 0 {
            let nominal = tr.fresh_max_nominal;
            learned = (learned.0.max(nominal), rep.max_cols, rep.steps);
            rep.last_productive_degree = nominal;
            st.sig_degree_max = st.sig_degree_max.max(d % POT_STRIDE);
        }
        tr.elements = s.elems.len();
        tr.pairs_left = s.pairs.len();
        tr.ms = step_started.elapsed().as_secs_f64() * 1e3;
        if let Some(f) = opts.on_sig_step {
            f(rep.steps, &tr);
        }
        steps.push(tr);
        if unit_found {
            rep.inconsistent = true;
            rep.basis = unit();
            rep.solving_degree_max = learned.0;
            rep.max_cols_to_solution = learned.1;
            rep.steps_to_solution = learned.2;
            return done(rep, st, steps);
        }
        if let Some(bound) = opts.stop_staircase {
            if !s.pairs.is_empty() {
                let lms = minimal_lms(&s);
                if let Some(count) = staircase_at_most(&lms, s.n_tower, ring.n_free, bound) {
                    rep.staircase_at_stop = Some(count);
                    break;
                }
            }
        }
    }
    rep.solving_degree_max = learned.0;
    rep.max_cols_to_solution = learned.1;
    rep.steps_to_solution = learned.2;
    // A minimal Gröbner basis: one element per minimal leading monomial.
    let lms = minimal_lms(&s);
    rep.basis = lms
        .iter()
        .map(|m| s.elems[s.lm_min[m] as usize].to_rpoly())
        .collect();
    done(rep, st, steps)
}

/// `a·b` for monomials of `R` sharing no tower variable.
fn mono_mul(a: Mono, b: Mono) -> Mono {
    let (fa, fb) = (free_of(a), free_of(b));
    let mut f = [0u8; MAX_FREE];
    for k in 0..MAX_FREE {
        f[k] = fa[k] + fb[k];
    }
    mono(mask_of(a) | mask_of(b), f)
}

const POT_STRIDE: u32 = 10_000;

/// The element index a pair's row is a multiple of.
fn src_elem(src: Source) -> Option<u32> {
    match src {
        Source::Gen(_) => None,
        Source::Crit(_, g) | Source::Tower(g, _) => Some(g),
    }
}

fn mul_elem(ring: &TowerRing, fp: Fp, e: &SElem, t: Mono) -> RPoly {
    ring.mul_terms_fp(fp, e.terms(), e.pos.len(), t)
}

/// The leading monomials of the elements that no other leading monomial
/// divides, one each, descending.
fn minimal_lms(s: &State) -> Vec<Mono> {
    let mut lms: Vec<Mono> = s.lm_min.keys().copied().collect();
    lms.sort_unstable_by(|a, b| b.cmp(a));
    let set: MonoMap<()> = lms.iter().map(|&m| (m, ())).collect();
    lms.into_iter()
        .filter(|&m| !any_divisor(m, |d| d != m && set.contains_key(&d)))
        .collect()
}

enum Reduced {
    Zero,
    Singular,
    Pivot(Row),
}

/// Top-reduces `row` by the pivots of smaller signature until its leading
/// column has none; the rest of the row is kept as it stands (semi-reduced).
fn reduce_row(
    fp: Fp,
    acc: &mut Acc,
    row: Row,
    sig: PSig,
    pivot_of: &[u32],
    pivots: &[(Row, PSig)],
    muladds: &mut u64,
) -> Reduced {
    let p0 = pivot_of[row.cols[0] as usize];
    if p0 == NONE {
        let inv = fp.inv(u64::from(row.vals[0]));
        let vals = row
            .vals
            .iter()
            .map(|&v| fp.mul(u64::from(v), inv) as u32)
            .collect();
        return Reduced::Pivot(Row {
            cols: row.cols,
            vals,
        });
    }
    if pivots[p0 as usize].1 == sig {
        return Reduced::Singular;
    }
    acc.load(&row);
    let mut w = row.cols[0] as usize / 64;
    while w <= acc.hi {
        let mut word = acc.bits[w];
        acc.bits[w] = 0;
        while word != 0 {
            let b = word.trailing_zeros() as usize;
            word &= word - 1;
            let c = w * 64 + b;
            let v = acc.vals[c];
            acc.vals[c] = 0;
            if v == 0 {
                continue;
            }
            let p = pivot_of[c];
            if p != NONE {
                if pivots[p as usize].1 == sig {
                    // Singular: clear what is left and drop the row.
                    acc.bits[w] = word;
                    let mut sink = Row::default();
                    acc.drain_from(fp, w, 1, &mut sink);
                    return Reduced::Singular;
                }
                *muladds += acc.sub_tail(fp, v, &pivots[p as usize].0, w, &mut word);
                continue;
            }
            let inv = fp.inv(v);
            let mut out = Row {
                cols: vec![c as u32],
                vals: vec![1],
            };
            acc.bits[w] = word;
            acc.drain_from(fp, w, inv, &mut out);
            return Reduced::Pivot(out);
        }
        w += 1;
    }
    Reduced::Zero
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cryptanalysis::f4_fp_tower::{divides, f4_tower, SquareRule};

    #[test]
    fn signatures_order_like_mono_keys_when_square_free() {
        use rand::{Rng, SeedableRng};
        let mut rng = rand::rngs::StdRng::seed_from_u64(3);
        for _ in 0..2000 {
            let rnd = |rng: &mut rand::rngs::StdRng| {
                let mask = rng.gen::<u64>() & 0xff;
                let free = [rng.gen_range(0..3), rng.gen_range(0..3), 0, 0];
                mono(mask, free)
            };
            let (a, b) = (rnd(&mut rng), rnd(&mut rng));
            let (sa, sb) = (PSig::of(a, 0, 0), PSig::of(b, 0, 0));
            if degree_of(a) == degree_of(b) {
                assert_eq!(sa.cmp(&sb), a.cmp(&b), "{a:x} {b:x}");
            }
            // Multiplication is compatible with the order.
            let u = rnd(&mut rng);
            if sa < sb {
                assert!(sa.times(u) < sb.times(u));
            }
        }
    }

    fn kummer_block(p: u64, t: usize, base: usize) -> (Vec<SquareRule>, Vec<Vec<u64>>) {
        let f = Fp::new(p);
        let pow = |mut a: u64, mut e: u64| {
            let mut r = 1u64;
            while e > 0 {
                if e & 1 == 1 {
                    r = f.mul(r, a);
                }
                a = f.mul(a, a);
                e >>= 1;
            }
            r
        };
        let zeta = (2..p)
            .map(|h| pow(h, (p - 1) >> t))
            .find(|&z| pow(z, 1 << (t - 1)) != 1)
            .unwrap();
        let rules: Vec<SquareRule> = (0..t)
            .map(|j| SquareRule {
                next: (j + 1 < t).then_some((base + j + 1) as u8),
                a: 0,
                b: u64::from(j + 1 < t),
                c: 0,
                d: u64::from(j + 1 == t),
            })
            .collect();
        let pts = (0..1u64 << t)
            .map(|k| {
                let mut x = pow(zeta, k);
                let mut v = Vec::new();
                for _ in 0..t {
                    v.push(x);
                    x = f.mul(x, x);
                }
                v
            })
            .collect();
        (rules, pts)
    }

    /// A random polynomial of total raw degree ≤ `deg` in `n` variables.
    fn random_poly(
        rng: &mut rand::rngs::StdRng,
        ring: &TowerRing,
        terms: usize,
        deg: u32,
    ) -> RPoly {
        use rand::Rng;
        let n = ring.n_vars();
        let raw: Vec<(Vec<u32>, u64)> = (0..terms)
            .map(|_| {
                let mut e = vec![0u32; n];
                let mut left = deg;
                for x in e.iter_mut() {
                    if left > 0 && rng.gen_range(0..3) == 0 {
                        *x = 1;
                        left -= 1;
                    }
                }
                (e, rng.gen_range(1..ring.p))
            })
            .collect();
        ring.from_raw(&raw)
    }

    /// The reduced Gröbner basis's leading monomials, from any basis.
    fn minimal(lms: &[Mono]) -> Vec<Mono> {
        let mut v: Vec<Mono> = lms
            .iter()
            .copied()
            .filter(|&m| !lms.iter().any(|&d| d != m && divides(d, m)))
            .collect();
        v.sort_unstable();
        v.dedup();
        v
    }

    #[test]
    fn the_basis_matches_f4_on_random_systems() {
        use rand::SeedableRng;
        let mut rng = rand::rngs::StdRng::seed_from_u64(17);
        let p = 97u64;
        let mut refuted = 0;
        for trial in 0..120 {
            let t = 1 + trial % 3;
            let (r0, _) = kummer_block(p, t, 0);
            let (r1, _) = kummer_block(p, t, t);
            let n_free = trial % 2;
            let ring = TowerRing {
                p,
                rules: [r0, r1].concat(),
                n_free,
            };
            let k = 1 + trial % 3;
            let input: Vec<RPoly> = (0..k).map(|_| random_poly(&mut rng, &ring, 4, 3)).collect();
            let opts = TowerF4Options::new(40);
            let a = f4_tower(&input, &ring, &opts);
            let b = sig_f4_tower(&input, &ring, &opts);
            assert!(!a.timed_out && !b.report.timed_out);
            assert_eq!(a.inconsistent, b.report.inconsistent, "trial {trial}");
            refuted += usize::from(a.inconsistent);
            let la: Vec<Mono> = a.basis.iter().filter_map(RPoly::lm).collect();
            let lb: Vec<Mono> = b.report.basis.iter().filter_map(RPoly::lm).collect();
            assert_eq!(minimal(&la), minimal(&lb), "trial {trial}");
            // Every element of either basis reduces to zero by the other:
            // the same ideal, checked on the leading monomials above and on
            // membership here through f4 of the union.
            let mut union = a.basis.clone();
            union.extend(b.report.basis.iter().cloned());
            let c = f4_tower(&union, &ring, &opts);
            let lc: Vec<Mono> = c.basis.iter().filter_map(RPoly::lm).collect();
            assert_eq!(
                minimal(&lc),
                minimal(&la),
                "trial {trial}: not the same ideal"
            );
        }
        assert!(
            refuted > 5 && refuted < 115,
            "a mix of refuted and solvable systems: {refuted}"
        );
    }

    /// Towers whose rules use every coefficient (`a y_j y_{j+1} + b y_{j+1}
    /// + c y_j + d`), several generators and a free variable: the basis
    /// must match `f4_fp_tower`'s, and the criteria must have removed rows.
    #[test]
    fn the_basis_matches_f4_on_general_towers() {
        use rand::{Rng, SeedableRng};
        let mut rng = rand::rngs::StdRng::seed_from_u64(29);
        let p = 1_000_003u64;
        let (mut sig_zero, mut f4_rows, mut skipped) = (0u64, 0u64, 0u64);
        for trial in 0..60 {
            let t = 2 + trial % 3;
            let mut rules = Vec::new();
            for b in 0..2usize {
                for j in 0..t {
                    let top = j + 1 == t;
                    rules.push(SquareRule {
                        next: (!top).then_some((b * t + j + 1) as u8),
                        a: if top { 0 } else { rng.gen_range(0..p) },
                        b: if top { 0 } else { rng.gen_range(0..p) },
                        c: rng.gen_range(0..p),
                        d: rng.gen_range(0..p),
                    });
                }
            }
            let ring = TowerRing {
                p,
                rules,
                n_free: trial % 2,
            };
            let k = 1 + trial % 3;
            let input: Vec<RPoly> = (0..k)
                .map(|_| random_poly(&mut rng, &ring, 5, 2 + (trial % 2) as u32))
                .collect();
            let opts = TowerF4Options::new(40);
            let a = f4_tower(&input, &ring, &opts);
            let b = sig_f4_tower(&input, &ring, &opts);
            assert!(!a.timed_out && !b.report.timed_out);
            assert_eq!(a.inconsistent, b.report.inconsistent, "trial {trial}");
            let la: Vec<Mono> = a.basis.iter().filter_map(RPoly::lm).collect();
            let lb: Vec<Mono> = b.report.basis.iter().filter_map(RPoly::lm).collect();
            assert_eq!(minimal(&la), minimal(&lb), "trial {trial}");
            let mut union = a.basis.clone();
            union.extend(b.report.basis.iter().cloned());
            let c = f4_tower(&union, &ring, &opts);
            let lc: Vec<Mono> = c.basis.iter().filter_map(RPoly::lm).collect();
            assert_eq!(
                minimal(&lc),
                minimal(&la),
                "trial {trial}: not the same ideal"
            );
            sig_zero += b.stats.zero_rows;
            skipped += b.stats.skipped_syzygy + b.stats.skipped_rewrite;
            f4_rows += a.critical_pairs_reduced + a.tower_pairs_reduced;
        }
        assert!(skipped > 0, "the criteria never fired");
        eprintln!("sig zero rows {sig_zero}, skipped {skipped}; f4 S-rows {f4_rows}");
    }

    /// Every variant (both module orders, both rewrite orders, steps by
    /// degree or by signature) computes the ideal `f4_fp_tower` computes, on
    /// homogeneous systems without a tower and on general towers.
    #[test]
    fn every_variant_computes_the_same_ideal() {
        use rand::{Rng, SeedableRng};
        let mut rng = rand::rngs::StdRng::seed_from_u64(41);
        let p = 1_000_003u64;
        let variants = [
            (ModuleOrder::PositionFirst, Rewrite::Ratio, false),
            (ModuleOrder::PositionFirst, Rewrite::Insertion, false),
            (ModuleOrder::DegreeFirst, Rewrite::Ratio, false),
            (ModuleOrder::DegreeFirst, Rewrite::Insertion, false),
            (ModuleOrder::DegreeFirst, Rewrite::Ratio, true),
        ];
        for trial in 0..24 {
            let homogeneous = trial % 2 == 0;
            let ring = if homogeneous {
                TowerRing {
                    p,
                    rules: Vec::new(),
                    n_free: 4,
                }
            } else {
                let t = 2 + trial % 2;
                let mut rules = Vec::new();
                for b in 0..2usize {
                    for j in 0..t {
                        let top = j + 1 == t;
                        rules.push(SquareRule {
                            next: (!top).then_some((b * t + j + 1) as u8),
                            a: if top { 0 } else { rng.gen_range(0..p) },
                            b: if top { 0 } else { rng.gen_range(0..p) },
                            c: rng.gen_range(0..p),
                            d: rng.gen_range(0..p),
                        });
                    }
                }
                TowerRing {
                    p,
                    rules,
                    n_free: 1,
                }
            };
            let k = 2 + trial % 3;
            let input: Vec<RPoly> = (0..k)
                .map(|_| {
                    if homogeneous {
                        let raw: Vec<(Vec<u32>, u64)> = (0..10)
                            .map(|_| {
                                let mut e = vec![0u32; 4];
                                for _ in 0..3 {
                                    e[rng.gen_range(0..4)] += 1;
                                }
                                (e, rng.gen_range(1..p))
                            })
                            .collect();
                        ring.from_raw(&raw)
                    } else {
                        random_poly(&mut rng, &ring, 5, 2)
                    }
                })
                .collect();
            let opts = TowerF4Options::new(40);
            let a = f4_tower(&input, &ring, &opts);
            let la: Vec<Mono> = a.basis.iter().filter_map(RPoly::lm).collect();
            for &(order, rewrite, one_signature) in &variants {
                let so = SigOptions {
                    order,
                    rewrite,
                    one_signature,
                };
                let b = sig_f4_tower_with(&input, &ring, &opts, so);
                assert!(!b.report.timed_out);
                assert_eq!(
                    a.inconsistent, b.report.inconsistent,
                    "trial {trial} {so:?}"
                );
                let lb: Vec<Mono> = b.report.basis.iter().filter_map(RPoly::lm).collect();
                assert_eq!(minimal(&la), minimal(&lb), "trial {trial} {so:?}");
                let mut union = a.basis.clone();
                union.extend(b.report.basis.iter().cloned());
                let c = f4_tower(&union, &ring, &opts);
                let lc: Vec<Mono> = c.basis.iter().filter_map(RPoly::lm).collect();
                assert_eq!(
                    minimal(&lc),
                    minimal(&la),
                    "trial {trial} {so:?}: another ideal"
                );
            }
        }
    }

    /// Longer Kummer towers (`N` = 10 and 12 over two blocks) with one
    /// generator, the shape of the pilot's `m = 2` systems. Here a row
    /// becomes an element while an element found earlier in its step could
    /// still reduce its lead. The pair that finishes that reduction has the
    /// element's own signature, and a build that skipped rebuilding an
    /// element (`t = 1`) returned a basis without it and called refuted
    /// systems solvable.
    #[test]
    fn long_towers_with_one_generator_match_f4() {
        use rand::SeedableRng;
        let mut rng = rand::rngs::StdRng::seed_from_u64(61);
        let p = 2_013_265_921u64;
        let variants = [
            (ModuleOrder::PositionFirst, Rewrite::Ratio),
            (ModuleOrder::PositionFirst, Rewrite::Insertion),
            (ModuleOrder::DegreeFirst, Rewrite::Ratio),
            (ModuleOrder::DegreeFirst, Rewrite::Insertion),
        ];
        let mut refuted = 0;
        for trial in 0..6 {
            let t = 5 + trial % 2;
            let (r0, _) = kummer_block(p, t, 0);
            let (r1, _) = kummer_block(p, t, t);
            let ring = TowerRing {
                p,
                rules: [r0, r1].concat(),
                n_free: 0,
            };
            let g = random_poly(&mut rng, &ring, 8, 2);
            if g.is_empty() {
                continue;
            }
            let input = [g];
            let opts = TowerF4Options::new(40);
            let a = f4_tower(&input, &ring, &opts);
            refuted += usize::from(a.inconsistent);
            let la: Vec<Mono> = a.basis.iter().filter_map(RPoly::lm).collect();
            for &(order, rewrite) in &variants {
                let so = SigOptions {
                    order,
                    rewrite,
                    one_signature: false,
                };
                let b = sig_f4_tower_with(&input, &ring, &opts, so);
                assert!(!a.timed_out && !b.report.timed_out);
                assert_eq!(
                    a.inconsistent, b.report.inconsistent,
                    "trial {trial} {so:?}"
                );
                let lb: Vec<Mono> = b.report.basis.iter().filter_map(RPoly::lm).collect();
                assert_eq!(minimal(&la), minimal(&lb), "trial {trial} {so:?}");
            }
        }
        assert!(refuted > 0, "no refuted system: {refuted}");
    }

    #[test]
    fn refutes_exactly_the_empty_kummer_systems() {
        use rand::{Rng, SeedableRng};
        let mut rng = rand::rngs::StdRng::seed_from_u64(5);
        let p = 97u64;
        for t in 1..=3usize {
            let (r0, pts) = kummer_block(p, t, 0);
            let (r1, _) = kummer_block(p, t, t);
            let ring = TowerRing {
                p,
                rules: [r0, r1].concat(),
                n_free: 0,
            };
            for _ in 0..15 {
                let g = random_poly(&mut rng, &ring, 5, 2);
                if g.is_empty() {
                    continue;
                }
                let mut zeros = 0;
                for a in &pts {
                    for b in &pts {
                        let x = [a.clone(), b.clone()].concat();
                        zeros += usize::from(ring.eval(&g, &x) == 0);
                    }
                }
                let rep = sig_f4_tower(std::slice::from_ref(&g), &ring, &TowerF4Options::new(64));
                assert_eq!(rep.report.inconsistent, zeros == 0, "t {t}");
                if zeros > 0 {
                    let lms: Vec<Mono> = rep.report.basis.iter().filter_map(RPoly::lm).collect();
                    assert_eq!(
                        staircase_at_most(&lms, ring.n_tower(), 0, 1 << 12),
                        // radical: V is a set of distinct points and g
                        // cuts it
                        Some(zeros),
                    );
                }
                let _ = rng.gen::<u8>();
            }
        }
    }
}
