"""Generate packed point-halving linear maps for the type-II ONB.

The field stores gamma_i at bit i-1.  Reorder those bits by the discrete
logarithm L(i), where Frobenius is a one-bit cyclic rotation.  In that order,
solving z^2+z=a is a prefix XOR and taking a square root is a rotation.
"""
from pathlib import Path
import argparse

from gensigma import route


M = 131
N = 263


def fold(e):
    e %= N
    return min(e, N - e)


def phase_permutation():
    log = {}
    e = 1
    for k in range(M):
        log[fold(e)] = k
        e = 2 * e % N
    p = list(range(256))
    for i in range(1, M + 1):
        p[i - 1] = log[i]
    return p


def invert(p):
    q = [0] * len(p)
    for i, j in enumerate(p):
        q[j] = i
    return q


def apply_network(x, net):
    for distance, mask in net:
        t = ((x >> distance) ^ x) & mask
        x ^= t ^ (t << distance)
    return x


def emit_network(name, perm):
    net = route(perm)
    lines = [f"ECC_HD P131 {name}(P131 a) {{",
             "    uint32_t v[8] = {a.v[0],a.v[1],a.v[2],a.v[3],a.v[4],0,0,0};",
             "    uint32_t t;"]
    for distance, mask in net:
        for word in range(8):
            wm = (mask >> (32 * word)) & 0xffffffff
            if not wm:
                continue
            if distance < 32:
                lines += [
                    f"    t=((v[{word}] >> {distance})^v[{word}])&0x{wm:08x}u;",
                    f"    v[{word}]^=t^(t << {distance});",
                ]
            else:
                other = word + distance // 32
                lines += [
                    f"    t=(v[{word}]^v[{other}])&0x{wm:08x}u;",
                    f"    v[{word}]^=t; v[{other}]^=t;",
                ]
    lines += ["    return P131{{v[0],v[1],v[2],v[3],v[4]&7u}};", "}"]
    return lines


def generate():
    to_phase = phase_permutation()
    from_phase = invert(to_phase)
    for p in (to_phase, from_phase):
        net = route(p)
        for bit in range(256):
            if apply_network(1 << bit, net) != 1 << p[bit]:
                raise ValueError(("bad halving permutation", bit))
    lines = [
        "// Generated by codegen/genhalving.py; included inside eccPacked131.",
        "#pragma once",
    ]
    lines += emit_network("toHalvingPhase131", to_phase)
    lines += emit_network("fromHalvingPhase131", from_phase)
    lines += [
        "ECC_HD P131 halvingQuadraticRoot131(P131 a) {",
        "    P131 z=toHalvingPhase131(a);",
        "    z.v[0]&=~1u;",
        "    const int shifts[7]={1,2,4,8,16,32,64};",
        "#pragma unroll",
        "    for(int k=0;k<7;k++){",
        "        const int s=shifts[k], words=s>>5, bits=s&31;",
        "        P131 old=z;",
        "#pragma unroll",
        "        for(int i=4;i>=0;i--){",
        "            uint32_t q=0;",
        "            if(i>=words){ q=old.v[i-words]<<bits; if(bits&&i>words)q|=old.v[i-words-1]>>(32-bits); }",
        "            z.v[i]^=q;",
        "        }",
        "        z.v[4]&=7u;",
        "    }",
        "    return fromHalvingPhase131(z);",
        "}",
        "ECC_HD P131 halvingSqrt131(P131 a) {",
        "    P131 q=toHalvingPhase131(a), r;",
        "    r.v[0]=(q.v[0]>>1)|(q.v[1]<<31);",
        "    r.v[1]=(q.v[1]>>1)|(q.v[2]<<31);",
        "    r.v[2]=(q.v[2]>>1)|(q.v[3]<<31);",
        "    r.v[3]=(q.v[3]>>1)|(q.v[4]<<31);",
        "    r.v[4]=(q.v[4]>>1)|((q.v[0]&1u)<<2);",
        "    return fromHalvingPhase131(r);",
        "}",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="../include/packedhalving131.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    path = Path(args.out)
    if args.check:
        if path.read_text() != text:
            raise SystemExit("packed halving header does not match generator")
    else:
        path.write_text(text)
    print("PASS: packed point-halving phase maps")
