"""Generate packed point-halving linear maps for the type-II ONB.

The field stores gamma_i at bit i-1.  Reorder those bits by the discrete
logarithm L(i), where Frobenius is a one-bit cyclic rotation.  In that order,
solving z^2+z=a is a prefix XOR and taking a square root is a rotation.
"""
from pathlib import Path
import argparse

from gensigma import route


M = 131
N = 263


def fold(e):
    e %= N
    return min(e, N - e)


def phase_permutation():
    log = {}
    e = 1
    for k in range(M):
        log[fold(e)] = k
        e = 2 * e % N
    p = list(range(256))
    for i in range(1, M + 1):
        p[i - 1] = log[i]
    return p


def invert(p):
    q = [0] * len(p)
    for i, j in enumerate(p):
        q[j] = i
    return q


def apply_network(x, net):
    for distance, mask in net:
        t = ((x >> distance) ^ x) & mask
        x ^= t ^ (t << distance)
    return x


def emit_network(name, perm):
    net = route(perm)
    lines = [f"ECC_HD P131 {name}(P131 a) {{",
             "    uint32_t v[8] = {a.v[0],a.v[1],a.v[2],a.v[3],a.v[4],0,0,0};",
             "    uint32_t t;"]
    for distance, mask in net:
        for word in range(8):
            wm = (mask >> (32 * word)) & 0xffffffff
            if not wm:
                continue
            if distance < 32:
                lines += [
                    f"    t=((v[{word}] >> {distance})^v[{word}])&0x{wm:08x}u;",
                    f"    v[{word}]^=t^(t << {distance});",
                ]
            else:
                other = word + distance // 32
                lines += [
                    f"    t=(v[{word}]^v[{other}])&0x{wm:08x}u;",
                    f"    v[{word}]^=t; v[{other}]^=t;",
                ]
    lines += ["    return P131{{v[0],v[1],v[2],v[3],v[4]&7u}};", "}"]
    return lines


def emit_pair_network(name, perm):
    net = route(perm)
    lines = ["struct HalvingPair131 { P131 first, second; };",
             f"ECC_HD HalvingPair131 {name}(P131 a, P131 b) {{",
             "    uint32_t av[8]={a.v[0],a.v[1],a.v[2],a.v[3],a.v[4],0,0,0};",
             "    uint32_t bv[8]={b.v[0],b.v[1],b.v[2],b.v[3],b.v[4],0,0,0};",
             "    uint32_t t;"]
    for distance, mask in net:
        for word in range(8):
            wm = (mask >> (32 * word)) & 0xffffffff
            if not wm:
                continue
            for value in ("av", "bv"):
                if distance < 32:
                    lines += [
                        f"    t=(({value}[{word}] >> {distance})^{value}[{word}])&0x{wm:08x}u;",
                        f"    {value}[{word}]^=t^(t << {distance});",
                    ]
                else:
                    other = word + distance // 32
                    lines += [
                        f"    t=({value}[{word}]^{value}[{other}])&0x{wm:08x}u;",
                        f"    {value}[{word}]^=t; {value}[{other}]^=t;",
                    ]
    lines += [
        "    return HalvingPair131{P131{{av[0],av[1],av[2],av[3],av[4]&7u}},",
        "                          P131{{bv[0],bv[1],bv[2],bv[3],bv[4]&7u}}};",
        "}",
    ]
    return lines


def generate():
    to_phase = phase_permutation()
    from_phase = invert(to_phase)
    for p in (to_phase, from_phase):
        net = route(p)
        for bit in range(256):
            if apply_network(1 << bit, net) != 1 << p[bit]:
                raise ValueError(("bad halving permutation", bit))
    phase_net = route(to_phase)
    def reference_second_trace(a):
        q = apply_network(a, phase_net)
        z = q & ~1
        for shift in (1, 2, 4, 8, 16, 32, 64, 128):
            z ^= (z << shift) & ((1 << M) - 1)
        return (q & z).bit_count() & 1
    def closed_second_trace(a):
        w = (a & ~1).bit_count()
        return ((w * (w + 1)) // 2) & 1
    probes = [0] + [1 << i for i in range(M)]
    probes += [(1 << i) | (1 << j) for i in range(M) for j in range(i)]
    for value in probes:
        if reference_second_trace(value) != closed_second_trace(value):
            raise ValueError(("bad second-trace closed form", value))
    lines = [
        "// Generated by codegen/genhalving.py; included inside eccPacked131.",
        "#pragma once",
    ]
    lines += emit_network("toHalvingPhase131", to_phase)
    lines += emit_network("fromHalvingPhase131", from_phase)
    # Direct inverse-Frobenius permutation.  Keeping the phase-order
    # implementation would pay two Beneš networks for one square root.
    sqrt_perm = list(range(256))
    for i in range(1, M + 1):
        j = i * pow(2, M - 1, N) % N
        sqrt_perm[i - 1] = fold(j) - 1
    lines += emit_network("halvingSqrt131", sqrt_perm)
    lines += emit_pair_network("halvingSqrtPair131", sqrt_perm)
    lines += [
        "ECC_HD P131 halvingQuadraticRoot131(P131 a) {",
        "    P131 z=toHalvingPhase131(a);",
        "    z.v[0]&=~1u;",
        "    const int shifts[8]={1,2,4,8,16,32,64,128};",
        "#pragma unroll",
        "    for(int k=0;k<8;k++){",
        "        const int s=shifts[k], words=s>>5, bits=s&31;",
        "        P131 old=z;",
        "#pragma unroll",
        "        for(int i=4;i>=0;i--){",
        "            uint32_t q=0;",
        "            if(i>=words){ q=old.v[i-words]<<bits; if(bits&&i>words)q|=old.v[i-words-1]>>(32-bits); }",
        "            z.v[i]^=q;",
        "        }",
        "        z.v[4]&=7u;",
        "    }",
        "    return fromHalvingPhase131(z);",
        "}",
        "ECC_HD unsigned halvingSecondTrace131(P131 a) {",
        "    unsigned w=0;",
        "#ifdef __CUDA_ARCH__",
        "    w=__popc(a.v[0]&~1u)+__popc(a.v[1])+__popc(a.v[2])+__popc(a.v[3])+__popc(a.v[4]);",
        "#else",
        "    w=__builtin_popcount(a.v[0]&~1u)+__builtin_popcount(a.v[1])+__builtin_popcount(a.v[2])+",
        "      __builtin_popcount(a.v[3])+__builtin_popcount(a.v[4]);",
        "#endif",
        "    return ((w*(w+1u))>>1)&1u;",
        "}",
    ]
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default="../include/packedhalving131.h")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    path = Path(args.out)
    if args.check:
        if path.read_text() != text:
            raise SystemExit("packed halving header does not match generator")
    else:
        path.write_text(text)
    print("PASS: packed point-halving phase maps")
