"""Generate the pentanomial-basis change of basis for the packed GF(2^131) walk.

The walk can keep its coordinates in F_2[t]/(t^131 + t^13 + t^2 + t + 1),
Certicom's own polynomial basis for ECC2K-130, where reduction after a
product is a four-tap shift fold with no quotient multiply.  Everything
basis-dependent (the normal-basis weight, the Frobenius maps) is then one
F_2-linear map applied through the nibble tables of SIGMA-TABLE.md.  This
emits the two 131 x 131 matrices those tables are built from: the ONB
coordinates of t^i, and the pentanomial coordinates of gamma_(i+1).

The root t is found in the ONB model by Cantor-Zassenhaus (field.findRootInOnb
through curves.basisImages, the same path gen.py uses for the challenge
points), and the change of basis is checked to be a ring isomorphism that
commutes with Frobenius before anything is written.
"""
import argparse
from pathlib import Path
import random
import curves
import field

M = 131
POLY = (1 << 131) | (1 << 13) | (1 << 2) | (1 << 1) | 1
TAPS = (13, 2, 1)


def words(v):
    return [(v >> (32 * i)) & 0xffffffff for i in range(5)]


def generate():
    onb = field.Onb(M)
    pb = field.Pb(M, POLY)
    if not pb.isIrreducible():
        raise RuntimeError('pentanomial is not irreducible')
    rng = random.Random(0x131131)
    root, zToOnb, gammaToPb = curves.basisImages(onb, POLY, M, rng)

    def pbToOnb(v):
        acc = 0
        for i in range(M):
            if (v >> i) & 1:
                acc ^= zToOnb[i]
        return acc

    def onbToPb(c):
        acc = 0
        for i in range(M):
            if (c >> i) & 1:
                acc ^= gammaToPb[i]
        return acc

    # Identity, homomorphism, Frobenius: the matrices must describe one field.
    for i in range(M):
        if onbToPb(zToOnb[i]) != (1 << i) or pbToOnb(gammaToPb[i]) != (1 << i):
            raise RuntimeError('change of basis does not round-trip on basis vector %d' % i)
    for _ in range(96):
        u, v = rng.getrandbits(M), rng.getrandbits(M)
        a, b = onb.fromCoords(u), onb.fromCoords(v)
        if onbToPb(onb.toCoords(onb.mul(a, b))) != pb.mul(onbToPb(u), onbToPb(v)):
            raise RuntimeError('change of basis is not multiplicative')
        if onbToPb(onb.toCoords(onb.sqr(a))) != pb.sqr(onbToPb(u)):
            raise RuntimeError('change of basis does not commute with squaring')
        if onbToPb(onb.toCoords(onb.frob(a, 7))) != pb.pow(onbToPb(u), 1 << 7):
            raise RuntimeError('change of basis does not commute with sigma^7')
    lines = ['// Generated by codegen/genpenta.py; included inside eccPacked131.',
             '// F_2[t]/(t^131 + t^13 + t^2 + t + 1): ONB coordinates of t^i, and the',
             '// pentanomial coordinates of the ONB basis element gamma_(i+1).',
             '#pragma once',
             'static const int PENTA_TAPS[3] = {%d, %d, %d};' % TAPS,
             'static const uint32_t pentaToOnb131[131][5] = {']
    for i in range(M):
        lines.append('    {' + ','.join('0x%08xu' % w for w in words(zToOnb[i])) + '},')
    lines += ['};', 'static const uint32_t pentaFromOnb131[131][5] = {']
    for i in range(M):
        lines.append('    {' + ','.join('0x%08xu' % w for w in words(gammaToPb[i])) + '},')
    lines += ['};']
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', default='../include/packedpenta131.h')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if Path(args.out).read_text() != generated:
            raise SystemExit('pentanomial header does not match the generator')
        print('Pentanomial change of basis verified; generated header matches:', args.out)
    else:
        Path(args.out).write_text(generated)
        print('Pentanomial change of basis verified (round trip, products, squaring, sigma^7) and generated:', args.out)
