"""Generate reduction in the existing optimal polynomial basis.

Let A=1+x+x^3 and S=1+x^8+x^16+x^32+x^64+x^128. The reciprocal
minimal polynomial is F=A*S+x^7. Since S^2+S=x^8+x^256,
F*(F+A)=x^7+A^2*x^256. Thus (F+A)/x^7 is the truncated inverse
needed for a degree-260 dividend. It has only sixteen terms.
"""
import argparse
from pathlib import Path
import random


def reverse(x, n):
    return int(format(x, '0%db' % n)[::-1], 2)


def polynomial():
    previous, current, f = 0, 2, 1
    for _ in range(131):
        f ^= current
        previous, current = current, (current << 1)^previous
    return f


def reference(x, f):
    while x.bit_length() > 131:
        x ^= f << (x.bit_length()-132)
    return x


def fast(x):
    d = reverse(x >> 131, 130)
    r = d^(d<<1)^(d<<3)
    qr = d
    for shift in (1,9,25,57,121):
        qr ^= r << shift
    q = reverse(qr & ((1<<130)-1), 130)
    t = q^(q<<2)^(q<<3)
    result = x^t^(q<<124)
    for shift in (64,96,112,120,128):
        result ^= t << shift
    return result & ((1<<131)-1)


def check():
    f = polynomial()
    factored = (1<<124)
    for shift in (0,64,96,112,120,128):
        factored ^= ((1<<3)|(1<<2)|1) << shift
    if factored != f:
        raise ValueError('minimal-polynomial factorization mismatch')
    rng = random.Random(131)
    for x in [1<<i for i in range(261)] + [rng.getrandbits(261) for _ in range(1000)]:
        if fast(x) != reference(x,f):
            raise ValueError(('reduction mismatch',x))


def left(prefix, shift, word):
    offset, bits = divmod(shift,32)
    src = word-offset
    if src < 0:
        return None
    if not bits:
        return '%s%d' % (prefix,src)
    parts = ['(%s%d << %d)' % (prefix,src,bits)]
    if src > 0:
        parts.append('(%s%d >> %d)' % (prefix,src-1,32-bits))
    return '('+' | '.join(parts)+')'


def generate():
    check()
    lines = ['// Generated by codegen/genpolyreduce.py; included inside eccPacked131.',
             '#pragma once', 'ECC_HD P131 reducePolynomial131(const uint32_t *h) {']
    for i in range(5):
        expr = '((reverse32(h[%d]) >> 27) | (reverse32(h[%d]) << 5))' % (8-i,7-i)
        if i==4:
            expr += '&3u'
        lines.append('    uint32_t d%d=%s;' % (i,expr))
    for i in range(5):
        lines.append('    uint32_t r%d=d%d ^ %s ^ %s;' % (i,i,left('d',1,i),left('d',3,i)))
    for i in range(5):
        parts = ['d%d'%i]+[left('r',shift,i) for shift in (1,9,25,57,121)]
        expr = ' ^ '.join(p for p in parts if p)
        if i==4:
            expr = '('+expr+')&3u'
        lines.append('    uint32_t q%d=%s;' % (i,expr))
    for i in range(5):
        parts = ['(reverse32(q%d) >> 30)' % (4-i)]
        if i<4:
            parts.append('(reverse32(q%d) << 2)' % (3-i))
        lines.append('    uint32_t z%d=%s;' % (i,' | '.join(parts)))
    for i in range(5):
        lines.append('    uint32_t t%d=z%d ^ %s ^ %s;' % (i,i,left('z',2,i),left('z',3,i)))
    lines.append('    P131 out;')
    for i in range(5):
        parts = ['h[%d]'%i,'t%d'%i]+[left('t',s,i) for s in (64,96,112,120,128)]+[left('z',124,i)]
        expr = ' ^ '.join(p for p in parts if p)
        if i==4:
            expr = '('+expr+')&7u'
        lines.append('    out.v[%d]=%s;' % (i,expr))
    lines += ['    return out;', '}']
    return '\n'.join(lines)+'\n'


if __name__ == '__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--out',default='../include/packedpolyreduce131.h')
    args=parser.parse_args()
    Path(args.out).write_text(generate())
    print('PASS: reduction against polynomial long division on every input basis vector and 1000 dense cases')
