#!/usr/bin/env python3
# Emit synthesisable Verilog for the generated GF(2^m) circuits.
#
#   python3 genverilog.py [--out ../generated/rtl] [--m 131] [--leaf 9]
#                         [--gates-per-stage 8] [--vectors 16]
#
# This is the third back end of the straight-line IR in ir.py, after C
# (Prog.emit) and CNF (Prog.emitCnf).  The same DAG that becomes the CUDA
# client's field arithmetic becomes here a pipelined FPGA datapath: one
# GF(2^m) multiplication retired per clock at II = 1, with a tag carried
# alongside the operands so one multiplier can serve many independent walks --
# the arrangement hdl/ecc/ec_add_pipe.vhd already uses for secp256k1.
#
# Why generate it rather than write it.  ../FPGA-CEILING.md costs an FPGA
# version of the walk and finds the two dominant uncertainties are LUT packing
# and achievable clock, both of which need real synthesis.  Hand-written RTL
# would answer them for hand-written arithmetic; generated RTL answers them for
# the arithmetic the client actually uses, and is checked against the same
# independent field model.
#
# What is emitted, for m = 131:
#   ecc_mul131.v      pipelined multiplier, II = 1, latency = pipeline stages
#   ecc_hamming131.v  orbit weight and the distinguished-point test
#   ecc_sigma131.v    Frobenius sigma^j selection -- permutations and muxes only
#   tb_ecc_mul131.v   self-checking testbench (Icarus, Verilator, Vivado)
#   vectors_mul131.txt  operand/product vectors from field.Onb
#
# Verification.  Every emitted module is read back from disk by an independent
# evaluator (testverilog.py) and simulated cycle by cycle against field.Onb.
# That checks the emitted text rather than the IR; the IR is already checked by
# gen.py.  Squaring is free here in the literal sense: sigma is a permutation of
# ONB coordinates, so ecc_sigma131.v contains wires and 2:1 muxes and no gates.
#
# No type hints, camelCase identifiers, no itertools (project convention).

import argparse
import os
import random

import build
import field
import ir


def liveOrder(prog, roots):
    """Live nodes in topological (emission) order, inputs included."""
    rc = prog.refCounts(roots)
    out = []
    for i in range(len(prog.ops)):
        if prog.inputRef[i] is not None:
            if rc[i] > 0:
                out.append(i)
        elif prog.ops[i] is not None and rc[i] > 0:
            out.append(i)
    return out


def stageAssignment(prog, roots, order, gatesPerStage):
    """Cut the DAG into pipeline stages by gate depth.

    A node of gate depth d goes in stage (d-1)//gatesPerStage; inputs are depth
    0 and stage 0.  Registers are inserted at every stage boundary, so the
    latency in clocks equals the number of stages and the initiation interval
    stays 1.
    """
    depth = {}
    stage = {}
    for i in order:
        if prog.inputRef[i] is not None:
            depth[i] = 0
            stage[i] = 0
            continue
        worst = 0
        for x in prog.ops[i][1]:
            if depth[x] > worst:
                worst = depth[x]
        depth[i] = worst + 1
        stage[i] = (depth[i] - 1) // gatesPerStage
    nStages = 0
    for i in order:
        if stage[i] + 1 > nStages:
            nStages = stage[i] + 1
    return depth, stage, nStages


def registerPlan(prog, roots, order, stage, nStages):
    """For each node, the last stage at which a consumer reads it.

    A node produced in stage s and read in stage t > s is carried forward
    through t - s one-bit registers.  Roots are read at stage nStages, which is
    the output register bank.
    """
    lastNeed = {}
    for i in order:
        if prog.inputRef[i] is not None:
            continue
        for x in prog.ops[i][1]:
            if stage[i] > lastNeed.get(x, -1):
                lastNeed[x] = stage[i]
    for r in roots:
        if r is not None and nStages > lastNeed.get(r, -1):
            lastNeed[r] = nStages
    ffs = 0
    for i in order:
        if lastNeed.get(i, -1) > stage[i]:
            ffs += lastNeed[i] - stage[i]
    return lastNeed, ffs


def emitModule(name, prog, roots, inputs, outName, outLen, gatesPerStage,
               tagWidth):
    """Return (lines, stats) for a pipelined module computing roots."""
    order = liveOrder(prog, roots)
    depth, stage, nStages = stageAssignment(prog, roots, order, gatesPerStage)
    lastNeed, ffs = registerPlan(prog, roots, order, stage, nStages)

    def ref(node, atStage):
        if stage[node] == atStage:
            return 'w%d' % node
        return 'r%d_%d' % (node, atStage)

    nGates = 0
    for i in order:
        if prog.inputRef[i] is None:
            nGates += 1

    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// Pipelined %s: initiation interval 1, latency %d clocks.'
                 % (name, nStages))
    lines.append('// %d gates, %d pipeline registers, %d stages of <= %d gate levels.'
                 % (nGates, ffs, nStages, gatesPerStage))
    lines.append('`default_nettype none')
    lines.append('')
    ports = ['input  wire clk']
    for nm in inputs:
        ports.append('input  wire [%d:0] %s' % (inputWidth(prog, nm) - 1, nm))
    ports.append('input  wire [%d:0] tagIn' % (tagWidth - 1))
    ports.append('input  wire validIn')
    ports.append('output wire [%d:0] %s' % (outLen - 1, outName))
    ports.append('output wire [%d:0] tagOut' % (tagWidth - 1))
    ports.append('output wire validOut')
    lines.append('module %s (' % name)
    for k in range(len(ports)):
        lines.append('    %s%s' % (ports[k], ',' if k + 1 < len(ports) else ''))
    lines.append(');')
    lines.append('')

    byStage = {}
    for i in order:
        byStage.setdefault(stage[i], []).append(i)

    for s in range(nStages):
        lines.append('    // ---- stage %d ----' % s)
        for i in byStage.get(s, []):
            src = prog.inputRef[i]
            if src is not None:
                lines.append('    wire w%d = %s[%d];' % (i, src[0], src[1]))
                continue
            op, args = prog.ops[i]
            if op == ir.OP_NOT:
                expr = '~ %s' % ref(args[0], s)
            elif op == ir.OP_XOR:
                expr = '%s ^ %s' % (ref(args[0], s), ref(args[1], s))
            elif op == ir.OP_AND:
                expr = '%s & %s' % (ref(args[0], s), ref(args[1], s))
            elif op == ir.OP_OR:
                expr = '%s | %s' % (ref(args[0], s), ref(args[1], s))
            elif op == ir.OP_XOR3:
                expr = '%s ^ %s ^ %s' % (ref(args[0], s), ref(args[1], s),
                                         ref(args[2], s))
            elif op == ir.OP_XORAND:
                expr = '%s ^ ( %s & %s )' % (ref(args[0], s), ref(args[1], s),
                                             ref(args[2], s))
            elif op == ir.OP_MAJ:
                a, b, c = ref(args[0], s), ref(args[1], s), ref(args[2], s)
                expr = '( %s & %s ) | ( %s & %s ) | ( %s & %s )' % (a, b, a, c, b, c)
            else:
                raise ValueError('no Verilog rule for op ' + op)
            lines.append('    wire w%d = %s;' % (i, expr))
        crossing = []
        for i in order:
            if stage[i] <= s and lastNeed.get(i, -1) > s:
                crossing.append(i)
        if crossing:
            names = []
            for i in crossing:
                names.append('r%d_%d' % (i, s + 1))
            lines.append('    reg %s;' % ', '.join(names))
            lines.append('    always @(posedge clk) begin')
            for i in crossing:
                lines.append('        r%d_%d <= %s;' % (i, s + 1, ref(i, s)))
            lines.append('    end')
        lines.append('')

    lines.append('    // ---- outputs ----')
    for k in range(outLen):
        r = roots[k] if k < len(roots) else None
        if r is None:
            lines.append('    assign %s[%d] = 1\'b0;' % (outName, k))
        else:
            lines.append('    assign %s[%d] = %s;' % (outName, k, ref(r, nStages)))
    lines.append('')
    lines.append('    // tag and valid ride alongside the operands')
    lines.append('    reg [%d:0] tagPipe [0:%d];' % (tagWidth - 1, nStages - 1))
    lines.append('    reg [%d:0] validPipe;' % (nStages - 1))
    lines.append('    integer s;')
    lines.append('    always @(posedge clk) begin')
    lines.append('        tagPipe[0] <= tagIn;')
    lines.append('        for (s = 1; s < %d; s = s + 1)' % nStages)
    lines.append('            tagPipe[s] <= tagPipe[s-1];')
    lines.append('        validPipe <= {validPipe[%d:0], validIn};' % (nStages - 2)
                 if nStages > 1 else '        validPipe <= validIn;')
    lines.append('    end')
    lines.append('    assign tagOut = tagPipe[%d];' % (nStages - 1))
    lines.append('    assign validOut = validPipe[%d];' % (nStages - 1))
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')

    stats = {'gates': nGates, 'nodes': len(order),
             'stages': nStages, 'registers': ffs, 'gatesPerStage': gatesPerStage}
    return lines, stats


def inputWidth(prog, name):
    """Number of positions of input array `name` referenced by the program."""
    top = -1
    for i in range(len(prog.ops)):
        src = prog.inputRef[i]
        if src is not None and src[0] == name and src[1] > top:
            top = src[1]
    return top + 1


def buildMul(m, leaf):
    p = ir.Prog()
    a = []
    b = []
    for i in range(m):
        a.append(p.addInput('a', i))
    for i in range(m):
        b.append(p.addInput('b', i))
    pa = build.multPrepIr(p, a, m)
    pb = build.multPrepIr(p, b, m)
    hh = build.polyMulIr(p, pa, pb, leaf)
    return p, build.toOnbIr(p, hh, m)


def buildHamming(m, nBits):
    p = ir.Prog()
    x = []
    for i in range(m):
        x.append(p.addInput('x', i))
    return p, build.hammingIr(p, x, nBits)


def sigmaPermutation(m, j):
    """sigma^j on ONB coordinates, as perm[dst] = src.

    Coordinate k (0-based) carries gamma_{k+1}, and squaring sends gamma_i to
    gamma_{fold(2i)} with fold(t) = min(t mod n, n - t mod n), n = 2m+1.  So
    squaring permutes coordinates and costs no logic at all.

    The direction matters and is easy to get backwards: the map runs forwards
    on the *source* index, so coordinate fold(2^j * i) of the result takes
    coordinate i of the operand.  Indexing the result by fold(2^j * k) instead
    wires up sigma^-j, which is a permutation too and passes every shape check
    while computing the wrong Frobenius power.
    """
    n = 2 * m + 1
    perm = [None] * m
    for i in range(1, m + 1):
        t = (i << j) % n
        if t > m:
            t = n - t
        perm[t - 1] = i - 1
    return perm


def emitSigma(m, name):
    """sigma^j for j = 3 + ((weight/2) mod 8), as three conditional squarings."""
    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// sigma^j on ONB coordinates, j = 3 + ((hw/2) mod 8).')
    lines.append('// Frobenius is a coordinate permutation in this basis, so this')
    lines.append('// module is wires and 2:1 muxes: no gates, no carry, no logic levels')
    lines.append('// beyond the three selects.  This is the "squaring is free" claim')
    lines.append('// in ../FPGA-CEILING.md, made literal.')
    lines.append('`default_nettype none')
    lines.append('')
    lines.append('module %s (' % name)
    lines.append('    input  wire [%d:0] x,' % (m - 1))
    lines.append('    input  wire [2:0]  sel,   // (hw/2) mod 8')
    lines.append('    output wire [%d:0] y' % (m - 1))
    lines.append(');')
    lines.append('')
    base = sigmaPermutation(m, 3)
    lines.append('    // fixed sigma^3')
    lines.append('    wire [%d:0] s3;' % (m - 1))
    for k in range(m):
        lines.append('    assign s3[%d] = x[%d];' % (k, base[k]))
    lines.append('')
    prev = 's3'
    for bit in range(3):
        step = 1 << bit
        perm = sigmaPermutation(m, step)
        nxt = 'c%d' % bit
        lines.append('    // conditional sigma^%d' % step)
        lines.append('    wire [%d:0] %sp;' % (m - 1, nxt))
        for k in range(m):
            lines.append('    assign %sp[%d] = %s[%d];' % (nxt, k, prev, perm[k]))
        lines.append('    wire [%d:0] %s = sel[%d] ? %sp : %s;'
                     % (m - 1, nxt, bit, nxt, prev))
        lines.append('')
        prev = nxt
    lines.append('    assign y = %s;' % prev)
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')
    return lines


def emitTestbench(name, module, m, stages, vectorFile, count):
    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// Self-checking testbench: drives %d operand pairs back to back and' % count)
    lines.append('// checks the product, the latency and that the tag follows its operands.')
    lines.append('// Vectors come from field.Onb via the generator, the same oracle the')
    lines.append('// CUDA and CPU clients are checked against.')
    lines.append('`timescale 1ns/1ps')
    lines.append('`default_nettype none')
    lines.append('')
    lines.append('module %s;' % name)
    lines.append('    localparam M = %d;' % m)
    lines.append('    localparam LAT = %d;' % stages)
    lines.append('    localparam N = %d;' % count)
    lines.append('')
    lines.append('    reg clk = 1\'b0;')
    lines.append('    always #5 clk = ~clk;')
    lines.append('')
    lines.append('    reg  [M-1:0] a = {M{1\'b0}};')
    lines.append('    reg  [M-1:0] b = {M{1\'b0}};')
    lines.append('    reg  [7:0]   tagIn = 8\'d0;')
    lines.append('    reg          validIn = 1\'b0;')
    lines.append('    wire [M-1:0] p;')
    lines.append('    wire [7:0]   tagOut;')
    lines.append('    wire         validOut;')
    lines.append('')
    lines.append('    %s dut (.clk(clk), .a(a), .b(b), .tagIn(tagIn),' % module)
    lines.append('        .validIn(validIn), .p(p), .tagOut(tagOut), .validOut(validOut));')
    lines.append('')
    lines.append('    reg [M-1:0] av [0:N-1];')
    lines.append('    reg [M-1:0] bv [0:N-1];')
    lines.append('    reg [M-1:0] pv [0:N-1];')
    lines.append('    reg [3*M-1:0] row [0:N-1];')
    lines.append('')
    lines.append('    integer i, issued, checked, errors;')
    lines.append('    initial begin')
    lines.append('        errors = 0;')
    lines.append('        $readmemh("%s", row);' % vectorFile)
    lines.append('        for (i = 0; i < N; i = i + 1) begin')
    lines.append('            av[i] = row[i][3*M-1:2*M];')
    lines.append('            bv[i] = row[i][2*M-1:M];')
    lines.append('            pv[i] = row[i][M-1:0];')
    lines.append('        end')
    lines.append('        @(negedge clk);')
    lines.append('        // one vector per clock: the pipeline must accept them back to back')
    lines.append('        for (issued = 0; issued < N; issued = issued + 1) begin')
    lines.append('            a <= av[issued];')
    lines.append('            b <= bv[issued];')
    lines.append('            tagIn <= issued[7:0];')
    lines.append('            validIn <= 1\'b1;')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        validIn <= 1\'b0;')
    lines.append('    end')
    lines.append('')
    lines.append('    initial begin')
    lines.append('        checked = 0;')
    lines.append('        @(negedge clk);')
    lines.append('        // nothing may be claimed valid before the pipeline has filled')
    lines.append('        for (i = 0; i < LAT; i = i + 1) begin')
    lines.append('            if (validOut !== 1\'b0) begin')
    lines.append('                $display("%s: valid asserted after %0d clocks, latency is %0d", "FAIL", i, LAT);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        while (checked < N) begin')
    lines.append('            if (validOut !== 1\'b1) begin')
    lines.append('                $display("FAIL: gap in the output stream at vector %0d", checked);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            if (p !== pv[checked]) begin')
    lines.append('                $display("FAIL: vector %0d product mismatch", checked);')
    lines.append('                $display("  got  %h", p);')
    lines.append('                $display("  want %h", pv[checked]);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            if (tagOut !== checked[7:0]) begin')
    lines.append('                $display("FAIL: vector %0d tag %0d did not follow its operands",')
    lines.append('                    checked, tagOut);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            checked = checked + 1;')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        if (errors == 0)')
    lines.append('            $display("%s: %0d multiplications, II=1, latency %0d clk",')
    lines.append('                "PASS", N, LAT);')
    lines.append('        else')
    lines.append('            $display("FAIL: %0d errors", errors);')
    lines.append('        $finish;')
    lines.append('    end')
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')
    return lines


def vectorRows(m, onb, rng, count):
    """(a, b, a*b) triples in ONB coordinates, most significant field first."""
    rows = []
    specials = [(0, 0), (1, 1)]
    for k in range(count):
        if k < len(specials):
            u = onb.fromCoords(specials[k][0])
            v = onb.fromCoords(specials[k][1])
        else:
            u = onb.randomElement(rng)
            v = onb.randomElement(rng)
        ca = onb.toCoords(u)
        cb = onb.toCoords(v)
        cp = onb.toCoords(onb.mul(u, v))
        rows.append((ca, cb, cp))
    return rows


def writeLines(path, lines):
    fh = open(path, 'w')
    for line in lines:
        fh.write(line + '\n')
    fh.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join('..', 'generated', 'rtl'))
    ap.add_argument('--m', type=int, default=131)
    ap.add_argument('--leaf', type=int, default=9)
    ap.add_argument('--gates-per-stage', type=int, default=8, dest='gatesPerStage')
    ap.add_argument('--vectors', type=int, default=16)
    args = ap.parse_args()

    m = args.m
    if not os.path.isdir(args.out):
        os.makedirs(args.out)
    rng = random.Random(0x5EED0000 + m)
    onb = field.Onb(m)
    onb.selfTest(rng)

    prog, roots = buildMul(m, args.leaf)
    lines, mulStats = emitModule('ecc_mul%d' % m, prog, roots, ['a', 'b'], 'p', m,
                                 args.gatesPerStage, 8)
    writeLines(os.path.join(args.out, 'ecc_mul%d.v' % m), lines)

    nBits = 1
    while (1 << nBits) <= m:
        nBits += 1
    hProg, hRoots = buildHamming(m, nBits)
    hLines, hamStats = emitModule('ecc_hamming%d' % m, hProg, hRoots, ['x'], 'hw',
                                  nBits, args.gatesPerStage, 8)
    # the distinguished-point test is an nBits comparator, not worth a gate DAG
    tail = hLines.index('endmodule')
    hLines[tail:tail] = [
        '    // distinguished point: HW(x) <= cutoff, one comparator',
        '    assign dp = (hw <= cutoff);',
        '']
    for k in range(len(hLines)):
        if hLines[k].startswith('module ecc_hamming'):
            hLines[k] = ('module ecc_hamming%d #(parameter [%d:0] cutoff = %d) ('
                         % (m, nBits - 1, 34))
        if hLines[k].strip() == 'output wire validOut':
            hLines[k] = '    output wire validOut,'
            hLines.insert(k + 1, '    output wire dp')
            break
    writeLines(os.path.join(args.out, 'ecc_hamming%d.v' % m), hLines)

    writeLines(os.path.join(args.out, 'ecc_sigma%d.v' % m),
               emitSigma(m, 'ecc_sigma%d' % m))

    rows = vectorRows(m, onb, rng, args.vectors)
    width = (3 * m + 3) // 4
    vlines = ['// a | b | a*b in ONB coordinates, %d bits each, from field.Onb' % m]
    for ca, cb, cp in rows:
        packed = (ca << (2 * m)) | (cb << m) | cp
        vlines.append('%0*x' % (width, packed))
    writeLines(os.path.join(args.out, 'vectors_mul%d.txt' % m), vlines)

    writeLines(os.path.join(args.out, 'tb_ecc_mul%d.v' % m),
               emitTestbench('tb_ecc_mul%d' % m, 'ecc_mul%d' % m, m,
                             mulStats['stages'], 'vectors_mul%d.txt' % m,
                             args.vectors))

    print('wrote %s' % args.out)
    print('  ecc_mul%d.v       %d gates, %d stages, %d pipeline registers'
          % (m, mulStats['gates'], mulStats['stages'], mulStats['registers']))
    print('  ecc_hamming%d.v   %d gates, %d stages, %d pipeline registers'
          % (m, hamStats['gates'], hamStats['stages'], hamStats['registers']))
    print('  ecc_sigma%d.v     0 gates (coordinate permutation and 3 muxes)' % m)
    print('  tb_ecc_mul%d.v    %d vectors' % (m, args.vectors))


if __name__ == '__main__':
    main()
