#!/usr/bin/env python3
# Emit synthesisable Verilog for the generated GF(2^m) circuits.
#
#   python3 genverilog.py [--out ../generated/rtl] [--m 131] [--leaf 9]
#                         [--gates-per-stage 8] [--vectors 16]
#
# This is the third back end of the straight-line IR in ir.py, after C
# (Prog.emit) and CNF (Prog.emitCnf).  The same DAG that becomes the CUDA
# client's field arithmetic becomes here a pipelined FPGA datapath: one
# GF(2^m) multiplication retired per clock at II = 1, with a tag carried
# alongside the operands so one multiplier can serve many independent walks --
# the arrangement hdl/ecc/ec_add_pipe.vhd already uses for secp256k1.
#
# Why generate it rather than write it.  ../FPGA-CEILING.md costs an FPGA
# version of the walk and finds the two dominant uncertainties are LUT packing
# and achievable clock, both of which need real synthesis.  Hand-written RTL
# would answer them for hand-written arithmetic; generated RTL answers them for
# the arithmetic the client actually uses, and is checked against the same
# independent field model.
#
# What is emitted, for m = 131:
#   ecc_mul131.v      pipelined multiplier, II = 1, latency = pipeline stages
#   ecc_hamming131.v  orbit weight and the distinguished-point test
#   ecc_sigma131.v    Frobenius sigma^j selection -- permutations and muxes only
#   tb_ecc_mul131.v   self-checking testbench (Icarus, Verilator, Vivado)
#   vectors_mul131.txt  operand/product vectors from field.Onb
#
# Verification.  Every emitted module is read back from disk by an independent
# evaluator (testverilog.py) and simulated cycle by cycle against field.Onb.
# That checks the emitted text rather than the IR; the IR is already checked by
# gen.py.  Squaring is free here in the literal sense: sigma is a permutation of
# ONB coordinates, so ecc_sigma131.v contains wires and 2:1 muxes and no gates.
#
# No type hints, camelCase identifiers, no itertools (project convention).

import argparse
import os
import random

import build
import curves
import field
import ir


def liveOrder(prog, roots):
    """Live nodes in topological (emission) order, inputs included."""
    rc = prog.refCounts(roots)
    out = []
    for i in range(len(prog.ops)):
        if prog.inputRef[i] is not None:
            if rc[i] > 0:
                out.append(i)
        elif prog.ops[i] is not None and rc[i] > 0:
            out.append(i)
    return out


def stageAssignment(prog, roots, order, gatesPerStage):
    """Cut the DAG into pipeline stages by gate depth.

    A node of gate depth d goes in stage (d-1)//gatesPerStage; inputs are depth
    0 and stage 0.  Registers are inserted at every stage boundary, so the
    latency in clocks equals the number of stages and the initiation interval
    stays 1.
    """
    depth = {}
    stage = {}
    for i in order:
        if prog.inputRef[i] is not None:
            depth[i] = 0
            stage[i] = 0
            continue
        worst = 0
        for x in prog.ops[i][1]:
            if depth[x] > worst:
                worst = depth[x]
        depth[i] = worst + 1
        stage[i] = (depth[i] - 1) // gatesPerStage
    nStages = 0
    for i in order:
        if stage[i] + 1 > nStages:
            nStages = stage[i] + 1
    return depth, stage, nStages


def registerPlan(prog, roots, order, stage, nStages):
    """For each node, the last stage at which a consumer reads it.

    A node produced in stage s and read in stage t > s is carried forward
    through t - s one-bit registers.  Roots are read at stage nStages, which is
    the output register bank.
    """
    lastNeed = {}
    for i in order:
        if prog.inputRef[i] is not None:
            continue
        for x in prog.ops[i][1]:
            if stage[i] > lastNeed.get(x, -1):
                lastNeed[x] = stage[i]
    for r in roots:
        if r is not None and nStages > lastNeed.get(r, -1):
            lastNeed[r] = nStages
    ffs = 0
    for i in order:
        if lastNeed.get(i, -1) > stage[i]:
            ffs += lastNeed[i] - stage[i]
    return lastNeed, ffs


def emitModule(name, prog, outs, inputs, gatesPerStage, tagWidth):
    """Return (lines, stats) for a pipelined module.

    `outs` is a list of (portName, roots); every output leaves the pipeline at
    the same stage, so a module with several results stays a single datapath
    with one latency and one valid.
    """
    roots = []
    for _, rs in outs:
        roots.extend(rs)
    order = liveOrder(prog, roots)
    depth, stage, nStages = stageAssignment(prog, roots, order, gatesPerStage)
    lastNeed, ffs = registerPlan(prog, roots, order, stage, nStages)

    def ref(node, atStage):
        if stage[node] == atStage:
            return 'w%d' % node
        return 'r%d_%d' % (node, atStage)

    nGates = 0
    for i in order:
        if prog.inputRef[i] is None:
            nGates += 1

    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// Pipelined %s: initiation interval 1, latency %d clocks.'
                 % (name, nStages))
    lines.append('// %d gates, %d pipeline registers, %d stages of <= %d gate levels.'
                 % (nGates, ffs, nStages, gatesPerStage))
    lines.append('`default_nettype none')
    lines.append('')
    ports = ['input  wire clk']
    for nm in inputs:
        ports.append('input  wire [%d:0] %s' % (inputWidth(prog, nm) - 1, nm))
    ports.append('input  wire [%d:0] tagIn' % (tagWidth - 1))
    ports.append('input  wire validIn')
    for nm, rs in outs:
        ports.append('output wire [%d:0] %s' % (len(rs) - 1, nm))
    ports.append('output wire [%d:0] tagOut' % (tagWidth - 1))
    ports.append('output wire validOut')
    lines.append('module %s (' % name)
    for k in range(len(ports)):
        lines.append('    %s%s' % (ports[k], ',' if k + 1 < len(ports) else ''))
    lines.append(');')
    lines.append('')

    byStage = {}
    for i in order:
        byStage.setdefault(stage[i], []).append(i)

    for s in range(nStages):
        lines.append('    // ---- stage %d ----' % s)
        for i in byStage.get(s, []):
            src = prog.inputRef[i]
            if src is not None:
                lines.append('    wire w%d = %s[%d];' % (i, src[0], src[1]))
                continue
            op, args = prog.ops[i]
            if op == ir.OP_NOT:
                expr = '~ %s' % ref(args[0], s)
            elif op == ir.OP_XOR:
                expr = '%s ^ %s' % (ref(args[0], s), ref(args[1], s))
            elif op == ir.OP_AND:
                expr = '%s & %s' % (ref(args[0], s), ref(args[1], s))
            elif op == ir.OP_OR:
                expr = '%s | %s' % (ref(args[0], s), ref(args[1], s))
            elif op == ir.OP_XOR3:
                expr = '%s ^ %s ^ %s' % (ref(args[0], s), ref(args[1], s),
                                         ref(args[2], s))
            elif op == ir.OP_XORAND:
                expr = '%s ^ ( %s & %s )' % (ref(args[0], s), ref(args[1], s),
                                             ref(args[2], s))
            elif op == ir.OP_MAJ:
                a, b, c = ref(args[0], s), ref(args[1], s), ref(args[2], s)
                expr = '( %s & %s ) | ( %s & %s ) | ( %s & %s )' % (a, b, a, c, b, c)
            else:
                raise ValueError('no Verilog rule for op ' + op)
            lines.append('    wire w%d = %s;' % (i, expr))
        crossing = []
        for i in order:
            if stage[i] <= s and lastNeed.get(i, -1) > s:
                crossing.append(i)
        if crossing:
            names = []
            for i in crossing:
                names.append('r%d_%d' % (i, s + 1))
            lines.append('    reg %s;' % ', '.join(names))
            lines.append('    always @(posedge clk) begin')
            for i in crossing:
                lines.append('        r%d_%d <= %s;' % (i, s + 1, ref(i, s)))
            lines.append('    end')
        lines.append('')

    lines.append('    // ---- outputs ----')
    for nm, rs in outs:
        for k in range(len(rs)):
            if rs[k] is None:
                lines.append('    assign %s[%d] = 1\'b0;' % (nm, k))
            else:
                lines.append('    assign %s[%d] = %s;' % (nm, k, ref(rs[k], nStages)))
    lines.append('')
    lines.append('    // tag and valid ride alongside the operands')
    lines.append('    reg [%d:0] tagPipe [0:%d];' % (tagWidth - 1, nStages - 1))
    # validPipe must start at zero, not X: nothing may claim valid before the
    # pipeline has filled, and a declaration initialiser is honoured both by
    # simulation and by FPGA bitstream initialisation.  The data path needs no
    # reset, because valid gates every consumer.
    lines.append('    reg [%d:0] validPipe = %d\'b0;' % (nStages - 1, nStages))
    lines.append('    integer s;')
    lines.append('    always @(posedge clk) begin')
    lines.append('        tagPipe[0] <= tagIn;')
    lines.append('        for (s = 1; s < %d; s = s + 1)' % nStages)
    lines.append('            tagPipe[s] <= tagPipe[s-1];')
    lines.append('        validPipe <= {validPipe[%d:0], validIn};' % (nStages - 2)
                 if nStages > 1 else '        validPipe <= validIn;')
    lines.append('    end')
    lines.append('    assign tagOut = tagPipe[%d];' % (nStages - 1))
    lines.append('    assign validOut = validPipe[%d];' % (nStages - 1))
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')

    stats = {'gates': nGates, 'nodes': len(order),
             'stages': nStages, 'registers': ffs, 'gatesPerStage': gatesPerStage}
    return lines, stats


def inputWidth(prog, name):
    """Number of positions of input array `name` referenced by the program."""
    top = -1
    for i in range(len(prog.ops)):
        src = prog.inputRef[i]
        if src is not None and src[0] == name and src[1] > top:
            top = src[1]
    return top + 1


def sigmaList(m, u, k):
    """sigma^k on a list of nets: a permutation of the list, so it is free.

    Mirrors FieldBs::sigma in include/fieldbs.h -- the coefficient of
    gamma_{i+1} moves to gamma_{fold(2^k (i+1))}.
    """
    n = 2 * m + 1
    e = pow(2, k, n)
    out = [None] * m
    for i in range(m):
        t = ((i + 1) * e) % n
        d = (t if t <= m else n - t) - 1
        out[d] = u[i]
    return out


def selList(p, mask, aList, bList):
    """ECC_SEL: mask ? a : b, as b ^ ((a ^ b) & mask)."""
    out = []
    for i in range(len(aList)):
        out.append(p.xor(bList[i], p.andOp(p.xor(aList[i], bList[i]), mask)))
    return out


def mulIr(p, m, leaf, u, v):
    """One GF(2^m) multiplication inside a larger program."""
    pu = build.multPrepIr(p, u, m)
    pv = build.multPrepIr(p, v, m)
    return build.toOnbIr(p, build.polyMulIr(p, pu, pv, leaf), m)


def buildPre(m, nBits):
    """Pass 1 of the walk: weight, sigma^j selection and the two addends.

    R' = sigma^j(R) + R with j = 3 + ((HW(x)/2) mod 8), so this block computes
    HW(x), selects sigma^j through three conditional squarings, and emits the
    addition's denominator d = x + sigma^j(x) and numerator e = y + sigma^j(y).

    It contains **no multiplication**: squaring is a permutation and addition is
    XOR, so pass 1 is the weight tree plus muxes.  Unlike the CUDA client, which
    recomputes sigma^j in pass 2 to save memory traffic, the hardware just lets
    d and e ride the pipeline.
    """
    p = ir.Prog()
    x = []
    y = []
    for i in range(m):
        x.append(p.addInput('x', i))
    for i in range(m):
        y.append(p.addInput('y', i))
    hb = build.hammingIr(p, x, nBits)
    sx = sigmaList(m, x, 3)
    sy = sigmaList(m, y, 3)
    for idx, step in ((1, 1), (2, 2), (3, 4)):
        sx = selList(p, hb[idx], sigmaList(m, sx, step), sx)
        sy = selList(p, hb[idx], sigmaList(m, sy, step), sy)
    d = []
    e = []
    for i in range(m):
        d.append(p.xor(x[i], sx[i]))
        e.append(p.xor(y[i], sy[i]))
    return p, d, e, hb


def buildPost(m, leaf):
    """Pass 2 of the walk: the affine addition, given the inverted denominator.

    lam = e * dinv;  x3 = lam^2 + lam + d;  y3 = lam*(x + x3) + x3 + y.
    Two multiplications, matching Walk::pointAdd in include/walk.h.  The inverse
    arrives from outside because one inverter is shared across a whole batch by
    Montgomery's trick -- the same reason hdl/ecc/ec_add_pipe.vhd takes it as a
    port.
    """
    p = ir.Prog()
    x = []
    y = []
    d = []
    e = []
    di = []
    for i in range(m):
        x.append(p.addInput('x', i))
    for i in range(m):
        y.append(p.addInput('y', i))
    for i in range(m):
        d.append(p.addInput('d', i))
    for i in range(m):
        e.append(p.addInput('e', i))
    for i in range(m):
        di.append(p.addInput('di', i))
    lam = mulIr(p, m, leaf, e, di)
    lamSq = sigmaList(m, lam, 1)
    x3 = []
    for i in range(m):
        x3.append(p.xor(p.xor(lamSq[i], lam[i]), d[i]))
    t = []
    for i in range(m):
        t.append(p.xor(x[i], x3[i]))
    prod = mulIr(p, m, leaf, lam, t)
    y3 = []
    for i in range(m):
        y3.append(p.xor(p.xor(prod[i], x3[i]), y[i]))
    return p, x3, y3


def buildMul(m, leaf):
    p = ir.Prog()
    a = []
    b = []
    for i in range(m):
        a.append(p.addInput('a', i))
    for i in range(m):
        b.append(p.addInput('b', i))
    pa = build.multPrepIr(p, a, m)
    pb = build.multPrepIr(p, b, m)
    hh = build.polyMulIr(p, pa, pb, leaf)
    return p, build.toOnbIr(p, hh, m)


def buildHamming(m, nBits):
    p = ir.Prog()
    x = []
    for i in range(m):
        x.append(p.addInput('x', i))
    return p, build.hammingIr(p, x, nBits)


def sigmaPermutation(m, j):
    """sigma^j on ONB coordinates, as perm[dst] = src.

    Coordinate k (0-based) carries gamma_{k+1}, and squaring sends gamma_i to
    gamma_{fold(2i)} with fold(t) = min(t mod n, n - t mod n), n = 2m+1.  So
    squaring permutes coordinates and costs no logic at all.

    The direction matters and is easy to get backwards: the map runs forwards
    on the *source* index, so coordinate fold(2^j * i) of the result takes
    coordinate i of the operand.  Indexing the result by fold(2^j * k) instead
    wires up sigma^-j, which is a permutation too and passes every shape check
    while computing the wrong Frobenius power.
    """
    n = 2 * m + 1
    perm = [None] * m
    for i in range(1, m + 1):
        t = (i << j) % n
        if t > m:
            t = n - t
        perm[t - 1] = i - 1
    return perm


def emitSigma(m, name):
    """sigma^j for j = 3 + ((weight/2) mod 8), as three conditional squarings."""
    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// sigma^j on ONB coordinates, j = 3 + ((hw/2) mod 8).')
    lines.append('// Frobenius is a coordinate permutation in this basis, so this')
    lines.append('// module is wires and 2:1 muxes: no gates, no carry, no logic levels')
    lines.append('// beyond the three selects.  This is the "squaring is free" claim')
    lines.append('// in ../FPGA-CEILING.md, made literal.')
    lines.append('`default_nettype none')
    lines.append('')
    lines.append('module %s (' % name)
    lines.append('    input  wire [%d:0] x,' % (m - 1))
    lines.append('    input  wire [2:0]  sel,   // (hw/2) mod 8')
    lines.append('    output wire [%d:0] y' % (m - 1))
    lines.append(');')
    lines.append('')
    base = sigmaPermutation(m, 3)
    lines.append('    // fixed sigma^3')
    lines.append('    wire [%d:0] s3;' % (m - 1))
    for k in range(m):
        lines.append('    assign s3[%d] = x[%d];' % (k, base[k]))
    lines.append('')
    prev = 's3'
    for bit in range(3):
        step = 1 << bit
        perm = sigmaPermutation(m, step)
        nxt = 'c%d' % bit
        lines.append('    // conditional sigma^%d' % step)
        lines.append('    wire [%d:0] %sp;' % (m - 1, nxt))
        for k in range(m):
            lines.append('    assign %sp[%d] = %s[%d];' % (nxt, k, prev, perm[k]))
        lines.append('    wire [%d:0] %s = sel[%d] ? %sp : %s;'
                     % (m - 1, nxt, bit, nxt, prev))
        lines.append('')
        prev = nxt
    lines.append('    assign y = %s;' % prev)
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')
    return lines


def invChain(m):
    """The Itoh-Tsujii schedule, mirroring FieldBs::inv in include/fieldbs.h.

    a^-1 = a^(2^m - 2) = (a^(2^(m-1) - 1))^2, built with an addition chain for
    m-1.  Returns [(sigmaExponent, operand)] with operand 'acc' or 'a', and the
    exponent of the final squaring.  For m = 131 this is 8 multiplications,
    which is the known optimum for an addition chain to 130.
    """
    e = m - 1
    hb = 0
    while (1 << (hb + 1)) <= e:
        hb += 1
    steps = []
    k = 1
    for bit in range(hb - 1, -1, -1):
        steps.append((k, 'acc'))
        k <<= 1
        if (e >> bit) & 1:
            steps.append((1, 'a'))
            k += 1
    if k != e:
        raise RuntimeError('addition chain ended at %d, not %d' % (k, e))
    return steps, 1


def emitDelay(name):
    """A plain shift register, for operands that must wait for the pipeline."""
    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('`default_nettype none')
    lines.append('')
    lines.append('module %s #(parameter WIDTH = 131, parameter DEPTH = 1) (' % name)
    lines.append('    input  wire             clk,')
    lines.append('    input  wire [WIDTH-1:0] d,')
    lines.append('    output wire [WIDTH-1:0] q')
    lines.append(');')
    lines.append('    reg [WIDTH-1:0] pipe [0:DEPTH-1];')
    lines.append('    integer i;')
    lines.append('    always @(posedge clk) begin')
    lines.append('        pipe[0] <= d;')
    lines.append('        for (i = 1; i < DEPTH; i = i + 1) pipe[i] <= pipe[i-1];')
    lines.append('    end')
    lines.append('    assign q = pipe[DEPTH-1];')
    lines.append('endmodule')
    lines.append('`default_nettype wire')
    return lines


def sigmaWires(m, dstNet, srcNet, k):
    """assign dstNet[...] = srcNet[...] implementing sigma^k: pure wiring."""
    perm = sigmaPermutation(m, k)
    out = []
    for i in range(m):
        out.append('    assign %s[%d] = %s[%d];' % (dstNet, i, srcNet, perm[i]))
    return out


def emitInv(m, name, mulName, delayName, mulLatency, tagWidth):
    """Itoh-Tsujii inversion as a chain of multiplier instances.

    Every squaring between multiplications is a permutation, so the only logic
    here is the multipliers themselves: 8 of them, fully pipelined, II = 1,
    latency 8 x mulLatency.  One inverter serves every core on the device
    through Montgomery's trick, so unrolling it costs about 5% of a VU47P --
    the published Spartan-6 designs used a one-multiplier sequencer instead
    because there 8 multipliers would have been most of the chip.
    """
    steps, finalSigma = invChain(m)
    latency = len(steps) * mulLatency
    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// Itoh-Tsujii inversion in GF(2^%d): %d multiplications, II = 1,'
                 % (m, len(steps)))
    lines.append('// latency %d clocks.  Squarings are permutations, hence free.'
                 % latency)
    lines.append('`default_nettype none')
    lines.append('')
    lines.append('module %s (' % name)
    lines.append('    input  wire clk,')
    lines.append('    input  wire [%d:0] a,' % (m - 1))
    lines.append('    input  wire [%d:0] tagIn,' % (tagWidth - 1))
    lines.append('    input  wire validIn,')
    lines.append('    output wire [%d:0] r,' % (m - 1))
    lines.append('    output wire [%d:0] tagOut,' % (tagWidth - 1))
    lines.append('    output wire validOut')
    lines.append(');')
    lines.append('')
    lines.append('    wire [%d:0] acc0 = a;' % (m - 1))
    lines.append('    wire [%d:0] tag0 = tagIn;' % (tagWidth - 1))
    lines.append('    wire        v0 = validIn;')
    lines.append('')
    needDelay = {}
    for i in range(len(steps)):
        if steps[i][1] == 'a' and i > 0:
            needDelay[i] = i * mulLatency
    for i in sorted(needDelay):
        lines.append('    // the original operand must wait for %d stages of pipeline'
                     % i)
        lines.append('    wire [%d:0] aDel%d;' % (m - 1, i))
        lines.append('    %s #(.WIDTH(%d), .DEPTH(%d)) uDel%d ('
                     % (delayName, m, needDelay[i], i))
        lines.append('        .clk(clk), .d(a), .q(aDel%d));' % i)
        lines.append('')
    for i in range(len(steps)):
        k, operand = steps[i]
        lines.append('    // step %d: sigma^%d(acc) * %s' % (i + 1, k, operand))
        lines.append('    wire [%d:0] s%d;' % (m - 1, i))
        lines.extend(sigmaWires(m, 's%d' % i, 'acc%d' % i, k))
        if operand == 'acc':
            other = 'acc%d' % i
        elif i == 0:
            other = 'a'
        else:
            other = 'aDel%d' % i
        lines.append('    wire [%d:0] acc%d;' % (m - 1, i + 1))
        lines.append('    wire [%d:0] tag%d;' % (tagWidth - 1, i + 1))
        lines.append('    wire        v%d;' % (i + 1))
        lines.append('    %s u%d (.clk(clk), .a(s%d), .b(%s), .tagIn(tag%d),'
                     % (mulName, i, i, other, i))
        lines.append('        .validIn(v%d), .p(acc%d), .tagOut(tag%d), .validOut(v%d));'
                     % (i, i + 1, i + 1, i + 1))
        lines.append('')
    last = len(steps)
    lines.append('    // final squaring, again just wiring')
    lines.extend(sigmaWires(m, 'r', 'acc%d' % last, finalSigma))
    lines.append('    assign tagOut = tag%d;' % last)
    lines.append('    assign validOut = v%d;' % last)
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')
    return lines, latency, len(steps)


def emitOneInputTestbench(name, module, m, latency, vectorFile, count, what):
    """Self-checking testbench for a one-operand module (a -> r)."""
    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// Drives %d operands back to back and checks %s, the latency and'
                 % (count, what))
    lines.append('// that the tag follows its operand.  Vectors come from field.Onb.')
    lines.append('`timescale 1ns/1ps')
    lines.append('`default_nettype none')
    lines.append('')
    lines.append('module %s;' % name)
    lines.append('    localparam M = %d;' % m)
    lines.append('    localparam LAT = %d;' % latency)
    lines.append('    localparam N = %d;' % count)
    lines.append('')
    lines.append('    reg clk = 1\'b0;')
    lines.append('    always #5 clk = ~clk;')
    lines.append('')
    lines.append('    reg  [M-1:0] a = {M{1\'b0}};')
    lines.append('    reg  [7:0]   tagIn = 8\'d0;')
    lines.append('    reg          validIn = 1\'b0;')
    lines.append('    wire [M-1:0] r;')
    lines.append('    wire [7:0]   tagOut;')
    lines.append('    wire         validOut;')
    lines.append('')
    lines.append('    %s dut (.clk(clk), .a(a), .tagIn(tagIn), .validIn(validIn),'
                 % module)
    lines.append('        .r(r), .tagOut(tagOut), .validOut(validOut));')
    lines.append('')
    lines.append('    reg [2*M-1:0] row [0:N-1];')
    lines.append('    reg [M-1:0] av [0:N-1];')
    lines.append('    reg [M-1:0] rv [0:N-1];')
    lines.append('')
    lines.append('    integer i, issued, checked;')
    lines.append('    integer errors = 0;')
    lines.append('    initial begin')
    lines.append('        $readmemh("%s", row);' % vectorFile)
    lines.append('        for (i = 0; i < N; i = i + 1) begin')
    lines.append('            av[i] = row[i][2*M-1:M];')
    lines.append('            rv[i] = row[i][M-1:0];')
    lines.append('        end')
    lines.append('        @(negedge clk);')
    lines.append('        for (issued = 0; issued < N; issued = issued + 1) begin')
    lines.append('            a <= av[issued];')
    lines.append('            tagIn <= issued[7:0];')
    lines.append('            validIn <= 1\'b1;')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        validIn <= 1\'b0;')
    lines.append('    end')
    lines.append('')
    lines.append('    initial begin')
    lines.append('        checked = 0;')
    lines.append('        @(negedge clk);')
    lines.append('        for (i = 0; i < LAT; i = i + 1) begin')
    lines.append('            if (validOut !== 1\'b0) begin')
    lines.append('                $display("FAIL: valid after %0d clocks, latency is %0d",')
    lines.append('                    i, LAT);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        while (checked < N) begin')
    lines.append('            if (validOut !== 1\'b1) begin')
    lines.append('                $display("FAIL: gap in the output stream at %0d", checked);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            if (r !== rv[checked]) begin')
    lines.append('                $display("FAIL: vector %0d mismatch", checked);')
    lines.append('                $display("  got  %h", r);')
    lines.append('                $display("  want %h", rv[checked]);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            if (tagOut !== checked[7:0]) begin')
    lines.append('                $display("FAIL: vector %0d tag %0d out of order",')
    lines.append('                    checked, tagOut);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            checked = checked + 1;')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        if (errors == 0)')
    lines.append('            $display("%s: %0d %s, II=1, latency %0d clk",')
    lines.append('                "PASS", N, "%s", LAT);' % what)
    lines.append('        else')
    lines.append('            $display("FAIL: %0d errors", errors);')
    lines.append('        $finish;')
    lines.append('    end')
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')
    return lines


def walkStep(onb, curve, point):
    """One iteration of the reference walk: sigma^j(R) + R."""
    weight = bin(onb.toCoords(point[0])).count('1')
    j = 3 + ((weight // 2) % 8)
    other = curve.frob(point, j)
    if onb.toCoords(onb.add(point[0], other[0])) == 0:
        return None
    return curve.add(point, other)


def walkVectorRows(m, onb, curve, rng, slots, steps):
    """For each slot, a start point and the trajectory it must follow.

    Row (s, t) is the point after t steps of walk s, so the hardware's retired
    steps can be compared against the reference one for one.
    """
    rows = []
    while len(rows) < slots:
        point = curve.pointFromX(onb.randomElement(rng))
        if point is None:
            continue
        traj = [point]
        ok = True
        for _ in range(steps):
            nxt = walkStep(onb, curve, traj[-1])
            if nxt is None:
                ok = False
                break
            traj.append(nxt)
        if ok:
            rows.append(traj)
    return rows


def invVectorRows(m, onb, rng, count):
    """(a, a^-1) pairs, a nonzero."""
    rows = []
    while len(rows) < count:
        u = onb.randomElement(rng)
        if onb.toCoords(u) == 0:
            continue
        rows.append((onb.toCoords(u), onb.toCoords(onb.inv(u))))
    return rows


def emitTestbench(name, module, m, stages, vectorFile, count):
    lines = []
    lines.append('// Generated by codegen/genverilog.py -- do not edit.')
    lines.append('// Self-checking testbench: drives %d operand pairs back to back and' % count)
    lines.append('// checks the product, the latency and that the tag follows its operands.')
    lines.append('// Vectors come from field.Onb via the generator, the same oracle the')
    lines.append('// CUDA and CPU clients are checked against.')
    lines.append('`timescale 1ns/1ps')
    lines.append('`default_nettype none')
    lines.append('')
    lines.append('module %s;' % name)
    lines.append('    localparam M = %d;' % m)
    lines.append('    localparam LAT = %d;' % stages)
    lines.append('    localparam N = %d;' % count)
    lines.append('')
    lines.append('    reg clk = 1\'b0;')
    lines.append('    always #5 clk = ~clk;')
    lines.append('')
    lines.append('    reg  [M-1:0] a = {M{1\'b0}};')
    lines.append('    reg  [M-1:0] b = {M{1\'b0}};')
    lines.append('    reg  [7:0]   tagIn = 8\'d0;')
    lines.append('    reg          validIn = 1\'b0;')
    lines.append('    wire [M-1:0] p;')
    lines.append('    wire [7:0]   tagOut;')
    lines.append('    wire         validOut;')
    lines.append('')
    lines.append('    %s dut (.clk(clk), .a(a), .b(b), .tagIn(tagIn),' % module)
    lines.append('        .validIn(validIn), .p(p), .tagOut(tagOut), .validOut(validOut));')
    lines.append('')
    lines.append('    reg [M-1:0] av [0:N-1];')
    lines.append('    reg [M-1:0] bv [0:N-1];')
    lines.append('    reg [M-1:0] pv [0:N-1];')
    lines.append('    reg [3*M-1:0] row [0:N-1];')
    lines.append('')
    lines.append('    integer i, issued, checked;')
    # errors is initialised at declaration, not inside one of the two initial
    # blocks: both start at time zero, so zeroing it in one races with an
    # increment in the other and silently loses a failure.
    lines.append('    integer errors = 0;')
    lines.append('    initial begin')
    lines.append('        $readmemh("%s", row);' % vectorFile)
    lines.append('        for (i = 0; i < N; i = i + 1) begin')
    lines.append('            av[i] = row[i][3*M-1:2*M];')
    lines.append('            bv[i] = row[i][2*M-1:M];')
    lines.append('            pv[i] = row[i][M-1:0];')
    lines.append('        end')
    lines.append('        @(negedge clk);')
    lines.append('        // one vector per clock: the pipeline must accept them back to back')
    lines.append('        for (issued = 0; issued < N; issued = issued + 1) begin')
    lines.append('            a <= av[issued];')
    lines.append('            b <= bv[issued];')
    lines.append('            tagIn <= issued[7:0];')
    lines.append('            validIn <= 1\'b1;')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        validIn <= 1\'b0;')
    lines.append('    end')
    lines.append('')
    lines.append('    initial begin')
    lines.append('        checked = 0;')
    lines.append('        @(negedge clk);')
    lines.append('        // nothing may be claimed valid before the pipeline has filled')
    lines.append('        for (i = 0; i < LAT; i = i + 1) begin')
    lines.append('            if (validOut !== 1\'b0) begin')
    lines.append('                $display("%s: valid asserted after %0d clocks, latency is %0d", "FAIL", i, LAT);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        while (checked < N) begin')
    lines.append('            if (validOut !== 1\'b1) begin')
    lines.append('                $display("FAIL: gap in the output stream at vector %0d", checked);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            if (p !== pv[checked]) begin')
    lines.append('                $display("FAIL: vector %0d product mismatch", checked);')
    lines.append('                $display("  got  %h", p);')
    lines.append('                $display("  want %h", pv[checked]);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            if (tagOut !== checked[7:0]) begin')
    lines.append('                $display("FAIL: vector %0d tag %0d did not follow its operands",')
    lines.append('                    checked, tagOut);')
    lines.append('                errors = errors + 1;')
    lines.append('            end')
    lines.append('            checked = checked + 1;')
    lines.append('            @(negedge clk);')
    lines.append('        end')
    lines.append('        if (errors == 0)')
    lines.append('            $display("%s: %0d multiplications, II=1, latency %0d clk",')
    lines.append('                "PASS", N, LAT);')
    lines.append('        else')
    lines.append('            $display("FAIL: %0d errors", errors);')
    lines.append('        $finish;')
    lines.append('    end')
    lines.append('')
    lines.append('endmodule')
    lines.append('`default_nettype wire')
    return lines


def vectorRows(m, onb, rng, count):
    """(a, b, a*b) triples in ONB coordinates, most significant field first."""
    rows = []
    specials = [(0, 0), (1, 1)]
    for k in range(count):
        if k < len(specials):
            u = onb.fromCoords(specials[k][0])
            v = onb.fromCoords(specials[k][1])
        else:
            u = onb.randomElement(rng)
            v = onb.randomElement(rng)
        ca = onb.toCoords(u)
        cb = onb.toCoords(v)
        cp = onb.toCoords(onb.mul(u, v))
        rows.append((ca, cb, cp))
    return rows


def writeLines(path, lines):
    fh = open(path, 'w')
    for line in lines:
        fh.write(line + '\n')
    fh.close()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', default=os.path.join('..', 'generated', 'rtl'))
    ap.add_argument('--m', type=int, default=131)
    ap.add_argument('--leaf', type=int, default=9)
    ap.add_argument('--gates-per-stage', type=int, default=8, dest='gatesPerStage')
    ap.add_argument('--vectors', type=int, default=16)
    # one start point per ring slot: pre + inverter + RAM + post, see
    # hdl/ecc2k130/ecc_rho_core.v
    ap.add_argument('--slots', type=int, default=124)
    ap.add_argument('--steps', type=int, default=3)
    args = ap.parse_args()

    m = args.m
    if not os.path.isdir(args.out):
        os.makedirs(args.out)
    rng = random.Random(0x5EED0000 + m)
    onb = field.Onb(m)
    onb.selfTest(rng)
    curve = curves.Curve(onb)

    prog, roots = buildMul(m, args.leaf)
    lines, mulStats = emitModule('ecc_mul%d' % m, prog, [('p', roots)],
                                 ['a', 'b'], args.gatesPerStage, 8)
    writeLines(os.path.join(args.out, 'ecc_mul%d.v' % m), lines)

    nBits = 1
    while (1 << nBits) <= m:
        nBits += 1
    hProg, hRoots = buildHamming(m, nBits)
    hLines, hamStats = emitModule('ecc_hamming%d' % m, hProg, [('hw', hRoots)],
                                  ['x'], args.gatesPerStage, 8)
    # the distinguished-point test is an nBits comparator, not worth a gate DAG
    tail = hLines.index('endmodule')
    hLines[tail:tail] = [
        '    // distinguished point: HW(x) <= cutoff, one comparator',
        '    assign dp = (hw <= cutoff);',
        '']
    for k in range(len(hLines)):
        if hLines[k].startswith('module ecc_hamming'):
            hLines[k] = ('module ecc_hamming%d #(parameter [%d:0] cutoff = %d) ('
                         % (m, nBits - 1, 34))
        if hLines[k].strip() == 'output wire validOut':
            hLines[k] = '    output wire validOut,'
            hLines.insert(k + 1, '    output wire dp')
            break
    writeLines(os.path.join(args.out, 'ecc_hamming%d.v' % m), hLines)

    writeLines(os.path.join(args.out, 'ecc_sigma%d.v' % m),
               emitSigma(m, 'ecc_sigma%d' % m))

    preProg, preD, preE, preHb = buildPre(m, nBits)
    preLines, preStats = emitModule(
        'ecc_pre%d' % m, preProg,
        [('d', preD), ('e', preE), ('hw', preHb)], ['x', 'y'],
        args.gatesPerStage, 8)
    writeLines(os.path.join(args.out, 'ecc_pre%d.v' % m), preLines)

    postProg, postX3, postY3 = buildPost(m, args.leaf)
    postLines, postStats = emitModule(
        'ecc_post%d' % m, postProg, [('x3', postX3), ('y3', postY3)],
        ['x', 'y', 'd', 'e', 'di'], args.gatesPerStage, 8)
    writeLines(os.path.join(args.out, 'ecc_post%d.v' % m), postLines)

    writeLines(os.path.join(args.out, 'ecc_delay.v'), emitDelay('ecc_delay'))

    invLines, invLat, invMults = emitInv(m, 'ecc_inv%d' % m, 'ecc_mul%d' % m,
                                         'ecc_delay', mulStats['stages'], 8)
    writeLines(os.path.join(args.out, 'ecc_inv%d.v' % m), invLines)

    invRows = invVectorRows(m, onb, rng, args.vectors)
    iWidth = (2 * m + 3) // 4
    iLines = ['// a | a^-1 in ONB coordinates, %d bits each, from field.Onb' % m]
    for ca, ci in invRows:
        iLines.append('%0*x' % (iWidth, (ca << m) | ci))
    writeLines(os.path.join(args.out, 'vectors_inv%d.txt' % m), iLines)
    writeLines(os.path.join(args.out, 'tb_ecc_inv%d.v' % m),
               emitOneInputTestbench('tb_ecc_inv%d' % m, 'ecc_inv%d' % m, m,
                                     invLat, 'vectors_inv%d.txt' % m,
                                     args.vectors, 'inversions'))

    # Reference trajectories for the rho core: one start point per ring slot,
    # then the exact sequence of points the hardware must reproduce.
    traj = walkVectorRows(m, onb, curve, rng, args.slots, args.steps)
    tWidth = (2 * m + 3) // 4
    tLines = ['// x | y after t steps, slot-major, %d slots x %d points, '
              'from curves.Curve' % (args.slots, args.steps + 1)]
    for walk in traj:
        for point in walk:
            tLines.append('%0*x' % (tWidth, (onb.toCoords(point[0]) << m)
                                    | onb.toCoords(point[1])))
    writeLines(os.path.join(args.out, 'vectors_walk%d.txt' % m), tLines)

    rows = vectorRows(m, onb, rng, args.vectors)
    width = (3 * m + 3) // 4
    vlines = ['// a | b | a*b in ONB coordinates, %d bits each, from field.Onb' % m]
    for ca, cb, cp in rows:
        packed = (ca << (2 * m)) | (cb << m) | cp
        vlines.append('%0*x' % (width, packed))
    writeLines(os.path.join(args.out, 'vectors_mul%d.txt' % m), vlines)

    writeLines(os.path.join(args.out, 'tb_ecc_mul%d.v' % m),
               emitTestbench('tb_ecc_mul%d' % m, 'ecc_mul%d' % m, m,
                             mulStats['stages'], 'vectors_mul%d.txt' % m,
                             args.vectors))

    print('wrote %s' % args.out)
    print('  ecc_mul%d.v       %d gates, %d stages, %d pipeline registers'
          % (m, mulStats['gates'], mulStats['stages'], mulStats['registers']))
    print('  ecc_hamming%d.v   %d gates, %d stages, %d pipeline registers'
          % (m, hamStats['gates'], hamStats['stages'], hamStats['registers']))
    print('  ecc_sigma%d.v     0 gates (coordinate permutation and 3 muxes)' % m)
    print('  ecc_pre%d.v       %d gates, %d stages, %d pipeline registers '
          '(no multiplication)'
          % (m, preStats['gates'], preStats['stages'], preStats['registers']))
    print('  ecc_post%d.v      %d gates, %d stages, %d pipeline registers '
          '(2 multiplications)'
          % (m, postStats['gates'], postStats['stages'], postStats['registers']))
    print('  ecc_inv%d.v       %d multiplier instances, II=1, latency %d clk'
          % (m, invMults, invLat))
    print('  tb_ecc_mul%d.v, tb_ecc_inv%d.v    %d vectors each'
          % (m, m, args.vectors))


if __name__ == '__main__':
    main()
