#!/usr/bin/env python3
"""Compose current gates with the selected n59 bucket-index prefetch."""
from __future__ import annotations
import argparse,hashlib,json,subprocess,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1];E=R/'research/sat_factor_base_review_20260908/continuation-05-sota-gates';S=E/'stage-148-current-gate-audit-20260922';F=R/'docs/ic/runs/koblitz-n59-bucket-prefetch-optimization-20260922.json';P=R/'docs/ic/params/k1n59-cofactor-projected-l15-rank-tail-public-59001.json';G=E/'GATE_STATUS.md';SC='koblitz_stage149_current_gate_audit.v1';SS='koblitz_stage149_current_gate_audit_seal.v1';MARK='Current through Stage 149'
class Error(RuntimeError):pass
def req(v,m):
 if not v:raise Error(m)
def load(p,c):v=json.loads(p.read_text());req(isinstance(v,dict),f'{c} object');return v
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def replay():
 x=subprocess.run([sys.executable,str(R/'scripts/compose_koblitz_stage148_gate_audit.py'),'verify','--output',str(S)],cwd=R,text=True,capture_output=True,check=True);v=json.loads(x.stdout);req(v.get('schema')=='koblitz_stage148_current_gate_audit.v1','Stage-148 replay changed');return v
def compose():
 p=replay();f=load(F,'bucket-prefetch evidence');params=load(P,'selected params');req(f.get('operation')=='koblitz_n59_bucket_prefetch_optimization','identity');req(params.get('name')=='k1n59-cofactor-projected-l15-rank-tail-public-59001-stage138','params identity');req(f['params']['sha256']==sha(P),'params pin');req(f['factor_base']['points']==32934 and f['factor_base']['projected_columns']==16344,'base shape');req(f['factor_base']['factor_base_logs_known_by_construction'] is False and f['factor_base']['target_subgroup_enumerated'] is False and f['factor_base']['scalar_preimages_retained'] is False,'knowledge boundary');one=f['one_unit_panel'];default=f['selected_default_panel'];worker=f['selected_one_worker_pair'];req(one['exact_relation_equality'] is True and len(one['runs'])==8,'pilot');req(default['all_paired_relation_unit_comparisons_win'] is True and len(default['runs'])==8,'default panel');dc=default['comparison'];req(dc['relation_units_wall_seconds']['change_fraction']<-.19 and dc['relation_units_cpu_seconds']['change_fraction']<-.063 and dc['ic_wall_seconds']['change_fraction']<-.124 and dc['whole_cpu_seconds']['change_fraction']<-.043,'default improvement');wc=worker['comparison'];req(wc['ic_wall_seconds']['change_fraction']<-.10 and wc['whole_cpu_seconds']['change_fraction']<-.078 and wc['relation_units_wall_seconds']['change_fraction']<-.08,'one-worker improvement');req(f['relation_stream']['combined_relations']==31798 and f['relation_stream']['exact_equality_across_all_full_runs'] is True,'relation stream');req(all(x['verified'] is True and x['recovered_scalar']==17861472351607 for x in default['runs']+worker['runs']),'solutions');a=f['process_accounting'];req(a['retained_processes']==26 and a['retained_total_core_seconds']>10455 and a['retained_peak_rss_bytes']==10084040704,'accounting');req(f['decision']['status']=='selected' and f['decision']['full_cost_gate_passed'] is False,'decision');req(f['software']['source_stack_head']=='f3ea24fcc16ea800dafd3876493db171c2f8cddd','source pin');req(MARK in G.read_text(),'marker');g=dict(p['gates']);g['1_all_stage_resource_charging']='partial_bucket_prefetch_selection_charged_magma_and_one_preliminary_receipt_missing';g['3_single_core_core_memory_conflicts_wall']='partial_current_n59_bucket_prefetch_complete_magma_missing';g['6_full_cost_vs_automorphism_rho']='failed_current_n59_bucket_prefetch_improved_far_behind_rho'
 return {'schema':SC,'status':'current_seven_gate_audit_verified','all_seven_gates_passed':False,'koblitz_index_calculus_sota':False,'claim_boundary':'finite same-public-target selected bucket-index-prefetch optimization with matched default and one-worker full-cost improvements; full IC remains far behind rho and this is not a SOTA','predecessor':{'stage148_audit_sha256':sha(S/'audit.json'),'stage148_seal_sha256':sha(S/'result-seal.json'),'stage148_status':p['status']},'evidence_pins':{'bucket_prefetch_evidence_sha256':sha(F),'selected_params_sha256':sha(P),'gate_status_sha256':sha(G)},**{k:p[k] for k in p if k.startswith('inherited_')},'inherited_current_n59_cached_hash_rejection':p['current_n59_cached_hash_rejection'],'current_n59_bucket_prefetch':f,'gates':g,'next_targets':['execute the frozen 160-input packet under licensed Magma F4 with complete resource and terminal receipts','reduce the selected n59 full cost further while charging factor-base discovery, the 10 GB table and every policy search','obtain unaffiliated reproduction and a source-pinned novelty/correctness review'],'licensed_magma_complete':False,'independent_external_reproduction_satisfied':False,'full_cost_gate_passed':False}
def new(p,v):req(not p.exists(),f'overwrite {p}');p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
def build(o):req(not o.exists(),f'overwrite {o}');o.mkdir(parents=True);a=compose();new(o/'audit.json',a);new(o/'result-seal.json',{'schema':SS,'status':'audit_frozen','audit_sha256':sha(o/'audit.json')});return a
def verify(o):s=load(o/'result-seal.json','seal');req(s.get('schema')==SS,'seal schema');req(sha(o/'audit.json')==s.get('audit_sha256'),'seal');a=load(o/'audit.json','audit');req(a.get('schema')==SC,'audit schema');req(a.get('status')=='current_seven_gate_audit_verified','audit status');return a
def main():
 p=argparse.ArgumentParser();sp=p.add_subparsers(dest='cmd',required=True)
 for c in ('build','verify'):q=sp.add_parser(c);q.add_argument('--output',type=Path,required=True)
 a=p.parse_args()
 try:r=build(a.output.resolve()) if a.cmd=='build' else verify(a.output.resolve(strict=True));print(json.dumps(r,indent=2,sort_keys=True))
 except (OSError,ValueError,KeyError,subprocess.CalledProcessError,Error) as e:raise SystemExit(f'stage149-gate-audit: {e}')
if __name__=='__main__':main()
