"""Generate the existing degree-131 remainder in direct coefficient order.

Conjugating the reciprocal quotient circuit by reversal changes its left
shifts to right shifts. D is the 130-bit high part of a degree-260 dividend:
R = D + (D >> 1) + (D >> 3),
Q = D + (R >> 1) + (R >> 9) + (R >> 25) + (R >> 57) + (R >> 121).
The existing final remainder circuit is then applied to Q directly.
"""
import argparse
from pathlib import Path
import random

from genpolyreduce import left, polynomial, reference


def direct(x):
    d = (x >> 131) & ((1 << 130) - 1)
    r = d ^ (d >> 1) ^ (d >> 3)
    q = d ^ (r >> 1) ^ (r >> 9) ^ (r >> 25) ^ (r >> 57) ^ (r >> 121)
    t = q ^ (q << 2) ^ (q << 3)
    return (x ^ t ^ (q << 124) ^ (t << 64) ^ (t << 96)
            ^ (t << 112) ^ (t << 120) ^ (t << 128)) & ((1 << 131) - 1)


def right(prefix, shift, word):
    offset, bits = divmod(shift, 32)
    src = word + offset
    if src > 4:
        return None
    if not bits:
        return '%s%d' % (prefix, src)
    # Every intermediate remains at most 130 bits. Its top word has two bits.
    parts = [] if src == 4 and bits >= 2 else ['(%s%d >> %d)' % (prefix, src, bits)]
    if src < 4:
        parts.append('(%s%d << %d)' % (prefix, src + 1, 32 - bits))
    return '(' + ' | '.join(parts) + ')' if parts else None


def check():
    f = polynomial()
    if f != 0xd1d0d000d0000000d000000000000000d:
        raise ValueError('existing field polynomial changed')
    rng = random.Random(20260910)
    cases = [0, (1 << 261) - 1] + [1 << i for i in range(261)]
    cases += [rng.getrandbits(261) for _ in range(10000)]
    for x in cases:
        if direct(x) != reference(x, f):
            raise ValueError(('direct reduction mismatch', x))


def generate():
    check()
    lines = ['// Generated by codegen/gendirectreduce.py; included inside eccPacked131.',
             '#pragma once', 'ECC_HD P131 reducePolynomial131(const uint32_t *h) {']
    for i in range(4):
        lines.append('    uint32_t d%d=(h[%d] >> 3) | (h[%d] << 29);' % (i, i + 4, i + 5))
    # Match the original reducer's degree-260 input boundary even if unused
    # high bits of h[8] are set. Valid field products have those bits zero.
    lines.append('    uint32_t d4=(h[8] >> 3)&3u;')
    for i in range(5):
        parts = ['d%d' % i] + [right('d', shift, i) for shift in (1, 3)]
        lines.append('    uint32_t r%d=%s;' % (i, ' ^ '.join(p for p in parts if p)))
    for i in range(5):
        parts = ['d%d' % i] + [right('r', shift, i) for shift in (1, 9, 25, 57, 121)]
        lines.append('    uint32_t q%d=%s;' % (i, ' ^ '.join(p for p in parts if p)))
    for i in range(5):
        lines.append('    uint32_t t%d=q%d ^ %s ^ %s;' % (i, i, left('q', 2, i), left('q', 3, i)))
    lines.append('    P131 out;')
    for i in range(5):
        parts = ['h[%d]' % i, 't%d' % i] + [left('t', s, i) for s in (64, 96, 112, 120, 128)]
        parts.append(left('q', 124, i))
        expr = ' ^ '.join(p for p in parts if p)
        if i == 4:
            expr = '(' + expr + ')&7u'
        lines.append('    out.v[%d]=%s;' % (i, expr))
    return '\n'.join(lines + ['    return out;', '}']) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--out', default='../include/packeddirectreduce131.h')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if Path(args.out).read_text() != generated:
            raise SystemExit('direct reduction header does not match the generator')
    else:
        Path(args.out).write_text(generated)
    print('PASS: direct reduction against long division on 261 basis, 2 edge and 10000 dense inputs')
