#!/usr/bin/env python3
"""Oracle for gpu/semaev: the pairs-and-solve decomposition sweep.

Everything the kernels are compared against is computed here, in plain
Python, from the algebra rather than from the kernel's own logic.  The
decisive vector is the **exhaustive triple enumeration**: walking every
(X1, X2, X3) in V^3 and testing f3 = 0 directly.  That is the ground
truth the Rust module's `decomposition_agrees_with_exhaustive_search`
also uses, and it is what a wrong gcd or a wrong subspace polynomial
fails against.

    python3 sref.py params  --l 6 > params.h
    python3 sref.py vectors --l 6 > vectors.h
"""

import argparse
import sys


# ── GF(2^n), one word ───────────────────────────────────────────────

class Gf:
    def __init__(self, n, irr_low):
        self.n = n
        self.irr_low = irr_low          # f(z) - z^n
        self.mask = (1 << n) - 1

    def mul(self, a, b):
        a &= self.mask
        b &= self.mask
        r = 0
        for i in range(self.n - 1, -1, -1):
            carry = (r >> (self.n - 1)) & 1
            r = ((r << 1) & self.mask) ^ (self.irr_low if carry else 0)
            if (b >> i) & 1:
                r ^= a
        return r

    def sqr(self, a):
        return self.mul(a, a)

    def sqr_k(self, a, k):
        for _ in range(k):
            a = self.sqr(a)
        return a

    def inv(self, a):
        if a == 0:
            raise ZeroDivisionError
        r, acc = 0, a
        for i in range(1, self.n):
            acc = self.sqr(acc)
            r = acc if i == 1 else self.mul(r, acc)
        return r


def poly_mod_mul_x(bits, n, irr_low):
    """Multiply a polynomial (as a bitmask) by z, reduced."""
    carry = (bits >> (n - 1)) & 1
    return ((bits << 1) & ((1 << n) - 1)) ^ (irr_low if carry else 0)


def is_irreducible(n, irr_low):
    """Rabin's test on f(z) = z^n + irr_low over F_2."""
    if irr_low & 1 == 0:
        return False                                   # divisible by z
    gf = Gf(n, irr_low)
    # z^(2^n) must be z
    x = 2
    v = x
    for _ in range(n):
        v = gf.sqr(v)
    if v != x:
        return False
    # and z^(2^(n/q)) - z must be coprime to f for every prime q | n
    for q in set(prime_factors(n)):
        v = x
        for _ in range(n // q):
            v = gf.sqr(v)
        if v == x:
            return False
    return True


def prime_factors(m):
    out, d = [], 2
    while d * d <= m:
        while m % d == 0:
            out.append(d)
            m //= d
        d += 1
    if m > 1:
        out.append(m)
    return out


def find_irreducible(n):
    """Lowest irreducible f(z) = z^n + (sparse tail), searched not tabled."""
    for low in range(1, 1 << min(n, 20)):
        if is_irreducible(n, low):
            return low
    sys.exit(f"no irreducible found for n={n}")


# ── The algorithm ───────────────────────────────────────────────────

def subspace_poly(l, gf):
    """Coefficients a_0..a_l of L_V(t) = sum a_i t^(2^i) for
    V = <1, z, ..., z^(l-1)>."""
    a = [1]
    for i in range(l):
        b = 1 << i
        lb = 0
        for j, aj in enumerate(a):
            lb ^= gf.mul(aj, gf.sqr_k(b, j))
        nxt = [0] * (len(a) + 1)
        for j, aj in enumerate(a):
            nxt[j + 1] ^= gf.sqr(aj)
            nxt[j] ^= gf.mul(lb, aj)
        a = nxt
    return a


def quartic(x1, x2, xr, gf):
    """f3(X1, X2, t, x_R) as coefficients [c0..c4] in t."""
    xr2 = gf.sqr(xr)
    xr3 = gf.mul(xr2, xr)
    xr4 = gf.sqr(xr2)
    s = x1 ^ x2
    p = gf.mul(x1, x2)
    s2, p2 = gf.sqr(s), gf.sqr(p)
    s4, p4 = gf.sqr(s2), gf.sqr(p2)
    p3 = gf.mul(p2, p)
    p_s2 = gf.mul(p, s2)
    p2_xr2 = gf.mul(p2, xr2)
    return [
        xr4 ^ s4 ^ gf.mul(p4, xr4) ^ p2_xr2,
        gf.mul(p3, xr3) ^ gf.mul(p_s2, xr) ^ gf.mul(p, xr3),
        gf.mul(gf.mul(p2, s2), xr2) ^ gf.mul(p2, xr4) ^ p2 ^ gf.mul(s2, xr2),
        gf.mul(p3, xr) ^ gf.mul(p_s2, xr3) ^ gf.mul(p, xr),
        1 ^ p4 ^ gf.mul(s4, xr4) ^ p2_xr2,
    ]


def eval_f3(x1, x2, x3, xr, gf):
    v = 0
    for c in reversed(quartic(x1, x2, xr, gf)):
        v = gf.mul(v, x3) ^ c
    return v


def decompose_exhaustive(xr, l, gf):
    """Ground truth: walk every sorted triple of V^3.

    Complete because f3 is symmetric in X1, X2, X3."""
    span = 1 << l
    for x1 in range(span):
        for x2 in range(x1, span):
            for x3 in range(x2, span):
                if eval_f3(x1, x2, x3, xr, gf) == 0:
                    return (x1, x2, x3)
    return None


# ── Emitters ────────────────────────────────────────────────────────

def emit_params(args):
    l = args.l
    n = args.n if args.n else 3 * l
    irr = find_irreducible(n)
    print("/* generated by sref.py -- do not edit */")
    print("#pragma once")
    print("#include <stdint.h>")
    print(f"#define SEM_N   {n}")
    print(f"#define SEM_L   {l}")
    print(f"#define SEM_IRR 0x{irr:x}ull   /* f(z) - z^n */")


def emit_vectors(args):
    l = args.l
    n = args.n if args.n else 3 * l
    irr = find_irreducible(n)
    gf = Gf(n, irr)
    print("/* generated by sref.py -- do not edit */")
    print("#pragma once")
    print("#include <stdint.h>")
    print()

    # Field arithmetic vectors.
    pairs = [(1, 1), (2, 3), (5, 7), (1 << (n - 1), 3), (0, 9), (11, 13)]
    mul = ",".join(f"{{{a}ull,{b}ull,{gf.mul(a, b)}ull}}" for a, b in pairs)
    print(f"static const uint64_t FIELD_MUL[][3] = {{{mul}}};")
    print(f"static const int FIELD_MUL_N = {len(pairs)};")
    sq = [1, 2, 3, 5, 1 << (n - 1), 255]
    sqs = ",".join(f"{{{a}ull,{gf.sqr(a)}ull}}" for a in sq)
    print(f"static const uint64_t FIELD_SQR[][2] = {{{sqs}}};")
    print(f"static const int FIELD_SQR_N = {len(sq)};")
    iv = [a for a in (1, 2, 3, 7, 100) if a % (1 << n)]
    ivs = ",".join(f"{{{a}ull,{gf.inv(a)}ull}}" for a in iv)
    print(f"static const uint64_t FIELD_INV[][2] = {{{ivs}}};")
    print(f"static const int FIELD_INV_N = {len(iv)};")
    print()

    # The subspace polynomial.
    lv = subspace_poly(l, gf)
    print(f"static const uint64_t LV[] = {{{','.join(f'{x}ull' for x in lv)}}};")
    print(f"static const int LV_N = {len(lv)};")
    print()

    # Quartic coefficients for a few pairs, so a transcription error in
    # the twelve folded constants is caught directly.
    qs = []
    for (x1, x2, xr) in [(0, 0, 1), (1, 2, 5), (3, 5, 37), (1, 1, 100)]:
        c = quartic(x1, x2, xr % (1 << n), gf)
        qs.append(f"{{{x1}ull,{x2}ull,{xr % (1 << n)}ull,"
                  + ",".join(f"{v}ull" for v in c) + "}")
    print(f"static const uint64_t QUARTIC[][8] = {{{','.join(qs)}}};")
    print(f"static const int QUARTIC_N = {len(qs)};")
    print()

    # Targets with the exhaustive verdict.  Both outcomes must occur or
    # the comparison could pass vacuously; the harness asserts it.
    span = 1 << l
    targets, yes, no = [], 0, 0
    cand = list(range(1, min(1 << n, 4096)))
    for xr in cand:
        if yes >= args.yes and no >= args.no:
            break
        w = decompose_exhaustive(xr, l, gf)
        if w and yes < args.yes:
            targets.append((xr, 1, w))
            yes += 1
        elif not w and no < args.no:
            targets.append((xr, 0, (0, 0, 0)))
            no += 1
    rows = ",".join(
        f"{{{xr}ull,{ok}ull,{w[0]}ull,{w[1]}ull,{w[2]}ull}}" for xr, ok, w in targets
    )
    print(f"/* {yes} decomposable, {no} not, decided by exhaustive triples */")
    print(f"static const uint64_t TARGETS[][5] = {{{rows}}};")
    print(f"static const int TARGETS_N = {len(targets)};")
    print(f"static const int TARGETS_YES = {yes};")
    print(f"static const int TARGETS_NO = {no};")
    print(f"static const uint64_t SPAN = {span}ull;")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="cmd", required=True)
    for name in ("params", "vectors"):
        s = sub.add_parser(name)
        s.add_argument("--l", type=int, default=5)
        s.add_argument("--n", type=int, default=0, help="default 3l")
        s.add_argument("--yes", type=int, default=4)
        s.add_argument("--no", type=int, default=4)
    args = ap.parse_args()
    if args.cmd == "params":
        emit_params(args)
    else:
        emit_vectors(args)


if __name__ == "__main__":
    main()
