#!/usr/bin/env python3
"""One representative per `sigma`-class, enumerated at constant amortised cost.

`target_boundary.py` prices the stored side of the meet-in-the-middle as one
entry per `sigma`-orbit of `s`-subsets of the support -- `2^s C(B,s) / 131`
entries rather than `2^s C(B,s)`.  That is only a saving if the
representatives can be *enumerated* at a cost proportional to their number.
Enumerating all subsets and discarding 130 of every 131 would pay the full
price and keep none of it.

The note carried that as an assumption, with a stated `2^3.3` penalty if it
turned out to be false.  This module discharges it.

The support is `T` Frobenius orbits of length `m = 131`, and `sigma` shifts
every orbit by one position at once.  A subset of it is therefore a string of
length `m` over an alphabet of `2^T` symbols -- which track-memberships each
position holds -- and a `sigma`-class is exactly a **necklace**: such a string
up to rotation.  Fixed-density necklaces are generated by the standard
Fredricksen--Kessler--Maiorana recursion with a density prune, which visits a
bounded number of internal nodes per necklace emitted.

Two things are checked in `test_four_point_orbit.py` rather than argued:

  * the count is exactly `C(T*m, d) / m`.  `m` is prime and `d < m`, so no
    subset is fixed by a non-trivial rotation and every class has exactly `m`
    members;
  * the recursion nodes per emitted necklace stay bounded -- measured at
    13--31 and *falling* with density, flat in `m` -- rather than growing
    like `m`, which is what would sink the accounting.
"""

from __future__ import annotations

import sys


def necklaces(m: int, tracks: int, density: int, emit: bool = True):
    """`sigma`-class representatives of `density`-subsets of `tracks` x `Z/m`.

    Returns `(representatives_or_count, recursion_nodes)`.  With `emit=False`
    only the count is kept, so large parameters can be measured without
    materialising the output.
    """
    alphabet = 1 << tracks
    a = [0] * (m + 1)
    out: list = []
    count = [0]
    nodes = [0]
    limit = sys.getrecursionlimit()
    if m + 10 > limit:
        sys.setrecursionlimit(m + 100)

    def popcount(v: int) -> int:
        return bin(v).count("1")

    def gen(t: int, p: int, ones: int) -> None:
        nodes[0] += 1
        if ones > density or ones + (m - t + 1) * tracks < density:
            return                      # density prune, both directions
        if t > m:
            if m % p == 0 and ones == density:
                count[0] += 1
                if emit:
                    out.append(tuple(a[1:m + 1]))
            return
        a[t] = a[t - p]
        gen(t + 1, p, ones + popcount(a[t]))
        for j in range(a[t - p] + 1, alphabet):
            a[t] = j
            gen(t + 1, t, ones + popcount(j))
        a[t] = 0

    gen(1, 1, 0)
    return (out if emit else count[0]), nodes[0]


def cost_per_representative(m: int, tracks: int, density: int) -> float:
    """Recursion nodes per necklace emitted -- the quantity that must stay O(1)."""
    n, nodes = necklaces(m, tracks, density, emit=False)
    return nodes / n if n else float("inf")
