#!/usr/bin/env python3
"""Four-point relations on ECC2K-130, grouped by signed Frobenius orbit.

`P1 + P2 + P3 + P4 = O` says `P1 + P2 = -(P3 + P4)`, and a point and its
negative share an abscissa, so a four-point relation forces two pairs whose
sums share an abscissa.  That turns a quadruple enumeration into a
collision search over pair sums.

What this run adds to `run_four_point.py` is the Frobenius quotient it
declined to take.  On a **normal-basis** weight-two support (see
`normalbasis.py`) the support is closed under `sigma`, so:

  * pairs come in `sigma`-orbits of size `m = 131`, and one canonical
    representative per orbit is enumerated rather than all of them;
  * a pair sum is keyed by the least abscissa in its `sigma`-orbit, so one
    stored key stands for 131 pairs, and a key collision hands back all
    131 rotations of the relation at once.

Together those turn `B(B-1) = 1.3e7` stored pair sums into `B(B-1)/131 =
1.0e5`.

Two corrections over the first attempt at this, both of which produced
plausible output rather than an error:

**Anchoring, done once.**  A pair whose elements lie in different orbits
can be rotated to put *either* element at position 0.  Taking both is a
double count, and the first orbit-grouped run reported 125,953 "relations"
on that account.  `NormalSupport.canonical_pair_orbits` enumerates by
`(t1, t2, delta)` instead, which names each orbit exactly once.

**`E[4]`, not `O`.**  The cofactor is 4, and a four-point sum landing
anywhere in `E[4]` still gives a usable equation once the cofactor is
cleared.  Requiring the sum to be exactly `O` discards usable relations, so
each pair sum is probed against every `E[4]` translate, not only against
itself.  Measured at small `m`, the sums reach only two of the four
elements of `E[4]` -- see `fourpoint.py` and the research note -- so the
correction is worth a factor of 2, not the factor of 4 a uniform-coset
guess gives.

    python3 run_four_point_orbit.py [--bases N] [--budget-seconds S]
"""

from __future__ import annotations

import argparse
import json
import math
import platform
import random
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import relations as R                                        # noqa: E402
from normalbasis import NormalSupport, find_normal_elements  # noqa: E402
from fourpoint import supply_prediction                      # noqa: E402


def four_torsion_challenge(E, r: int):
    """`E[4]` on the challenge curve: `O`, the order-2 point, and two of order 4.

    The rational 2-torsion is `O` and `(0, sqrt(b))`, so the 2-Sylow is
    cyclic of order 4 and `E[4]` is generated by any point whose odd part
    has order 4.
    """
    F = E.F
    T2 = (0, F.frobenius(E.b, F.deg - 1))
    assert E.mul(T2, 2) is None, "the x=0 point should be 2-torsion"
    rng = random.Random(1)
    while True:
        x = rng.getrandbits(F.deg) & F.mask
        pts = E.points_over(x)
        if not pts:
            continue
        T = E.mul(pts[0], r)                   # kill the odd part
        if T is not None and E.mul(T, 2) is not None and E.mul(T, 4) is None:
            return [None, T2, T, E.mul(T, 3)]


def pair_sums(E, support: NormalSupport, reps, *, budget_seconds=None,
              log=print, name="run"):
    """Canonical `sigma`-orbit key for every canonical signed pair-orbit.

    Returns `(keys, pairs, complete, elapsed)` where `keys[i]` is the key of
    `pairs[i]`, and `pairs[i]` is `(ia, ib, eps)` into the support.
    """
    total = support.pair_orbit_count()
    keys, pairs = [], []
    started = time.time()
    last = started
    complete = True
    buf_a, buf_b, buf_p = [], [], []

    def flush():
        if not buf_a:
            return
        for S, p in zip(R.batch_add(E, buf_a, buf_b), buf_p):
            if S is not None:
                keys.append(support.sigma_canonical_x(S[0]))
                pairs.append(p)
        buf_a.clear(); buf_b.clear(); buf_p.clear()

    for ia, ib, eps in support.canonical_pair_orbits():
        buf_a.append(reps[ia])
        buf_b.append(reps[ib] if eps > 0 else E.neg(reps[ib]))
        buf_p.append((ia, ib, eps))
        if len(buf_a) >= 4096:
            flush()
            now = time.time()
            if now - last >= 30:
                last = now
                frac = len(pairs) / total
                el = now - started
                log(f"[{name}]   {len(pairs):,}/{total:,} ({frac:6.2%}) "
                    f"elapsed={el:6.0f}s eta={el / frac - el if frac else 0:6.0f}s")
            if budget_seconds and now - started > budget_seconds:
                complete = False
                break
    flush()
    return keys, pairs, complete, time.time() - started


def certify(E, support, reps, pa, pb, e4):
    """Recompute a candidate in full; return the relation or a rejection reason.

    A candidate says two pair sums agree up to `sigma` and up to an `E[4]`
    translate.  Which rotation, which sign and which translate is not
    recorded -- recovering it costs `131 * 2 * 4` group additions and is
    only ever done for a candidate, which is rare.
    """
    ia, ib, ea = pa
    ic, idd, ec = pb
    A = reps[ia]
    B = reps[ib] if ea > 0 else E.neg(reps[ib])
    for k in range(support.m):
        C0 = reps[support.index(*divmod(ic, support.m))] if False else None
        tc, kc = divmod(ic, support.m)
        td, kd = divmod(idd, support.m)
        C = reps[support.index(tc, kc + k)]
        D0 = reps[support.index(td, kd + k)]
        for sd in (1, -1):
            D = D0 if (ec * sd) > 0 else E.neg(D0)
            for sc in (1, -1):
                Cs = C if sc > 0 else E.neg(C)
                xs = {A[0], B[0], Cs[0], D[0]}
                if len(xs) < 4:
                    continue
                S = E.sum_points([A, B, Cs, D])
                if S in e4 or (S is None and None in e4):
                    return {
                        "points": [[hex(p[0]), hex(p[1])]
                                   for p in (A, B, Cs, D)],
                        "sum": "O" if S is None else hex(S[0]),
                        "exact": S is None,
                    }
    return None


def run_basis(E, r, alpha, e4, *, budget_seconds, log=print, name="basis"):
    F = E.F
    support = NormalSupport(F, E, alpha)
    if support.size == 0:
        return {"name": name, "alpha": hex(alpha), "support_size": 0,
                "skipped": "no lifting orbits"}

    reps = support.orbit_points(E)

    log(f"[{name}] alpha={hex(alpha)[:18]}... orbits={support.orbit_count}"
        f"/{support.total_orbits()} B={support.size} "
        f"pair-orbits={support.pair_orbit_count():,}")
    assert support.is_sigma_stable(), "support must be closed under sigma"
    assert not support.mixed_orbits, "lifting must be constant on an orbit"

    keys, pairs, complete, elapsed = pair_sums(
        E, support, reps, budget_seconds=budget_seconds, log=log, name=name)

    # Collision search: a shared canonical key, or a key matching an E[4]
    # translate of another pair's sum.
    index: dict[int, list[int]] = {}
    for i, k in enumerate(keys):
        index.setdefault(k, []).append(i)

    candidates = []
    for k, group in index.items():
        for a in range(len(group)):
            for b in range(a + 1, len(group)):
                candidates.append((group[a], group[b]))

    translate_hits = 0
    nonzero_e4 = [T for T in e4 if T is not None]
    if nonzero_e4:
        for i, (ia, ib, eps) in enumerate(pairs):
            S = E.add(reps[ia], reps[ib] if eps > 0 else E.neg(reps[ib]))
            for T in nonzero_e4:
                ST = E.add(S, T)
                if ST is None:
                    continue
                for j in index.get(support.sigma_canonical_x(ST[0]), ()):
                    if j != i:
                        candidates.append((i, j))
                        translate_hits += 1

    certified, rejected = [], 0
    e4set = set(e4)
    for i, j in candidates:
        rel = certify(E, support, reps, pairs[i], pairs[j], e4set)
        if rel is None:
            rejected += 1
        else:
            certified.append(rel)

    pred = supply_prediction(support.size, 4 * r, len(e4))
    return {
        "name": name,
        "alpha": hex(alpha),
        "lifting_orbits": support.orbit_count,
        "total_orbits": support.total_orbits(),
        "support_size": support.size,
        "unknowns": support.orbit_count,
        "pair_orbits_expected": support.pair_orbit_count(),
        "pair_orbits_enumerated": len(pairs),
        "complete": complete,
        "elapsed_seconds": round(elapsed, 1),
        "pairs_per_second": round(len(pairs) / elapsed, 1) if elapsed else None,
        "raw_candidates": len(candidates),
        "translate_candidates": translate_hits,
        "rejected_degenerate": rejected,
        "certified_relations": len(certified),
        "relations": certified[:16],
        "log2_expected_usable": pred["log2_expected_usable"],
        "log2_expected_exact": pred["log2_expected_exact"],
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bases", type=int, default=4)
    ap.add_argument("--budget-seconds", type=float, default=3600.0)
    ap.add_argument("--seed", type=int, default=20260917)
    ap.add_argument("--out", default=str(HERE / "results"))
    args = ap.parse_args()

    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)

    F, E, P, Q, r = R.challenge_curve()
    e4 = four_torsion_challenge(E, r)
    rng = random.Random(args.seed)
    alphas = find_normal_elements(F, args.bases, rng)

    summary = {
        "instance": "ECC2K-130",
        "subgroup_order_r": str(r),
        "group_order": str(4 * r),
        "four_torsion_size": len(e4),
        "seed": args.seed,
        "budget_seconds": args.budget_seconds,
        "python": sys.version.split()[0],
        "platform": platform.platform(),
        "bases": [],
    }

    for n, alpha in enumerate(alphas):
        res = run_basis(E, r, alpha, e4, budget_seconds=args.budget_seconds,
                        name=f"nb{n}")
        (outdir / f"four_orbit_nb{n}.json").write_text(json.dumps(res, indent=2))
        summary["bases"].append({k: v for k, v in res.items()
                                 if k != "relations"})
        (outdir / "four_point_orbit_summary.json").write_text(
            json.dumps(summary, indent=2))
        print(json.dumps(summary["bases"][-1], indent=2))

    tot = sum(b.get("pair_orbits_enumerated", 0) for b in summary["bases"])
    cert = sum(b.get("certified_relations", 0) for b in summary["bases"])
    print(f"\ntotal pair-orbits {tot:,}  certified relations {cert}")


if __name__ == "__main__":
    main()
