#!/usr/bin/env python3
"""Small analogues of the challenge curve, for controls.

`y^2 + xy = x^3 + 1` over `F_2^m` for small odd `m`.  The point of these is
that everything the ECC2K-130 sweep can only predict -- how many four-point
relations a support of size `B` actually holds -- can be *counted* here, so
the supply model is checked against ground truth before it is quoted at
`m = 131`.

Prime `m` is required, not merely odd: the orbit structure of
`normalbasis.NormalSupport` relies on `sigma` having prime order, so a
composite `m` would be a control of a different object.
"""

from __future__ import annotations

from fastfield import FastGF2m
from relations import Koblitz

# Irreducible polynomials, verified in `test_four_point_orbit.py` rather
# than taken on trust.
IRR = {
    11: (1 << 11) | 0x005,        # x^11 + x^2 + 1
    13: (1 << 13) | 0x01b,        # x^13 + x^4 + x^3 + x + 1
    17: (1 << 17) | 0x009,        # x^17 + x^3 + 1
    19: (1 << 19) | 0x027,        # x^19 + x^5 + x^2 + x + 1
}


def curve_order(m: int) -> int:
    """`#E(F_2^m)` from the Koblitz recursion.

    `#E(F_2) = 4`, so the base-field trace is `t = 2 + 1 - 4 = -1` and the
    Weil numbers satisfy `V_k = t V_{k-1} - 2 V_{k-2}` with `V_0 = 2`,
    `V_1 = t`.  Then `#E(F_2^m) = 2^m + 1 - V_m`.
    """
    t = -1
    v0, v1 = 2, t
    for _ in range(m - 1):
        v0, v1 = v1, t * v1 - 2 * v0
    return (1 << m) + 1 - v1


def small_curve(m: int):
    """`(F, E, order)` for the small analogue of degree `m`."""
    if m not in IRR:
        raise KeyError(f"no irreducible polynomial recorded for m={m}")
    F = FastGF2m(m, IRR[m])
    return F, Koblitz(F, a=0, b=1), curve_order(m)


def count_points(E: Koblitz) -> int:
    """Exhaustive point count, including the point at infinity."""
    return 1 + sum(len(E.points_over(x)) for x in range(1 << E.F.deg))


def four_torsion(E: Koblitz, order: int):
    """Every `T` in `E(F_2^m)` with `4T = O`, the identity written `None`.

    A four-point sum landing anywhere in here is a usable relation, not
    only a sum landing exactly on the identity: the cofactor is 4, so such
    a sum still gives an equation on the order-`r` subgroup after clearing
    it.  Requiring exactness instead is the defect that discarded 57% of
    the supply.

    The rational 2-torsion of `y^2 + xy = x^3 + a x^2 + b` is just `O` and
    `(0, sqrt(b))` -- the doubling formula needs `x != 0`, so no other
    point halves to the identity -- which makes the 2-Sylow cyclic.  With
    cofactor 4 it is `Z/4`, so `E[4]` is generated by any point whose odd
    part has order 4, and there is no need to walk the curve.
    """
    odd = order
    while odd % 2 == 0:
        odd //= 2
    for x in range(1, 1 << E.F.deg):
        for P in E.points_over(x):
            T = E.mul(P, odd)
            if T is not None and E.mul(T, 2) is not None and E.mul(T, 4) is None:
                return [None, T, E.mul(T, 2), E.mul(T, 3)]
    raise RuntimeError("no point of order 4 found; 2-Sylow is not Z/4")
